### ISSUE TITLE
As someone consolidating data at TTS, I want that data to be interoperable

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#100]
Part of #7.

- [ ] See if FAS/GSA have any existing data dictionaries
- [ ] Connect with data.gov team to get their input
- [ ] Get a sense of what fields are / could be commonly used for joining data - email address is a simple example - to identify what would make sense in a TTS-specific data dictionary

**Comment by afeld** [comment]
Decided this is out of scope for the Tech Portfolio right now.
