### ISSUE TITLE
AutoML access for Feedback Analytics

### ISSUE THREAD

**Issue by ryanwoldatwork** [18F/tts-tech-portfolio#1003]
## Background Information

As a Feedback Analytics program staffer,
I want to analyze feedback text
So that I can better understand the technical capabilities for use in feedback products (and potentially other TTS products)
And so that I can discover opportunities to improve existing public services.

## Implementation Steps

* [x] Get budget approval for a small amount of cloud spend.
* [x] Grant access to TEST Feedback Analytics cloud account

## Acceptance Criteria

* [x] FBA team member (Ryan) can use AutoML to test a set of open-text feedback

**Comment by JJediny** [comment]
@ryanwoldatwork confirmed but reopen if needed
