### ISSUE TITLE
H1 Invoices - due date 12/2

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1004]
## Implementation Steps
- [x] Figure out date the invoices need to be paid by
- [x] Ask H1 to have their folks email the invoices
- [ ] Access the VCCS system
- [ ] Follow the COR process on paying invoices
  - [ ] Fill in the Form
  - [ ] Update the SmartSheet
  - [ ] Route through DocuSign

## Acceptance Criteria

- [ ] H1 Invoice is paid

**Comment by its-a-lisa-at-work** [comment]
Got new billing invoices now

**Comment by its-a-lisa-at-work** [comment]
Closing this out; @JenniferCalik is going to send an email explaining our expectations
