### ISSUE TITLE
H1  Contractor Performance Assessment Report (CPAR) - Due Date 1/17/21

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1005]
## Background Information

The Federal Acquisition Regulation (FAR) requires that contractor performance information be
collected (FAR Part 42.15) and used in source selection evaluations (FAR Part 15). Source
selection officials rely on clear and timely evaluations of contractor performance to make
informed business decisions when awarding government contracts and orders. This information
is critical to ensuring that the Federal government only does business with companies that
provide quality products and services in support of the agency’s missions.

https://www.cpars.gov/documents/CPARS-Guidance.pdf 

## Pre-Implementation Steps
- [x] login to the CPAR website
- [x] update the background information of this card
- [x] update the implementation steps

## Implementation Steps
![image](https://user-images.githubusercontent.com/31391902/101299044-9a026080-37fe-11eb-92af-810b321730c8.png)
- [x] Set up time to chat with users of H1
- [x] Talk with all folks who volunteered to chat
- [x] See if there are other people to chat with
  - [x] If so, set up time to talk with them
- [x] Mention CPAR to H1 
- [ ] Receive H1 self assessment
- [ ] Evaluation and Ratings and Narratives
  - [ ] Gather others feedback
  - [x] Create draft. - due 1/8/21
  - [x] Share draft with CO
  - [ ] formally submit

## Acceptance Criteria
- [x] Evaluation and Ratings and Narratives are submitted and sent to CPAR Representative
- [ ] Create any follow up issues

**Comment by its-a-lisa-at-work** [comment]
Submitted draft this morning; waiting for the H1 Self Assessment; we have our meeting set up with them tomorrow, so will likely get it then; and then assure that the CO has seen it before submitting for final

moving to `Waiting/Feedback` until that is accomplished

**Comment by its-a-lisa-at-work** [comment]
Coming back from leave and looking into this; asked @JenniferCalik what the status is in [slack](https://gsa-tts.slack.com/archives/C0X2FMJ86/p1611253306000600); moving back to `Waiting/Feedback` until I hear back

**Comment by its-a-lisa-at-work** [comment]
Got self assessment back from H1; wasn't able to submit it in the CPAR system; don't have any more tasks in my to-do list on the CPARS website; no follow up issues at this time; closing this issue
