### ISSUE TITLE
handle adding to TTS-wide tools as part of onboarding

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1007]
## Background Information

Right now, when someone joins TTS, they need to explicitly request access to TTS-wide tools, notably:

- GitHub
- Trello
- Mural

For Slack, on the other hand, the Onboarding team puts in the request for them to get added, ensuring it's done in advance of employees starting, and taking that burden off the new employee.

For GitHub in particular, the Tech Portfolio kinda needs to take their word for it on what they should be added to. It would be better security-wise to find out what team they are part of from an official source (e.g. Talent), and add them to the appropriate GitHub team/organization.

Mural is a little trickier since we only have a limited number of licenses; maybe we add people as [Guests](https://support.mural.co/en/articles/2113719-types-of-users-in-mural) by default, and have them request being a Member if/when needed.

## Implementation Steps

- [x] Decide whether we want Onboarding to handle the user management directly
- [x] Get consensus from the Onboarding team on updated process
- [x] Update relevant Handbook pages - https://github.com/18F/handbook/pull/2245
- [x] Update Ops Rotation checklist
- [x] Update [Onboarding Lead checklist](https://docs.google.com/spreadsheets/d/1h5i9qTAvgCRcK8Qm4z2hvuQWrEq0q_2cg-fqCyHW1iY/edit#gid=0)
- [x] Update new hire checklists

## Acceptance Criteria

- [x] New TTS staff are being added to relevant SaaS proactively

**Comment by colinmurphy01** [comment]
Instructional recording for adding peeps to Mural, Trello and Github: https://drive.google.com/file/d/133_Ck4WAWauRXx9RNYBXJNsudl83nyP6/view

**Comment by afeld** [comment]
Gonna leave it open until I make sure all the loose ends are tied up.

**Comment by afeld** [comment]
All set! Walked @AnnabelLombard through, and (I think) got all the documentation+checklists updated to where she'll add new hires to GitHub, Trello, and Mural.
