### ISSUE TITLE
propose unified approval processes for integrations

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1012]
## Background Information

Various SaaS TTS uses has support for integrations/add-ons/power-ups/etc., which connect one cloud service to another. We also have distinct review processes for each:

- [GitHub](https://handbook.tts.gsa.gov/github/#rules)
- [Slack](https://handbook.tts.gsa.gov/tools/slack/integrations/)
- [Trello](https://handbook.tts.gsa.gov/trello/#power-ups)

While the mechanics of researching/enabling integrations vary by platform, the considerations are (or could/should) be similar. GSA has a (mostly) shared understanding on how to approve individual pieces of SaaS (IT Standards), but things get a bit fuzzy when connecting between them. Not aware of any existing guidance/policy from GSA around this.

## Implementation Steps

- [ ] Ask Security for existing relevant guidance
- [ ] Create proposal (written, or a presentation) about what this would encompass and how it might work
- [ ] Send to IT Standards participants
- [ ] Determine who would make the decision on this — Security? CTO?

## Acceptance Criteria

- [ ] Proposal presented / shared with the groups involved in IT Standards
