### ISSUE TITLE
Retroactively add all AWS accounts to aws-admin terraform

### ISSUE THREAD

**Issue by amitfreeman-gov** [18F/tts-tech-portfolio#1017]
## Background Information
aws-admin currently has templates and stanzas for different AWS accounts on which we've performed operations.  However, not all of our accounts are represented in the configuration.

## Implementation Steps
- [x] Add all AWS accounts to aws-admin such that any changes can be made uniformly
- [x] Modify the new AWS account template to include adding new accounts to aws-admin terraform (even if they are in an inactive state within the configuration)

## Acceptance Criteria
- [x] All TTS AWS accounts are represented in the terraform configuration
- [x] All documentation is up-to-date with respect to adding configurations to aws-admin

**Comment by JJediny** [comment]
All accounts managed have been crosswalked and provisioned with baseline configuration (not including login/cloud accounts that they self-manage).
