### ISSUE TITLE
As a member of TTS leadership, I don't want manual effort to report regular metrics

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#102]
- [x] Look through Business Weekly decks ([example](https://docs.google.com/presentation/d/1exCLF3j1N6dK7Dc40chLJqD_zhnE75K8vasBEMcGDiE/edit#slide=id.p) - can ask Hilary Lutz for more) to see what metrics are regularly reported
- [x] Look back through [the interview with Finance](https://docs.google.com/document/d/1r85WtVG_ZGwUGMgid9GWoVvqsenErEBxdS83qU99DmA/edit)
- [ ] Ask Finance about their reporting requirements
- [ ] Figure out where these can be automated - _split this out to separate issue(s)_

**Comment by c-manger** [comment]
Doc I am taking notes in:

https://docs.google.com/document/d/12vBGPoAagezsL0cri13sIrTDzr4lSv9AKyHnvNUTKrg/edit?usp=sharing

**Comment by afeld** [comment]
Decided this is out of scope for the Tech Portfolio right now.
