### ISSUE TITLE
finalize Mac admin rights request workflow in ServiceNow

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1023]
[Trello card](https://trello.com/c/cHGL9ORL/207-create-local-admin-rights-request-process)

## Background Information

GSA IT is moving the [request procedures](https://docs.google.com/document/d/1xepZsh83lxPDykrb1NXoeHxj8m78qsdW-9KqzO_CHOQ/edit#heading=h.49lwkdmpmwle) from a Generic Request to a ServiceNow ticket type built for this purpose.

## Implementation Steps
- [x] Complete user acceptance testing (UAT)
- [x] Provide feedback
- [x] Update [documentation](https://docs.google.com/document/d/1xepZsh83lxPDykrb1NXoeHxj8m78qsdW-9KqzO_CHOQ/edit#heading=h.49lwkdmpmwle)

## Acceptance Criteria

- [x] Mac admin request flow is moved over to ServiceNow
- [ ] Instructions added to Handbook

**Comment by afeld** [comment]
Done!
