### ISSUE TITLE
document the current state of Identity GIVE - due 12/2

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1028]
[**document**](https://docs.google.com/document/d/1mEDZ0E9L6A5MBqHaAT4zS2pBPL9fEPZfsKUy5r5NFxU/edit)

## Background Information

There are a lot of moving parts and confusion around the Identity GIVE project. We have a meeting around procurement for the project on 12/3 — looking to have a shared understanding of the current state written down that we can share with everyone before then.

## Implementation Steps
- [x] Write first draft
- [x] Send to TTS for initial review
- [x] Send to other stakeholders
- [ ] Reviewed by:
   - [ ] TTS
      - [ ] @melanienleopold 
      - [x] @its-a-lisa-at-work 
      - [x] @JenniferCalik 
   - [ ] CTO team
      - [x] @josephderosales 
      - [ ] @Zergessc
      - [ ] @CinnyaSm  
   - [ ] Security
      - [ ] @jhoyt22 
      - [x] Jody Denner
      - [x] Nate Ciano

## Acceptance Criteria

- [x] A written description of the current state of the project has been shared with stakeholders

**Comment by afeld** [comment]
Started writing this in email and Slack multiple times; moved to [a doc](https://docs.google.com/document/d/1mEDZ0E9L6A5MBqHaAT4zS2pBPL9fEPZfsKUy5r5NFxU/edit).

**Comment by afeld** [comment]
Sent to everyone involved. Not everyone has viewed; folks will be coming back from vacation at different times, but don't think we need to keep the issue open for that.
