### ISSUE TITLE
talking points for Government & Defense Conference - due 12/2

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1029]
## Background Information

@DsaleGov was asked to speak at the [Baird Government & Defense Conference](https://www.bairdconferences.com/conference2/Index/27). Asked to help with talking points.

## Implementation Steps

- [x] Confirm the topic
- [x] Talking points filled out
- [x] Diana Cameron notified

## Acceptance Criteria

- [x] Responses given to each of the questions in the [talking points](https://docs.google.com/document/d/1mbMXjcdcLkBB0QbnIy42NqfT00ydmiZTDPtgqOakDG8/edit?ts=5fbea5bb)

**Comment by afeld** [comment]
Done.
