### ISSUE TITLE
DevSecOps Guild - Leadership Introduction

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1032]
## Background Information

Alyssa was recently selected as a lead for the DevSecOps guild. 

## Implementation Steps
- [x] Meet with the current guild leadership
- [x] Make action items/cards for anything else 

## Acceptance Criteria

- [x] Alyssa knows what she has to do as a DevSecOps lead

**Comment by its-a-lisa-at-work** [comment]
Created action item for follow up activity https://github.com/18F/Security-Compliance/issues/7
