### ISSUE TITLE
SmartSheet - 10k ft authorization clarification

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1034]
## Implementation Steps
- [x] Meet with Smartsheet
- [x] Document any action items

## Acceptance Criteria

- [x] Meet with Smartsheet to understand whether 10k ft will be under their FedRAMP package

**Comment by its-a-lisa-at-work** [comment]
No action items to speak of on TTS side. The Smartsheet folks are going to go back and talk with the 10k ft folks and get a better grasp on what the approach to authorization for 10k ft is. We got the clarity we were seeking and answers that:
- 10k ft is NOT going to be included in the SmartSheet FedRAMP authorization
- 10k ft would be an _integration_ to SmartSheet, and not sure if that _integration_ would be a part of the SmartSheet Gov authorization at the beginning
- 10k ft is a completely separate product and won't be integrated from a technology stand point
- 10k ft would require a new/different license from what we currently have from SmartSheet
