### ISSUE TITLE
Look into the pros/cons of GitLab

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1035]
## Background Information

We've had GitHub for a while and now other Federal agencies are using GitLab and there are no known plans for [GitHub to migrate to a moderate ATO](https://gsa-tts.slack.com/archives/CNW3GL70S/p1606486595079800) 

There also seems to be some interest https://gsa-tts.slack.com/archives/C5HNZUCJ3/p1607531251146400

## Implementation Steps (no particular order)
- [ ] Understand what was done originally for GitHub requirements
- [ ] Determine if there is an interest in going down this path
- [ ] Submit a New Software request

## Acceptance Criteria

- [ ] GitLab has been explored as an option

**Comment by pburkholder** [comment]
Maybe this should get assigned to @Mzia or @sharms since I think login has a more pressing need for Moderate SCM than cloud does at this moment.

**Comment by its-a-lisa-at-work** [comment]
Max.gov will probably also have a need so I can be assigned as well.

Maybe we should start a #wg-software-factory for the tooling that we'll
need for developing Shared Services coming out of TTS that will need to go
to FedRAMP JAB at Moderate & above

**Comment by mzia** [comment]
For now.. what we are doing is using AWS CodeCommit which is JAB authorized to be a middle man repo to host our deploy code... but GitLabs would help us work with a single tool and drop CodeCommit... Another catch for login.gov is if we are in the JAB world, TRs would prefer GitLabs to be JAB authorized as well.... and that is what they should pursue IMO.  The JAB will also allow them to meet IL2-IL4 with augmentation to FedRAMP Moderate (or High) baseline security controls.  But it's a big ask and won't happen overnight.

**Comment by afeld** [comment]
Merging into https://github.com/18F/tts-tech-portfolio/issues/1305.
