### ISSUE TITLE
ask questions around EBCs - due 12/9

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1043]
## Background Information

[Executive Business Cases (EBCs)](https://sites.google.com/a/gsa.gov/fas-systems-governance/ebcs) are being submitted for this round of funding from the FAS Systems Governance Committee (FSGC). We have been asked to provide questions by 12/7, prior to the presentations about them happening that week.

- [Documentation for all the EBCs](https://drive.google.com/drive/folders/1UvD81FqkvuK-17kd9Ll2hX5awdqZ3QEE)
- [Q&A sheet](https://docs.google.com/spreadsheets/d/1AGORHiLbxQhomnRK5AqOSWX6898kZd_zxfOcnnKXu7w/edit#gid=0)

## Implementation Steps

Provide questions/comments on:

- [x] First half of EBCs - due 12/7
- [x] Second half of EBCs - due 12/9

## Acceptance Criteria

- [x] Any questions have been submitted to [tracker](https://docs.google.com/spreadsheets/d/1AGORHiLbxQhomnRK5AqOSWX6898kZd_zxfOcnnKXu7w/edit#gid=0)

**Comment by afeld** [comment]
Provided comments on first four, which have presentations Tuesday and thus need feedback sooner. Will do remaining four over next few days.

**Comment by afeld** [comment]
- [ ] @its-a-lisa-at-work provide feedback on [Supply Chain Support Cell (SC2) EBC](https://docs.google.com/document/d/1RBoK556lfGTvu0Pw6xfPcYqodmzu90xted0vX3F9SSI/edit)

**Comment by afeld** [comment]
Done with mine. @its-a-lisa-at-work let me know if you still have more you want/plan to do.

**Comment by afeld** [comment]
- [ ] Check in about TTS contributions

**Comment by afeld** [comment]
Outstanding question was answered.
