### ISSUE TITLE
TTS AWS Management Guide - 2021 Rollout

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#1044]
## Background Information

Closes and consolidates outcomes of:
- https://github.com/18F/aws-admin/issues/23
- https://github.com/18F/tts-tech-portfolio/issues/739
- https://github.com/18F/aws-admin/issues/39

This issue distills the remaining tasks for the issues referenced above, this issue was created to track the implementation and communication to TTS Programs for how we will be managing AWS at TTS.

The [TTS AWS Management Guide](https://github.com/18F/aws-admin/tree/master/docs) was created to holistically address "how we intent to manage AWS at TTS". The document covers the technical details around A&A, change control, account provisioning, management, and baseline configuration.

## Implementation Steps
- [x] Prereqs
   - https://github.com/18F/aws-admin/issues/102
   - https://github.com/18F/aws-admin/issues/103
- [x] Determine where it will live - https://before-you-ship.18f.gov/
- [x] The Guide has been circulated for a 2 week comment period - n/a we will point teams to it once published
- [x] TTS Programs Infrastructure Roadmaps are linked to in the Guide - https://github.com/18F/tts-tech-portfolio/issues/1020 - NA the findings from the interview will be apart of the guide/guidance
- [x] The Guide covers A&A implementation as-is and future state - https://github.com/18F/aws-admin/issues/47
- [x] An issue is created for updating TTS Handbook or Before-you-ship website

## Acceptance Criteria

- [x] (Initial) rules and information about configuration of AWS in TTS are documented

**Comment by afeld** [comment]
This issue is too large; let's split to smaller pieces.

**Comment by afeld** [comment]
Question from @its-a-lisa-at-work: Will this ensure all systems incorporate a security stack?

**Comment by its-a-lisa-at-work** [comment]
should we change this back to `g:initial` so that we can go back and groom it?

**Comment by adborden** [comment]
@JJediny and I think the common controls work (https://github.com/18F/tts-common-controls/issues/3 and others) will continue to refine the AWS Management Guide.
