### ISSUE TITLE
read up on NewPay - due 12/7

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1048]
## Background Information

Got invited to a meeting with the HR QSMO — want to do a bit of research on NewPay to have some context.

## Implementation Steps

Read:

- [x] https://www.gsa.gov/shared-services/newpay
- [x] https://interact.gsa.gov/group/newpay-initiative/information
- [x] https://federalnewsnetwork.com/reporters-notebook-jason-miller/2020/11/general-services-administration-newpay-and-application-modernization/
- [ ] [Executive Business Case (EBC)](https://docs.google.com/document/d/1btlsm9LvCHrSCBC8_UsWM1SseMIh1Hdm/edit?rtpof=true)

## Acceptance Criteria

- [x] Gain a high-level understanding of NewPay

**Comment by afeld** [comment]
Read up enough, and they gave an overview in the meeting anyway.
