### ISSUE TITLE
decommission `Department of Labor - Wage and Hour - Section 14c` repository

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#105]
https://github.com/18F/dol-whd-14c

Seems the 18F work has ended, but the issues are still active. Doesn't make sense for it to stay under the 18F org as is.

- [ ] Figure out 18F stakeholders, if any remain
- [ ] [Transfer repository](https://handbook.18f.gov/github/#rules) to Department of Labor, or
- [ ] Archive the repository
- [ ] Remove the GitHub [users](https://github.com/orgs/18F/teams/dol-whd-partner/members) (that aren't TTS staff) and [team](https://github.com/orgs/18F/teams/dol-whd-partner)

See email thread `Zenhub Problem`.

cc @18F/dol-whd-partner

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.

**Comment by mgwalker** [comment]
For context on this one should it ever get revisited, we tried _several times_ to get the tech lead on the DOL side to transfer the repo, and they never could/would. I think there were administrative problems at first, and then they were just too busy. They had moved development into their local on-prem Gitlab but were still using Github for issues. Presumably now that the repo has been archived, they can't use the issues anymore, and it seems like it should be safe to remove the partners from the TTS org/teams.

**Comment by PrabhakarThummalaDOL** [comment]
@mgwalker 
Greg, we are still using the Github for the issues. Is there a way to import/export all the issues from github? Currently we are copying the issues manually. And please do not remove us from the list. Thanks.

**Comment by afeld** [comment]
@PrabhakarThummalaDOL Hey there, good to hear from you. Depends what you want them exported _to_, I suppose. The short answer is: they can be exported using the GitHub API. There are definitely tools out there that _use_ that API and might do what you want. Examples:

- https://developer.github.com/v3/issues/#list-repository-issues
- https://docs.gitlab.com/ee/user/project/import/github.html
- https://backhub.co/
- https://stackoverflow.com/questions/41369365/how-can-i-export-github-issues-to-excel

That said, we don't plan to delete the repository, so the issues will remain readable/linkable. Does that answer your question?

**Comment by binwang89** [comment]
@afeld  Yes, please keep our repository readable/linkable.  we will try to export the issues from github to DOL gitlab repository.  thanks 

-Michelle
