### ISSUE TITLE
lay out options for different engineering org structures

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1050]
- [Reading notes](https://docs.google.com/document/d/10c67oU37KAi_hhg10zWkcp-5TWqLXvEJL-0iR8nuIn0/edit#heading=h.az0p0fg4fjhz)
- [Deck](https://docs.google.com/presentation/d/1aNpduPDUVgoPY7X12cBbCUuDvw5QZ52nXedwUMIzzDE/edit#slide=id.p)

## Background Information

Broken out from https://github.com/18F/tts-tech-portfolio/issues/777.

There are a _lot_ of resources out there about different ways to organize engineering teams. They need digesting.

## Implementation Steps
- [x] Collect list of things to read
- [x] [Solicit suggestions from TTS](https://gsa-tts.slack.com/archives/C3F3HR717/p1606343138059200?thread_ts=1606343138059200&cid=C3F3HR717)
- [x] Read and take notes

## Acceptance Criteria

- [x] There is a list of options with tradeoffs of each

**Comment by afeld** [comment]
First round complete.
