### ISSUE TITLE
conduct interviews about engineering pain points and opportunities in Solutions

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1051]
## Background Information

Broken out from https://github.com/18F/tts-tech-portfolio/issues/777.

There are a lot of people within Solutions who could be affected by a change to how we structure engineering, so want to make sure that their input is heard and considered.

## Implementation Steps
- [ ] Seed list of interviewees
- [ ] Get a note-taker
- [ ] Ask for additional volunteers
- [ ] Reach out to set up times
- [ ] Interviews complete
- [ ] Summarize

## Acceptance Criteria

- [ ] The pain points and hopes for a sample of people in Solutions (engineering-wise, at least) have been documented

**Comment by afeld** [comment]
- We've kinda done this through #1020 
- Lots captured in the [Engineering @ Solutions notes](https://docs.google.com/document/d/1jm5mDHeZQtwulXVtldBU8te7WyeH_MKwNTgoXvGGM7U/edit?usp=sharing)
- This arguably isn't the Tech Portfolio's responsibility

Therefore, going to close.
