### ISSUE TITLE
prep presentation for new TTS Commissioner - due 12/21

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1055]
[**Slides**](https://docs.google.com/presentation/d/1z_dJpqNr4GVUAdyRJAXdRzDjcFZfJBmJCjBv3W18jAs/edit#slide=id.p)

## Background Information

@DsaleGov suggested giving Dave Shive a presentation on the state of TTS' infrastructure.

## Implementation Steps

- [x] Get date set
- [x] Determine scope of meeting in terms of attendees
- [x] Work out exactly the scope of what we want to cover with @DsaleGov. Things that he mentioned so far:
   - Current state of infrastructure
   - Consolidation plan
- [x] Create an outline
- [x] Solicit input from the Tech Portfolio

## Acceptance Criteria

- [x] Presentation ready

**Comment by afeld** [comment]
We'll make some minor tweaks right up until the meeting I'm sure, but the deck is in good shape.
