### ISSUE TITLE
InVision Transition off - due December 31st

### ISSUE THREAD

**Issue by melanienleopold** [18F/tts-tech-portfolio#1059]
## Background information

InVision has declined to go through FedRAMP. We need to notify the program office that InVision will no longer be able to be used moving forward. The easiest route is to let the InVision contract expire, instead of renewing the next option period on 3/14/20.

## Implementation Steps
- [x] Alyssa send @melanienleopold previous announcements of transitions
- [x] Set up a time to mention decision with key stakeholders
- [x] Make title more clear
- [ ] Draft transition statement 
   - [ ] Run it by @annepetersen for review
- [ ] Reach out to InVision to understand why they don't want to pursue
- [ ] Announce to TTS
- [ ] Let IT Security know
- [ ] Let CTO/IT Standards know
  - [ ] Request that it be properly reflected in GEAR
- [ ] Update Software Smartsheet

## Acceptance criteria

- [ ] TTS is notified that InVision will need to be rolled off of by 3/13/20 when InVision's Option is to be exercised.

---

**Comment by melanienleopold** [comment]
Meeting 12/14 with the program office.

**Comment by melanienleopold** [comment]
Met with InVision on 12/22. They are asking internally if they can pursue FedRAMP. This is the first time a government customer has come to them saying they need to get FedRAMP or the customer would not use InVision anymore. They feel this could be the push they need to get those in the position to make the decision to pursue FedRAMP. They will get back to us as soon as possible.

**Comment by melanienleopold** [comment]
InVision has committed to going through FedRAMP. Once they send it in writing, I will close this issue and open a new one for exercising the Option Period.

**Comment by melanienleopold** [comment]
Asked for another meeting. The security team gave different information than the contracting team.

**Comment by afeld** [comment]
@melanienleopold will split out separate issues; closing this in the meantime, as it seems there is a path forward.
