### ISSUE TITLE
Review Documentation

### ISSUE THREAD

**Issue by c-manger** [18F/tts-tech-portfolio#106]
- [x] https://drive.google.com/drive/folders/1BybZ1RZeL6Ul3gxH9By_NsmLwr7u5E_G
- [x] https://docs.google.com/document/d/1_psMhMYdn0RLRzymcV6Jhw1URioebzzNH6yMHCgKk6Y/edit
- [x] emails
- [x] https://docs.google.com/spreadsheets/d/1L_tApOrPp5Gm_Twbdgsjutin1ZpFeYbZfWHFo4cDfFE/edit#gid=2094820121
- [x] https://docs.google.com/spreadsheets/d/1oHJWEKQZKs8qHAYWS6NUgqAHsEvdINIDvyJ8qjlrCaE/edit#gid=390094063
