### ISSUE TITLE
Update ATO issue template

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1063]
## Background Information

[The ATO template](https://github.com/18F/tts-tech-portfolio/blob/master/.github/ISSUE_TEMPLATE/ato.md) is all sorts of out of date and is currently being used heavily. 

## Implementation Steps
- [x] Review current (Custom Software) ATO Issue Template
- [ ] Implementation Plan
  - [x] Replace anything that has stayed the same, but just changed
  - [x] Remove anything that is currently not true anymore
  - [x] Make changes to improve what is there
- [x] Make announcement of the change
- [x] Directly tell people who have current issue of the change
- [ ] Remove [existing issue template](https://github.com/18F/tts-tech-portfolio/blob/master/.github/ISSUE_TEMPLATE/ato.md) and references to it

## Acceptance Criteria

- [ ] ATO Issue Template is updated and only has recent and relevant instructions

**Comment by its-a-lisa-at-work** [comment]
Did some work related to this, moving to `Waiting/Feedback' until I get some feedback on https://github.com/18F/tts-tech-portfolio/issues/1132

**Comment by its-a-lisa-at-work** [comment]
Added these to the [new checklist](https://app.smartsheet.com/sheets/WCJPc4RqJGHwMhMGw3GJFFfVfg275gwWrQxWRM81), thanks! The idea is that this checklist is going to get deleted in favor of the Smartsheet checklist that is more versatile for the different types of systems that we have and does a better job at tracking dates.

**Comment by its-a-lisa-at-work** [comment]
Moving to `Blocked` until Smartsheet roll out is finish and can sunset the GitHub template in favor of the Smartsheet

**Comment by afeld** [comment]
[Took some notes as I was introduced to the Smartsheet version](https://docs.google.com/document/d/1aBZjFKv6fjYChOzBxv2Xbm9mvZvqh68_aLXA6ljgOJs/edit)
