### ISSUE TITLE
Broken link site scanning for TTS applications

### ISSUE THREAD

**Issue by adborden** [18F/tts-tech-portfolio#1068]
## Background Information

In order to prevent stale/broken link takeovers on TTS applications, TTS developers want an automated broken link checking as a service that they can configure for their own applications.

Broken link checking is a common need for web applications. In most cases, it helps to keep information up-to-date. In rare cases, it can also prevent low-severity security issues if the [stale link can be taken over](https://hackerone.com/reports/1035400). Having a TTS-wide service would help provide better services to users and keep our applications more secure.

## Implementation Steps
- [ ] Developers can register a URL to be scanned
- [ ] Developers can add exceptions for specific URLs

## Acceptance Criteria

- [ ] GIVEN I add my TTS application to this service
  AND my application contains a broken link
  WHEN the automated scan runs
  THEN I get a report listing the broken links that I can take action on

**Comment by afeld** [comment]
@adborden Is this urgent, or is this a nice-to-have?

**Comment by adborden** [comment]
Nice to have.

**Comment by afeld** [comment]
Not planning to tackle in next six months, so closing. Might be an idea to bring up with the Spotlight team. For static sites, suggest using [HTML Proofer](https://github.com/gjtorikian/html-proofer).
