### ISSUE TITLE
Learn coding by bumping Before-You-Ship  from 3.17.3 to 3.17.4

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1069]
## Background Information

https://github.com/18F/before-you-ship/pull/495

## Implementation Steps
- [ ] Research if there are similar sites to Before You Ship that this has been done already
- [ ] Take a look to understand what is happening
- [ ] Come up with a strategy of what needs to be done
- [ ] Request someone to pair so you can walk them through the logic
- [ ] Make updates 
- [ ]  submit PR

## Acceptance Criteria

- [ ] PR is merged
