### ISSUE TITLE
Get everyone in TTS Smartsheet access

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1070]
## Background Information

Alyssa started to put together a group of all of TTS folks within TTS. Some people were not able to be added because they had never signed into SmartSheet for the first time. 

## Implementation Steps
- [x] Get consensus that Tech Portfolio wants everyone in TTS to have access
- [x] Create form for folks to fill out
- [x] Draft language to be sent out to TTS
- [x] Have Outreach send an announcement

## Acceptance Criteria

- [x] Everyone in TTS has logged into Smartsheet

**Comment by afeld** [comment]
Waiting for the migration to Gov.

**Comment by its-a-lisa-at-work** [comment]
Sent @AndreaSigz an email with the recent prompt from GSA IT and sent a message through [slack](https://gsa-tts.slack.com/archives/C03CPV8KK/p1609863925048500) requesting assistance with this

**Comment by afeld** [comment]
cc https://github.com/18F/handbook/issues/2269

**Comment by afeld** [comment]
@its-a-lisa-at-work Is there anything we should be sending out TTS-wide about this?

**Comment by its-a-lisa-at-work** [comment]
Let's take this to slack and include @melanienleopold -- I think sending out TTS-wide info would fall into a Software Concierge activity -- my purpose was scoped specifically to getting folks access to the Software List since we moved it over to Smartsheet
