### ISSUE TITLE
add Level 1 and 2 ratings to Performance Plan - due 7/1

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1071]
## Background Information

Broken out from https://github.com/18F/tts-tech-portfolio/issues/714#issuecomment-741983686. Deadline above is the hard deadline of 120 days out from the end of the Fiscal Year.

## Implementation Steps

- [x] [Confirm this does not have the same deadline as establishing a (preliminary) FY21 Plan](https://gsa-tts.slack.com/archives/C2L9JPGS2/p1607540640045800)
- [ ] Write ratings
- [ ] Get sign-off from team
- [ ] Re-submit in HRLinks
- [ ] All Performance Plans re-acknowledged

## Acceptance Criteria

- [ ] All measures have descriptions for Level 1 and 2 ratings for all team members

**Comment by afeld** [comment]
Not necessary.
