### ISSUE TITLE
Get 'Need by Date' for custom system ATOs

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1075]
## Background Information

Let's find out if there are firm deadlines.

## Implementation Steps
- [x] Get a Need by Date from the sites

   - [x] Acuant COFRS
   - [x] Touchpoints (TP)
   - [x] Federalist
   - [x] Api.Data.gov
   - [x] Data.gov
   - [x] Tock
   - [x] Code.gov
   - [x] Search.gov
   - [x] analytics.usa.gov
   - [x] GIVE (Identity)
   - [x] Forms as a Service
   - [x] Privacy Dashboard
   - [ ] Site Scanner
   - [x] challenge.gov
   - [x] AI Use Case Library (ai.gsa.gov)
   - [x] Charlie
   - [x] 10x.gsa.gov
 

## Acceptance Criteria

- [ ] The [TTS Software Assurance sheet](https://docs.google.com/spreadsheets/d/19wyA91KhGoZvnAA0fihC0WF_mU79YLRTHzDd-Frs8Qs/edit#gid=0) is updated with the dates

**Comment by its-a-lisa-at-work** [comment]
@gbinal let me know when you have a date; a rough estimate is good at this point so we can help prioritize and get ya'll on the assessment schedule.

**Comment by gbinal** [comment]
Roger that (sorry to be the last one on this list!).  Chatting you in Slack now.
