### ISSUE TITLE
prep for Slack Enterprise Grid migration - due 1/1

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1076]
## Background Information

There's some cleanup and prep work that is required before migrating TTS' Slack workspace to Enterprise Grid. Setting due date a week out so Slack can run a pre-migration report again and we can find any remaining required cleanup with enough lead time. [Notes from meeting](https://docs.google.com/document/d/1-nPzPUNL35VWCLgtR5iEiOSaExPChTHLi_9lZX5mODg/edit) where we laid out a lot of these TODOs.

## Implementation Steps

May make sense to split some of these into individual issues.

### Due 1/1

Before we have Slack run another report.

- [x] [Ensure all Full Members have GSA emails](https://docs.google.com/spreadsheets/d/1er7c9dCUyOrqAEqN1Y0B5Rqs74TDtiHjc2CRNqQz198/edit?ts=5fd38ab5#gid=102427456&fvid=299065490)
   - For those who have GSA emails, let them know and [switch the emails on their accounts](https://gsa-tts.slack.com/admin)
   - Remainder need to be converted to Guests (likely Multi-Channel — will need to check what they should have access to)
- [x] GSA IT: [Where usernames match](https://docs.google.com/spreadsheets/d/1er7c9dCUyOrqAEqN1Y0B5Rqs74TDtiHjc2CRNqQz198/edit?ts=5fd38ab5#gid=58880101), ensure emails match
   - For users with [short name](https://insite.gsa.gov/cdnstatic/insite/SOP-SNA_ShortName_Request_Procedure_%281%29_%281%29.pdf) emails, notify the users and switch them to those
   - For names we don't recognize, email the GSA address and check if the non-GSA email is theirs
      - If they're not the same person, we should change the usernames on the GSA side
   - For others, notify the users and switch to their GSA emails
- [x] [Review where access level is different between TTS and Grid](https://docs.google.com/spreadsheets/d/1er7c9dCUyOrqAEqN1Y0B5Rqs74TDtiHjc2CRNqQz198/edit?ts=5fd38ab5#gid=1913960411) and confirm we are comfortable with higher level permission
   - Document which single channels each have access to
- [x] GSA IT: Convert `#gsait-shared` to a public channel on the GSA IT side
   - [x] Check if it's possible for Slack to convert a channel from a private to public - it isn't
   - [x] Rename `#tts_gsait` to `#tts_gsait-old` on the GSA IT side
   - [x] Send a new shared channel request from the TTS side
   - [x] Create a new public channel on the GSA IT side to be shared

### Due 1/8

Before the migration itself.

- [ ] GSA IT: Move all users with gsa.gov emails to the Google access group
- [x] Slack: Confirm what happens with message history (direct messages, and attribution for messages in channels) for duplicate users
- [x] [Draft communication to be sent to all users](https://docs.google.com/document/d/1Bqk9ihBnTYeCFaMj6zYyJ2UxJAgCQiWmODrVgrLXgPA/edit)
   - [x] [Get a copy of the message that gets sent by Slack](https://slack.enterprise.slack.com/files/W015REG3JG6/F01H31VLK6V/enterprise_grid_communications_template_for_customers__1_.docx)
      - [Another copy](https://gsa-tts.slack.com/archives/C01CVRM54S2/p1609806905015000?thread_ts=1609261365.011100&cid=C01CVRM54S2)
   - [ ] Get a copy of the message that GSA IT has sent for past migrations
   - [x] Everyone will be signed out; sign back in through Google
   - [x] If using on mobile, make sure your app is up to date
   - [x] If having trouble signing in, contact Slack support
   - [x] Expected downtime of ~3 hours
   - [x] For Guests, they will still sign in with username and password
   - [x] Send
- [x] Draft communication to drop in all shared channels
   - [x] Send
- [x] Draft an update to the Slack Handbook pages - https://github.com/18F/handbook/pull/2301

## Acceptance Criteria

- [x] TTS has a clean pre-migration report

**Comment by afeld** [comment]
They are going to run another pre-migration report, but we expect it to be clean, so closing this.

**Comment by afeld** [comment]
Follow-up tasks: https://github.com/18F/tts-tech-portfolio/issues/1159 https://github.com/18F/tts-tech-portfolio/issues/1077
