### ISSUE TITLE
ensure custom Slack emoji are reviewed before use

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1077]
In order to quickly add new emoji to express feelings and communicate more clearly over text chat, TTS Slack users want a lightweight process for emoji approvals that conforms with the GSA IT Rules of Behavior.

## Background Information

Broken out from https://github.com/18F/tts-tech-portfolio/issues/925#issuecomment-743351908.

## Implementation Steps

- [x] Determine feasibility of notification / posting to a channel when new emoji are added
- [x] Restrict creation to admins
- [x] Get Workflow from Slack
- [x] Document the process
- [x] Get consensus from Slack admins

## Acceptance Criteria

- [x] There is a documented mechanism/procedure for review of new custom emoji

**Comment by afeld** [comment]
Added a soft deadline.

**Comment by afeld** [comment]
Kevin Carter from Slack mentioned that another agency is using [Workflow Builder](https://slack.com/help/articles/360035692513-Guide-to-Workflow-Builder) to achieve this, which would be great since it wouldn't require any custom code. He's going to send that example.

**Comment by tbaxter-18f** [comment]
Just a note (and I hope this is the right place) that I think losing the ability to have custom emoji would be a huge cultural shift and loss to TTS.

**Comment by afeld** [comment]
For others who come across this issue: Please refrain from other comments debating whether this should or shouldn't be the case. The issue has been discussed at length by TTS and GSA IT leadership, and [this policy update](https://github.com/18F/tts-tech-portfolio/issues/925#issuecomment-756994321) is the result. This issue is about finding a way to support custom emoji creation in compliance with that policy with minimal friction.

**Comment by afeld** [comment]
[Workflow](https://gsa-tts.slack.com/archives/C01CVRM54S2/p1610574227019700)

**Comment by afeld** [comment]
Since emoji creation is disabled for members (and thus we are in compliance with the policy), removing the due date.

**Comment by afeld** [comment]
[Idea for using voting as the approval mechanism.](https://gsa-tts.slack.com/archives/C0X2T36AY/p1621527383017200) We'll see how complicated it will be to implement.

**Comment by adborden** [comment]
@afeld the workflow file from [slack](https://gsa-tts.slack.com/archives/C01CVRM54S2/p1610574227019700) has been deleted (or archived?). I don't suppose you have a copy of it?

**Comment by adborden** [comment]
I was able to create a workflow implementing this outline of a process. We're still missing the most important part of the workflow, the emoji publish (more on that below).

1. Requester opens #emoji-showcase in Slack.
2. Requester uses the workflow button (lightning bolt) and selects "Request new emoji"
3. Fill out the form (name and URL)
4. #emoji-showcase receives the request
4. Private channel #admin-emoji receives the request
5. After review, #admin-emoji click "Approve" button
5. Once published, #emoji-showcase will be notified.

To keep the implementation simple, #admin-emoji is private only so that a requester cannot approve their own emoji. Workflows don't have logic to say "if approver is not requester...". But it's not important who the approvers are. It could be a group of volunteers and it doesn't need to be restricted to tts-tech-portfolio.

There is no "Reject", ignoring the request is the simplest solution to implement. #admin-emoji can reach out to the individual requester directly. Workflows only support one button, but we could use an emoji trigger to approve, reject, etc, it's just _slightly_ more effort.

On the emoji publish part, I'm not seeing how to call Slack APIs from the Workflow. From what I gather in the docs, you need to create a Slack App to handle this part. However, the linked Slack conversations seem to say it's possible without an App, but I'm missing the context. Maybe I need Slack admin permissions? Anyway, could use some pointers on this part. I'll keep digging.

**Comment by adborden** [comment]
I'm on the fence about the request being public or not (posting the emoji name/URL to #emoji-showcase before it's approved). I feel like transparency and openness are good and would discourage abuse, but I also think that visibility can be problematic. If an emoji is offensive to someone, the damage is done before it was even approved. I'm leaning toward keeping it private.

**Comment by adborden** [comment]
I added a user story above based on my understanding of the problem.
> In order to quickly add new emoji to express feelings and communicate more clearly over text chat, TTS Slack users want a lightweight process for emoji approvals that conforms with the GSA IT Rules of Behavior.

**Comment by adborden** [comment]
Unfortunately, this is getting a bit complicated. I've asked Kevin from Slack to clarify, but the example workflow requires the emoji admin to _manually_ add the emoji and then click the "Emoji has been created" button to continue the workflow. I'm pretty confident that Slack only offers sending messages or sending forms as workflow steps. Anything additional requires installing/developing an App.

![Screen Shot 2021-06-02 at 5 03 27 PM](https://user-images.githubusercontent.com/509703/120566740-c4effa80-c3c4-11eb-96ea-8b1551635ce7.png)

@mgwalker has offered to give me a tour over https://github.com/18F/charlie, so I don't expect it to be difficult to build the App. I assume we have an existing ATO to bundle this into.

I also want to sync up and make sure we have buy-in from the Slack Admins. Whether manual or automated, adding emoji likely requires admin permissions. The [admin.emoji.add API](https://api.slack.com/methods/admin.emoji.add) requires [admin.teams:write](https://api.slack.com/scopes/admin.teams:write) scope, which does quite a bit more than just emoji. We could delegate creation to #admins-slack, they are pretty quick.

**Comment by adborden** [comment]
Have a draft PR to the handbook ^ describing our ideal process. We'll update this PR as our implementation converges.

We're currently on hold as our options for the actual publishing of emoji (manually or automated) requires Slack admin permissions. We'll be discussing this with the Slack team next week.

**Comment by adborden** [comment]
We just met with the GSA Slack team (Amar) and they are fine to start with a manual approach. They'd love to see the automation bit too, but we'll start with the manual slack workflow which keeps this simple. They requested that approved emojis end up in a new channel separate from #admins-slack, so we'll update the workflow with this in mind.

**Comment by adborden** [comment]
Workflow and [draft documentation](https://github.com/18F/handbook/pull/2502) updated. I even created a [demo](https://drive.google.com/file/d/1iKUE2GuFpFOX6j_UjLleYvKTarSzEUAa/view?usp=sharing).

Next step is to test the workflow with the GSA Slack team.

**Comment by adborden** [comment]
We've got some time on the calendar for Tuesday.

**Comment by adborden** [comment]
First emoji was successfully created following the new process. We've announced this to a few channels and will continue to monitor with GSA IT for any process tweaks.
