### ISSUE TITLE
Standup the GSA Software Assurance Working Group

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1080]
## Background Information

Breaking out the SCRM WG into smaller working groups and leading the software group. Need to get this launched. 
## Implementation Steps
- [x] Reach out to folks interested
- [x] Set up a time to talk
- [ ] Create agenda
   - [ ] Future Meeting decisions
       - [ ] Meeting Frequency
       - [ ] Inter meeting communication methodology
       - [ ] Decide on artifacts
         - [ ] Charter?
         - [ ] Roadmap?
- [ ] Take action items

## Acceptance Criteria

- [x] First meeting scheduled
