### ISSUE TITLE
Setup an Automated CIS Benchmark Scan for all managed GCP accounts

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#1082]
MITRE has developed a set of inspec benchmarks mapped to NIST Controls for GCP - https://github.com/mitre/inspec-gcp-cis-benchmark. There is also https://github.com/devsec profiles, both also have k8s CIS benchmarks for GKE. No known complimentary terraform hardening modules are tied to the inspec test directly.

## Implementation Steps
- [ ] Setup inspec to run as part of CI against all accounts as a:
   - [ ] CRON runner
   - [ ] part of the standard PR (might be too long to run each time)
- [ ] Determine how to best store/track/display test results
   - [ ] consider deploying https://github.com/mitre/heimdall2 as a cloud.gov app to serve as a `{{ account }}-{{ timestamp }}.json` endpoint to save and diff results over time
   - [ ] forgo tracking and just invest in upfront remediation to assume 100% pass

## AC
- [ ] GCP CIS Benchmark status is known and tracked continuously for all managed accounts

**Comment by JJediny** [comment]
Needs to be reassessed during PRISMA implementation cc @nateprice18f @MichaelSides
