### ISSUE TITLE
Formalize Melanie's Detail

### ISSUE THREAD

**Issue by melanienleopold** [18F/tts-tech-portfolio#1100]

**Comment by melanienleopold** [comment]
## Background information

Melanie is on a detail to the Tech Portfolio and has been since July. The detail is not formal and should be in writing.

## Implementation Steps
- [ ] Melanie write out roles and responsibilities on the Tech Portfolio
- [ ] Supervisors on both teams review
- [ ] Take any HR actions necessary

## Acceptance criteria

- [ ] Melanie's detail is accepted by OA and the Tech Portfolio

**Comment by afeld** [comment]
No longer necessary.
