### ISSUE TITLE
Policy Recommendations: FedRAMP Cloud Computing Definitions Draft Policy Memorandum

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1101]
## Background Information

TTS and OGP have been working together to work on unblocking certain policies that prevent emerging technology to be widely adopted by the federal government. 

## Implementation Steps
- [x] Read FedRAMP exception for [social media](https://docs.google.com/document/d/1nHYc8egAIHvx8FSAZlZRvHKl2mSjaQ_Ejf7qcXhGbb8/edit?usp=sharing)
- [x] Provide comments
- [ ] Set up meeting to discuss

## Acceptance Criteria

- [x] Recommendations are provided to OGP

**Comment by afeld** [comment]
In same email as https://github.com/18F/tts-tech-portfolio/issues/1102.

**Comment by its-a-lisa-at-work** [comment]
Requested comment access and provided the comments in the request. 

Moving to `Waiting/Feedback` until get access or suggestions on how to proceed forward

@melanienleopold there wasn't anything that stood out to me particularly that would be of concern fo you; it is a really easy 5 minute read (for me), so you're welcome to pass on any comments, concerns or suggestions through me and I'll make sure they get added when I include mine

**Comment by its-a-lisa-at-work** [comment]
Got access to the documents, waiting to hear from Jimi on whether or not the comments I put in the request were received

**Comment by its-a-lisa-at-work** [comment]
Comments provided and accepted; no further action at this time so closing
