### ISSUE TITLE
Policy Recommendation: Open Source Software as an Alternative for the Federal Government

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1102]
## Background Information

TTS and OGP have been working together to work on unblocking certain policies that prevent emerging technology to be widely adopted by the federal government. 

## Implementation Steps
- [x] Read open source software as an alternative to [buying software](https://docs.google.com/document/d/1PS6ZlrxgtVyL28URt3S2N37ZFpH1KG6XLNF8JT2s7xc/edit?usp=sharing)
  - [x] @its-a-lisa-at-work 
  - [x]  @melanienleopold 
- [x] Provide comments
- [ ] Set up meeting to discuss

## Acceptance Criteria

- [ ] Recommendations are provided to OGP

**Comment by its-a-lisa-at-work** [comment]
Ahh @melanienleopold I changed the titles, this is actually the one that you should be listed on. Let's tag up on this one and see how we want to approach this on behalf of TTS. 

My high level thoughts are:
- Not sure why this needs to be done through policy and isn't something we could just do in a Before You Buy playbook cc: https://github.com/18F/tts-tech-portfolio/issues/769

**Comment by melanienleopold** [comment]
I read through it. I have the exact same question as you. @its-a-lisa-at-work let me know if you want to sync up on this.

**Comment by its-a-lisa-at-work** [comment]
Ok, left the comment in the doc; going to move this to `waiting/feedback`

**Comment by its-a-lisa-at-work** [comment]
Comments provided and accepted; no further action at this time so closing
