### ISSUE TITLE
revisit Initiative ownership

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1105]
## Background Information

We have imbalance in terms of the number of Initiatives per team member, as well as the number of issues contained within each.

## Implementation Steps

- [x] Define the problem
- [x] Consensus about what Initiatives exist
- [x] Decide if any Initiatives should be split up
- [x] Update labels - https://github.com/18F/tts-tech-portfolio/pull/1319
   - [x] Replace labels that are being removed on open issues
- [x] Update issues in `Initiatives` column
   - [x] Reassign
- [x] Confirm that split is even, in terms of number of Initiatives and/or the issues they contain

## Acceptance Criteria

- [x] There is consensus among the team about the split/size/scope of our Initiatives

**Comment by afeld** [comment]
- [Mural](https://app.mural.co/t/gsa6/m/gsa6/1612556998913/a6be3c6d3ca3b5ff41a8cc99f50e21ea97600aa9)
- [Problem/goals](https://docs.google.com/document/d/1ynxrt_5rBrGX67VnDjcqT457MWMfCkzvEFgYEub73Sc/edit#heading=h.9yal55cvuffg)

**Comment by afeld** [comment]
Snapshot of the number of open issues each:

- [`custom software`](https://github.com/search?q=is%3Aopen+user%3A18f+label%3A%22i%3A+custom+software%22): 59
- [`customer support`](https://github.com/search?q=is%3Aopen+user%3A18f+label%3A%22i%3A+customer+support%22): 14
- [`infrastructure`](https://github.com/search?q=is%3Aopen+user%3A18f+label%3A%22i%3A+infrastructure%22): 52
- [`internal team`](https://github.com/search?q=is%3Aopen+user%3A18f+label%3A%22i%3A+internal+team%22): 23
- [`misc`](https://github.com/search?q=is%3Aopen+user%3A18f+label%3A%22i%3A+misc%22): 46
- [`SaaS`](https://github.com/search?q=is%3Aopen+user%3A18f+label%3A%22i%3A+SaaS%22): 29

A relatively even split!
