### ISSUE TITLE
tech Q&A

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1108]
## Background Information

Megan Reed and I were chatting, and she had a great insight:

There is a widely-held (but unspoken) assumption that all TTS staff have some baseline level of technical knowledge, but that is not necessarily accurate. There may be folks who have questions about what our systems do, what different jargon means, etc., but may not feel like they have a place to ask.

We already have the `#questions` Slack channel, but I was thinking something more dedicated and anonymous, like a Q&A session driven by a Google Form with anonymous submissions to "What tech questions do you have but have been too afraid to ask?"

## Implementation Steps
- [ ] Ask for feedback from Outreach
- [ ] Schedule it
- [x] Set up a form

## Acceptance Criteria

- [ ] Roll out a test way for folks to get tech questions answered

**Comment by afeld** [comment]
@KendrickDaniel @echappen @Sgtpluck @jadudm expressed interest in picking this up.

**Comment by echappen** [comment]
Our group has [made a form](https://forms.gle/dTCqHsciLQP37uvK8) that we'd like to share widely across TTS. It asks about what kinds of questions folks are too afraid to ask at work. 

We're thinking this can be used as a starting point to gauge how these questions can or should be answered. Answering them might take many different approaches, but first we need to gather data. 

The form's open to anyone in TTS, regardless of position. Please help us share it!: https://forms.gle/dTCqHsciLQP37uvK8

**Comment by afeld** [comment]
Great! Seems like the Acceptance Criteria was met here…good to close?

**Comment by afeld** [comment]
You might want to try something like setting up a recurring reminder in #questions or whatnot. Since this seems like it's done, closing.
