### ISSUE TITLE
Personally explore Mulesoft capabilities

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1111]
## Background Information

Heard from security in a meeting today that there is now policy in place to use Mulesoft. 
- https://insite.gsa.gov/cdnstatic/insite/Robotic_Process_Automation_%28RPA%29_Security_%5BCIO_IT_Security_19-97_Rev_2%5D_03-31-2020docx_%282%29.pdf

https://insite.gsa.gov/cdnstatic/insite/Mulesoft_API_Security_Process_%5BCIO_IT_Security_20-108_Initial_Release%5D_09-18-2020docx_%281%29.pdf

Timebox to a certain number of hours.

## Implementation Steps
- [ ] Read policy
- [ ] Get access to tool
- [ ] Spend time using tool
- [ ] Demo tool for team
- [ ] Provide write up on tool experience and where tool might fit in throughout org

## Acceptance Criteria

- [ ] Information shared with TTS (Slack, Guild meeting, whatever) about what Mulesoft is and what it could be useful for
