### ISSUE TITLE
TTS Tech Radar: Security Tools (Continuous Authorization)

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1113]
## Background Information

User story from @lauraGgit : As someone developing custom developed software, I would like a way to continually assess the security posture of the system that I am developing so that I do not have to have to disrupt developers as they are working. 

Breakout from: https://github.com/18F/tts-tech-portfolio/issues/1084

## Implementation Steps
- [ ] Conduct further user research
- [ ] Look into what we currently have
- [ ] Document current state
- [ ] Add to roadmap for future state

## Acceptance Criteria

- [ ] Gaps with current inventory of tools is known an a plan to fill the gap is documented

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/1237.
