### ISSUE TITLE
TTS Definition of 'System'

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1114]
## Background Information

Want to think about Mission and Business needs and the Information Technology that supports these needs holistically. For consideration, something like the Micropurchase Bot or the FITARA review or the Contract sheet -- might not be considered as Systems -- but they are a 'Tool' that People use for a Process; so while I don't think we should have to do FISMA reporting for these Systems, we should at least have an inventory of these systems existing and what the impact would be on the confidentiality, integrity and availability needs of these Systems. 

## Implementation Steps
- [ ] Review inventory of systems
- [ ] Conduct user research on what tools folks use for their job
- [ ] Document the data needs of these systems

## Acceptance Criteria

- [ ] Opinions on how to proceed are documented in a White Paper

**Comment by its-a-lisa-at-work** [comment]
"Currently, we have Tock ... it is currently a custom developed system and therefor needs an ATO. If/when it switches to SaaS -- the requirements and mission impact of the collection of needs will still remain. In my opinion, it will then be a Minor system within the Major system (whatever the SaaS is) and I wouldn't recommend decomissioning the system at the PIA or SORN level; but instead, expanding the definition of System and start tracking systems based on how they fit into the people, process and tools of TTS so that anything that enables the TTS mission is then categorized as a system so if/when it needs to be replaced then it will be easier to do so. 

This is and also relates to what is going on with AirTable; it is a system that many folks use and their individual should get its own categorization based on the data being used within the system. "
