### ISSUE TITLE
FIPS 199 Audit

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1115]
## Background Information

Related to https://github.com/18F/tts-tech-portfolio/issues/1114

## Implementation Steps
- [ ] Gather all FIPS 199 in TTS
 - [ ] Cloud Systems
 - [.] Custom Developed Systems
 - [ ] Other ['Systems'](https://github.com/18F/tts-tech-portfolio/issues/1114)

## Acceptance Criteria

- [ ] All Systems have up to date FIPS 199

**Comment by JJediny** [comment]
Team helps system owners do this as a part of their existing A&A, not planning to breakout a separate tracking effort. We will ensure these 3 are part of the ATO schedule.
