### ISSUE TITLE
Tech Talk - Step 1: System Categorization

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1116]
## Background Information

There has recently been a lot of new systems being developed and FIPS 199s seem to be coming up a lot lately. 

Would be great to make this a series going through the RMF steps and host it on digital.gov

## Implementation Steps
- [ ] Gather resources
- [ ] Collect recent use cases
- [ ] Put presentation together
- [ ] Update our information

## Acceptance Criteria

- [ ]

**Comment by afeld** [comment]
Closing as stale.
