### ISSUE TITLE
Implement Common Alerting / Alert Management Solutions

### ISSUE THREAD

**Issue by amitfreeman-gov** [18F/tts-tech-portfolio#1120]
## Background Information

As gatekeepers of TTS Infrastructure, we would benefit from consolidating and distributing common alerts generated by the infrastructure we oversee and/or manage.  Tools exists that assist in targetting alerts to specific teams / groups (e.g. OpsGenie, Pagerduty, NewRelic, etc), and a common implementation of these tools would allow for better distribution of the alerting we are putting in place

## Implementation Steps
- [ ] Evaluate tools already in use within TTS for suitability
- [ ] Solicit feedback from program teams with regards to what alerting tools they presently used and/or are willing to consolidate on
- [ ] Select tooling to which we will send alerts for appropriate fan-out

## Acceptance Criteria

- [ ] A tool is selected to distribute alerts authored by tech portfolio
- [ ] Groups are created for specific program team distribution of relevant alerts
- [ ] Program teams are onboard with receiving alerts from selected tool
