### ISSUE TITLE
Develop Software Concierge intake process

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1121]
## Background Information

Next step from https://github.com/18F/tts-tech-portfolio/issues/989

## Implementation Steps
- [x] Clarify when an ATO should be started and a checklist issue should be submitted to Tech Portfolio
- [x] Understand how the VPAT process fits into the Software Concierge Process

## Acceptance Criteria

- [x] A process is laid out for the Concierge to follow for new requests (from intake through IT Standards)

**Comment by afeld** [comment]
@melanienleopold Where do I find the doc for this?

**Comment by melanienleopold** [comment]
https://docs.google.com/document/d/1DBCuxMFE5anShLIRxUD1qE7eDffKsrNEtAscjCF978s/edit#heading=h.q97rrjg0jet7 sorry about that!

**Comment by afeld** [comment]
Left feedback — nice work!

**Comment by afeld** [comment]
Done re-reviewing. Some minor open comments in there, but we are good to keep going!
