### ISSUE TITLE
resolve "questionable" OpsGenie charge 

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1125]
## Background Information

There's a "questionable charge" that needs resolving.

## Implementation Steps
- [x] Create Pegasys log (CL) for OpsGenie purchase on 9/28
   - [x] "The log should include a description of what was purchased and the written pre-authorization and invoice or receipt should be uploaded to the CL."
   - [x] "The invoice or receipt should indicate what was purchased and the transaction amount."
- [x] Notify Janney this is complete

## Acceptance Criteria

- [ ] Purchase card is restored
