### ISSUE TITLE
better handling of frequent email alerts

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1130]
## Background Information

We get a bunch of emails, and it's not always clear if we need to act on them, or how best to do so. Example subject lines:

- `Let's Encrypt certificate expiration notice`
- DotGov `Domain <whatever>.gov is due for renewal`
- AWS
   - `Your AWS Abuse Report`
   - `deprecation notice`
   - `AWS Budgets: <budget> has exceeded your alert threshold`
   - `Attention required on case`
   - `Amazon EC2 Instance Retirement`
   - `Amazon EC2 Maintenance: Instance scheduled for retirement`

## Implementation Steps
- [ ] Split out issues for things to do _besides_ documenting what to do with them
   - For example, updating contacts for AWS accounts to ensure AWS alerts go directly to relevant teams (https://github.com/18F/aws-admin/issues/26)
- [ ] Update Ops Rotation checklist/documentation
- [ ] Unsubscribe / filter out things we don't need to care about

## Acceptance Criteria

- [ ] For alerts that (will still) regularly come to Tech Portfolio mailing lists, have documented procedure for handling

**Comment by rocheller123** [comment]
AWS email alerts will eventually be sent to the relevant contact's email address directly. Therefore, Tech Portfolio may not be required to send AWS-related emails to the programs.
