### ISSUE TITLE
Get feedback on the authorization checklists

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1132]
## Background Information

Prior to deprecating the current checklist that [exists](https://github.com/18F/tts-tech-portfolio/issues/new?assignees=&labels=g%3A+accepted%2C+i%3A+software+assurance&template=ato.md&title=ATO+for+%5Bsystem%5D+-+due+%5Bdate%5D), want to make sure there is feedback on the new one that has been [created](https://app.smartsheet.com/folders/9mfvjQr7Rh95RxvhvQqQW3VwchXhmp2x5mJJgVX1). 

Related issues:
https://github.com/18F/tts-tech-portfolio/issues/980
https://github.com/18F/tts-tech-portfolio/issues/1063

## Implementation Steps
- [x] Seek feedback
- [x] Respond to feedback
  - [ ] Inline when possible
  - [ ] dedicated conversations when practical

## Acceptance Criteria

- [x] The software authorization checklist is accepted
