### ISSUE TITLE
adjust Software Authorizations performance measure - due 7/1

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1143]
## Background Information

It seems a lot of the bullets under the [Software Authorizations performance measure](https://docs.google.com/document/d/1KOUN5NArmq9tisgcGzTLDm1M47BQwkd3HiCWoYah8SQ/edit#heading=h.pbuleousq8he) are a copy-and-paste from the [Acquisitions](https://docs.google.com/document/d/1KOUN5NArmq9tisgcGzTLDm1M47BQwkd3HiCWoYah8SQ/edit#heading=h.imj32cuxwbw1) one. This is fine as a placeholder, but there are a number of mentions of "contracts" and the like that aren't applicable.

## Implementation Steps

- [ ] Update in doc
- [ ] @afeld Submit through HRLinks
- [ ] Re-acknowledge in HRLinks

## Acceptance Criteria

- [ ] All bullets under the measure are applicable to Software Authorizations
