### ISSUE TITLE
Complete p-card transition

### ISSUE THREAD

**Issue by melanienleopold** [18F/tts-tech-portfolio#1148]
## Background information

The pcard transition is almost ready for the handoff.

## Implementation steps

There are a few steps John and I need to take to be prepared for the final handoff:

- [x] Consensus between teams about what should be transferred (and not)
- [x] Ask if we should re-request all recurring micropurchases
- [x] All invoices are forwarded to purchase card email
- [x] Shared passwords and logins are in one place
- [x] Micropurchase sheet is updated with changes
- [x] Convey p-card takeaways
   - List of recurring logs and what date they are expected
   - Track when things need to be re-submitted
      - Potentially synchronize when re-approvals are submitted
- [x] Melanie and John's Pegasys logs are complete
- [x] Final thumbs up from Ops team and OA

## Acceptance criteria

- [x] Transition to Ops team is complete

**Comment by JJediny** [comment]
Confirmed complete with @melanienleopold
