### ISSUE TITLE
adjust scopes for Bug Bounty

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#115]
- [ ] For cloud.gov, what assets do we _not_ want in scope? `*.app.cloud.gov` and staging, at least
- [ ] Can cloud.gov be bumped up to Standard tier?
- [ ] Can code.gov be bumped up to Standard tier?

**Comment by mxplusb** [comment]
I think staging should be fine because then we get a chance to see bugs before they happen.

**Comment by afeld** [comment]
Seems to be complete.
