### ISSUE TITLE
review Mission Essential Function submissions - due 1/15

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1151]
## Background Information

TTS is being asked to complete a data call to reassess what our Mission Essential Functions should be. Each division is being asked to fill out their rows, and I was asked to review what they submitted.

## Implementation Steps
- [x] Review [slides](https://drive.google.com/file/d/1BdSua0_3lSWl_dAMuKxpMmymc6mKSHGU/view)
- [x] Fill out [Tech Portfolio row(s)](https://docs.google.com/spreadsheets/d/11q7Lkx9WZPkyy139Vm05JTOWdekyR1hcS0-FSS21yo4/edit#gid=1060912075&range=109:109) - due 1/5
   - [x] Concurrence from @its-a-lisa-at-work 
- [x] Review [Form 1A](https://docs.google.com/spreadsheets/d/11q7Lkx9WZPkyy139Vm05JTOWdekyR1hcS0-FSS21yo4/edit#gid=1060912075) after submissions are in - after 1/5, due 1/15
   - [x] Ensure any edits are reflected in [the doc version](https://docs.google.com/document/d/1X9nTfDB5kFcQtnDTmYEwtkf2h1MzDR8G/edit)

## Acceptance Criteria

- [x] Tech Portfolio concurs with content of Form 1A

**Comment by afeld** [comment]
@its-a-lisa-at-work If you have time, would love to get your 👀 on [our `Manage TTS-wide software and infrastructure` Function](https://docs.google.com/spreadsheets/d/11q7Lkx9WZPkyy139Vm05JTOWdekyR1hcS0-FSS21yo4/edit#gid=1060912075&range=92:92), specifically the responses I put in the `TEST 2` columns. Should be quick, but if you don't have time, no worries.

**Comment by afeld** [comment]
Will give another few days for submissions to be updated before reviewing them.

**Comment by its-a-lisa-at-work** [comment]
Requested access to the document today

**Comment by afeld** [comment]
Try now.

**Comment by afeld** [comment]
Left comments; waiting on response from Cristina.

**Comment by afeld** [comment]
Cristina confirmed my suggestions, so done.
