### ISSUE TITLE
fix Zendesk slack integration

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1158]
## Background Information

The previous owner of the [Zendesk (Legacy)](https://gsa-tts.slack.com/apps/A0F81FPJS-zendesk-legacy) Slack integration for cloud.gov and Federalist left TTS, which broke Zendesk ticket notifications coming into Slack.

## Implementation Steps
- [x] Investigate [new Zendesk integration](https://gsa-tts.slack.com/apps/A9WFQ3M0B-zendesk)
   - [x] Enable
- [x] Fix for cloud.gov
- [x] Fix for Federalist

## Acceptance Criteria

- [x] Zendesk notifications are flowing into Slack for the teams that want them

**Comment by afeld** [comment]
It seems that the new Zendesk integration can only be used in a single workspace of an Enterprise Grid. Switched everyone back to the Legacy integration.

**Comment by afeld** [comment]
Checking in on Federalist integration.

**Comment by JJediny** [comment]
multiple instances of the legacy app have been configured and integrated to each respective channel. Will reopen if any issues resurface
