### ISSUE TITLE
revisit things that broke or changed in unexpected/undesirable ways in the Slack migration

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1159]
## Background Information

With the move to Grid, there are [some settings that were different in the TTS workspace from the Enterprise Grid](https://docs.google.com/spreadsheets/d/1T0WSHtq9GqtGbUhXlE5JatuM8VlsUlynwrcVl39eCzY/edit#gid=1770053690), which will be overridden. For the ones we care about, need to work through them with GSA IT.

## Implementation Steps

- [ ] Allow creation of custom emoji - https://github.com/18F/tts-tech-portfolio/issues/1077
- [x] Go through [workspace settings](https://gsa-tts.slack.com/admin/settings) with GSA IT
- [x] Figure out if we can turn off [mobile passcodes](https://slack.com/help/articles/360033808693-Require-a-mobile-passcode-on-Enterprise-Grid-) for GSA phones
   - We'll revisit integration with the Mobile Device Management (MDM) later
- [x] Figure out if profile data can be restored
- [x] Figure out exactly [what changed for Guests](https://gsa-tts.slack.com/archives/C3F14AHSQ/p1610306617006500)
- [x] Figure out what's going on with [complaints about gsa-tts.slack.com](https://gsa-tts.slack.com/archives/C0DH5B68Y/p1610297361002500) not working
- [x] Email notification settings reset
- [x] Guests who were deactivated - https://github.com/18F/tts-tech-portfolio/issues/1161
- [x] [Emoji that were renamed due to conflict and now have numbers in the name](https://gsa-tts.slack.com/archives/C0X2T36AY/p1610476908012200)
- [x] Revisit Slack full name guidance
- [ ] [Joining workspaces](https://gsa-tts.slack.com/archives/C01CVRM54S2/p1610415736004400?thread_ts=1610414430.004200&cid=C01CVRM54S2)
- [x] [Communication around what actions users need to do](https://docs.google.com/document/d/1Bqk9ihBnTYeCFaMj6zYyJ2UxJAgCQiWmODrVgrLXgPA/edit#heading=h.jmvb26s4n8my)
- [x] Update request form to ask for canonical GSA email
- [ ] Get [Apps](https://app.slack.com/apps-manage/T025AQGAN) approved GSA-wide
- [x] [Propose changes to Security](https://docs.google.com/spreadsheets/d/1iloo7Q1GbH971oYodyR7utZoE89oCjjdD-2xrRPAyEE/edit#gid=45241000)
- [x] [Users who were using email aliases:](https://docs.google.com/spreadsheets/d/1iloo7Q1GbH971oYodyR7utZoE89oCjjdD-2xrRPAyEE/edit#gid=0) delete their GSA Slack users and either change their TTS Slack email to the canonical one, or add their alias to the access group

---

- [x] [Email notice to TTS](https://docs.google.com/document/d/1Bqk9ihBnTYeCFaMj6zYyJ2UxJAgCQiWmODrVgrLXgPA/edit#heading=h.52xgqzdwwpq6)
   - [x] Drafted
   - [x] Sent

## Acceptance Criteria

- [x] For each setting listed, either concur with outcome, or get GSA IT to change to match TTS' needs

**Comment by ccostino** [comment]
Thank you, @afeld!

One thing that jumped out to me and I saw reported elsewhere is your display name seems to be reset to `First Last - Org Code` even after you edit it again (for doing things like adding project/program, pronouns, location, pronunciation, etc.).

**Comment by afeld** [comment]
Will likely split out individual issues for some.

**Comment by tbaxter-18f** [comment]
Aidan, I'm not sure if this is the right spot or not -- and forgive me if it's not -- but I'd like to propose the removal of two GSA IT emoji:

:nice: has some pretty unsettling context from it's original South Park usage, and the renamed :nice-9483: is more clearly an unambiguous affirmation.

:awyeah: is just.... wow, how is that OK?

**Comment by adborden** [comment]
I am no longer able to access the GSA slack on my personal phone since the migration. This was essential for receiving outage alerts after hours and during business hours ET.

**Comment by adborden** [comment]
I see that we're tracking the session duration issue requiring folks to sign-in every morning, but in my case, I have to re-add the TTS workspace each morning. It's just gone 🤷

**Comment by mogul** [comment]
Aliases to TTS emoji that were renamed still point to the old name. In some
cases that means the alias points to an emoji that is inconsistent with the
intent of the alias.

**Comment by lggsa** [comment]
From adborden: 
I am no longer able to access the GSA slack on my personal phone since the migration. This was essential for receiving outage alerts after hours and during business hours ET.

I see that we're tracking the session duration issue requiring folks to sign-in every morning, but in my case, I have to re-add the TTS workspace each morning. It's just gone 🤷

Same for me on both issues.

**Comment by afeld** [comment]
> I'd like to propose the removal of two GSA IT emoji

Tracking in [this spreadsheet](https://docs.google.com/spreadsheets/d/1iloo7Q1GbH971oYodyR7utZoE89oCjjdD-2xrRPAyEE/edit#gid=1988221268).

> I have to re-add the TTS workspace each morning.

Please [reach out to Slack support](https://gsa-tts.slack.com/help/requests/new).

> Aliases to TTS emoji that were renamed still point to the old name. In some cases that means the alias points to an emoji that is inconsistent with the intent of the alias.

Please put any examples in [this spreadsheet](https://docs.google.com/spreadsheets/d/1iloo7Q1GbH971oYodyR7utZoE89oCjjdD-2xrRPAyEE/edit#gid=1988221268).

**Comment by afeld** [comment]
Waiting for response about the proposed settings from Amar.

**Comment by robertgoldel** [comment]
Getting a consistent issue where I'm getting signed out multiple times per day. TTS icon shows a yellow triangle with an exclamation point. Clicking the icon takes me to [https://gsa-tts.slack.com/ssb/signin_redirect...]. How often should we expect to have to re-auth?

**Comment by afeld** [comment]
@robertgoldel I believe every 12 hours, at the moment.

**Comment by afeld** [comment]
Waiting on Outreach review of [the update](https://docs.google.com/document/d/1Bqk9ihBnTYeCFaMj6zYyJ2UxJAgCQiWmODrVgrLXgPA/edit#heading=h.52xgqzdwwpq6).

**Comment by afeld** [comment]
Updates will go out in the next TTS newsletter.

**Comment by porta-antiporta** [comment]
popping in to say :thank-you: for fixing the short edit timeouts and being able to edit slack groups!
