### ISSUE TITLE
create Solutions mailing list(s)

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#116]
- [Slack conversation](https://gsa-tts.slack.com/archives/C1ZPQUJNA/p1570034801107000)
- [`opp-team`](https://groups.google.com/a/gsa.gov/forum/#!forum/opp-team)
- [`opp-contractors`](https://groups.google.com/a/gsa.gov/forum/#!forum/opp-contractors)

## TODOs

- [x] Rename lists - [`tts-solutions-feds`](https://groups.google.com/a/gsa.gov/forum/#!forum/tts-solutions-feds) and [`tts-solutions-contractors`](https://groups.google.com/a/gsa.gov/forum/#!forum/tts-solutions-contractors)
- [x] Get lists updated
- [x] Announce to lists
- [x] Announce to Slack
- [ ] Change references in the Handbook

**Comment by awichman** [comment]
@afeld Can you give me permission to add members to tts-solutions-contractors? I can for the feds listserv, but not for contractors, and we're missing a few folks.

**Comment by afeld** [comment]
So sorry, just saw your question! Looks like you are an Owner now.

**Comment by awichman** [comment]
@afeld following up on today's SMT chat - this GH Issue is still open because I know we need to update the Handbook references to OPP.

**Comment by awichman** [comment]
Also noting = I think there is enough nuance to consider, that a blanket swap of "OPP" to "Solutions" probably won't be sufficient. I think this is the right time to review pages for inclusive TTS-wide language.

**Comment by afeld** [comment]
> this GH Issue is still open because I know we need to update the Handbook references to OPP

Got it. Closing in favor of https://github.com/18F/handbook/issues/1522 then.

> a blanket swap of "OPP" to "Solutions" probably won't be sufficient

For sure.

> this is the right time to review pages for inclusive TTS-wide language

Not something the Tech Portfolio can take on right now, but if you are interested in taking a pass, happy to help get you set up with the Handbook locally to do so!

cc https://github.com/18F/handbook/issues/1452
