### ISSUE TITLE
move recurring purchases off John's p-card

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1160]
## Background Information

Part of https://github.com/18F/tts-tech-portfolio/issues/1148. Short of fully handing off to BizOps, doesn't seem helpful to have this responsibility split between @JJediny and @melanienleopold: the sum of the work is greater than the parts.

## Implementation Steps
- [x] Ensure logs are up to date
- [x] Clarity on exactly what is isn't being transferred
   - [x] Domain registrations (John will continue with these)
   - [x] [Dockerhub (cloud.gov)](https://docs.google.com/spreadsheets/d/1dO1qz9TFAWFgGqteRL10Bbq4JSKskXzdwlgAeKtMYj8/edit#gid=2001741130&range=272:272)
   - [x] [Opsgenie (login.gov)](https://docs.google.com/spreadsheets/d/1dO1qz9TFAWFgGqteRL10Bbq4JSKskXzdwlgAeKtMYj8/edit#gid=2001741130&range=295:295) 1/19/21 - need to reattest tax exemption and pay new annual invoice
   - [x] [Statuspage (cloud.gov)](https://docs.google.com/spreadsheets/d/1dO1qz9TFAWFgGqteRL10Bbq4JSKskXzdwlgAeKtMYj8/edit#gid=2001741130&range=55:55)

## Acceptance Criteria

- [x] @JJediny no longer has recurring purchases on his p-card

**Comment by afeld** [comment]
@melanienleopold Sounds like there are only a few remaining; would you be ok with taking them on a temporary basis?

**Comment by JJediny** [comment]
@melanienleopold all micropurchase lines for the 3 remaining reoccurring items are ready for your review to confirm we can easily transfer

**Comment by afeld** [comment]
For tax exemption, need to have a certificate with the same name as what's on the account (e.g. "login.gov").
