### ISSUE TITLE
Review SBOM SOW Language

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1172]
## Background Information

Kelley Artz has asked if we could come up with SBOM Language to include in contracts

## Implementation Steps
- [ ] Review [SBOM Contract Language](https://docs.google.com/document/d/1RqIYDEyQpo8Fw15MV468Qccw1K7SJ-DgjG-NtBtDHCI/edit?usp=sharing)
- [x] Ask Synopsys about the copyright of the product from the [Mayo Clinic](https://gsa-tts.slack.com/archives/C02CD5VUQ/p1598625413067600?thread_ts=1597967004.008000&cid=C02CD5VUQ)
   - [ ] Get response
- [x] Ask Healthcare Proof of Concept if they have sample language
   - [x] Get response
- [x] [Look into](https://gsa-tts.slack.com/archives/C01FCFXHZMK/p1611275241001700) the DoD Language that exists related to software data
   - [x] Get response

## Acceptance Criteria

- [ ] The SBOM SOW Language has been reviewed and any comments have been made

**Comment by its-a-lisa-at-work** [comment]
Started to look into this; what is written looks good so far, but I think there could be additional language that could be added; have questions out based on other things that are tangential ... moving to `Waiting/Feedback` until I get response
