### ISSUE TITLE
confirm security authorization requirements for AI/ML environment

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1175]
## Implementation Steps
- [ ] Determine if it's a TTS or ITC system
- [ ] Add to system inventory
- [ ] Add to assessment schedule

## Acceptance Criteria

- [ ] Yes/no on whether the Proof of Concept will need an ATO (or equivalent)

**Comment by afeld** [comment]
cc https://github.com/18F/tts-tech-portfolio/issues/1174

**Comment by its-a-lisa-at-work** [comment]
Meeting (`ATO Requirements - Working Session`) on 1/29/21 to discuss this based on the email that had the question:

> Recently, we've had the question come up of "what requires an ATO"? And I was hoping maybe we could block off some time with either you or someone on your team to work through the thought process. It has come to my attention that my standpoint of "any information that could be compromised" or "any information system that we spent government resources on it" might be more restrictive on GSA's interpretation of what should have an ATO. 
> 
> Ideally, the outcome of this session will result in an update of the current guidance we have on Before You Ship for pre authorizations. 

and the response was given:

> We're in the process of developing a 'Clean ATO guide' which should be published by the end of Q2 to help augment your pre-authorization efforts.
> 
> In short, the following mandates what's to be ATO'd by Fed Agencies:
> 
> - OMB Circular A-11 (formerly known as OMB Exhibit 300/53)
> - OMB A-130
> - E Government Act of 2002
> - FISMA 2002/2014
> - NIST FIPS (standards) & SPs (guidance)
> - GSA policy & guidance

**Comment by afeld** [comment]
[Salesforce request](https://gsa.lightning.force.com/lightning/r/Request_Tracker__c/a1Zt0000000oPzYEAU/view) was just `Approved`.

**Comment by its-a-lisa-at-work** [comment]
I spoked with @jhoyt22 and was talking with @mogul for something else and consulted with him; I have a better way that this is done within GSA now, and don't feel like the Infrastructure themselves need an ATO. 

@afeld based on the acceptance criteria, I think this can be closed; but I'm a little hesitant based on the other Implementation Steps -- thoughts?

**Comment by its-a-lisa-at-work** [comment]
Started [conversation](https://gsa-tts.slack.com/archives/C01FQU04JHK/p1612382301018800) and provided form to fill out to get the high level information

**Comment by its-a-lisa-at-work** [comment]
This is the response we got related to this:

> ITC is having TTS build it on our sandboxes for proof of concept, so currently it’s a TTS system build on top of COE AWS, Azure Sandboxes, and the TTS GCP sandbox. So currently I would say TTS System under the TTS Tech Portfolio
> 
> I think the success we’ve had thus far with Aiden and John we’d want to keep this effort rolling. :slightly_smiling_face:
> 
> I think if this POC is successful and we go to full pilot on govcloud, then we’ll identify the FISMA name as “AI COE Innovation Laboratory” under TTS as we’ll be moving and shaking supporting a number of different AI/ML efforts next partnering with ITC and the newly stood up ITVMO.
> 
> btw I think all those sandboxes are TTS… :slightly_smiling_face:

**Comment by afeld** [comment]
Punting back to Icebox; will revisit as we get further through the Proof of Concept.

**Comment by afeld** [comment]
This project is on indefinite hold pending more funds, so closing.
