### ISSUE TITLE
upgrade Trello

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1176]
## Implementation Steps
- [x] Andrew: Confirm how hard it is to add (and maybe remove) licenses later
- [x] Andrew: Confirm that this will transition to DIGIT contract cleanly
- [ ] ~~Survey TTS about use of project management tools~~
- [x] Decide on Trello Team structure, in terms of who should have access to all boards in that Team
- [x] Andrew: Pass along emails of active users
- [x] Determine the license count TTS would need
- [x] [Letter to potential admins](https://docs.google.com/document/d/1sHNpGMePaBwX0TBoJIxExelTdetbeessVgewsgtu2Lo/edit?ts=604980f7#heading=h.wkq0cg1oimj1)
   - [x] Drafted
   - [x] Feedback from Andrew P
   - [x] Sent
- [x] Get formal onboarding steps from CTO
- [x] Create teams
- [x] Add admins
- [x] Schedule migration
- [x] Notify admins about details of migration
- [x] [TTS-wide email](https://docs.google.com/document/d/1sHNpGMePaBwX0TBoJIxExelTdetbeessVgewsgtu2Lo/edit#heading=h.5alzoc7ca2lb)
- [x] Transfer [existing teams](https://docs.google.com/document/d/1sHNpGMePaBwX0TBoJIxExelTdetbeessVgewsgtu2Lo/edit#heading=h.vtnco5yqk3rw)
- [x] Update Handbook - https://github.com/18F/handbook/pull/2422
- [x] Transfer / clean up random boards
   - [x] https://trello.com/b/kpqSA2JO/bailes-personal
   - [x] https://trello.com/b/pP8tDITq/talent-acquisition-work-system
   - [x] https://trello.com/b/pL5qaGA0/g-diversity-2019-2021
   - [x] https://trello.com/b/TbbxwARF/acquisitions-team
   - [x] https://trello.com/b/CugpXglI/personal-to-do
   - [x] https://trello.com/b/c5xcBMQG/usagov-remainged-development-tasks
- [x] Transfer / clean up random Workspaces
   - [x] https://trello.com/tts129
   - [x] https://trello.com/18facquisitionchapter
   - [x] https://trello.com/usagovwebopsteam
- [x] Check how Acquisitions teams want to handle sensitivity of their boards
   - [x] [TTS Acq](https://gsa-tts.slack.com/archives/CD4F3TGB1/p1618321186001200)
   - [x] [18F Acq](https://gsa-tts.slack.com/archives/C054NH1FW/p1618321060007000?thread_ts=1618242890.002800&cid=C054NH1FW)
- [ ] Figure out ownership of @18fteam user
- [ ] [TTS-wide follow-up email](https://docs.google.com/document/d/1sHNpGMePaBwX0TBoJIxExelTdetbeessVgewsgtu2Lo/edit#heading=h.phtuxs1d72j5)

## Acceptance Criteria

- [x] We are on a compliant version of Trello

**Comment by afeld** [comment]
[Notes from meeting with CTO team](https://docs.google.com/document/d/1sHNpGMePaBwX0TBoJIxExelTdetbeessVgewsgtu2Lo/edit)

**Comment by afeld** [comment]
[Letter to admins](https://docs.google.com/document/d/1sHNpGMePaBwX0TBoJIxExelTdetbeessVgewsgtu2Lo/edit?ts=604980f7#heading=h.wkq0cg1oimj1) drafted; waiting on feedback.

**Comment by afeld** [comment]
[Sent letter to potential admins in Slack.](https://gsa-tts.slack.com/archives/C055J0BL0/p1616510189009900)

**Comment by afeld** [comment]
Not hearing any objection, so [asking for next steps from CTO team](https://gsa-tts.slack.com/archives/C055J0BL0/p1616683067017000).

**Comment by afeld** [comment]
Migration scheduled for Friday 4/9 at 3:30pm ET. Emailed TTS and the admins with info.

**Comment by afeld** [comment]
[Decided not to bother with the follow-up email right now.](https://gsa-tts.slack.com/archives/C055J0BL0/p1621623026011600) Calling this "done enough."
