### ISSUE TITLE
Get Pulse moved out

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#118]
The Pulse production resources seem to be running in the 18F Sandbox AWS account. They shouldn't be in a sandbox account, nor should they be in a TTS account anymore.

- [x] Determine what account they live in
- [x] Grant access to OGP team
- [ ] [Share cost history](https://gsa-tts.slack.com/archives/C03UCSM2T/p1570226010000300)
- [ ] Get confirmation that the resources have been migrated
- [ ] Remove the resources from the Sandbox
- [ ] Remove the OGP IAM users
- [ ] Remove from New Relic

**Comment by its-a-lisa** [comment]
Making a comment here so the card is fresh on our minds ahead of Monday's sprint planning meeting

**Comment by afeld** [comment]
https://twitter.com/gbinal/status/1269067070601334786

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/506.
