### ISSUE TITLE
Privacy Dashboard ATO support

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1180]
## Background Information

Tock is going through a Full ATO 
Does being a 12 factor app help?
Given the nature of the system, does it

## Implementation Steps
- [x] LATO or Full?
- [x] What templates?
- [x] Full set of controls?
- [x] What should they fill out for the SSSP?
- [ ] Which controls should they focus on?
- [x] How much leveraging should they do from other programs?

## Acceptance Criteria

- [x] Guidance has been provided on what steps the team should focus on with the little time they have left

**Comment by its-a-lisa-at-work** [comment]
Moving to `Blocked/Watching` since I emailed to get an ISSO assigned and this also is an example of not sure how I should be involved or answering and hopefully that will get addressed once https://github.com/18F/tts-tech-portfolio/issues/1194 is accomplished

**Comment by its-a-lisa-at-work** [comment]
Met with @peterrowland yesterday and talk through most of these items
