### ISSUE TITLE
Bug Bounty Budget

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1181]
## Background Information

The option is coming up for the next Bug Bounty option; need to figure out what our options are and what we're going to fund and if we don't fund things, what affect that has. 

cc https://github.com/18F/tts-tech-portfolio/issues/1185

## Implementation Steps
- [x] Provide documentation to GSA IT Security
- [ ] Review information that H1 is going to provide
- [x] Review financial documents
- [x] Propose options on how to go forward
- [ ] @afeld Review

## Acceptance Criteria

- [ ] Consensus on budget split from programs participating in next Option

**Comment by its-a-lisa-at-work** [comment]
Put a [document](https://docs.google.com/spreadsheets/d/1z0LtH56Z_4GHqm9hALf47RmopBYQZMzrRe2wBExm0DI/edit#gid=0) together with the options going forward and mentioned it in the acq related slack channel; moving to `Waiting/Feedback` until I hear feedback

**Comment by its-a-lisa-at-work** [comment]
got the thumbs up from @HuixianXu that she'll take it from here; might have to hop on a call to explain the analysis that I put together; but the main legwork is done on our end
