### ISSUE TITLE
exercise HackerOne option - due 3/19

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1185]
## Background Information

The option for the H1 contract is up in March; need to take steps to execute now to renew. 

## Implementation Steps
- [x] Sign DocuSign
- [x] Get updated pricing info from HackerOne
- [x] Understand [budget breakdown](https://docs.google.com/spreadsheets/d/1z0LtH56Z_4GHqm9hALf47RmopBYQZMzrRe2wBExm0DI/edit#gid=2061939810&range=P31:P41)
- [x] Submit purchase request(s)

## Acceptance Criteria

- [x] Execute H1 Option

**Comment by its-a-lisa-at-work** [comment]
Moving back to `Ready` since the blocker with the Budget is closed

**Comment by afeld** [comment]
Dates:

- Option expires 3/19
- @JenniferCalik needs Purchase Requests by 3/15
- Purchase Requests need to be started by 3/1, so amount is needed from HackerOne by then

Per @JenniferCalik, "we can accept a discount, but that can't change the structure/terms."

**Comment by afeld** [comment]
[Cost breakdown per program](https://docs.google.com/spreadsheets/d/1z0LtH56Z_4GHqm9hALf47RmopBYQZMzrRe2wBExm0DI/edit#gid=2061939810&range=P31:P41)

**Comment by afeld** [comment]
Complete!
