### ISSUE TITLE
investigate analytic hierarchy process (AHP) for Software Concierge

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1186]
## Background Information

In a meeting with Dave Shive talking about CRM tooling, he suggesting using the [analytic hierarchy process (AHP)](https://en.wikipedia.org/wiki/Analytic_hierarchy_process) for evaluating options.

cc @ethanheppner 

## Implementation Steps
- [x] See if there's anyone in GSA who can give insight about how to use the process for software analysis of alternatives

## Acceptance Criteria

- [x] 👍 / 👎 on whether to incorporate AHD into the Concierge process
- [x] Follow-up issues created

**Comment by melanienleopold** [comment]
This seems a lot more complicated than necessary for software concierge. I am using some of the information in the software concierge prioritization, but don't think this whole process should be used in this use case.
