### ISSUE TITLE
Capability Assessment Phase II - due 2/2

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1188]
[**Spreadsheet**](https://docs.google.com/spreadsheets/d/153uoLxX3_0q3dIsUgpMCXyIKSG6t-IPJMtvCCfkXB6o/edit#gid=380139903)

## Background Information

See `Your TTS Capability Assessment Phase II Spreadsheet (Due by February 2)` email.

- [Capability list](https://docs.google.com/spreadsheets/d/1FSi_1PvTR6CO_ZUTR9c4jR8a6aJANJ03w_X_U-GgryE/edit#gid=260781910)
- [Proficiency levels](https://docs.google.com/spreadsheets/d/1ALXtAsVmj1hf0YkaNz5cbWAQ1y0uZtXZsWO3XrEZ0Y8/edit#gid=1578535080)

## Implementation Steps

- [x] @afeld Send overview of what this is for
- [x] @its-a-lisa-at-work filled out
- [x] @JJediny filled out
- [x] @afeld confirms
- [x] @afeld sends back

## Acceptance Criteria

- [x] Employee Proficiencies provided

**Comment by afeld** [comment]
Sent.
