### ISSUE TITLE
inform OSM about our OT-CRM efforts - Due Date 1/28/21

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1191]
## Background Information

I today's meeting with the OT-CRM team, a task came up for the Tech Portfolio team to complete

## Implementation Steps
- [x] Check with Office of Systems Management team
  - [x] Fill them in with what we're doing

## Acceptance Criteria

- [x] Team is aware of our efforts

**Comment by its-a-lisa-at-work** [comment]
Sent the team the original and new AoA and have a meeting set up with them tomorrow.

**Comment by its-a-lisa-at-work** [comment]
The team is aware of what we're doing and told them we'd send the briefing to them when we had finalized it and that we'd keep them updated as we go along.
