### ISSUE TITLE
Review SBOM documents - due date 2/4/21

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1192]
## Implementation Steps
- [x] Review documents
  - [x] [SBOM FAQ](https://drive.google.com/open?id=15j573Tqjnce3SZ4H5kBNEg92tXCIaHdBmCCaCnlY6Dc)
  - [x] [SBOM Two Pager](https://drive.google.com/open?id=1BEf-lthbIkOHwD7vjwpGUzVEc3Icp7bW8WSiWIs7D10)
- [x] Provide comments

## Acceptance Criteria

- [x] Provide review to documents
