### ISSUE TITLE
Resolve Google tax issue

### ISSUE THREAD

**Issue by melanienleopold** [18F/tts-tech-portfolio#1193]
## Background information

After months of buying GSuite from Google for cloud.gov on the pcard, they are still charging state taxes. John attempted to submit a tax exempt form and so did I, but they were rejected. As the federal government, we cannot be charged taxes on purchases. We need to ensure past taxes are refunded and no taxes are charged moving forward.

## Implementation Steps
- [x] Contact Google support
- [x] Correct tax exempt form
- [x]  Refund taxes on @melanienleopold's credit card starting from 09/20 - 01/21.

## Acceptance criteria

- [x] Taxes are refunded and not charged on the next invoice.
