### ISSUE TITLE
GSA IT Security & TTS - Roles and Responsibilities

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1194]
## Background Information

It is not clear what the purpose of the TTS Tech Portfolio being involved in the custom developed software security authorization process is. 

## Implementation Steps
- [ ] Put a draft of paper
- [ ] Get input from IST
- [ ] Talk to folks within TTS who have custom developed software

## Acceptance Criteria

- [ ] Documented list of roles and responsibilities as they relate to each group

**Comment by afeld** [comment]
Doesn't feel like a pain point right now, so closing.
