### ISSUE TITLE
revise Slack Administration Guide

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1200]
[**guide**](https://docs.google.com/document/d/1ncHqriv2CnsZQ7brrZ3mlLCK_i-XuvW-kRpXb0fP0t4/edit#)

## Background Information

With the move to Enterprise Grid, lots has changed in regards to GSA's management of Slack.

## Implementation Steps

- [ ] Review guide for accuracy
- [ ] Review [Handbook pages](https://handbook.tts.gsa.gov/tools/slack/) to see what content should be escalated to be GSA-wide

…proposing changes as needed.

## Acceptance Criteria

- [ ] Consensus between GSA and IDT around the guide being accurate and comprehensive

**Comment by afeld** [comment]
This isn't TTS' responsibility, so closing.
