### ISSUE TITLE
migrate additional Slack workspaces

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1201]
[**workspace list**](https://docs.google.com/spreadsheets/d/1Dz2zou7AN2GxVthU2j3r1GjUjsOZ9HyhL_Ww2m9Tg9I/edit#gid=825955963)

## Background Information

GSA is requiring all GSA-run Slack workspaces to be part of the Enterprise Grid. They are going to do a [domain claim](https://slack.com/help/articles/115001379947-Claim-domains-on-Enterprise-Grid) sooner or later to bring all the scattered workspaces into the fold. Either before or after, we need to migrate the ones that were TTS-related into Grid to make sure the records are retained.

## Implementation Steps
- [ ] Fill in alternate contacts
- [ ] Identify TTS-related workspaces
- [ ] Identify workspaces that can be sunset

For those that can be sunset:

- [ ] Get set as Primary Owner
- [ ] Deactivate users
- [ ] Get pre-migration reports
- [ ] Migrate
- [ ] [Hide them](https://slack.com/help/articles/115005225987-Manage-a-workspace-on-Enterprise-Grid#2u46-settings-and-permissions)

## Acceptance Criteria

- [ ] All TTS Slack workspaces are part of Enterprise Grid

**Comment by afeld** [comment]
> Any existing workspace that was created using an email domain that is subsequently claimed will work as normal.

https://gsa-tts.slack.com/archives/C01CVRM54S2/p1611593045015500

**Comment by afeld** [comment]
Audit reports:

- [1/12](https://docs.google.com/spreadsheets/d/1Dz2zou7AN2GxVthU2j3r1GjUjsOZ9HyhL_Ww2m9Tg9I/edit#gid=825955963)
- [1/28](https://docs.google.com/spreadsheets/d/17ndTj9IvjGkMgUqeb3YAPsMIDpdDdVVR/edit#gid=995441368)

**Comment by JJediny** [comment]
Slack accounts have been migrated under GSA IT Enterprise Buy
