### ISSUE TITLE
update Slack profile rules/guidance

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1202]
## Background Information

Some settings changed with the move to Enterprise Grid (https://github.com/18F/tts-tech-portfolio/issues/1159), requiring updates around how we include extra info in the names that show up in Slack.

## Implementation Steps
- [ ] ~~Stop syncing of profiles on login~~
- [x] Update rules to direct people to edit the `Display name` rather than `Full name` - https://github.com/18F/handbook/pull/2318
- [x] Send [survey about what display names should contain](https://docs.google.com/forms/d/e/1FAIpQLSfzW0msTAZu9fYoj-BP1eQLEq0T-W68_YdScmqkICskzvJj9w/viewform)
- [x] Share at Diversity Guild
- [x] Update display name rules/guidance - https://github.com/18F/handbook/pull/2327
- [x] [TTS-wide communication](https://docs.google.com/document/d/1Bqk9ihBnTYeCFaMj6zYyJ2UxJAgCQiWmODrVgrLXgPA/edit#heading=h.52xgqzdwwpq6)
   - [x] Draft
   - [x] Send

## Acceptance Criteria

- [x] TTS staff are informed about what information they should be putting in their Slack profiles, and where

**Comment by afeld** [comment]
[Handbook updated](https://handbook.tts.gsa.gov/tools/slack/rules/#profile), TTS-wide email queued up.
