### ISSUE TITLE
kick off Document Jam Sprint

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1208]
## Background Information

[Overview](https://docs.google.com/presentation/d/1asgKBAoVqbscKJSkeJ-rb_nHEre_qVhVQaEm0CfL9J4/edit#slide=id.ga316be7714_0_64)

@michelle-rago was selected as the lead and @durland18F volunteered. Given the Tech Portfolio's ownership/involvement with the Handbook and other documentation/microsites at TTS, and benefits to us (making Ops Rotation easier by having better things to point to), want to help them get it off the ground.

## Implementation Steps
- [x] [Gather ideas of things to work on](https://docs.google.com/document/d/1s8T6_xn0S3v4ciB_3HmXrHOApZApKquNcuk2bqvnQD0/edit)
- [x] Meet with @michelle-rago and @durland18F 
- [x] Meet with Content Guild

## Acceptance Criteria

- [x] The Documentation Sprint team has gotten suggestions from the Tech Portfolio on what to focus on

**Comment by afeld** [comment]
Calling this "done enough for now"; will meet as needed.
