### ISSUE TITLE
decide if we want to buy dedicated Smartsheet licenses for TTS

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1213]
## Background Information

https://trello.com/c/xAi93LDH/342-smartsheet-tts-license-pool

## Implementation Steps
- [ ] How many would we want to buy?
- [x] What would the cost look like?
- [ ] How would this impact other large SaaS purchases?
- [ ] Are there any tools/licenses we think it could replace?

## Acceptance Criteria

- [ ] Consensus from Tech Portfolio + TTS leadership on whether to pursue a TTS license pool

**Comment by afeld** [comment]
Set a soft deadline, as it's relevant for ongoing conversations around SaaS prioritization, etc.

**Comment by afeld** [comment]
Blocked by https://github.com/18F/tts-tech-portfolio/issues/944.

**Comment by its-a-lisa-at-work** [comment]
Since #944 is closed; is this no longer blocked? The max.gov team (about 9 people and growing, plus about 5 people that are on the edge supporting us) would like licenses.

**Comment by afeld** [comment]
Unfortunately, there is not enough room in the SaaS budget for FY21 to buy licenses for _everyone_ in TTS. Emailed Kyle Steffensmeier to try and get a sense of how many we would need to cover current demand.

cc @josephderosales

**Comment by afeld** [comment]
Not going to pursue right now; haven't been hearing demand recently.
