### ISSUE TITLE
Custom ATO Leadership Prioritization

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#1214]
[**Assessment schedule**](https://docs.google.com/spreadsheets/d/19wyA91KhGoZvnAA0fihC0WF_mU79YLRTHzDd-Frs8Qs/edit#gid=0)

## Background Information

We got the dates #1075 and now we need to get leadership prioritization 

Follow up from https://github.com/18F/tts-tech-portfolio/issues/1075

## Implementation Steps
- [x] Add in a priority column
- [x] Tech Portfolio consensus
- [x] Send notification to Ashley M letting her know what we're looking for
    - [ ] Validate the priority
    - [x] Support the expected Date
    - [x] Provide approval

## Acceptance Criteria

- [ ] Leadership has validated ATO prioritization

**Comment by its-a-lisa-at-work** [comment]
Sent email to Ashley M for her review and emailed to get on her calendar to walk her through what we're asking

**Comment by afeld** [comment]
@JJediny @melanienleopold and I reviewed with @jhoyt22 and updated the numbers based on what's already scheduled, ATO expirations, and assessment readiness.

**Comment by afeld** [comment]
Got input from Ashley, who suggested we go in a slightly different direction (which wouldn't include Priority): https://github.com/18F/tts-tech-portfolio/issues/1214
