### ISSUE TITLE
ensure shared passwords are shared

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1215]
## Background Information

While we should minimize the need for them whenever possible, the Tech Portfolio inevitably has passwords that need to be shared within the team.

## Implementation Steps
- [x] Confirm that we want to stick with KeePassXC + Drive File Sync for the foreseeable future
   - We can split out an issue for proposing/trying a different tool if we want
- [x] Ensure all existing shared passwords are present
- [x] Document how to access
- [x] Document how to add new items

## Acceptance Criteria

- [ ] Team members confirm that they can access shared passwords

**Comment by afeld** [comment]
https://github.com/18F/tts-tech-portfolio/issues/1019 is for solving the problem more holistically.
