### ISSUE TITLE
Complete December IaaS Invoices

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#1219]
## Implementation Steps
- [x] update December spend per program 
- [x] Sign Docusign Package
- [x] Notify BizOps the Budget is ready

## Acceptance 
- All actions completed and parties notified of its availability
