### ISSUE TITLE
prep for Coding it Forward interview - due 2/9

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1227]
## Background Information

From `Coding It Forward Update: Interview Briefing and Timeline` email:

> You should expect to receive 3-4 referrals on Monday 2/8 and plan to complete interviews by next Friday 2/12.

Need to be prepped before the first scheduled interview.

## Implementation Steps
- [x] Determine who is conducting interviews: Star and @afeld 
- [x] [Prep list of questions](https://docs.google.com/document/d/162wlLqAxftJzG0fyuKxWPWd0oRPPlh_VL1BbYbZkQAo/edit)

## Acceptance Criteria

- [x] List of questions is prepared

**Comment by afeld** [comment]
Done.
