### ISSUE TITLE
Scheduler Tool - Software Concierge

### ISSUE THREAD

**Issue by melanienleopold** [18F/tts-tech-portfolio#1232]
## Background information

TTS is in need of a scheduling tool. An informal intake was submitted to the software concierge.

## Implementation Steps
- [ ] Meet with the project team
- [ ] Analysis of alternatives
- [ ] Determine path forward

## Acceptance criteria

- [ ] A plan is in place to acquire a scheduler tool

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/1291.
