### ISSUE TITLE
review staff competencies - due 2/12

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1235]
## Background Information

[Request](https://gsa-tts.slack.com/archives/C3F3HR717/p1612899922041400)

## Implementation Steps
- [ ] Review [Final Competencies](https://docs.google.com/spreadsheets/d/1SMhcDZRTmRZtIP5MBcNvZNJR6kRpwiCt4DTQT0KG4j8/edit#gid=866523612)
- [ ] Add any that are missing

## Acceptance Criteria

- [ ] List reflects "all the skills you have on your team, as well as skills you anticipate that you’ll need in the future"

**Comment by afeld** [comment]
I missed the boat on this one.
