### ISSUE TITLE
select Coding it Forward candidates - due 2/19

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1236]
## Background Information

_**Do not put names in this issue.**_

## Implementation Steps

- [x] Block times for interviews
- [x] Get resumes from Coding it Forward
- [x] Schedule interviews
- [x] Review resumes - see email `Fwd: Project 71 Referrals` or [Drive folder](https://drive.google.com/drive/folders/1b80bgSYsvO0Se57YnDTVmwU1aiz9fOWa)
- [x] Conduct interviews
- [x] Submit ranking

## Acceptance Criteria

- [x] Ranked choices provided to Coding it Forward

**Comment by afeld** [comment]
Submitted!
