### ISSUE TITLE
settle on Tech Radar to use

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1237]
## Background Information

We have had a number of attempts to create a "Technology Radar" over the years, but none have stuck. We should decide which we're going to use and go with it. [Notes from All Hands.](https://docs.google.com/document/d/1ynxrt_5rBrGX67VnDjcqT457MWMfCkzvEFgYEub73Sc/edit#heading=h.em5vemvhsok2)

## Implementation Steps
- [ ] Decide which we want to use
- [ ] Link from [the Software page](https://handbook.tts.gsa.gov/software/)
- [ ] Mark the others as deprecated

Updating the information, deciding what the categories should be, etc. is out of scope for this issue.

## Acceptance Criteria

- [ ] As a user, there is a single place to look to see what tools are available in TTS in a given category

**Comment by afeld** [comment]
For various reasons, we decided to go back [software inventory spreadsheet](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=0). @JJediny will combine information from other existing sources into there. Reminder: We can always move it later; important thing in having _a_ source of truth.

**Comment by afeld** [comment]
Saw this [Founders Checklist / Startup Stack](https://www.notion.so/Founders-Checklist-Startup-Stack-f24d0601ffc04abfb6b5faf86098371c) list on Twitter. I like that there's a chronology to it: you don't need _everything_ up front.

**Comment by josephderosales** [comment]
Requested access to:

Software Overview Card View (Smartsheet)
IT Standards entries by Category (Smartsheet)
Tech Radar (Smartsheet)
GSA Cloud Capabilities Alignment (Google Sheet)

Given the Software Concierge Role and in order to minimize the maintaining multiple items, the tracking/source file that this role will be using should be the authoritative source that users should be referencing ie: https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=0

**Comment by josephderosales** [comment]
Can someone give me access to these:

[Software Overview Card View (Smartsheet)](https://app.smartsheet.com/sheets/g2pXwW7GCVxR2W8VWmGrX9xrfx92jPj7WqVqFG41?view=card&cardLevel=0&cardViewByColumnId=8876022719375236)
[IT Standards entries by Category (Smartsheet)](https://app.smartsheet.com/sheets/MxWgV2V4W26jR2qrXv3J4GP896cFxXj7vFcC4Fp1?view=card&cardLevel=0&cardViewByColumnId=170596792330116)
[Tech Radar (Smartsheet)](https://app.smartsheet.com/sheets/W4g74J4fxpFx2Pc24HrfJF2cWXFCm27wC7hj7451?view=grid)
[GSA Cloud Capabilities Alignment (Google Sheet)](https://docs.google.com/spreadsheets/d/1PJDLs9o8CYzxHxhjJfs37RRjlcgj_lTZQ-XtDngmxpI/edit#gid=1382801360)


^^^ Note: The SmartSheets above need to be shared from the recently migrated files

**Comment by afeld** [comment]
Sorry for the slow response. I believe all of those Smartsheets have been deleted, and I'm not sure if it's possible for me to pull them up again. Feel free to skip those.

**Comment by JJediny** [comment]
Working Outline:
```
Build/roll out the Tech Radar
What does a “tech radar” mean to you?
What’s on the horizon? How can we utilize that?
Categories
What you’d want from each
Gap analysis
How widespread is the use?
Utilization: How frequently/heavily is each used?
How critical it is to people doing their job
Above: Time vs. coverage vs. depth
Maturity
https://www.thoughtworks.com/radar
Highlights whether there’s a tool vs. a preferred tool
Relates to acquisition: if there’s a tool, buy it. If not, build it.
https://www.digitalmarketplace.service.gov.uk/
Past TTS attempts:
Software Overview Card View (Smartsheet)
IT Standards entries by Category (Smartsheet)
Tech Radar (Smartsheet)
TTS Components (Trello)
GSA Cloud Capabilities Alignment (Google Sheet)
GEAR
Handbook
Tools list
Collaboration Tools
Meetings and meeting tools
What do we want it to be used for?
Reduce redundancies
Overhead of maintenance
Isolation of expertise
Go all in on what you have
Leverage new features
Education
Get full benefit
Better support internally
Plan
Change things vs. make things stay the same?
Be strategic through adopting new technologies
Customer satisfaction
Really frustrating to not have the tool to do your job
UX community does a good job advocating for themselves
Engineering tends to deal with what they are given
Project Management can make it work with minimal tools
Help teams do research into new tools
Saves time
“I didn’t know I needed this tool”
Triage
Prioritization
Focus on what’s missing
Releasing RFIs
Need to be careful to not have tools picked out in advance
Communication
Transparency
Consistency
Relevant links:
Project management tool landscape
Continuous Authorization tools
Collaboration Tools page
Decision tree for magical spreadsheets
We are close to having something already — need to follow through
https://github.com/18F/tts-tech-portfolio/issues/1237
What are the categories?
What attributes do we want to have?
```

**Comment by jonahczerwinski** [comment]
Exciting to see there's interest in creating a Tech Radar for TTS/18f. A group of us here at TW would love to help out if we can.

**Comment by JJediny** [comment]
This concept dovetails with the work you've demoed 10/10/24 on the new Software Inventory. This fits more into how that data is displayed   adding you to this issue for awareness only
