### ISSUE TITLE
write up job description

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1240]
## Background Information

We don't have the go-ahead to hire _yet_, but the hope is that that will come soon, and we'll want to be ready.

## Implementation Steps
- [x] Get consensus on what skill(s) we could benefit from the most
    - [Stormdraining](https://docs.google.com/spreadsheets/d/1ENJFQXtFZfkCkX0f_r8q_u3Pz2qta8skwU_6fvXI_cE/edit#gid=0)
- [x] Make copy of [Technology Portfolio Specialist post](https://join.tts.gsa.gov/join/technology-portfolio-specialist/)
- [x] Edit as needed

## Acceptance Criteria

- [x] Job description ready to send to Hiring team

**Comment by afeld** [comment]
[Detail position job opening draft](https://docs.google.com/document/d/1pXOg7iz2mRjTlP00DqjLnAgQqxYJP8EyGb0QIYiZom0/edit#)

**Comment by afeld** [comment]
Resolved all comments, and passed along to Ashley M and Karen T.

**Comment by afeld** [comment]
[Agenda for staffing meeting on 3/15](https://docs.google.com/document/d/15hYi_2WM4io9Q0U_u4j9yPa1V4xy-4pGUe638fcb2Wo/edit#heading=h.ggt3brf5lemt)
