### ISSUE TITLE
InVision Option - Due 3/14

### ISSUE THREAD

**Issue by melanienleopold** [18F/tts-tech-portfolio#1244]
## Background information

The InVision option needs to be exercised by 3/14.

## Implementation Steps

- [x] Send a letter to the client asking them if they want to exercise the option
- [x] Send a letter to the contractor notifying them of the intent to exercise the option
- [x] Get funding from the program office
- [x] Exercise the option in ASSIST

## Acceptance criteria
- [x] InVision option is exercised with the condition they will get FedRAMPed and make progress by May or the contract will be terminated.
