### ISSUE TITLE
make ATO assessment scheduling more objective

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1246]
## Background Information

We met with Ashley Mahan last week to get her input on how to prioritize upcoming assessments against each other (https://github.com/18F/tts-tech-portfolio/issues/1214). Based on her experience in FedRAMP, her advice was that the fairest way to handle this was to make it as objective as possible: once a system meets certain criteria, it gets into the queue, first come first served. "This system is really important so should go first" should be the exception (or not happen at all), not be the rule. Very wise!

We also need to make sure this works for Security. One way to approach this is with a "fixed resources flexible scope": have one or two assessments for TTS systems happening at any given time, and the first thing that's ready gets slotted in next. Assessment schedules:

- [TTS](https://docs.google.com/spreadsheets/d/19wyA91KhGoZvnAA0fihC0WF_mU79YLRTHzDd-Frs8Qs/edit#gid=0)
- [All of GSA](https://docs.google.com/spreadsheets/d/1e0qq84omixyVTXenOXAOqwSUgGkI80KdSwgoClMwk9s/edit?ts=5fa2bbda#gid=998527993) 

## Implementation Steps
- [x] Confirm with Security that this approach would work for them
- [x] Get consensus between the Tech Portfolio and Security on what the scheduling entrance criteria should be
- [x] Update ATO checklist to reflect prerequisites for assessment (scheduling)

## Acceptance Criteria

- [x] There are documented objective criteria/process for how assessments are ordered

**Comment by afeld** [comment]
The Security team is building out checklist templates and automation in Trello that will achieve this, all under the "Clean ATO" umbrella. Will follow their lead.

**Comment by afeld** [comment]
Per @rpalmer-gsa, prerequisites are coming in the forthcoming Clean ATO Guide.

**Comment by rpalmer-gsa** [comment]
Will have ATO checklist by EOW. View as guidelines that still need steering.

**Comment by afeld** [comment]
Finished this while completing https://github.com/18F/tts-tech-portfolio/issues/1359.
