### ISSUE TITLE
respond to Inspector General Hotline complaint re: custom emoji - due 2/22

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1251]
## Background Information

[The complaint](https://drive.google.com/file/d/1p9elzF4HjgVnLc9UvBYOHw3LZwJCWEpR/view?usp=sharing):

> TTS has created a custom emoji keyboard of over 6000 emojis. These custom emojis have been created on GSA staff time. They don’t feel like they can express themselves using only the standard emoji keyboard. … custom emojis could have all kinds of inappropriate issues

TTS is given the opportunity to provide an "informal reply".

## Implementation Steps
- [x] Get advice on how long/detailed the response should be
- [x] Fill out [response template](https://docs.google.com/document/d/1gnwSXyFUy5Pq4Rdp7V2yn7ZXsxTDOihC/edit#)
- [x] Notify Neichole

## Acceptance Criteria

- [x] Response provided to Inspector General

**Comment by afeld** [comment]
Completed.
