### ISSUE TITLE
process for Software Concierge prioritization

### ISSUE THREAD

**Issue by melanienleopold** [18F/tts-tech-portfolio#1253]
## Background information

We get a lot of requests for tools; how do we decide which to spend time on?

https://handbook.tts.gsa.gov/software/

## Implementation steps

- [x] Break out [the Concierge questions](https://docs.google.com/document/d/1DBCuxMFE5anShLIRxUD1qE7eDffKsrNEtAscjCF978s/edit#heading=h.mibezfdjpr7p) as a template
- [x] Documented way to enter the queue

## Acceptance criteria

- [x] Documented process around how we prioritize requests for new software

**Comment by afeld** [comment]
@melanienleopold Can you confirm this card matches what you intended?

**Comment by josephderosales** [comment]
IT Standards Team utilizes "first in - first out" in terms of prioritization, unless there is an urgent need or leadership needs immediate turnaround.

**Comment by josephderosales** [comment]
I created a Software Concierge Analysis form based on the new process which captures the needs of the customer and the prioritization of reviews.

@afeld Create a copy and modify as needed:

https://docs.google.com/document/d/171AvY7bQc03EPqgbvsy29zvjOivr6WuXFXb_1WKinkM/edit?usp=sharing

**Comment by josephderosales** [comment]
@afeld resolved all your comments from the PR. Feel free to modify as needed, merge changes, and close this issue when you're comfortable.

**Comment by afeld** [comment]
Closed via https://github.com/18F/handbook/pull/2471.
