### ISSUE TITLE
stormdraining - FY21 Q2

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1257]
## Background Information

https://docs.google.com/spreadsheets/d/1ENJFQXtFZfkCkX0f_r8q_u3Pz2qta8skwU_6fvXI_cE/edit#gid=0

## Implementation Steps
- [x] Stormdraining spreadsheet filled in
- [ ] Issues created around action items

## Acceptance Criteria

- [ ] Action items around how to reclaim tech portfolio time and reducing toil

**Comment by afeld** [comment]
Folding into https://github.com/18F/tts-tech-portfolio/issues/890.
