### ISSUE TITLE
lay out different SaaS ATO options at GSA

### ISSUE THREAD

**Issue by melanienleopold** [18F/tts-tech-portfolio#1259]
## Background
There is a big difference between FedRAMP an an agency ATO. Just because a SaaS product has a FedRAMP approval doesn't mean they have an ATO and vice versa. This is a common question that many in government don't understand.

**User story:** As a TTS staff member trying to use SaaS, I want a guide to help me understand what ATO path to take to get the tool I need.

## Implementation Steps

- [ ] Decide on intended audience(s)
- [ ] Read about the difference between FedRAMP and an ATO
- [ ] Create a short one pager about the differences
- [ ] GSA IT approves 

## Acceptance Criteria
- [ ] We have a flowchart showing the SaaS ATO options at GSA

**Comment by afeld** [comment]
- [FedRAMP Tailored Overview](https://docs.google.com/document/d/1FhnHstwCUgbvLGkCP7DSkgGZPnMuYm1UiWiWfZKq1pc/edit#)
- [LISaaS Process Guide](https://www.gsa.gov/cdnstatic/Low_Impact_SaaS_(LiSaaS)_Solutions_Authorization_Process_%5B16-75_Rev_4%5D_03-02-2020docx.pdf)

**Comment by afeld** [comment]
Imagining a decision tree showing the relationship between the different security authorization processes at GSA (FedRAMP, LISaaS, etc).

**Comment by afeld** [comment]
Sounds like @rpalmer-gsa is working on this.

**Comment by afeld** [comment]
Started [a sketch of a decision tree](https://docs.google.com/drawings/d/1vvrnyj_3JSSp-Kw89-PF9Yh2KKtnOcHX3244XrkFKwg/edit), just to get it out of my head. Not planning to spend more time on it right now.

**Comment by afeld** [comment]
@its-a-lisa-at-work put together [a similar diagram in Mural](https://app.mural.co/t/gsa6/m/gsa6/1615221353863/3906324760f0fbe6cd1cff26b75751109101d802).

**Comment by rpalmer-gsa** [comment]
Working on this with release of Clean ATO Guide.

**Comment by afeld** [comment]
Figure this will be a great first issue for @rocheller123 to pick up, in terms of:

- Getting a lay of the land in terms of the authorization processes at GSA
- Working closely with @rpalmer-gsa 
- Being relatively self-contained
- Not requiring stakeholder buy-in, negotiation, etc.

@josephderosales Unassigning ya, since it seems likely @rocheller123 will get to it before you have bandwidth. Let us know if you'd still like to be involved.

**Comment by adborden** [comment]
Maybe we can include https://github.com/18F/handbook/issues/2701 when we address this work.

**Comment by JJediny** [comment]
Closing as we have updated the TTS Handbook to point TTS members directly to the GSA IT Standards process - https://sites.google.com/a/gsa.gov/it_standards/it-standards
