### ISSUE TITLE
All Hands TODO - Meeting adjustments

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#126]
As a member for TTS Tech Portfolio, I want less meetings and shorter meetings

As per task #123 one of the tasks is to capture all the TODOs and make them a GitHub issue and [this](https://docs.google.com/document/d/1N4osbsZjxbNQUZCXNd706BAzWRhBlb8pfh7wAWJbnPU/edit#bookmark=id.q9q7lkfzgo9t), [this](https://docs.google.com/document/d/1N4osbsZjxbNQUZCXNd706BAzWRhBlb8pfh7wAWJbnPU/edit#bookmark=id.m4kxk1f2beh9), [this](https://docs.google.com/document/d/1N4osbsZjxbNQUZCXNd706BAzWRhBlb8pfh7wAWJbnPU/edit#bookmark=id.18y1h11qumwj) and [this](https://docs.google.com/document/d/1N4osbsZjxbNQUZCXNd706BAzWRhBlb8pfh7wAWJbnPU/edit#bookmark=id.l57pc613b5tu) was ones from the meeting

- [x] Make current meetings shorter

- [x] Cancel meetings (like one on ones) 

- [x] Schedule stand-ups on Monday, Wednesday & Friday from 9:30-10:00

- [ ] @JJediny to create a meeting template

**Comment by its-a-lisa** [comment]
Put together a [template](https://docs.google.com/document/d/1K1ErVdKNf4UAXK01L5enoTwCjqF0HhFHswr57hcXqwo/edit)
