### ISSUE TITLE
reconcile what lives in Smartsheet vs. elsewhere

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1268]
## Background Information

cc https://github.com/18F/tts-tech-portfolio/issues/1213

## Implementation Steps
- [x] Set up meeting with @its-a-lisa-at-work 
- [x] Inventory what is present in Smartsheet
- [x] Decide what we want to continue to maintain there
- [x] Deprecate what needs to be deprecated

## Acceptance Criteria

- [x] We have decided on (current state) sources of truth

**Comment by afeld** [comment]
[Notes](https://docs.google.com/document/d/1gDDCqXJ8_mUoK1u_QmD8yLIPcIbKGrb59eM4sxGuRiY/edit). Set up a follow-up time to dig into the `Software` and `TTS Tech Portfolio` workspaces.

**Comment by afeld** [comment]
Complete.
