### ISSUE TITLE
All-Hands TODO - Travel Budget Review

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#127]
As a member for TTS Tech Portfolio, I want to know how much travel budget we have. 

As per task #123 one of the tasks is to capture all the TODOs and make them a GitHub issue and [this](https://docs.google.com/document/d/1N4osbsZjxbNQUZCXNd706BAzWRhBlb8pfh7wAWJbnPU/edit#bookmark=id.iwcdekicz5vf) was one of them

- [ ] Aidan figures out travel budget with Dom

- [ ] The team projects how much travel they plan on completing in FY20

- [ ] The team makes sure to request enough travel budget for the next year

**Comment by afeld** [comment]
Part of #166.
