### ISSUE TITLE
ensure Tech Portfolio awareness for large non-OA acquisitions

### ISSUE THREAD

**Issue by josephderosales** [18F/tts-tech-portfolio#1273]
## Background Information

Agree on a process to initiate FITARA reviews for large dollar value TTS acquisitions going to NCR for processing.

## Implementation Steps
- [x] Decide on exactly what we want to be notified about
- [x] Find out how Acq wants to handle
- [x] Formalize process
- [x] Notify TTS offices impacted

## Acceptance Criteria

- [x] Process in place to notify Tech Portfolio about large upcoming technical acquisitions (requiring FITARA)

**Comment by josephderosales** [comment]
Pull request created : Update fitara.md #2430 on https://handbook.tts.gsa.gov/fitara/

@afeld listed as reviewer

**Comment by afeld** [comment]
Included in [the Tech Portfolio updates for the next newsletter](https://docs.google.com/document/d/1H7-1iYQaCYOqrozOchK5vdfp142dvCfr-GQ3p4J-0i4/edit#heading=h.mdujyb1mkxat). Good enough for now!
