### ISSUE TITLE
make plan for American Rescue Plan

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1277]
## Background Information

[The American Rescue Plan Act contains $150M for the FCSF.](https://www.congress.gov/bill/117th-congress/house-bill/1319/text#toc-HB7796CF334B347FA85DCE071C306EDE8) Solutions needs a plan for how that money should be spent.

## Implementation Steps
- [x] Consensus on scope
- [x] Decide on format for meeting with portfolio leads
- [x] Create destination for proposals
- [x] Decision on proposal limits (e.g. X per program)
- [x] Instructions sent to portfolio leads
- [x] Brainstorming session scheduled
- [x] Get constraints from OGC (e.g. how tightly focused on COVID does the spending need to be)
- [x] Pick [top three Tech Portfolio ideas](https://docs.google.com/document/d/14NNssZCvnrPZqbZb0UguG9WzOuMRHT1YnwvmS_YS3ew/edit#)

## Acceptance Criteria

- [x] Spend plan created

**Comment by afeld** [comment]
[Notes on approach](https://docs.google.com/document/d/14NNssZCvnrPZqbZb0UguG9WzOuMRHT1YnwvmS_YS3ew/edit) (restricted access)

**Comment by afeld** [comment]
[Ideas submitted on behalf of Tech Portfolio.](https://docs.google.com/document/d/1ejCV1LYnkiJVGrESlBszBGnr_mz5TY4S4j1FzC84Iqw/edit#heading=h.rg99ueeqibvl) Kristina B is taking next steps.

**Comment by afeld** [comment]
This is now being handled by Ashley Mahan and Karen Trebon, so closing.
