### ISSUE TITLE
Establish a structure to rotate operations tasks

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#128]
## Story

As a member for TTS Tech Portfolio, I want an on call structure within the team so I can focus on tasks uninterrupted 

## Problem we're trying to solve:
- Constantly context switching makes it hard to accomplish assigned issues. 
- Spending too much time working on tactical items and not strategic vision

## Background information: 
As per task #123 one of the tasks is to capture all the TODOs and make them a GitHub issue and [this](https://docs.google.com/document/d/1N4osbsZjxbNQUZCXNd706BAzWRhBlb8pfh7wAWJbnPU/edit#bookmark=id.3kqg2afdre2e) was ones from the meeting

## Actions to take: 
- [x] Enumerate all the services that the on-call person would be responsible for; [Guide](https://docs.google.com/document/d/1Qw8AWzmv22yiTYb0tiUmv6I3mbLPUnShnnZVfrN34Wg/edit#heading=h.rb09koewes5q)

- [ ] Validate that each person has the knowledge, skills, access, & abilities to handle each request; [Spreadsheet](https://docs.google.com/spreadsheets/d/1O66d2NpNBfOEr76u0MJ85O7HuJSxijCHyKUEL6i8zTU/edit#gid=341495638) - #147

- [x] Create an on-call schedule; [calendar](https://calendar.google.com/calendar?cid=Z3NhLmdvdl82aDI5YnF1ZGx0NGVoZTVzOWswOGlmdGZxMEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

- [x] Send out meeting invites for schedule on shared calendar  [calendar](https://calendar.google.com/calendar?cid=Z3NhLmdvdl82aDI5YnF1ZGx0NGVoZTVzOWswOGlmdGZxMEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

- [x] Communicate the on-call concept with stakeholders

- [x] Develop [playbooks](https://docs.google.com/document/d/1CZ5WMA8o3Ysn9ZhKUF8doevldPGmKISzmNHjEWsBBVk/edit#) for on-call purposes

## Acceptance Criteria

- [x] All members of the Tech Portfolio review documents 
- [x] All members of the Tech Portfolio approve documents 

## Initial documentation: 

- [On call documentation](https://docs.google.com/document/d/1-E6uUv8rCoByejWm7fYBl7SbtjeHd4PXTC0ZBnyrwXo/edit#)

## Task Origin: 
All Hands TODO

**Comment by afeld** [comment]
The [SaaS inventory](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=0) is the entry point for how to manage each service.

**Comment by its-a-lisa** [comment]
Checked off the task to communicate the on-call concept with the stakeholders since @afeld posted it in the #infrastructure slack channel and @mogul pinned it

https://gsa-tts.slack.com/archives/C039MHHF8/p1574107589303900

**Comment by its-a-lisa** [comment]
Closing issue since all acceptance criteria has been met; the task of access will be addressed in #147
