### ISSUE TITLE
prep for AMA - due 3/19

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1281]
[**Prep doc**](https://docs.google.com/document/d/1ZkfZtMHNK7idajH2k8ZqgGVhKzDluWOZHGkhaV4SY6s/edit#)

## Background Information

Our team got asked to do a TTS-wide Ask Me Anything session.

## Implementation Steps
- [x] Fill out calendar invite template
- [x] Prep presentation
   - [x] Pull info from [past presentations](https://drive.google.com/drive/folders/10LCPsg-ENLbqO_xEXPsbx81vTZc36iIX)
   - [x] Provide overview of the team, assuming there are people new to TTS
   - [x] Introduce team members
   - [x] Include call to action (join channel, etc.)
- [x] Come up with some seed questions for moderator

## Acceptance Criteria

- [x] Prepped for AMA

**Comment by afeld** [comment]
[Slide deck](https://docs.google.com/presentation/d/1OBvGHFDm1VPQ4GngJ47Kr_YCYZ2I7iMMowomCK34l6M/edit?usp=sharing) (work in progress)

**Comment by afeld** [comment]
[Feedback and retro materials](https://docs.google.com/presentation/d/1C_JduBO3NyMttHM_W3m-9WUNiwQYEZbkNtSyi9N8GGY/edit#slide=id.g86f50b263d_0_121), for later reference.
