### ISSUE TITLE
determine if Google Drive integration is usable in Slack

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1285]
## Background Information

Question has come up a couple of times recently:

- https://gsa-tts.slack.com/archives/C03EMDS6P/p1615991785027400
- https://gsa-tts.slack.com/archives/C05693VM7/p1616032443001100
- https://gsa-tts.slack.com/archives/C03EMDS6P/p1621953516055800?thread_ts=1621952105.052800&cid=C03EMDS6P

Need to confirm that is intentional, as it caused us compliance problems in the past.

## Implementation Steps
- [x] Check if Handbook needs to be updated
- [x] [Notify TTS](https://docs.google.com/document/d/1H7-1iYQaCYOqrozOchK5vdfp142dvCfr-GQ3p4J-0i4/edit#heading=h.3boghnllsheh)

## Acceptance Criteria

- [x] TTS staff have been made aware of whether the Google Drive integration can be used

**Comment by afeld** [comment]
[Confirmed.](https://gsa-tts.slack.com/archives/C02KW46DP/p1623957036032800?thread_ts=1621614309.014600&amp;cid=C02KW46DP) Added to newsletter as part of https://github.com/18F/tts-tech-portfolio/issues/1389, so staff will be notified when that goes out.
