### ISSUE TITLE
New Relic Call Order - due 4/14

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1286]
## Implementation steps

- [x] Figure out data usage split
- [x] Figure out cloud.gov amount

## Acceptance criteria

- [x] Call order issued
- [x] Option exercised

**Comment by melanienleopold** [comment]
PRs for Solutions is complete. Login and cloud PRs are in progress.

**Comment by melanienleopold** [comment]
Waiting on Cloud and Login PRs.

**Comment by melanienleopold** [comment]
Send to vendor for signature.
