### ISSUE TITLE
Google Data Studio

### ISSUE THREAD

**Issue by josephderosales** [18F/tts-tech-portfolio#1287]
## Background Information

Some offices within TTS require the use of Google Data Studio (free tool) for their Dashboarding needs. Tableau is not a free solution and does meet specific use-cases for folks wanting to use Google Data Studio.

## Implementation Steps
- [ ] Determine history of Google Data Studio
- [ ] Engage IT Security 
- [ ] Re-open any necessary IT Standard request ticket if needed
- [ ] Process ticket accordingly

## Acceptance Criteria

- [ ] Obtain approval or updated denial (with justifications) of Google Data Studio

**Comment by josephderosales** [comment]
Emailed Chris M and Security to get a status update and to re-engage this request: https://gsa.my.salesforce.com/a1Zt0000000PiZn?srPos=0&srKp=a1Z

**Comment by josephderosales** [comment]
**From GSuite Admins:**
Data Studio has been rejected by IT Security.
Furthermore, Google has no intention of ever making it part of the scope of the FedRAMP boundary for Workspace.

**From IT Security:**
Google services/apps that are not part of the FedRAMP boundary will not be approved.
