### ISSUE TITLE
Raspberry Pie Equipment Purchase

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1292]
## Background information

The 10x team is requesting the purchase of raspberry pies to gather data at 9 libraries around the country. They would be purchasing the equipment in the [spreadsheet ](https://docs.google.com/spreadsheets/d/1TE78BBcLyaqqqXMHXlklsEvjNnzN4tsIrYntamJXRXY/edit#gid=0)and sending them out to libraries.

## Implementation Steps
- [x] Requester submits [equipment form](https://gsa.servicenowservices.com/sp/?id=sc_cat_item&sys_id=ed419ee8dbd2e7000dc9ff621f9619c6) to IT
- [x] IT Approval
- [x] FITARA
- [x] Micropurchase Approval

## Acceptance criteria

- [x] Raspberry pies are approved by IT and purchased OR
- [ ] Raspberry pies are not approved and the team finds a different path forward

**Comment by melanienleopold** [comment]
Waiting on FITARA review
