### ISSUE TITLE
ServiceNow Pricing for on-call functionality

### ISSUE THREAD

**Issue by melanienleopold** [18F/tts-tech-portfolio#1300]
[**Notes doc**](https://docs.google.com/document/d/1UgE4dgBvUGq-ssj7_ecOTCyH_WP8wIKZuYIRT4nhAAU/edit#)

## Background information

Continued from [#979](https://github.com/18F/tts-tech-portfolio-private/issues/979)

## Implementation steps

- [x] Metrics collected from teams
- [x] Pricing estimate received from GSA IT
- [x] [Cost difference calculated](https://docs.google.com/spreadsheets/d/1SvVJwIXBwDCjb7Fl-a57rSLYgQ3P7WdI8A22pz_oRE8/edit#gid=440187249)
- [x] Tech Portfolio shares pricing information with offices
- [x] Enumerate what costs would be consolidated (moving from other software)
- [x] Confirmation from:
   - [x] cloud.gov
   - [x] login.gov
   - [x] FCSF

## Acceptance criteria
- [x] TTS programs willing to use it and pay for it are identified.

**Comment by afeld** [comment]
Submitted ticket IDEA0001920 to get information about pricing and implementation timeline.

**Comment by afeld** [comment]
@melanienleopold Mind passing the ticket number along to whomever directed us to that form?

**Comment by melanienleopold** [comment]
Done!

**Comment by melanienleopold** [comment]
Likely we will receive the ROM early May. Will follow up with the ServiceNow team at the end of the month.

**Comment by afeld** [comment]
As requested by the ServiceNow team, put together [a spreadsheet collecting metrics from each team](https://docs.google.com/spreadsheets/d/1v8mw5grwDkuklUmL7z3FfDMNSBUMQczRBGpjpy8PM1o/edit#gid=0) and pinged all of them to fill in.

**Comment by afeld** [comment]
Passed the list of programs and their metrics to the ServiceNow team; waiting for them to get back on next steps.

**Comment by afeld** [comment]
Currently thinking of the move to ServiceNow in the following order (subject to change):

1. Replacing current usage things we need to move off of
   1. OpsGenie (#876)
   1. HubSpot
   1. ZenDesk
1. Open up to usage by additional teams that weren't using the above
   1. Help desk
   1. On-call alerting
1. Consider [replacing StatusPage](https://docs.servicenow.com/bundle/quebec-servicenow-platform/page/build/service-portal/concept/service-status-widgets.html)

**Comment by afeld** [comment]
Narrowed scope of this issue to the on-call functionality, for which the ServiceNow team says they have what they need. Will create follow-up issues as applicable.

**Comment by afeld** [comment]
- [Project Charter](https://docs.google.com/document/d/1kdUTTzEF9st_971ZoSVD1B7rqiGrbE9G8fC0nMltqys/edit)
- [Estimate](https://docs.google.com/spreadsheets/d/1SvVJwIXBwDCjb7Fl-a57rSLYgQ3P7WdI8A22pz_oRE8/edit#gid=440187249)

**Comment by afeld** [comment]
Pricing confirmed by the affected teams.

**Comment by afeld** [comment]
Moved the roadmap above into the [Charter](https://docs.google.com/document/d/1kdUTTzEF9st_971ZoSVD1B7rqiGrbE9G8fC0nMltqys/edit#), under Major Milestones.
