### ISSUE TITLE
Tech Portfolio Included in OA Intake Process

### ISSUE THREAD

**Issue by melanienleopold** [18F/tts-tech-portfolio#1301]
## Background information

The Tech Portfolio should be looped into the OA intake process when software is involved in the request.

## Implementation steps
- [x] Meet with Megan from OA
- [x] Determine how to incorporate Tech Portfolio into the Google form
- [x] Determine where to direct new requests

## Acceptance criteria
- [x] Consensus with OA on how the Acquisition and software intake processes integrate/intersect

**Comment by afeld** [comment]
Noted we have a number of overlapping intake processes:

- Software Concierge
   - [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfnf4xWMMHCqZ8FmP8inVWMwE-1-H4mPAc5Et1JapesOdNkiA/viewform)
   - [Smartsheet](https://app.smartsheet.com/b/form/e11de350b35f498bb06bd9766a5a3d36)
- [Acquisition](https://docs.google.com/forms/d/e/1FAIpQLSeGoLWQ_6yEmxlrHuztlZWH6sX3t_0J0PPnzZxhwlK6nq1KoQ/viewform)
- [Micropurchase](https://docs.google.com/forms/d/e/1FAIpQLSd-GoOE9xWWfJvdZNRP3SE7mj5ysI_RfM8brxdG8YpyJV9yKA/viewform)

**Comment by afeld** [comment]
For now, @MeganReedGSA is going to send software-related requests to tts-software@gsa.gov.
