### ISSUE TITLE
writeup around compliant source code management tool - due 8/11

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1305]
## Background Information

TTS programs (particularly those that have / are going for FedRAMP JAB authorization) are in need of source code management tool that is authorized at Moderate (or above) and can be accepted as a third-party system by the JAB.

"Who's currently using what?" will be answered by #1237.

[Notes from initial conversation](https://docs.google.com/document/d/1EBealVgNKpClnGEQPaJiB57XrfxIYpno-IjABx-h8y4/edit)

## Implementation Steps
- [x] Document minimal requirements
- [x] Document options with pros and cons
- [ ] Convene Working Group

## Acceptance Criteria

- [ ] Minimum Viable solution identified

**Comment by afeld** [comment]
login.gov is actively working on a proof of concept deployment of GitLab. I sat in on the kickoff and emphasized that they should consider what it would take to solve the problem for more teams within TTS (at least). They acknowledged and are open to that. Plan for this issue is to make a more formal proposal across Solutions (if not across TTS or GSA).

**Comment by afeld** [comment]
[Notes from conversation with login.gov Mary team](https://docs.google.com/document/d/1_-g1K8oJk4nOUStGfl7CResAmlkBJwI3LDHXt_--qO0/edit)

**Comment by its-a-lisa-at-work** [comment]
@afeld is this something you'd like help from @wesley-dean-gsa ?

**Comment by rpalmer-gsa** [comment]
If deployed in LG boundary, it would be interesting to see how it will be shared. My initial impression is that cloud.gov would better fit and align.

**Comment by its-a-lisa-at-work** [comment]
+ 1 for this to happen in the cloud.gov boundary

**Comment by afeld** [comment]
Would welcome help! Idea here is to document current state of affairs and lay out some potential paths forward. @wesley-dean-gsa If you'd be willing to get things started by taking the [info you put in Slack](https://gsa-tts.slack.com/archives/CG8SNAEQM/p1628195395026000) into a doc as a starting place, that would be super helpful.

**Comment by wesley-dean-gsa** [comment]
@afeld is the documentation being requested due on Wednesday, August 11th (per the title of this issue)?  Also, I'm assuming that the documentation would be in the form of a markdown document added to this repo.  Is that correct?

**Comment by afeld** [comment]
There’s a meeting with Security on the 12th around this, so looking to share before that to ensure everyone is on the same page going in. I was thinking a Google Doc to make it easier for folks (especially without GitHub experience) to comment.

**Comment by wesley-dean-gsa** [comment]
Working on it now.  Google Doc will be just fine.

**Comment by wesley-dean-gsa** [comment]
Just started a blank Google Doc.  I'll focus on the documentation and let someone else more deeply gifted with design sense focus on the aesthetics.

https://docs.google.com/document/d/15xe_Xbxfc9HLma5nBr8xKjhilKmfph0fmqGiNFNyxQI/edit?usp=sharing

(all of GSA can edit)

**Comment by wesley-dean-gsa** [comment]
@afeld what is your vision for this document?  would it be a textual document laying things verbosely laying things out?  or should it be a chart for side-by-side comparison?  or both?  or neither?  (and if so, what would be the desired format?)

**Comment by afeld** [comment]
Added a "purpose" to the top of the doc. Will close this issue as soon as next steps are identified.

**Comment by afeld** [comment]
Short-term follow-ups around compliance for existing tools:

- https://github.com/18F/tts-tech-portfolio/issues/1504
- https://github.com/18F/tts-tech-portfolio/issues/1532

**Comment by afeld** [comment]
@bryanlalexander is taking next steps.
