### ISSUE TITLE
mid-year reviews - due 6/1

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1314]
## Implementation Steps
- [x] @afeld
    - [x] Provide 3-4 names for 360 reviews
    - [x] [Self-evaluation](https://docs.google.com/document/d/12lp0x1VycoQ1Tss9P2J2zsSGmUX7L9CXjHkXY3TbIHk/edit#)
    - [x] Meeting
    - [x] Acknowledged
- [x] @JJediny 
    - [x] 360 reviews
      - [x] Get 3-4 names
      - [x] Get feedback from them
      - [x] Summarize
    - [x] Meeting
    - [x] Review acknowledged

## Acceptance Criteria

- [x] Review acknowledged in HRLinks

**Comment by afeld** [comment]
Put together [a feedback form](https://docs.google.com/forms/d/1MY8T4JjVVG8pFLvWfcrzVBQdqJpS4ULw5LLgLA51APo/edit), and sent to [the names @JJediny provided](https://gsa-tts.slack.com/archives/CNW3GL70S/p1620409577034600?thread_ts=1620409309.033200&cid=CNW3GL70S).

**Comment by afeld** [comment]
Mine is complete. Summary provided to @JJediny — meeting next week.

**Comment by afeld** [comment]
Complete!
