### ISSUE TITLE
fill out MEF Forms 2 and 3 - due 4/26

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1327]
[**Drive folder**](https://drive.google.com/drive/folders/1I53LwxcMPHvoCWZziN4jvQ3wWFc2tvF8)

## Background Information

The Tech Portfolio was identified as being responsible for a Mission-Essential Function (MEF) of `Manage TTS-wide software and infrastructure`. We need to fill out the next round of paperwork.

[TTS MEF descriptions](https://docs.google.com/document/d/1FBpk7hNQ8A4iI_LtBamrv-PsakE2WYjCNAStAGMUqbI/edit?ts=6082ceaa)

## Implementation Steps
- [x] Fill out Form 2
- [x] Fill out Form 3
- [ ] ~~Tag @JJediny for input~~
- [ ] ~~Sketch COOP event process diagram~~
   - What does the Tech Portfolio need to do if/when a COOP event happens?
- [x] Send to Dan Irwin

## Acceptance Criteria

- [x] Forms 2 and 3 finalized

**Comment by afeld** [comment]
Second draft complete; waiting for input from teams that are included.

**Comment by afeld** [comment]
Complete.
