### ISSUE TITLE
match system names in Inventory to FISMA System names

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1328]
[**TTS system inventory**](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=1235102795)

## Background Information

GSA keeps [a list of FISMA systems in GEAR](https://ea.gsa.gov/#!/FISMA), which are presumably the names used in Archer and elsewhere.

## Implementation Steps
- [ ] Confirm that names in GEAR match those in Archer
- [ ] Update names in inventory (all sheets) to match
- [ ] Get any inconsistencies between GEAR and Archer addressed

## Acceptance Criteria

- [ ] System names match between GEAR, Archer, and TTS inventory
