### ISSUE TITLE
Clarify how to request Desktop Applications under GSA IT Standards

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#1333]
## Background Information

Some TTS users have requested specific desktop applications through the ServiceDesk and have had them approved as one off installations. The process to request having an application made available on GSA Self Service is not well established.

## Implementation Steps
- [x] Determine the workflow and entry point for new requests
- [x] Determine the security and package hosting requirements
- [x] Clarify on [software page of Handbook](https://handbook.tts.gsa.gov/software/) how to obtain approved vs. unapproved desktop software

## Acceptance Criteria

- [ ] Acknowledgement from service desk that requests for non-approved desktop software should be directed to IT Standards

**Comment by josephderosales** [comment]
handbook pull request Update software.md #2471 submitted to provide additional clarification

**Comment by josephderosales** [comment]
Bruce Teng has been formally notified and will pass the information along accordingly among the mac support team
