### ISSUE TITLE
create FedRAMP package request workflow

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1338]
[**Template**](https://app.docusign.com/templates/details/434e60cc-fbd1-4708-9373-aef41439ff05)

## Background Information

I was needing to put in a FedRAMP package request, and don't have a good way to do a digital signature locally. Started setting up the DocuSign package, and realized it was only a little more work to create a template that gets automatically filled and routed.

## Implementation Steps

- [x] Create template
- [x] Get access for:
   - [x] @jhoyt22 
   - [x] @rpalmer-gsa 
   - [x] @rhoesing 
- [x] Test
   - [x] Signed by @jhoyt22 
   - [x] Received by FedRAMP team
   - [ ] Package access granted

## Acceptance Criteria

- [x] There's a streamlined workflow for requesting FedRAMP packages in GSA

**Comment by afeld** [comment]
Asked GSA IT's Web Team if we can link to the Template from InSite; will close once I hear back from them.
