### ISSUE TITLE
fill out MEF Forms 3A and 3B - due 5/28

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1339]
## Background Information

Follow-up to https://github.com/18F/tts-tech-portfolio/issues/1327. These are the last two materials that need to be produced for this round of Mission Essential Function (MEF) creation/revision.

## Implementation Steps
- [x] First draft of [Form 3A](https://docs.google.com/document/d/1Ps9Yqk3-DUDnCsvgU40NP5MGhegrbeHE/edit)
- [x] First draft of [Form 3B](https://docs.google.com/spreadsheets/d/1xGeakXEtl9qxJHUYxkbpReNi3PNnl6N9/edit#gid=1922565526)

## Acceptance Criteria

- [x] Forms completed and team notified

**Comment by afeld** [comment]
Complete.
