### ISSUE TITLE
GitHub training

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#134]
## User Story:
As someone who is not familiar with GitHub, I would like to get better at it. 
As someone who is only using GitHub for markdown, I would like to know the basics. 
## Problem Statement: 
Have heard from multiple people who have joined recently that they aren't comfortable with GitHub, but want to be. 
## Actions to take:  
- [ ] Tech Portfolio offers one time training to get people caught up
- [ ] Determine  plan for how to handle on an ongoing basis for new hires 
## Acceptance criteria
- [ ] Everyone at TTS who is interested in getting comfortable with the basics of GitHub has done so
## Supporting Documentation:
- There are some useful Github-related resources listed in this [Slack thread](https://gsa-tts.slack.com/archives/CHZLJBWCV/p1559759830000500).
- [Slack thread one](https://gsa-tts.slack.com/archives/C03EMDS6P/p1570034930196500)
- [Slack thread two](https://gsa-tts.slack.com/archives/C04KL9ZN2/p1571357280118500)
- [Tweet](https://twitter.com/aidanfeldman/status/1179439208429211649)
- [Deck](https://docs.google.com/presentation/d/1lntgXxSS8udxuETJepCWOL55XZ2ddTBxtCHALFOof-A/edit) from @jeremyzilar
## Related Issues: 
- [ ] [GitHub documentation issue](https://github.com/18F/handbook/issues/1530)

**Comment by jeremyzilar** [comment]
We should update the Handbook on-boarding page to better reflect all of TTS.
And make sure we are not missing steps —https://handbook.18f.gov/github/

**Comment by vickimcfadden** [comment]
will slack recorded this training before he left - https://www.youtube.com/watch?v=uNa9GOtM6NE&feature=youtu.be

**Comment by JJediny** [comment]
https://lab.github.com/install is also a good suggested resource for onboarding

**Comment by afeld** [comment]
Closing as stale.
