### ISSUE TITLE
clarify contractor onboarding/offboarding procedure

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1340]
## Background Information

Follow-up to https://github.com/18F/tts-tech-portfolio/issues/458 and others.

From my initial calendar invite around this:

> There have been a lot of conversations/issues/materials happening recently around TTS contractor access and equipment. Figure it would be good for us all to check in to make sure there's shared understanding and TODOs for process/documentation/checklists that need to be created or modified.

## Implementation Steps

May make sense to split some of these out to their own issues.

- [x] Set up Slack channel: #wg-contractors
- [ ] Reconcile TTS contractor onboarding checklists:
   - [Office of Acquisition](https://docs.google.com/spreadsheets/d/1-RHrM2K-oupQ-wdQp5dhU6M1UtbiM2fj9kY3fGikQSg/edit#gid=0)
   - [BizOps](https://docs.google.com/spreadsheets/d/1w0WSTUT0l7q19mAI6c2QCIpCFs0Cei4eukaiiRBTbRA/edit#gid=710529923) 
- [ ] Ensure new contractors get those things going forward (via clear documentation, responsibilities, etc)
- [ ] Get those things for existing contractors

## Acceptance Criteria

Looking to have a resource for TTS staff and contractors (people, not contracts) that clearly states:

- [ ] The set of steps for onboarding new contractors
- [ ] The set of steps for offboarding contractors
- [ ] Who is responsible for what with the above
- [ ] What they should/shouldn't have access to and can/can't do, relative to feds

**Comment by afeld** [comment]
This is one of those things that started small and quickly snowballed; seeing if I can coerce Acquisitions and/or BizOps to take the lead 😉

**Comment by adborden** [comment]
Recently ran into this because we saw (what looked like) out of band requests to remove folks from the 18F GitHub org. Seems like that should be a request coming from someone performing an offboarding checklist.

**Comment by afeld** [comment]
[Meeting notes from 6/21.](https://docs.google.com/document/d/1q2W44S5F-0v3eUQX8f1t3iMwH0EJCXZXqUC7OOiLbhk/edit) As [noted in there](https://docs.google.com/document/d/1q2W44S5F-0v3eUQX8f1t3iMwH0EJCXZXqUC7OOiLbhk/edit?disco=AAAAM4s1ZfA), @keithrwilson is looking into leveraging the existing fed checklist (which does include GitHub removal) for contractors.

**Comment by adborden** [comment]
Here's the data.gov perspective:

Data.gov doesn't treat contractors any differently than team members. Instead, we think about "roles" within the team. Don't forget, there's also the compliance side of this because we have to document different roles and access. We have Admin and Developer roles. For simplicity, the Program Management Office are assigned as Admins, and all other team members, including contractors, are Developers. There's no rule that a contractor can't be an Admin. In the past, they have been and if there were fewer people in the PMO, we would probably do that for redundancy.

The compliance side is what requires our [onboarding](https://github.com/GSA/datagov-deploy/blob/master/.github/ISSUE_TEMPLATE/onboard-team-member.md) and [offboarding](https://github.com/GSA/datagov-deploy/blob/master/.github/ISSUE_TEMPLATE/offboard-team-member.md) checklists to exist. The offboarding checklist is mostly a mirror of the onboarding checklist.

All team members go through the same onboarding checklist, but if you're an Admin, you have additional tasks layered on top. The offboarding checklist doesn't really distinguish between roles. If you're offboarding, Admin or not, we want to make sure we've removed you from _everything_. Offboarding _does_ make the distinction between leaving the team vs leaving TTS vs leaving GSA. It would be easy to add a "open ticket to offboard member from TTS" task.

There's some assumptions made for contractors. Our contract requires contractors bring their own equipment (no GSA laptop). We try to require they get a GSA email and PIV (and go through all the background checks, Rules of Behavior, EQIP etc to get those). It makes things too difficult when they can't get that GSA access. So the baseline is that they meet most of the conditions that might apply to someone onboarding at TTS.

In the past our contracts have not been through OA though. cc @hkdctol @mogul

**Comment by afeld** [comment]
[Thread about contractors and the computers they use](https://gsa-tts.slack.com/archives/CT21777HC/p1624557119004100)

**Comment by afeld** [comment]
[Checking on outstanding TODOs](https://gsa-tts.slack.com/archives/CT21777HC/p1625151273002000)

**Comment by afeld** [comment]
From @keithrwilson [in Slack](https://gsa-tts.slack.com/archives/C027JDBCB1S/p1625675489000100):

> did a test for the offboarding tracker that would include employee and contractors:
https://docs.google.com/spreadsheets/d/1U6w9QqBCGQoD3l-l1LRIlvPX1jKtejqzE09lBWD7F9s/edit#gid=1115275725
>
> i'm think that i could also have a separate employee and contractor sheets to keep them separate, and then just pull all of the items relevant to technology portfolio into a compiled tracker

**Comment by afeld** [comment]
Seems we've lost momentum; moved back to Icebox.
