### ISSUE TITLE
AWS Budget Projection Update Due 6/1

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#1342]
## Implementation Steps
- [x] Obtain CLIN001-004 budget amounts per program
- [x] Breakdown per resource per program over entire duration of contract.
- [x] AWS Budget projections look back over ~1 1/2 of cumulative spend vs budget and can be used to determined next round of funding period.

## Acceptance Criteria

- [x] Teams provided a recommended number for their subsequent purchase request
