### ISSUE TITLE
prep tasks for detail - due 5/28

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1345]
[**Doc**](https://docs.google.com/document/d/1uQKGqwVIAwO-cefh1gxvxyrXbHxEt3WYWGtpWkEoeA8/edit#)

## Background Information

@adborden is starting his detail to the Tech Portfolio 6/1, and want to have a clear idea (or at most a few options) of what he should focus on by the time he starts.

cc https://github.com/18F/tts-tech-portfolio/issues/1346

## Implementation Steps

- [x] First draft
- [x] Consensus from @JJediny 
- [x] Set up initial meeting with @adborden 

## Acceptance Criteria

- [x] Document laying out area(s) of focus, with some example issues linked

**Comment by afeld** [comment]
Done.
