### ISSUE TITLE
hire through 18F Engineer pool

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1348]
**Do not put applicant names or other sensitive details in this issue.** Some of the links won't be accessible for the same reason.

[**Notes**](https://docs.google.com/document/d/1wCyPAjdozMw8ZRDcDlYpP2gzwlLuzoE2T-Ptf4DFUrk/edit)

## Background Information

I was [informed](https://gsa-tts.slack.com/archives/C020S0MB343/p1620773943011200) that the Tech Portfolio has the option of hiring through the [18F Consulting Engineer](https://join.tts.gsa.gov/join/consulting-software-engineer/) candidate pool.

## Implementation Steps
- [x] Review resume passed along
- [x] [Provide interview topics](https://gsa-tts.slack.com/archives/C020S0MB343/p1621889475001800?thread_ts=1620773943.011200&cid=C020S0MB343)
- [x] Create interview questions
- [x] Schedule interview

## Acceptance Criteria

- [x] Decision sent to Hiring team

**Comment by afeld** [comment]
Hiring team has next steps.
