### ISSUE TITLE
prep for onboarding of Coding it Forward Fellows - due 6/4

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1349]
## Background Information

While https://github.com/18F/tts-tech-portfolio/issues/1265 is about prepping for the Tech Portfolio's Fellow, this issue is about prepping for the cohort.

## Implementation Steps
- [x] Provide updated list of reading for the self-directed "class"
- [x] Expand tech-related [slides](https://docs.google.com/presentation/d/17SOkmQGyTEdHB0wHET5NnPcRe-5Wu_jj3NtstN_XRU0/edit#slide=id.g73bc30e74b_0_1037)
- [x] Notify @AnnabelLombard 

## Acceptance Criteria

- [x] We are presenting/directing new hires to all the relevant technology-related reading they need

**Comment by afeld** [comment]
Expanded the slides, and [provided an updated lists of readings for new hires](https://gsa-tts.slack.com/archives/C02E3TK0U/p1623081484001200).
