### ISSUE TITLE
re-settle on ATO checklist - due 6/18

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1359]
## Background Information

We previously had an ATO checklist for custom software as [a GitHub issue template](https://github.com/18F/tts-tech-portfolio/blob/master/.github/ISSUE_TEMPLATE/ato.md), which worked fairly well. We then experimented with Smartsheet, but backtracked with https://github.com/18F/tts-tech-portfolio/issues/1268. @rpalmer-gsa was also working on building something out in Trello. Now we're in a limbo where [a team asks what checklist to use and we don't have a good answer for them](https://gsa-tts.slack.com/archives/C039MHHF8/p1622582955012200).

A user story may help here:

- As someone involved in an ATO for custom software, I want to understand what steps are required to get to authorization and the status of each.

I _do not_ care about format/tool: GitHub issues, Trello cards, spreadsheets, whatever.

https://github.com/18F/tts-tech-portfolio/issues/1246 is related, in that it will use the status of the checklist to determine scheduling of the assessment.

## Implementation Steps

- [x] Work with Security to update
- [x] Announce in #infrastructure
- [x] Email system teams

## Acceptance Criteria

Minimum requirements:

- [x] A list of steps for a custom system to get through authorization, with links to find more information
- [x] Clear identification of who is responsible for each step
- [x] Consensus between Security and the Tech Portfolio on the canonical list

Nice-to-haves:

- [x] The list of steps being "live", in that everyone involved (notably System Owner, Tech Portfolio, ISSO, ISSM) is able to see up-to-date status of what steps are completed/outstanding
- [ ] An overview, being able to see status of systems relative to one another

**Comment by afeld** [comment]
Also, we don't need a perfect/forever solution: If we go back to the GitHub issue template for now and figure something else out later, that's totally fine. Setting an arbitrary deadline to force us to make a decision.

**Comment by afeld** [comment]
Decision with @rpalmer-gsa: Going to go back to the GitHub issue template, at least for now. Also clarified that up top that this is scoped to custom software.

**Comment by rpalmer-gsa** [comment]
General outline of deliverables for Internally developed systems systems seeking GSA ATO. Note, this list is subject to change and will require guidance and coordination with the assigned ISSO and ISSM. 

- [Program Team; Complete SSP Draft - Sections 1-12]
- [Program Team; Complete SSP Draft - Section 13]
- [Program Team; Complete PTA/PIA]
- [Program Team; Complete FIPS-199]
- [Program Team; Complete Digital Identity Acceptance]
- [Program Team; Complete ISA documentation if required]
- [Program Team; Complete BIA]
- [Program Team; Complete Continunity of Operations Plan]
- [Program Team; Complete Configuration Management Plan]
- [Program Team; Complete Incident Response Plan]
- [Program Team; Complete Rules of Behavior for system]
- [Program Team; Fully instantiate environment for assessment (Essentially means that your SaaS, IaaS, PaaS is configured for GSA usage)]
- [ISSO/SecOps; Complete OS/DB Scanning]
- [ISSO/SecOps; Complete Web Scanning for GSA implementation site (Netsparker scan from SecOps)]
- [Program Team; Remediate High and Critical Findings from Netsparker or WebApp scan]
- [ISSO/SecOps; Rescan to ensure remediation]
- [ISSO; Submit sections 1-12 of SSP for Architecture Review]
- [Program Team; Remediate any Architecture Review questions]
- [Program Team; Submit section 13 to ISSO for review and acceptance]
- [Program Team; Remediate any control comments from ISSO]
- [ISSO; ISSO submits section 13 to ISSM for acceptance and movement forward for assessment if no issues remain]

**Comment by afeld** [comment]
Done! Enjoyed working together on this, @rpalmer-gsa!
