### ISSUE TITLE
vote on FAS IT budget - due 6/18

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1370]
[**Budget breakdown**](https://docs.google.com/spreadsheets/d/1sspz-_SAoHJUnBY0P6B7CcSkMvNUglRgISuDHEtVYZg/edit#gid=90345426)

## Background Information

> We are asking that FSGC voting members review FAS IT's responses, engage in Q&A in this document, and vote either Yes or No to the proposed increase over the baseline for each line item by COB June 18th. Your vote (use these columns) and comments (use these columns) will be shared with the Commissioner for his consideration in setting a direction.

## Implementation Steps

- [x] Read [the explanation for the increase in cloud costs](https://docs.google.com/document/d/1J_7RYHVnS9TXBvY4vG_ieSBjEnVQZR93la9smGMdVPw/edit)
- [x] [Provide questions](https://docs.google.com/spreadsheets/d/1hpKrTLEpqKHc1bIdrxreTFt9nJSR_xgycIa2HhyrP0A/edit#gid=369173306)
- [x] Provide line item comments
- [x] Vote

## Acceptance Criteria

- [x] Provided objections to specific budget lines
- [x] Provided general feedback in Q&A doc

**Comment by afeld** [comment]
Complete.
