### ISSUE TITLE
Google Group for communication to TTS system teams

### ISSUE THREAD

**Issue by rpalmer-gsa** [18F/tts-tech-portfolio#1378]
## Background information
As security/privacy policies and procedures are updated there is a need to communicate them to key TTS system staff. Identify or create an email group that can be used to communicate these changes in addition to existing Slack communication.

See email columns in [TTS systems inventory](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=1235102795).

## Implementation Steps

- [x] Identify if already existing group can be utilized
- [x] Identify key communication expectations
- [x] Create group
- [x] Identify and add Key staff to Group
- [x] Identify responsibility for Group updates
- [x] Narrow to FISMA systems
- [x] Split out issue about getting every system to create a Google Group
- [x] Document how we communicate to system teams

## Acceptance criteria

- [x] We have documented how to reach all system teams at once

**Comment by afeld** [comment]
Creating a Google Group isn't hard, but we _could_ just copy and paste the email addresses from the inventory every time. A bit more tedious, but means one less place to maintain the list. Anyone have strong feelings either way?

**Comment by rpalmer-gsa** [comment]
Are the existing groups up to date? Perhaps just a @everyone or something in slack would serve a similar function?

**Comment by afeld** [comment]
> Are the existing groups up to date?

As far as we know, the emails in [the inventory](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=1235102795) are accurate and membership in those groups are maintained. There are existing email groups for:

- All TTS staff
- Solutions feds
- Solutions contractors
- TTS Supervisors
- GSA Content (website) Managers
- TTS Digital Council

which can also be used, depending on how broad we want a particular announcement to go.

> Perhaps just a @everyone or something in slack would serve a similar function? I should say @channel or whatever it is in slack. I think you get an email notification that way?

For things people _must_ read, we tend to use Slack+email.

https://handbook.tts.gsa.gov/outreach/#how-to-make-tts-wide-announcements

---

My gut is telling me, that in order to get a message to system teams:

- Post in #infrastructure
- Copy-and-paste the emails from the inventory

We can document the above as our standard practice and close this issue. Any objections?

**Comment by JJediny** [comment]
Created https://groups.google.com/a/gsa.gov/g/tts-systems/members so far

**Comment by afeld** [comment]
- [ ] Add the ISSOs
- [ ] Link from documentation

**Comment by rpalmer-gsa** [comment]
Added ISSOs currently supporting TTS systems.

**Comment by rpalmer-gsa** [comment]
Document method to maintain contact list (Archer).

Contact those teams to identify distribution list.

**Comment by afeld** [comment]
- [ ] Add the Tech Portfolio as Owners
