### ISSUE TITLE
develop roadmap for infrastructure Initiative

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1379]
## Background Information

We've talked about doing this before, but never really followed through. The best example we have is the first half of the [Software Concierge](https://docs.google.com/document/d/1DBCuxMFE5anShLIRxUD1qE7eDffKsrNEtAscjCF978s/edit#) doc. Things to build from:

- [Label](https://github.com/18F/tts-tech-portfolio/labels?q=infrastructure) description
- [Tech Portfolio Mission/Vision](https://handbook.tts.gsa.gov/tech-portfolio/)
- [Priorities](https://docs.google.com/document/d/1uQKGqwVIAwO-cefh1gxvxyrXbHxEt3WYWGtpWkEoeA8/edit#heading=h.fm9wid53w6j4) for @adborden's detail
- [Business Plan Goals](https://docs.google.com/document/d/1D8NjruISqW6A9rXu6EBN28JWyHyjHjGM/edit#heading=h.1t3h5sf)
- [Infrastructure needs](https://github.com/18F/aws-admin/blob/main/docs/tts-infrastructure-needs.md)

This has potential to snowball, so make sure to timebox to a matter of days.

## Implementation Steps

- [x] link to the roadmap in the [i:infrastructure issue](https://github.com/18F/tts-tech-portfolio/issues/635)
- [x] include a high-level description of the initiative and current goals in the [i:infrastructure issue](https://github.com/18F/tts-tech-portfolio/issues/635)

## Acceptance Criteria

Documentation that defines:

- [x] Goals for the Initiative for next X months
   - [x] Each priority references one or more systems' needs
- [x] Scope of this work
- [x] Relationship between Tech Portfolio and system owners

User story:

- [x] As someone who interacts with TTS infrastructure, I have a good sense of the Tech Portfolio's related priorities.

**Comment by afeld** [comment]
Open question: Is there a way to work backwards from the security controls that we want to fulfill?

**Comment by JJediny** [comment]
>Rather than try to solve in the abstract, we will address as part of 18F/newrelic-terraform#16 / #151 / 18F/tts-tech-portfolio#443.

I think we could better do this as suggested ^. I've created a [CRM crosswalk](https://docs.google.com/spreadsheets/d/1L2v1ZMlSscDgDMlDu1xvuH48HRDxnxHU3heFxtFq8RI/edit#gid=910638200) for all 3 CSPs we have access to (AWS/Azure/GCP) and Cloud.gov. If we were to go through each row and write up a `planned implementation` for the common controls.

**Comment by adborden** [comment]
I'm working from this [existing Roadmap doc](https://docs.google.com/document/d/1bGqZNiKdHexRvGK9KZh9uzQGUUOKI4LnKy45R0adt3Y/edit) which is linked from the [i:infrastructure issue](https://github.com/18F/tts-tech-portfolio/issues/635).

**Comment by adborden** [comment]
The ["Draft" section is ready for a review](https://docs.google.com/document/d/1bGqZNiKdHexRvGK9KZh9uzQGUUOKI4LnKy45R0adt3Y/edit#heading=h.5wb44tpqg6n3). It's at the point were we have a structure, have a problem statement defined and have incorporated the existing Infrastructure goals and work into the Roadmap.

**Comment by JJediny** [comment]
[Barriers to implementing were documented here](https://docs.google.com/document/d/1gUXV2sNjEW2073PVV-VMVsWOCBBX2PBUkQWPtSIN7lc/edit)

**Comment by adborden** [comment]
Dropping this here as some notes...

> Notes and ideas that might be missing, but we’d like to capture:
Encouraging developing shared services or solutions with the brokerpak model, e.g. terraform in a prescriptive structure. Also provides interoperability for inter-governmental platforms. Namely k8s, rancher, openshift.
>
> Should we be focusing on cloud.gov or limiting our options/offerings? Cater to cloud.gov customers first, but the AWS/other-cloud work supplements that. Baseline for all accounts and move more applications over to cloud.gov and figure out what supplementation needs are required.
>
> Login.gov needs GitLab (moderate software factory) now. Using this concrete problem to drive prioritization of our roadmap.
>
> Tie roadmap items to outcomes.

**Comment by adborden** [comment]
We will continue to monitor the Roadmap for any feedback and open new issues. We can call this done.
