### ISSUE TITLE
hand off login.gov credentials

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#138]
See the five login.gov accounts in the [account list](https://docs.google.com/spreadsheets/d/1DedSCiU9AsCAAVvAFZT0_Ii7AFIKlI-JNifzlpHNbDg/edit#gid=0).

- [x] Hand off each account
- [x] Change root passwords
- [x] Remove from KeePass
- [x] Update account list (above)
- [x] Mark the old account mailing lists deprecated
- [x] @afeld Delete OTP codes
- [x] @JJediny Delete OTP codes

Working with @brodygov.

**Comment by afeld** [comment]
Done!
