### ISSUE TITLE
decommission CloudCheckr

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1383]
## Background Information

We used to get CloudCheckr through our previous AWS reseller, and it seems like the account was never disabled. It's not FedRAMP authorized, so should no longer be used.

## Implementation Steps

- [x] Determine whose instance of CloudCheckr is still accessible - SaaS version at https://app.cloudcheckr.com/
- [x] Remove users
- [x] Remove IAM credentials
- [ ] Get account deleted
- [ ] Confirm with reseller that provided it (JHC) that there's nothing else to be done

## Acceptance Criteria

- [x] TTS users can no longer access CloudCheckr account

**Comment by ccostino** [comment]
Noting here that cloud.gov's instance is still accessible.

**Comment by afeld** [comment]
Calling this "done enough."
