### ISSUE TITLE
Review Mural usage

### ISSUE THREAD

**Issue by adborden** [18F/tts-tech-portfolio#1385]
## Background Information

Currently at 262 licenses, we are over allocated (230 licenses), some are inactive, and reactivations are being requested by both GSA and non-GSA fed employees. Need a better process to better manage numbers.

https://gsa-tts.slack.com/archives/C02E3QJGN/p1585673981027100?thread_ts=1585662935.023400&cid=C02E3QJGN

From Tech Portfolio lunch discussion.

## Implementation Steps

- [ ] Confirm available license count and how it's counted.
- [ ] Make it clear what is the difference between guest and member functionality. Clarify whether agency partners can be members. (And what should the policy be for who can be a member).

## Acceptance Criteria

- [ ] We are under our license count in terms of number of users
- [ ] Documentation for [how to manage Mural](https://github.com/18F/tts-tech-portfolio/blob/master/how_we_work/ops_rotation.md#play-mural-software-request) is updated

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio-private/issues/1008.
