### ISSUE TITLE
write updates for June 2021 TTS newsletter - due 6/23

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1389]
[**Working doc**](https://docs.google.com/document/d/1H7-1iYQaCYOqrozOchK5vdfp142dvCfr-GQ3p4J-0i4/edit#heading=h.mdujyb1mkxat)

## Background Information

Monthly ask for any updates the team might have to include in the newsletter.

## Implementation Steps

- [x] @adborden includes writeup about #1077
- [x] Before you ship guide has been merged into the TTS Handbook https://github.com/18F/handbook/pull/2542
- [x] Notify @AndreaSigz they are ready

## Acceptance Criteria

- [x] Updates ready

**Comment by afeld** [comment]
Sent to the team and @AndreaSigz for feedback. Will address comments as they come in.
