### ISSUE TITLE
migrate Mural management to GSA IT

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1393]
## Background Information

Split out from https://github.com/18F/tts-tech-portfolio/issues/788.

The email I sent to GSA IT:

> TTS regularly gets requests from other teams in GSA wanting to use [Mural](https://www.mural.co/). (I bet it's been at least ten teams in the past year.) Unfortunately, we have no headroom on the TTS contract, so can't offer it to them, even if we wanted to.
>
> With the agency likely staying more distributed than it's ever been, a virtual whiteboarding tool like Mural is extremely useful. (It doesn't *need* to be Mural specifically --- there are [alternatives](https://zapier.com/blog/best-online-whiteboard/).) Mural does have its LISaaS authorization, and is actively working on FedRAMP with our Security team.
>
> All of this to say: **We would like an enterprise offering of a virtual collaborative whiteboard tool.** We would like to hand off as much of the administration, contracting, and compliance pieces as we can, and are happy to pay for our share of it.

## Implementation Steps

- [x] Kickoff email
- [ ] Next steps received from GSA IT
- [ ] Pricing/reimbursement model known

## Acceptance Criteria

- [ ] TTS is using an enterprise-offered virtual whiteboarding tool

**Comment by afeld** [comment]
This issue is large and is largely out of our control; we'll try and split up when we have a clearer idea of next steps.

**Comment by afeld** [comment]
Response from IDT (email thread `virtual whiteboarding for GSA`) is that they aren't ready to take this (or any SaaS management) on, though they are working towards it. This won't be actionable for a while (until they tell us), so closing.
