### ISSUE TITLE
ARP proposal around Delivery Enablement

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1394]
[**Proposal**](https://docs.google.com/document/d/1VcAR3zNfwSn_MrUD7P7AS97SvLFNIc5KJMN_fm-wqQ0/edit)

## Background Information

- [Submission form](https://docs.google.com/forms/d/10lA7b_nplrNAbHtzFlCumF-3l7XM7QiTJmb1tlxQz84/viewform)
- [Background info](https://docs.google.com/presentation/d/1AzqOuXZdeLODBq5t_9bcPqJkVH5CpflyB359Bi1EgMs/edit#slide=id.p)
- [Questions doc](https://docs.google.com/document/d/1Xd8CPCc8J2UhSxVhdN7VT9YvjU-qc_mmjxj1rwTKgaQ/edit)
- [Solutions ARP proposal tracker](https://docs.google.com/spreadsheets/d/1q-FWDcyr1BwyfSZ22rbWZLNkWIxva9ydM8M93G41j4Q/edit#gid=0)

There's no hard deadline — submissions will be considered on a rolling basis — but presumably sooner is better than later. Ideas docs to pull from:

- [Solutions](https://docs.google.com/document/d/1B5Bdxt27ZKCI3Pl6xoLALh9yLI77zvIGN2Dz39X8UuQ/edit#)
- [Security & compliance](https://docs.google.com/document/d/1eEWwcWzvd_ua8KfL34Mc30M4iqvNniqAqJXiLWEKwuY/edit#heading=h.r15y1rbdzvy4)

## Implementation Steps

- [x] Confirm if leadership would like [the team budget proposal](https://docs.google.com/presentation/d/1TcccMb1DgGUk3eGkfdN2lSlmELZrkEGiQhJkSlAz80Y/edit#slide=id.p) submitted through the ARP form (as a whole or in chunks)
- [x] See if we can get access to the queue
- [x] Decide which ideas from docs above we want to turn into full proposals
- [x] Add to [Solutions proposal tracker](https://docs.google.com/spreadsheets/d/1q-FWDcyr1BwyfSZ22rbWZLNkWIxva9ydM8M93G41j4Q/edit#gid=0)
- [x] Tech Portfolio consensus on budget
- [x] Incorporate into [future state proposal](https://docs.google.com/presentation/d/1TcccMb1DgGUk3eGkfdN2lSlmELZrkEGiQhJkSlAz80Y/edit)
- [x] Set up time with Ashley M and Karen T
- [x] Sent to Solutions leads
   - [x] [Survey](https://docs.google.com/forms/d/e/1FAIpQLSe_n4OkJHPy2DeoC9tSHb78rRW0IFvuSncFdPc870iyvcI5Ug/viewform)
- [x] Incorporate survey results
- [x] Formally submit

## Acceptance Criteria

- [x] Tech Portfolio ARP ideas submitted for consideration

**Comment by JJediny** [comment]
Working Draft - https://docs.google.com/document/d/1VcAR3zNfwSn_MrUD7P7AS97SvLFNIc5KJMN_fm-wqQ0/edit

**Comment by afeld** [comment]
[Feedback from Ashley M](https://docs.google.com/document/d/15hYi_2WM4io9Q0U_u4j9yPa1V4xy-4pGUe638fcb2Wo/edit#heading=h.hznnkcgt7tm)

**Comment by afeld** [comment]
@JJediny Nice work on the proposal! Left some comments inline, focusing on intent rather than getting hung up on things like grammar.

- Is your thinking that we will need embedding long-term, or is that just to kick things off?
- Are those embedded contractors part of Delivery Enablement, Shared Product, both, or neither? Want to make sure the ARP and [Future State](https://docs.google.com/presentation/d/1TcccMb1DgGUk3eGkfdN2lSlmELZrkEGiQhJkSlAz80Y/edit#slide=id.gdea61129fe_0_124) proposals match.
- Is it possible to describe the potential/likely solutions (Common Controls, Service Brokers, Heimdall) without tying this proposal to specific ones?
   - For example, we want to offer self-service technology solutions for teams to leverage, but those might not always use a service broker interface.

**Comment by afeld** [comment]
Narrowed the scope in the title, in case we end up doing separate/subsequent ones.

**Comment by JJediny** [comment]
Proposal submitted!
