### ISSUE TITLE
propose changes to Slack - due 6/24

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1395]
[**Working doc**](https://docs.google.com/document/d/1dtRcFze6YBdGEpymhgDETCLayb7rtuxEpPDT_Up6Wsk/edit)

## Background Information

GSA IT prefers that we batch our requests for changes to the Slack configuration, to make them easier to run by all the relevant stakeholders. This is the latest batch.

## Implementation Steps

- [x] Draft proposal
- [x] Run by CTO team
- [x] Run by IDT team
- [ ] ~~Set meeting with Security~~

## Acceptance Criteria

- [x] Changes implemented, or decided that we won't

**Comment by afeld** [comment]
[Proposal](https://docs.google.com/document/d/1dtRcFze6YBdGEpymhgDETCLayb7rtuxEpPDT_Up6Wsk/edit#) sent. Waiting for feedback, then most likely a meeting or two.

**Comment by afeld** [comment]
After getting the go-ahead from Security, the Slack admins have:

- Turned off the message copying restriction on mobile
- Allowed any Member to share channels across GSA Workspaces
- Enabled the built-in pronoun field

Included info about all these in the TTS newsletter (https://github.com/18F/tts-tech-portfolio/issues/1389).
