### ISSUE TITLE
decide what to do with ION Channel

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1396]
## Implementation Steps

- [x] Review data in `Fwd: Per-Project Report/Outbrief` email
- [x] Write up proposal
- [x] Send to system teams

## Acceptance Criteria

- [x] Consensus within TTS on next steps with contract

**Comment by afeld** [comment]
Emailed:

> the TTS Technology Portfolio will not be pursuing a follow-on procurement around vulnerability management or Software Bills of Materials at this time.
