### ISSUE TITLE
software micropurchase reviews

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1397]
## Background Information

We need to start reviewing micropurchase requests for software as part of OpsRotation.

## Implementation Steps

- [ ] Document our involvement ([manually go into the sheet and move the drop down to supervisor approval](https://gsa-tts.slack.com/archives/G017C3R27MM/p1624375882001800?thread_ts=1624375693.001000&cid=G017C3R27MM))
   - Fine to link elsewhere, if it exists already
- [ ] Update [checklist](https://github.com/18F/tts-tech-portfolio/blob/master/.github/ISSUE_TEMPLATE/ops.md#readme)
- [ ] Catch up on outstanding requests

## Acceptance Criteria

- [ ] Tech Portfolio is caught up on reviews
- [ ] We have clear documentation of how to handle going forward

**Comment by afeld** [comment]
Complete.
