### ISSUE TITLE
DevSecOps talk approval - due 7/11

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1400]
## Background Information

Was invited to speak at [a virtual DevSecOps event through Public Sector Network](https://publicsectornetwork.co/event/virtual-event-devsecops-usa/). [Approval instructions.](https://handbook.tts.gsa.gov/conferences-events-training/#getting-approval-for-a-conference-event-or-training)

- [Salesforce tracker](https://gsa.lightning.force.com/lightning/r/Attendee__c/a1Ut000000635lYEAQ/view) (`events-21-0455`)

## Implementation Steps

- [x] Send [rider](https://afeld.me/rider/)
- [x] Ask the organizers to mark me as "pending approval"
- [x] Provide bio and headshot
- [x] [Write up talking points](https://docs.google.com/document/d/1L21mnAegYaxI_d2U62eMoV1SoEVyFjQ0Fw0txgpBRrE/edit#)
- [x] Submit approval form
- [x] Supervisor approval
- [x] OSC approval?
- [x] Organizers notified of approval

## Acceptance Criteria

- [x] Approved to speak

**Comment by JJediny** [comment]
Reference deck in case its useful https://docs.google.com/presentation/d/1t9LEuKN8ighJoo81Nzho2fWL2o4xiVjDtsRYdRexZaY/edit?usp=sharing

**Comment by afeld** [comment]
Approved!
