### ISSUE TITLE
prepare DevSecOps talk - due 7/11

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1404]
## Background Information

cc https://github.com/18F/tts-tech-portfolio/issues/1400

## Implementation Steps

- [x] Fill out [Presenter Requirements](https://psnevents.eventsair.com/2021-us-community-innovation-and-ict/presenter-requirements-form/Site/Register)
- [x] Slides created as Powerpoint
- [x] Presentation recorded as MP4, 16:9 ratio, 1280x720 pixels

See `Speaker presentation requirements | DevSecOps` email for details.

## Acceptance Criteria

- [x] Presentation ready for the event

**Comment by afeld** [comment]
[Slides + recording](https://drive.google.com/file/d/1vJDyhPP4jXT5jOJj1Y7TITy6Y0dktt6y/view?usp=sharing) complete. Sent!
