### ISSUE TITLE
re-work the Software Concierge flow

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1422]
## Background Information

The [existing process](https://docs.google.com/document/d/1DBCuxMFE5anShLIRxUD1qE7eDffKsrNEtAscjCF978s/edit#heading=h.ksw1rom8yhi) leverages a form that is no longer monitored.

## Implementation Steps

- [ ] Have requester prepare responses to the [questions](https://docs.google.com/document/d/1DBCuxMFE5anShLIRxUD1qE7eDffKsrNEtAscjCF978s/edit#heading=h.mibezfdjpr7p) up front to save time
- [ ] Decide if we still need an intake form, or can use GitHub issues
- [ ] Update [Handbook page](https://handbook.tts.gsa.gov/software/#purchase-new-software)

## Acceptance Criteria

- [ ] Handbook reflects our current process for requesting new software
