### ISSUE TITLE
generate team metrics

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1428]
[**Metrics sheet**](https://docs.google.com/spreadsheets/d/1Ih6X7AajzflC_qzzbsSquQjiIcBb7-TT4k2CyH5YfMY/edit#gid=1254692763)

## Background Information

Came up with [Portfolio Goals and Metrics](https://docs.google.com/document/d/1D8NjruISqW6A9rXu6EBN28JWyHyjHjGM/edit#heading=h.1t3h5sf) as part of the Business Plan (https://github.com/18F/tts-tech-portfolio/issues/890) — this issue is about turning those metric ideas into numbers.

## Implementation Steps

- [x] Ask D2D about how to best go about this
- [ ] Narrow metrics down to those that are easily measurable

## Acceptance Criteria

- [ ] We have current values for all metrics
