### ISSUE TITLE
Security team proposal - due 7/14

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1438]
## Background Information

A few people gave feedback on the [Tech Portfolio future state proposal](https://docs.google.com/presentation/d/1TcccMb1DgGUk3eGkfdN2lSlmELZrkEGiQhJkSlAz80Y/edit#slide=id.p) that they thought it would be useful for TTS to have a centralized security team.

## Implementation Steps

- [x] Consult @rpalmer-gsa 
- [x] Consult Security & Compliance Guild
- [ ] ~~Fill out:~~
   - [ ] [Team description](https://docs.google.com/presentation/d/1TcccMb1DgGUk3eGkfdN2lSlmELZrkEGiQhJkSlAz80Y/edit#slide=id.gdea61129fe_0_124)
   - [ ] [Example responsibilities](https://docs.google.com/presentation/d/1TcccMb1DgGUk3eGkfdN2lSlmELZrkEGiQhJkSlAz80Y/edit#slide=id.ge3e65e007e_0_0)
   - [ ] [Roles](https://docs.google.com/spreadsheets/d/1Q8gxf0tb-uqZhejh1qxVWi35R_5u9EuBcSN6U7kJUjM/edit#gid=0)
- [x] Update [total budget number](https://docs.google.com/presentation/d/1TcccMb1DgGUk3eGkfdN2lSlmELZrkEGiQhJkSlAz80Y/edit#slide=id.gdea61129fe_0_204)
- [x] Notify Dave Z
- [x] Move comments from doc to Discussion
- [x] Add to [project board](https://github.com/18F/tts-rfc/projects/1) - https://github.com/18F/tts-rfc/pull/24
- [x] Incorporate feedback from open comments and [Security & Compliance Guild meeting notes](https://docs.google.com/document/d/1eEWwcWzvd_ua8KfL34Mc30M4iqvNniqAqJXiLWEKwuY/edit#heading=h.pgnxaksbeson)
- [ ] Send survey to gauge how far we are from consensus
- [x] Rewrite in RFC format
- [x] Review https://github.com/18F/tts-rfc/pull/17
- [ ] Set up time to share with Ashley M

## Acceptance Criteria

- [x] Proposal around security investment at TTS presented to TTS leadership

**Comment by afeld** [comment]
Told Dave Z I would get this to him mid-week.

**Comment by afeld** [comment]
[Request for Comment (RFC)](https://docs.google.com/document/d/1RedCM0NgQ3D5NmVZXqLZv5HTvNTb05SCqROkqJLd18s/edit#)

**Comment by afeld** [comment]
Nudged several times for review; closing as it's out of my hands now.
