### ISSUE TITLE
FY21 Q3 Impact Stories - due 7/23

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1440]
[**Success stories**](https://docs.google.com/document/d/1HmAtF3A4HUvn2HRV_nfgaXxlO8spqIJmkOP8nJoUqQs/edit#)

## Background Information

> Now is the time to take a few moments to reflect and write about something awesome that your team has achieved. Did you launch a new website? Have you helped a new partner? Did you come up with a new internal process? Let your story be known.
>
> 🔔  Use the impact story template, provided in the document, and link your stories in the [solutions FY21 impact stories document](https://docs.google.com/document/d/1z06HZvBD_UyTSFHFAftSzmR0LjqFCrZ5d0MoDZ4eUs0/edit#bookmark=id.c10p6vswipms) by July 23rd.

## Implementation Steps

- [x] First draft complete
- [x] Run by team

## Acceptance Criteria

- [x] Impact Stories provided

**Comment by afeld** [comment]
I ended up writing about [Better leveraging GSA IT](https://docs.google.com/document/d/1HmAtF3A4HUvn2HRV_nfgaXxlO8spqIJmkOP8nJoUqQs/edit#heading=h.54m4aepvf41j), since it highlights the positive collaboration with another part of the agency. @18F/tts-tech-portfolio Going to close the issue, but your feedback is more than welcome.
