### ISSUE TITLE
automatically add issues and pull requests to boards

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1441]
## Background Information

Right now, we manually add issues and pull requests from [our repositories](https://github.com/18F/tts-tech-portfolio/blob/main/how_we_work/github.md#readme) to the [project board](https://github.com/orgs/18F/projects/11?fullscreen=true) and [pull request board](https://github.com/orgs/18F/projects/19?fullscreen=true), respectively. This happens either when the issues are created, or manually after the fact. This should be automatable. GitHub Actions that may do the trick:

- https://github.com/marketplace/actions/add-new-issue-to-column
- https://github.com/marketplace/actions/github-project-automation
- https://github.com/marketplace/actions/add-to-project 

## Implementation Steps

- [ ] Remove manual steps from:
   - [ ] [OpsRotation checklist](https://github.com/18F/tts-tech-portfolio/blob/main/.github/ISSUE_TEMPLATE/ops.md#github)
   - [ ] [Workflow](https://github.com/18F/tts-tech-portfolio/blob/main/how_we_work/workflow.md#cards)

## Acceptance Criteria

- [x] Issues created in a Tech Portfolio repository are automatically added to the issue board
- [x] Pull requests created in a Tech Portfolio repository are automatically added to the pull request board

**Comment by adborden** [comment]
[Confirmed](https://github.com/18F/tts-tech-portfolio/runs/3323524493?check_suite_focus=true) that new issues added to this repo are automatically added to the board.

PRs are added to the PR board, but https://github.com/18F/tts-tech-portfolio/pull/1535 will fix Draft PRs which should go to the Draft/WIP column instead of the Review required column.

**Comment by adborden** [comment]
The AC have been met but the steps in the Ops Rotation workflow still apply since we haven't applied these GH Action workflows to all repos. I made sure to cover these workflow files in https://github.com/18F/tts-tech-portfolio/issues/1513
