### ISSUE TITLE
architecture reviews?

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#145]
Does the Tech Portfolio want to explicitly offer architecture reviews to TTS teams? If so, how structured do we want them to be? Need to balance "this would be nice to have" with how much bandwidth we actually have available. [GSA Security also has a process](https://docs.google.com/presentation/d/1BIpHMx9hJEICMgoD9KLLgmNpaom1DWBRGNN6YLym1Vw/edit#slide=id.g5bb486ed51_0_116) that can be leveraged.

- [ ] Create a proposal for what this should look like
- [ ] Set expectations in terms of how much time the Tech Portfolio can devote to these
- [ ] Set some entrance criteria
- [ ] Present this proposal to the team

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
