### ISSUE TITLE
approval of SingularKey

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1452]
## Background Information

Identity PMO requires assistance to get approval to use SingularKey in support of the GIVE initiative.

## Implementation Steps

- [x] Submit IT Standards Ticket
- [x] Follow up as necessary
- [x] Determine next steps based on IT Standards determination 
 
## Acceptance Criteria

- [x] IT Standards approval or denial of SingularKey

**Comment by josephderosales** [comment]
Dear Requester:

The request to add Singular Key to the GSA IT Standards Profile has been denied.

Security Comments: Request for artifacts sent to POC.  6/9
2nd Request for artifacts sent to POC.  6/22
Recommend closure due to lack of response to artifact requests. 7/13/21
3rd Request for artifacts sent to POC. 7/14
Request forwarded to ISE for review.  7/14
Per the Requestor, this is an appliance and therefore outside the scope of ISE review..  7/21

No further action is required.

For reference, the internal Salesforce Request Number is 2021-94980.

This product was requested by:
John Yuda

**Comment by josephderosales** [comment]
Need to follow up w. Phil Lam:

Joseph and Ryan,

Is our assessment correct that since this does not fall under ISE review in IT Standards, that it would be covered in our GSA ATO process?

Just want to make sure we are all good here.

**Comment by josephderosales** [comment]
Did not fall within scope of IT Standards. Instead will be incorporated into the ATO as an "appliance".
