### ISSUE TITLE
get contract help around SaaS

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1456]
## Background Information

We have historically only used the `TTS SaaS` budget for licenses, but I don't think that _needs_ to be the case. We could potentially use it for things like:

- Handling OpsRotation
- Content design, especially around SaaS stuff
- Automating SaaS user management

## Implementation Steps

- [x] [Confirm the budget can be used for labor](https://gsa-tts.slack.com/archives/C03LNNVQ1/p1621951332004100)
- [ ] [Confirm budget remainder for FY21](https://gsa-tts.slack.com/archives/C03LNNVQ1/p1627339013000500)
- [x] Submit [OA intake form](https://docs.google.com/forms/d/e/1FAIpQLSdqd8GVxwJAGqwtEUJJ5rXtHZDMc9yLdGRUkp0tSkc4lwHhqw/viewform)

## Acceptance Criteria

- [ ] We get contract help through the `TTS SaaS` budget

**Comment by afeld** [comment]
Brittney from Acquisition asked that we hold off until the new fiscal year (October). Moving this to Backlog.
