### ISSUE TITLE
change Sketch email

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#146]
...from 18fsoftware to tts-software.

- [ ] [Update on the Sketch side](https://www.sketch.com/support/licensing-and-sales/change-email-address/)
- [ ] Update [documentation](https://handbook.18f.gov/sketch/#for-admins)

**Comment by its-a-lisa** [comment]
Created pull request to update it in handbook https://github.com/18F/handbook/pull/1651 since @JJediny updated it in Sketch last night

**Comment by its-a-lisa** [comment]
Tried to follow the procedures to get the sketch license using what we updated in the documentation and the `tts-software` account isn't registered in the sketch system and it is still the `18fsoftware `account

**Comment by JJediny** [comment]
There is no real need to fix this as we still have access to 18f software inbox and cannot update the email directly in sketch license manager. This hasn't been a priority.

- [ ] Need to email sketch to see if they can make the update.

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
