### ISSUE TITLE
get existing contractors on GSA-issued machines

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1466]
## Background Information

…where they need them, per the [recently-clarified guidance](https://handbook.tts.gsa.gov/contractors/#equipment). Could be a Windows or Mac machine, as appropriate.

## Implementation Steps

- [ ] Conduct audit of who would need them
- [ ] Ensure inventory - https://github.com/18F/tts-tech-portfolio/issues/1460
- [ ] Figure how to handle going forward

## Acceptance Criteria

- [ ] All existing contractors have gotten GSA-issued machines, or deemed to not need one

**Comment by afeld** [comment]
[Survey](https://docs.google.com/forms/d/1x-xEtCUF-ZfNRZVUhl_AiLEH3PSh3J1rI1ymMWQbxLY/edit)
