### ISSUE TITLE
OpsGenie ATO renewal

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1467]
## Background Information

> [Security] has agreed to allow 6 more months to get off of the solution, but will need a new LI-SaaS package to do that.  That means I need a new checklist completed along with web app and OS scans.

## Implementation Steps

- [x] Find OpsGenie contact
- [ ] Get operating system (OS) scans
- [ ] Get web application scans

## Acceptance Criteria

- [ ] ATO renewed/extended with enough time to cover https://github.com/18F/tts-tech-portfolio/issues/876

**Comment by afeld** [comment]
Kicked off email to them: `OpsGenie authorization renewal for GSA`.

**Comment by josephderosales** [comment]
@rpalmer-gsa TTS is actively building ServiceNow to replace OpsGenie. Does this require an ATO extension?

**Comment by afeld** [comment]
Yes; discussing in email how to proceed given https://github.com/18F/tts-tech-portfolio/issues/1300#issuecomment-870964937. (In other words: is it worth the trouble?)

**Comment by rpalmer-gsa** [comment]
Nate issued new ATO. Dave Shive is the AO not Aidan hence the confusion.

**Comment by rpalmer-gsa** [comment]
closing
