### ISSUE TITLE
establish Performance Plan for Rochelle

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1479]
## Background Information

As a new hire, @rocheller123 needs a Performance Plan established.

## Implementation Steps

@rocheller123:

- [x] [Read about Performance Management](https://insite.gsa.gov/employee-resources/hr-eeo-pay-and-leave/employee-performance-management)
- [x] Read [Performance Measures](https://docs.google.com/document/d/1KOUN5NArmq9tisgcGzTLDm1M47BQwkd3HiCWoYah8SQ/edit#)
- [x] Acknowledge in HRLinks

@afeld:

- [x] Confirm which [Duty Specific](https://docs.google.com/document/d/1KOUN5NArmq9tisgcGzTLDm1M47BQwkd3HiCWoYah8SQ/edit#heading=h.x18gzh86w5t1) Measures to use
- [ ] ~~Fix the software authorizations measure - https://github.com/18F/tts-tech-portfolio/issues/1143~~
- [x] Enter in HRLinks
- [x] Make [a copy of the doc for Rochelle](https://docs.google.com/document/d/13dOXb-X0QZC0k0O25bHuYsLqUmSHvTpkldvYO2TOCyI/edit#)

## Acceptance Criteria

- [x] Performance Plan established

**Comment by afeld** [comment]
@rocheller123 After looking through the Measures again, it seems like [Improves the security of TTS](https://docs.google.com/document/d/1KOUN5NArmq9tisgcGzTLDm1M47BQwkd3HiCWoYah8SQ/edit#heading=h.3zyepefkwvip) is most applicable to the things you have assigned to you on the board. (People on the team have different numbers of Individual performance measures, so fine that you just have the one.) Took a pass at the [weighting percentages for each](https://docs.google.com/spreadsheets/d/1Oki0CZ99qFG74lTUyZ6UJeQ9yXj8WlheanDxpY0CJCA/edit#gid=514278152&range=F:F); happy to tweak them if you'd like.

Sent you the official Performance Plan through HRLinks, which is just a copy-paste of that Measures doc and weighting spreadsheet. **If all sounds good to you, go ahead and Acknowledge in HRLinks.**

Reminder that this Plan is just for the end of FY21; we'll have new ones in FY22. Have a meeting about that Wednesday, so more details to come.

Thanks!

**Comment by rocheller123** [comment]
@afeld Acknowledged.

**Comment by afeld** [comment]
Awesome, thanks!

**Comment by afeld** [comment]
- [ ] Confirm what start and end dates should be.
