### ISSUE TITLE
confirm SA-2(c) issue for systems

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1481]
## Background Information

Cloud.gov has a POA&M item for [SA-2(c)](https://csrc.nist.gov/Projects/risk-management/sp800-53-controls/release-search#!/control?version=5.1&number=SA-2):

> Establish a discrete line item for information security and privacy in organizational programming and budgeting documentation.

Per the [GSA Control Tailoring Workbook](https://insite.gsa.gov/employee-resources/information-technology/security-and-privacy/it-security/it-security-forms-and-aids), SA-2 is `System-Specific`. I read this as GSA saying every FISMA system needs a security+privacy line item.

If true, this will take a lot of work to resolve; this issue is just about confirming the problem is there.

## Implementation Steps

- [ ] Confirm this is GSA Security's interpretation
- [ ] Confirm this is FedRAMP's interpretation
- [ ] Incorporate into https://github.com/18F/tts-tech-portfolio/issues/1438

## Acceptance Criteria

- [ ] We have confirmation that this control is not being fulfilled
