### ISSUE TITLE
Create a 'Decomissioning microsites' checklist

### ISSUE THREAD

**Issue by dylanirlbeck** [18F/tts-tech-portfolio#1501]
## Background Information

As part of the Digital Council's work on a Digital Strategy, decomissioning websites has come up at least a few times so far. It was asked that a checklist or recipe for decomissioning sites like before-you-ship (microsites, purely content, etc.) be created; this issue represents that work.

Note: there is an existing [decomissioning checklist](https://github.com/18F/tts-tech-portfolio/blob/main/.github/ISSUE_TEMPLATE/decommission.md#readme), but from my experience there were a lot of items that didn't apply or were confusing in context.

## Implementation Steps

- [ ] Create a "Decomissioning microsites" checklist
- [ ] Make this an issue template in the tech-portfolio repo
- [ ] Share with the Digital Council to ensure clarity

## Acceptance Criteria

- [ ] Clear guidance -- to technical and non-technical folks alike -- around decomissioning microsites is available and actionable.

**Comment by afeld** [comment]
Another option: clarify in the existing checklist which items apply to _all_ sites vs. only those with back ends, etc.

**Comment by dylanirlbeck** [comment]
Helpful resource for definitions (site vs microsite vs system): https://docs.google.com/document/d/1chNbOfxs2vLGSUuIPtWZregaUeT-ruLc8EufEzt9GZk/edit
