### ISSUE TITLE
[Due 08/13/21] Conduct NetlifyCMS usability testing

### ISSUE THREAD

**Issue by dylanirlbeck** [18F/tts-tech-portfolio#1507]
## Background Information

In order to gather more information on how the new NetlifyCMS process and its documentation is working for users, we should set up some light usability testing.

## Implementation Steps

- [x] Set up usability tests with Outreach team members.
- [x] Record information from each of those meetings.
- [x] Notes are synthesized and presented below

## Acceptance Criteria

- [x] Information on the documentation and overall Handbook contribution process is gathered.

**Comment by dylanirlbeck** [comment]
### Finding the help guide
* Most users had forgotten where the NetlifyCMS tutorial was located (it was in the CONTRIBUTING page). 
   * Action: Have `search.gov` re-index so that the result shows up in search; have better training during the Handbook 101 session; culturally standardize that the CONTRIBUTING page is where you need to go.


### Logging in to the CMS
* Nearly every user I spoke with got a "401 Unauthorized" error when navigating to `handbook.tts.gsa.gov/admin`. Once they went into their email and found and accepted the invite to join the `federalist-users` GitHub group, they could log in.
   * Action: Better error handling on Federalist; better instructions in the CONTRIBUTING doc for receiving and _accepting_ the invite.
* 

### Using the help guide

### Editor/Interface

### Verifying the changes went through

### Knowing that you're "done"

### Other

* Not
