### ISSUE TITLE
TTS programs not receiving bug bounty email notifications

### ISSUE THREAD

**Issue by adborden** [18F/tts-tech-portfolio#1508]
## Background Information

In order to take action on a bug bounty report, TTS programs in the bug bounty want to be notified when a report is assigned to their team (H1 group).

We've had several reports of folks not receiving notifications when they should've.
- https://gsa-tts.slack.com/archives/C0X2FMJ86/p1627579160006900

## Implementation Steps

- [x] Get advice from H1 folks about how notifications should be configured
- [x] Document the correct configuration in the Handbook
- [ ] Notify bug bounty members that they should check their notification settings
- [ ] Review permissions in H1 and ensure they're consistent with our documentation, specifically with respect to awarding bounties (unrelated to this user story, but related task)

## Acceptance Criteria

- [ ] GIVEN a valid bug bounty report has been triaged by H1 staff
  WHEN my team (group) is assigned in H1
  THEN I receive an email notification
- [ ] GIVEN a valid bug bounty report has been triaged by H1 staff
  WHEN some other team (group) is assigned in H1 which I am not a member
  THEN I do NOT receive an email notification

**Comment by adborden** [comment]
I'm collecting some examples and started some conversation in [#bug-bounty-partners](https://gsa-tts.slack.com/archives/C5JQCD9PH).

**Comment by afeld** [comment]
Not relevant, given https://github.com/18F/tts-tech-portfolio/issues/1224.
