### ISSUE TITLE
TTS'ers should have write access to Tech Portfolio docs

### ISSUE THREAD

**Issue by adborden** [18F/tts-tech-portfolio#1511]
## Background Information

In order to ensure that admin access to TTS infrastructure is managed with the principle of least privilege while providing TTS opportunities to collaborate, TTS programs want the Tech Portfolio to reduce access to how they manage GitHub admin permissions.

https://github.com/18F/tts-tech-portfolio is mutlipurpose. It serves as team documentation to Tech Portfolio and therefore we want everyone at TTS to contribute. It also includes [Terraform code](https://github.com/18F/tts-tech-portfolio/tree/main/terraform) to manage GitHub repos that Tech Portfolio maintains. Related, the Terraform is also used to manage admin access on TTS GitHub orgs, a power not to be taken lightly.

Following the principle openness and transparency, we want TTS'ers to contribute to our repos. But following the principle of least privilege, we want to keep tight control over things like IAM and admin access.

## Implementation Steps

- [ ] Split IAM to its own repository with tight control where TTS has read-only access
- [ ] (optional) Consider splitting the non-IAM terraform to its own repository
- [ ] Limit scope of the GitHub token used by 18F/tts-tech-portfolio CI, drop any admin:org functionality
- [ ] Enable "Restrict who can push to matching branches" branch protection on the `main` branch
- [ ] Give `gsa` Write permission to 18F/tts-tech-portfolio

## User stories

- [ ] WHEN I review [access permissions for 18F/tts-tech-portfolio](https://github.com/18F/tts-tech-portfolio/settings/access)
   THEN I see `gsa` team has Write access
- [ ] WHEN I review access permissions for IAM
  THEN I see `gsa` has Read access

## Acceptance Criteria

- [ ] Contributions from TTS staff (outside the Tech Portfolio) get the same feedback (via CI) as those from Tech Portfolio staff

**Comment by afeld** [comment]
We don't expect people outside the Tech Portfolio to contribute to this repository very often, so not going to worry about this.
