### ISSUE TITLE
Update emoji approval process instructions

### ISSUE THREAD

**Issue by mgwalker** [18F/tts-tech-portfolio#1522]
## Background Information

When emoji are created, it would be helpful to approvers if the Inclusion Bot could give the new emoji names a quick scan and indicate if there are any problems. See [Charlie#315](https://github.com/18F/charlie/issues/315) for more background.

## Implementation Steps

- [x] Add Charlie to the #admins-emoji channel. Inclusion Bot only checks messages of channels its in. It ***does*** check messages posted by workflows, so the emoji request message will be checked. It will add the `:inclusion-bot:` emoji reaction to any messages that include language that may be exclusionary.
- [x] Update the [Handbook page about emoji approval criteria](https://handbook.tts.gsa.gov/tools/slack/user-management/#approval-criteria) to remind approvers to look for the `:inclusion-bot:` emoji reaction, indicating that the Inclusion Bot has flagged the emoji name. Addressed in a [pending pull request](https://github.com/18F/handbook/pull/2782).

## Acceptance Criteria

- [x] Emoji approvers can quickly see if a new emoji name triggers the Inclusion Bot

**Comment by afeld** [comment]
Done, thanks @mgwalker!
