### ISSUE TITLE
Archer access for Tech Portfolio 

### ISSUE THREAD

**Issue by rocheller123** [18F/tts-tech-portfolio#1524]
## Implementation Steps

- [x] Get Archer access
- [x] Get SSP access
- [x] Get the above for the rest of the team
- [x] Document how to get added going forward
   - Add to onboarding?

## Acceptance Criteria

- [x] Tech Portfolio team member can access Archer.

**Comment by rocheller123** [comment]
Confirmed Tech Portfolio Team has Archer access.
