### ISSUE TITLE
Offboarding does not catch 18F project partners

### ISSUE THREAD

**Issue by adborden** [18F/tts-tech-portfolio#1529]
## Background Information

In order to prevent access from being abused when the access is no longer needed, TTS programs want the Tech Portfolio to trigger the offboarding process when 18F projects end and partners no longer need access.

Currently, TTS folks request access for partners in an ad-hoc fashion e.g. folks request access to Mural in #admins-mural. There is no similar ad-hoc offboarding and access gets left behind in most cases.

## Implementation Steps

- [ ] Create an issue template for offboarding a person from all Tech Portfolio services
- [ ] Reach out to 18F about if they have a project-ending checklist and add a task to open an offboarding issue in the Tech Portfolio backlog

## Acceptance Criteria

- [ ] GIVEN a person no longer needs access to Tech Portfolio services
  WHEN a triggering event occurs (project ends, contract ends, person leaves a project, etc) 
  THEN a checklist exists that will ensure the person is removed from Tech Portfolio services

**Comment by adborden** [comment]
This came up with @JJediny @rocheller123 's pairing on Ops Rotation about why there are so many users in Mural who should be cleaned up.

**Comment by afeld** [comment]
Duplicate of https://github.com/18F/handbook/issues/2019.

**Comment by adborden** [comment]
@afeld not sure what you want to do, I can update either issue so that the details are captured. Personally I think combining them is combining two separate aspects of a large problem and we would end up splitting the story anyway.
