### ISSUE TITLE
TTS Programs need to receive alerts and notifications related to their AWS accounts

### ISSUE THREAD

**Issue by adborden** [18F/tts-tech-portfolio#1530]
## Background Information

In order to take action on security notifications, like EOL database versions, TTS programs need to receive alerts from AWS that are currently going to devops@.

Related to https://github.com/18F/tts-tech-portfolio/issues/1130, but from the program side. Unlike https://github.com/18F/tts-tech-portfolio/issues/1130, the intention is not to reduce burden on the Tech Portfolio, but instead ensure TTS programs are receiving notifications.

This came up during @rocheller123 's OpsRotation and conversion about what to do with these AWS notifications.

## Implementation Steps

- [ ] Add a step to the [new AWS account template](https://github.com/18F/aws-admin/blob/main/.github/ISSUE_TEMPLATE/new_account.md) to include:
  - team contact email address required from program
  - new step in checklist to manually add additional contact email
- [ ] Determine if this can be automated in Terraform

## Acceptance Criteria

- [ ] GIVEN I've included my team's contact email in the new account request
  WHEN AWS sends an "Attention required on case" email notification
  THEN my team receives the notification in their inbox

**Comment by adborden** [comment]
Duplicate of https://github.com/18F/tts-tech-portfolio/issues/1142
