### ISSUE TITLE
Write up user stories for ARP Delivery Enablement proposal

### ISSUE THREAD

**Issue by adborden** [18F/tts-tech-portfolio#1533]
## Background Information

I wanted to get with @JJediny and write up some stories. Given the importance of [this proposal](https://docs.google.com/document/d/1VcAR3zNfwSn_MrUD7P7AS97SvLFNIc5KJMN_fm-wqQ0/edit), maybe it makes sense to start on some of those even before the proposal is approved or implemented. Some thoughts:
- Rename Initiatives based on the new teams e.g. Infrastructure -> Delivery Enablement
- Any foundational work for common controls that should be done before we throw a bunch of folks on it?
- Pilot embedding a team member on a program team
- Update roles.md to reference different teams, and who is "assigned" to each team (even if everyone is on all teams)

## Implementation Steps

- [ ] Rename Initiatives based on the new teams e.g. Infrastructure -> Delivery Enablement
- [ ] Update roles.md to reference different teams, and who is "assigned" to each team (even if everyone is on all teams)
- [ ] Define the teams that cover the Tech Portfolio's work in order to reduce cognitive load
- [ ] Review/revise the [Tech Portfolio mission, vision, and responsibilities](https://handbook.tts.gsa.gov/office-of-solutions/tech-portfolio/)

## Acceptance Criteria

- [ ] WHEN I review the backlog
  THEN I see prioritized, actionable GitHub issues that are aligned with the goals laid out in the proposal

**Comment by JJediny** [comment]
Handing over the ARP proposal to the #tts-future-platform team
