### ISSUE TITLE
finish handing off ATF eRegs

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#154]
ATF eRegs has been handed off to the agency (and is available at [regulations.atf.gov](https://regulations.atf.gov/)), but [atf-eregs.18f.gov](https://atf-eregs.18f.gov/) is still live, which makes it seem like it's still an 18F system. Unclear if it's the same deployment or not:

```
$ dig +short atf-eregs.18f.gov
d1a8iv0i0iazmn.cloudfront.net.
13.226.38.54
13.226.38.113
13.226.38.7
13.226.38.107
$ dig +short regulations.atf.gov
d2gjhji0hnkhl4.cloudfront.net.
13.226.38.44
13.226.38.9
13.226.38.125
13.226.38.103
```

[Conversation](https://gsa-tts.slack.com/archives/C40QTN4MR/p1568165945006600) about archiving [the repository](https://github.com/18F/atf-eregs).

## TODOs

- [ ] Determine the hosting situation for [atf-eregs.18f.gov](https://atf-eregs.18f.gov/) and [atf-eregs.app.cloud.gov](https://atf-eregs.app.cloud.gov/)
- [ ] Confirm with ATF that they are ok with the following plan
- [ ] Redirect to [regulations.atf.gov](https://regulations.atf.gov/)
- [ ] [Decommission](https://before-you-ship.18f.gov/infrastructure/decommissioning/)

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.

**Comment by afeld** [comment]
Replaced by https://github.com/18F/tts-tech-portfolio/issues/953.
