### ISSUE TITLE
Mural CPARS Assessment - due 9/15

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#1542]
Annual Contract Review for Mural

## Implementation Steps
- [x] Determine FedRAMP state as of end of Option 1, Feb 2020
- [x] Complete [the form](https://docs.google.com/document/d/1eIxg-4nn4ngtNnb2Tgrd_awx1UyECoMfj_IIJTMGhOk/edit?usp=sharing)
- [x] Send back

## Acceptance Criteria
- [x] uploaded in CPARS
