### ISSUE TITLE
Review M-21-31

### ISSUE THREAD

**Issue by rocheller123** [18F/tts-tech-portfolio#1552]
## Background Information

Review [M-21-31: Improving the Federal Government’s Investigative and Remediation Capabilities
Related to Cybersecurity Incidents](https://www.whitehouse.gov/wp-content/uploads/2021/08/M-21-31-Improving-the-Federal-Governments-Investigative-and-Remediation-Capabilities-Related-to-Cybersecurity-Incidents.pdf) to determine tasks that are relevant for TTS/Tech Portfolio to complete to meet the memo's requirements. 

## Implementation Steps

- [x] Review [M-21-31](https://www.whitehouse.gov/wp-content/uploads/2021/08/M-21-31-Improving-the-Federal-Governments-Investigative-and-Remediation-Capabilities-Related-to-Cybersecurity-Incidents.pdf).
- [x] Create required tasks from M-21-31 for TTS/Tech Portfolio to complete.

## Acceptance Criteria

- [x] Tasks have been defined to proceed with completing the requirements laid out in M-21-31.

**Comment by rocheller123** [comment]
Created new issues to address event logging tasks to be implemented from M-21-31: 
https://github.com/18F/tts-tech-portfolio/issues/1555
https://github.com/18F/tts-tech-portfolio/issues/1558
https://github.com/18F/tts-tech-portfolio/issues/1559
https://github.com/18F/tts-tech-portfolio/issues/1560
