### ISSUE TITLE
FY21 performance appraisals - due 10/1

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#1568]
## Implementation steps

- [x] Send notes for @adborden to @philipashlock 
- [ ] @afeld self-evaluation
- [ ] Send notes for @its-a-lisa-at-work to Karen T
- [ ] @JJediny 
   - [x] Provided
   - [x] Met
   - [ ] Acknowledged in HRLinks
- [x] @rocheller123 

## Acceptance Criteria
- [ ] FY21 performance appraisals completed in HR Links

**Comment by afeld** [comment]
All set.
