### ISSUE TITLE
revamp TTS onboarding materials

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1569]
## Background Information

As part of TTS onboarding, new hires are sent through the self-directed `Tech Portfolio` TTS Class. They are asked to go through the following:

1. [Infrastructure Best Practices](https://docs.google.com/document/d/1iQP1S_PbJyOaeTlPEpD9oxal3kgA0bb2YNYbN56fJSk/edit)
1. https://handbook.tts.gsa.gov/software/
1. https://handbook.tts.gsa.gov/collaboration-tools/
1. https://handbook.tts.gsa.gov/tools/slack/rules/
1. https://before-you-ship.18f.gov/security/
1. https://before-you-ship.18f.gov/infrastructure/
1. https://digital.gov/resources/an-introduction-github/
1. https://handbook.tts.gsa.gov/contributing/
1. [Confirmation quiz](https://docs.google.com/forms/d/e/1FAIpQLSeyTWbNU8_cdeBJVZXQG-aY8ciqgZVVvUopU9XOkCpQSUmiJA/viewform)

We should reconsider whether this is the right material to have them go through, or if anything's missing.

## Implementation Steps

- [ ] Ask for #microrequests help
- [ ] Update Infrastructure Best Practices, which may be rewriting it or deleting it (in favor of content that exists elsewhere)
- [ ] Marge Infrastructure Best Practices into the Handbook
- [ ] Rewrite quiz

## Acceptance Criteria

- [ ] Consensus in the Tech Portfolio that new hires are getting the appropriate information as it relates to things in our team's scope
