### ISSUE TITLE
close John's p-card

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1574]
## Background Information

Now that micropurchases in TTS have been centralized (again), there's no need for the Tech Portfolio to hold a card.

## Implementation Steps

- [x] Confirm with @JJediny that card can be cancelled
- [x] Notify Rochelle P - email thread `closing down John's purchase card`
- [ ] "clean up/reconcile any outstanding CL#'s"
- [ ] Card cancelled

## Acceptance Criteria

- [ ] John is no longer a purchase card holder
