### ISSUE TITLE
18F Account Managers and others are being deactivated from Mural too quickly

### ISSUE THREAD

**Issue by annepetersen** [18F/tts-tech-portfolio#1577]
## Background Information

18F Account Managers and others regularly conduct Project Health checks, among other things, via Mural. These usually happen twice a month. Despite this, Account Managers and other 18F staff are regularly being deactivated, which keeps them from completing this required task.

## Implementation Steps

- [ ] Could active 18F staff be made permanent Mural members?
- [ ] Can we disable the inactive check as described below

## Acceptance Criteria

- [ ] 18F staff do not get deactivated from Mural before 90 days of inactivity.

**Comment by adborden** [comment]
🤮  [Mural does indeed mark guests inactive after 14 days](https://support.mural.co/en/articles/3835231-inviting-collaborators#when-a-guest-is-inactive), which requires an admin to reactivate them.

**Comment by adborden** [comment]
@18F/tts-tech-portfolio Mural has an option to [disable the inactivation window](https://app.mural.co/t/gsa6/settings/profile). I don't really see a reason why we need that option enabled. Since our plan accommodates unlimited guests, there's no reason to expire them every 14 days. Can we disable this option?

![Screen Shot 2021-09-23 at 5 11 28 PM](https://user-images.githubusercontent.com/509703/134599980-4ed72e0a-7635-40b4-a0fd-f13b66260beb.png)

**Comment by adborden** [comment]
I unchecked the box. There's some memory on the team that this was already disabled and maybe became re-enabled. I'm going to call this done for now and I'll keep an eye on it.
