### ISSUE TITLE
Investigate IT categorization frameworks for doing Tech Portfolio Management

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#158]
## Story
As a member of the Tech Portfolio, I would like to have a frame of reference to model our work activity

## Problem we're trying to solve:
Issues on the Tech Portfolio GitHub board don't have any organization to follow.  

## Background information:
@its-a-lisa has suggested using Information Technology Infrastructure Language (ITIL)
@afeld has promoted the Agile Manifesto

## Actions to take
 - [ ] All members of Tech Portfolio research ITIL
 - [ ] All members of Tech Portfolio research Scaled Agile Framework
 - [ ] All members of Tech Portfolio research YaSM
 
## Acceptance Criteria
- [ ] We're all on the same page with what framework we're going to align to
## Supporting documentation:
https://yasm.com/wiki/en/index.php/What_is_YaSM
https://wiki.en.it-processmaps.com/index.php/ISO_20000
https://wiki.en.it-processmaps.com/index.php/History_of_ITIL
https://www.3cs.ch/manifesto-service-management-agility-summary/

## Working documentation:

**Comment by its-a-lisa** [comment]
I feel like we've done this at the last two all-hands and it is something that will continue to go on.
