### ISSUE TITLE
Trello - TTS License Count (due Oct 23rd)

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#1590]
## Background
The enterprise user and guest user scenerio we started with for the Trello consolidation will no longer be allowed. We need to provide GSA IT a total user count. 

$12.50 per user/month

## Implementation Steps
- [x] With with BizOps to ensure there is funding allocated to cover the new cost.
- [x] Work with GSA IT trello admins to get user metrics
   - [x] Total per workspace
   - [x] Activity per guest users (boards, edits, sessions)

## Acceptance Criteria

- [x] We can provide a count of total licenses for all of TTS for FY22 and the budget is available for that amount of users.
