### ISSUE TITLE
Macbook IT service desk help is inconsistent

### ISSUE THREAD

**Issue by adborden** [18F/tts-tech-portfolio#1593]
## Background Information

Recently we've had a few cases where the usual process of opening a Service Desk ticket for a Macbook issue resulted in delayed routing, or issues getting closed without resolution.

## Implementation Steps

- [ ] Gather ticket numbers for issues that were resolved successfully and issues that "got stuck"
- [ ] Work with GSA IT to identify how we can improve this

## Acceptance Criteria

- [ ] GIVEN I have an issue with my macbook
  WHEN I open an issue with the IT service desk
  THEN I have confidence that my issue will be resolved to my satisfaction
  AND I know what to expect in terms of time to resolution

**Comment by timothy-spencer** [comment]
My laptop is apparently not set up to allow it to get updates anymore since I restored my backup after a laptop refresh.  So I could not upgrade it to newer versions of the OS.  I requested information on how to get that fixed, so I could upgrade in INC3295501 on Nov 23, 2020.

After some emails, it was determined that my laptop was not properly enrolled in the self-service system, so it couldn't update itself.  I asked if there were any updates or a way for us to enroll my laptop again on Jan 8, 2021, and received no response to that or a "Hello?" sent on Feb 2, 2021.  INC3295501 was closed in May of 2021 with a comment saying something about how Big Sur was still being tested.

My system is still running Mojave.

**Comment by rocheller123** [comment]
These Macbook issues have been resolved. Will work more closely with TTS users and GSA IT to resolve issues quickly and efficiently. GSA IT recommends reaching out to the IT help desk and escalating an issue if tickets are not actively being worked on.

**Comment by rahearn** [comment]
> GSA IT recommends reaching out to the IT help desk and escalating an issue if tickets are not actively being worked on.

This is a really unsatisfying resolution. What does "escalating an issue" even look like, or how can we do it? How can we even know if something is being worked on since tickets never get updated and tickets that I've opened by calling don't always show up in IT Service Desk when I try to view the details from email notifications.
