### ISSUE TITLE
Change Ownership in Invision to Tech Portfolio 

### ISSUE THREAD

**Issue by rocheller123** [18F/tts-tech-portfolio#1595]
## Background Information

The Invision App currently has Aidan Feldman set as Owner. To change ownership and remove Aidan, Invision Customer support requires one of the TTS Invision users to access Aidan's inbox to retrieve an email to change the password to the account and change ownership from there. They stated this is the only way to change ownership. We should try to set the owner (or, very least, email address) to the Tech Portfolio group's email address. 

Information received from Invision Support about transferring ownership: 

> In InVision V7, owners can transfer the ownership of their team to a different member at any time. This must be done from the owner's account. 
> If this email address is a business or corporate address, I would direct you to your internal email server administrator and Human Resources representative to (re)gain access to the unavailable owner's email address.
> 
> Once you have access to the owner's email, you can reset the password to the InVision account and access it as necessary. To reset your InVision account password:
> - Click here: https://projects.invisionapp.com/d/password/requestReset
> - Enter the email address associated with your account.
> - Click Request Reset Link.

> Once you have access, follow these steps to transfer the ownership of a V7 team:
> - Sign in to your InVision account.
> - On the left, click People.
> - On the People page, click the dropdown next to your name and click Transfer team ownership.
> - From the drop-down, select a team member to be the new owner and click Next.
> - You’ll receive an email with a 6-digit verification code. Enter the code to complete the ownership transfer. (This email will go to the current owner's email as well)
> These steps are also listed here: https://support.invisionapp.com/hc/en-us/articles/360054427531

A ticket (# INC3578000) was open with GSA IT Service Desk to request access to Aidan's email account. Following was the response: 

> Before we can grant access to Aidan Feldman's email account, you'll need to gather a written approval from HR as well as 
> Aiden's former Government Supervisor. Once both written approvals have been obtained, you'll need to submit a Generic Service Catalog Request (SCR). Instructions on how to submit this Generic SCR can be found here: https://gsa.servicenowservices.com/kb_view.do?sysparm_article=KB0023307&sysparm_rank=1&sysparm_tsqueryId=2961d2aa1bd33810870ea86ce54bcb08
> 
>  
> 
> Please ensure to attach both written approvals in this Generic SCR, as well as who's mailbox you're trying to access and why. Once all of this is gathered and submitted, the ticket will be routed to the Google/Email team who can then grant you access. Thank you and have a nice day.  

## Implementation Steps

- [ ] Request access to Aidan's email account (See notes above)
     - [ ] Get written approval from HR 
     - [ ] Get written approval from Aidan's former manager 
     - [ ] Submit a [Generic Service Catalog Request (SCR)](https://gsa.servicenowservices.com/kb_view.do?sysparm_article=KB0023307&sysparm_rank=1&sysparm_tsqueryId=2961d2aa1bd33810870ea86ce54bcb08)
 - [ ] Reset the password to the InVision account and access it as necessary. Instructions to reset InVision account password are listed above.
 - [ ] Once you have access, follow the steps above to transfer the ownership to the Tech Portfolio team (steps are also listed [here](https://support.invisionapp.com/hc/en-us/articles/360054427531))
- [ ] After transferring ownership, remove Aidan as a member of the Invision app. 

## Acceptance Criteria

- [ ] Invision ownership has been transferred and Aidan has been removed as a member.
