### ISSUE TITLE
Request for 10x GH org

### ISSUE THREAD

**Issue by jadudm** [18F/tts-tech-portfolio#1602]
## Why do you want a dedicated GitHub org?

10x is growing its internal team (adding engineers, designers, PMs, etc.), and we are working to better coordinate access across the team and partners. This feels like a natural point to better consolidate and coordinate our work in GH.

## Tasks

1. [x] Review the [rules](https://handbook.tts.gsa.gov/github/#rules), as those will also apply to the new organization.
1. [x] Get a :+1: from the @18F/tts-tech-portfolio
1. [ ] [Submit a micropurchase request](https://handbook.tts.gsa.gov/purchase-requests/) if you need private repositories.
1. [ ] [Create the organization.](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch)
1. [ ] [Enforce two-factor authentication.](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/requiring-two-factor-authentication-in-your-organization)
1. [ ] Add to the [list of organizations in Terraform](https://github.com/18F/tts-tech-portfolio/blob/main/terraform/orgs.tf)
1. [ ] [Add users.](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/inviting-users-to-join-your-organization)
1. [ ] Ensure that all your webhooks, integrations, etc. are in place.
1. [ ] [Transfer repositories.](https://help.github.com/en/github/administering-a-repository/transferring-a-repository)
       — GitHub does redirects, but you'll want to make sure it doesn't break things like deployment.
1. [ ] Add to the [list of organizations in the Handbook](https://handbook.tts.gsa.gov/github/#organizations).

**Comment by jadudm** [comment]
I'm closing this ticket for now, because of infrastructure changes underway within the org.
