### ISSUE TITLE
FY22 COR Recertification for @jjediny

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#1619]
## Background Information

FAITAS was the system GSA formerly used to get your COR training and certification, CSOB is the new system only recently available. The Process has been updated with a new guide - https://docs.google.com/spreadsheets/d/1mKvloH4RpWx8adUB50n8fAFdJA2YZ6XhW2b8C7tGIp8/edit#gid=43193094 . @jjediny need to complete their COR recertification as there current one is too old. 

## Implementation Steps

- [ ] Follow the new [TTS COR Guide](https://docs.google.com/spreadsheets/d/1mKvloH4RpWx8adUB50n8fAFdJA2YZ6XhW2b8C7tGIp8/edit#gid=43193094)
- [ ] Complete training requirements
- [ ] Obtain new Certificate

## Acceptance Criteria

- [ ] Provided new Certificate to all Contracting Officer's @JJediny is currently a COR for
