### ISSUE TITLE
determine which cloud-synced design tool to pursue

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#165]
Following up on #121,

> there is a growing demand for tools that allow direct collaboration with partners and teammates. In general the tools mentioned fall into three categories: designing interfaces, prototyping, and sharing work with collaborators.

- [x] Determine if Figma plans to pursue FedRAMP
- [x] Determine if InVision plans to pursue FedRAMP
- [x] Determine if Sketch plans to pursue FedRAMP for their [Cloud](https://www.sketch.com/docs/sketch-cloud/) product - no response
- [ ] Acquire / procure / exercise option

**Comment by afeld** [comment]
- [ ] Update status of each above

**Comment by its-a-lisa** [comment]
In conversation with @afeld today we determined that there is one option going forward and we're going to go ahead with it and track it using a new issue #233

**Comment by annepetersen** [comment]
While I know here isn't the place, could someone notify me with the results of this decision?
