### ISSUE TITLE
consolidate approaches for customer service email

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#169]
## Background

We have a number of approaches being used for inbound business and customer support inquiries across TTS systems:

- Google Groups
   - Leveraging [collaborative inbox](https://support.google.com/a/answer/167430?hl=en)?
- Hubspot
- ~~[Public Slack channels](https://handbook.18f.gov/slack/#the-public)~~
- ZenDesk

Some recent issues around DMARC/DKIM/SPF have indicated that it feels like we are solving the same problems over and over across programs, and that it would make sense to try and settle on some best practices and consolidate approaches.

## User stories

- As someone managing a support inbox, I want to exert minimal effort in procuring, setting up, and maintaining it.
- As the Tech Portfolio, I want fewer pieces of software to manage ATOs and licenses for.

## Implementation Steps
- [ ] Monitor progress from stakeholders
- [ ] Facilitate bi-weekly meetings

## Acceptance Criteria

- [ ] Clearly documented way that we [will] do customer service emails, in terms of tooling, configuration, and maybe practices

cc https://github.com/GSA/digitalgov.gov/issues/107 https://github.com/GSA/digitalgov.gov/issues/1513

**Comment by its-a-lisa** [comment]
seems like [challenge.gov](https://gsa-tts.slack.com/archives/C02CD5VUQ/p1582579428007300) is also looking for something around this

**Comment by afeld** [comment]
We may leverage this card to cover both customer service email + a CRM, or treat them as separate—not sure.

cc @brianrfox

**Comment by afeld** [comment]
Likely can be broken down to smaller issues.

**Comment by afeld** [comment]
Seems like this has been replaced by other tasks; let's split out any remaining issues and close this.

**Comment by its-a-lisa-at-work** [comment]
Closing this issue in favor of https://github.com/18F/tts-tech-portfolio/issues/941
