### ISSUE TITLE
ensure root access for remaining AWS accounts

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#174]
- 096224847349
- 560284223511

TODOs:

- [x] Email GSA IT Service Desk about Ownership of corresponding Google Groups - `CALL1331757`/`INC2889171`
- [x] Submit Generic Catalog Request
- [x] Get Ownership of corresponding Google Groups
- [x] Log into accounts
- [x] Switch to `devops+aws-<account ID>@gsa.gov`
- [x] Mark the mailing lists as `DEPRECATED`

**Comment by afeld** [comment]
My email to the Service Desk:

> I am the (relatively) new Technology Director for TTS and need Ownership of these Google Groups:
>
> - 096224847349@gsa.gov
> - 560284223511@gsa.gov
>
> I don't believe anyone remaining on these mailing lists (namely Kimber Dowsett or Erik Burgess) are still at GSA. Let me know if any additional information is needed. Thanks!

Their response:

> You will need to place a generic catalog request for this.  Be very specific as to what is needed.  The below URL will show you how to place this.  If you have further questions, please let us know.
>
> https://gsa.service-now.com/sp?id=kb_article&sys_id=af3c23a4dbb0078007d97e721f96198c
