### ISSUE TITLE
move "how we work" somewhere canonical

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#176]
Follow-up to #80.

## User stories

- As a member of the Tech Portfolio, I want to know where to look to revisit our agreed-upon principles

## TODOs

- [x] Clean up [the list](https://docs.google.com/document/d/1N4osbsZjxbNQUZCXNd706BAzWRhBlb8pfh7wAWJbnPU/edit#heading=h.m84egu41cfkv
)
- [x] Move to somewhere canonical
- [x] Link from [Handbook page](https://handbook.18f.gov/tech-portfolio/#important-links) (if not on that page already)

**Comment by its-a-lisa** [comment]
I've done as much as I can for cleaning [the list](https://docs.google.com/document/d/1N4osbsZjxbNQUZCXNd706BAzWRhBlb8pfh7wAWJbnPU/edit#heading=h.m84egu41cfkv) the only thing that is left is for @JJediny to complete the #126 task -- do we want to close that or reprioritize it to move it to in-progress now?

**Comment by its-a-lisa** [comment]
Put the information in the team's readme.md page  https://github.com/18F/tts-tech-portfolio/pulls

**Comment by its-a-lisa** [comment]
Moved this to the handbook with this [pull request](https://github.com/18F/handbook/pull/1659)
