### ISSUE TITLE
plan for better SaaS user management

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#179]
## Background information

Related to #92, we have a need to remove user accounts from various SaaS when offboarding people. Would be great to handle this in one place. A [System for Cross-domain Identity Management (SCIM)](https://www.okta.com/blog/2017/01/what-is-scim/) is something that could help here.

## Implementation steps

- [x] Research what SCIM SaaS is available
- [x] Determine which of the SaaS we use supports SCIM
- [ ] Create issue(s) for any follow-up work

## Acceptance criteria

- [x] Roadmap for how to handle user management with third-party services TTS uses

**Comment by afeld** [comment]
Just learned that the GSA Separations report is available at https://d2d.gsa.gov/dataset/gsa-separations, which could be very helpful for this.

**Comment by afeld** [comment]
Good candidate for https://github.com/18F/tts-tech-portfolio/issues/1456.

**Comment by afeld** [comment]
Calling this "done enough for now"; we'll create more follow-up issues when contractors are in place.
