### ISSUE TITLE
Deep Grooming of Project Board (Nov 2019)

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#182]
#### Acceptance Criteria
- [x] convert all user story titles for issues into task-as-statements.
- [x] strip out all EPICs from Issues into one issue with links to all related/sub issues.
- [x] Establish Acceptance Criteria for all actionable tasks per issue.
- [x] Close out all issues that are not actionable.
- [x] Close and consolidate related issues `in favor
- [x] create an issue for transforming those EPICS into README.md in the https://github.com/18f/tts-tech-portfolio

- [x] @its-a-lisa 
- [x] @JJediny

**Comment by its-a-lisa** [comment]
- [x]  convert all user story titles for issues into task-as-statements.
- [x]  Establish Acceptance Criteria for all actionable tasks per issue.
- https://github.com/18F/tts-tech-portfolio/issues/77
- https://github.com/18F/before-you-ship/issues/420
- https://github.com/18F/tts-tech-portfolio/issues/47
- https://github.com/18F/handbook/issues/1530
- https://github.com/18F/tts-tech-portfolio/issues/198
- https://github.com/18F/tts-tech-portfolio/issues/22
- https://github.com/18F/laptop/issues/185
- https://github.com/18F/tts-tech-portfolio/issues/159
- https://github.com/18F/before-you-ship/issues/246
- https://github.com/18F/tts-tech-portfolio/issues/63
- https://github.com/18F/aws-admin/issues/23
- https://github.com/18F/before-you-ship/issues/412

- [x]  strip out all EPICs from Issues into one issue with links to all related/sub issues.
- https://github.com/18F/tts-tech-portfolio/issues/20

- [x]  Close out all issues that are not actionable.
- https://github.com/18F/before-you-ship/issues/212
- https://github.com/18F/before-you-ship/issues/274

- [x]  Close and consolidate related issues `in favor
- https://github.com/18F/tts-tech-portfolio/issues/110
- https://github.com/18F/vulnerability-disclosure-policy/issues/2
- [ ]  create an issue for transforming those EPICS into README.md in the https://github.com/18f/tts-tech-portfolio
