### ISSUE TITLE
Schedule in-person time for January - due 1/16

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#184]
## Story:
As a member of the Tech Portfolio, I want to know when the next time we're going to have a long session dedicated to our team. 

## Actions to take: 
- [x] Check calendars
- [x] Send out invitations
- [x] @afeld: Book travel
- [x] Book room - 2460B
- [x] Create Agenda.

## Acceptance criteria:
- [ ] Everything is squared away for meeting
- [ ] Establish the team's offical grooming and board management as documentation.

**Comment by its-a-lisa** [comment]
I think doing a Path Analysis on Software Request and Software Maintenance would be good agenda items for the next All Hands (whether in person or virtual) ... now that we are likely to have swimlanes going forward (based on conversation between @JJediny & @its-a-lisa  on 11/27) we should probably clearly lay who is responsible for what

**Comment by its-a-lisa** [comment]
Put together a best effort for an [Agenda](https://docs.google.com/spreadsheets/d/1zDLShyrRupzVD8GxbdUv2rrQA5x1Bes9jN-vfHf3C2k/edit#gid=1321932174) and [note prep](https://docs.google.com/document/d/1IOOAmgKeazMJXULnSdh-PYBQNsL60bv6gHMoPCKoNyI/edit#heading=h.85zaphjewlb)  -- I figure we can formulate it as we go -- I left Wednesday open enough so if I can come into the office, I will, but we should be able to work together well enough even if not. 

Moving to waiting/blocked so ya'll can review it and make comments, etc

**Comment by afeld** [comment]
Calling this "done".
