### ISSUE TITLE
reduce government barriers to entry for Low-impact SaaS

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#186]
## Background information

Follow-up task to #46. [Details.](https://docs.google.com/document/d/1_N1YkUGzBMIwJEv53VQUpfYVxykjYHvWXeOkrpFER4I/edit?ts=5d485306#heading=h.dcssz6q3z55s) Going to use "minimal" impact to mean lowest-of-the-Low, for lack of a better term.

## User stories

- As someone involved to get Security (re)approval for minimal-impact SaaS, I want to minimize the effort spent doing so so that I can focus on higher-risk things.
- As a vendor providing minimal-impact SaaS with little cost, I don't want to spend a lot of time or money on compliance because I won't necessarily get return on my investment.

## Implementation

- [x] Gauge the likelihood of changing the FedRAMP memo to explicitly allow minimal-impact SaaS to be accepted by agencies
   - Result: Not right now
- [x] TTS Tech Portfolio reviews updated LiSaaS Guidance and Checklist
    - [x] When reviewing, one of the review items should be whether or not the policy enables authorizations to be processed in weeks or days

## Acceptance criteria

- [x] TTS Tech Portfolio has provided comments to GSA IT Security
- [x] TTS Tech Portfolio creates new card to document the [Handbook Software page](https://handbook.tts.gsa.gov/software/)  with a deadlines of 1 week after it is published.

**Comment by its-a-lisa** [comment]
@afeld thanks for further grooming this card -- what about making this card about reviewing the new process and associated it with docs that GSA IT Security is in the process of doing right now and moving it to `in-progress`?

#### For the Implementation

 ... instead of saying:

> - [ ] Work with Security to formalize the GSA LISaaS program for long-term use

...We say: 

> - [ ] TTS Tech Portfolio reviews updated LiSaaS Guidance and Checklist
 >  - [ ] When reviewing, one of the review items should be whether or not the policy enables authorizations to be processed in weeks or days

#### For the Acceptance Criteria

 ... instead of saying:

> - [ ] There is a clear, documented pathway for minimal-impact SaaS to be authorized in a matter of weeks or days.

...We say: 

> - [ ] TTS Tech Portfolio has provided comments to GSA IT Security
> - [ ] TTS Tech Portfolio creates new card to document the Before You Ship guidance with a deadlines of 1 week after it is published.

**Comment by afeld** [comment]
That works! Minor: The updated LISaaS policy/process is more of a [Handbook Software page](https://handbook.tts.gsa.gov/software/) thing than a Before You Ship thing, as the latter is more about authorization for software built in-house.

**Comment by its-a-lisa** [comment]
That's right! It would be great to build out the 'Before You ...' documents into a series related to ATOs ... or maybe the handbook needs to have some ATO 101 content that folks aren't directed to BYS

**Comment by its-a-lisa** [comment]
Provided comments in the [Low_Impact_SaaS_(LiSaaS)_Solutions_Authorization_Process_[16-75_Rev_4]_01-23-2020_Clean](https://docs.google.com/document/d/1o2XJ7Hn4MFNuk9kMb_f53piTiOUGajwg8TTu1IRmDzQ/edit#) and [LiSaaS_Solution_Profile_Template_01-23-2020](https://docs.google.com/document/d/1o4CYQ-67Io0crBv6RtlxFA0r3QvLdGOzqtNw9QTBRJs/edit)

Drafted email to send to GSA IT Security - Compliance group to send off in the morning; adding label `Feedback Needed` and moving to `Waiting/Blocked` until presented at next standup before closing

**Comment by its-a-lisa** [comment]
Had meeting today to go over comments; closing issue.
