### ISSUE TITLE
better support teams without developers

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#193]
Cross-post [from Slack](https://gsa-tts.slack.com/archives/C3F3HR717/p1574381405193100):

> there have been a several examples in the past week of various programs in Solutions leaning on the Tech Portfolio to be their developers because they don't have anyone internally. one of these was a security vulnerability.
>
> i get _why_ they are asking us and don't blame anyone for this, but i'm raising it here as a systemic issue of running systems that are unmaintained (on a technical level). whether picking up random development tasks should be part of the Tech Portfolio's responsibilities is something we should talk about, but it's outside of our current stated scope and bandwidth.
>
> there has been talk before about "roving bandit(s)" of engineer(s) that can pick up technical tasks for Solutions / the FCSF Caucus.
>
> this is one of the things #dev-lab was created to help with, but my understanding is that OPP opted out.

Could be scoped to TTS teams, Solutions, or the FCSF Caucus. Running list of example needs:

- 10x ([notes](https://docs.google.com/document/d/1SXfHejnQmHA46FNokOw6NEHCvZyGjMt_ljnaSMOMkI0/edit))
   - pitch evaluations
   - project oversight
- https://github.com/18F/fedramp-dashboard/pull/84
- https://github.com/18F/fedramp-dashboard/issues/77
- https://github.com/18F/tts-tech-portfolio/issues/145

## Implementation

- [x] Write up proposal
- [x] Get feedback from @afomi 
- [x] Get feedback from @awichman
- [x] Get feedback from `#eng-solutions`
- [ ] Get feedback from Jay
- [ ] Get feedback from Dom
- [ ] Figure out next steps

## Related issues

#85 https://github.com/18F/handbook/pull/1669

**Comment by its-a-lisa** [comment]
@thecapacity based on our conversation at the sync yesterday. I took the following notes:
- Potential to assign POCs from the Tech Portfolio to lines of business (e.g. -- Alyssa support Solutions, John support 18F, etc)
- [ ] Need to better demonstrate what value the lines of business are getting from our portfolio to justify not helping in this area
- [ ] Develop mechanism for lines of business to provide input into our workflow

Let me know if you have anything else to add or I missed anything.

**Comment by afeld** [comment]
The majority of the work we've done thus far is cross-cutting of TTS, by design. Examples:

- Infrastructure buy
- Software approvals and user management

We certainly roll up our sleeves and dig in to help with specific projects, such as:

- Working through security vulnerabilities
- Shepherding through the ATO process

but picking up development tasks for a specific system is _not_ something we have done thus far, and which we noted explicitly being out of scope in https://github.com/18F/handbook/pull/1669. I am not opposed to it, but just want to note that it would be a change, and an increase in scope. 

Mentioned it to @HuixianXu today, and she suggested writing up a proposal of what responsibilities that could cover as well as how many hours a week we expect that to take, from which we could figure out the budgeting.

**Comment by kfoley-18F** [comment]
If any of this work can be staffed via microrequests or similar, there are 18F engineers who can help from time to time. Merging security vulnerabilities on behalf of other teams, for example, would be well within someone's abilities to pick up. 

With CR/budget situation at the moment, there are folks who can pick up small projects currently. 
@Jkrzy -- tagging you in on this thread.

**Comment by afeld** [comment]
My opinion is that we need _slightly_ more institutional memory (i.e. people working on projects longer, even if just in short bursts) than microrequests like that could provide. Certainly will list it as an option though. Thanks!

**Comment by afeld** [comment]
[Related letter from @afomi (that can maybe be adapted into this proposal.](https://docs.google.com/document/d/1fVTOAFG-2RqHlWUJfKYWOuP0MSj0_xYcC84IA18FfXc/edit?ts=5e00ef96)

**Comment by afeld** [comment]
Added [my idea](https://docs.google.com/document/d/1fVTOAFG-2RqHlWUJfKYWOuP0MSj0_xYcC84IA18FfXc/edit?ts=5e00ef96#heading=h.e5qcdedfsdmj) to the existing letter; waiting for feedback from @afomi and @awichman on how they would like to proceed. Comments from others welcome!

**Comment by awichman** [comment]
@afeld Left feedback/comments in doc

**Comment by afeld** [comment]
Most comments now resolved, so [soliciting wider feedback](https://gsa-tts.slack.com/archives/C3F3HR717/p1578520067007600?thread_ts=1574381405.193100&cid=C3F3HR717).

**Comment by its-a-lisa** [comment]
@afeld just wanted to remind you that from our standup on 1/31, you mentioned writing up some thoughts on this topic after you asked the TTS Tech Portfolio if we were supportive of going forward and I felt like I had some gaps in my knowledge for how we got to the current state to what you were proposing.

**Comment by afeld** [comment]
@stephencarroll set up a meeting today to talk through establishing a BPA for short-term staffing help, to sit somewhere between [microrequests](https://handbook.tts.gsa.gov/microrequests/) and the Simplified Acquisition Threshold ($250k). Details still being worked out, but that might be the best avenue here given its flexibility.

**Comment by afeld** [comment]
Given there isn't action needed from the Tech Portfolio right now, closing this out.
