### ISSUE TITLE
Implement a testing framework for all available CSP (AWS/GCP/Azure) providers Customer Responsibilities (CRMs)

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#195]
## User Story
As a TTS user of any Cloud Service Provider (CSP) available to TTS (Azure/AWS/GCP). I want the ability to audit my/any account's implementation of the FEDRAMP CRM customer responsibilities required to fully implement all security controls inherited. 

As the TTS Tech Portfolio, we have the ability to maintain a generic auditing/testing ability and framework to ensure that in the least all the technical security controls are implemented.

Modeling off of this project: https://github.com/mitre/cis-aws-foundations-baseline

#### Acceptance Criteria
- [ ] Implement auditing ability for Azure's CRM
- [ ] Implement auditing ability for AWS's CRM
- [ ] Implement auditing ability for GCP's CRM

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
