### ISSUE TITLE
prep for FSGC EBC Evaluation Part 1 meeting - due 12/10

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#197]
[The FAS Systems Governance Committee](https://sites.google.com/a/gsa.gov/fas-systems-governance/home) is responsible for voting on IT budget for FAS programs. The Dec 10 meeting is (I think) to review the next stage of the [Executive Business Case (EBC) Concepts](https://sites.google.com/a/gsa.gov/fas-systems-governance/ebcs/concepts) that were previously presented and voted on.

- [x] Get added to meeting
- [x] Read through [Nov 2019 Concept Decision Summaries](https://docs.google.com/spreadsheets/d/1Z18lrBuR4SFEP5GoDLFT3unKjx38GUUkTFr73tnaXNQ/edit#gid=0)
- [x] Optional: Read the `Comments / Notes` included with my vote on the other sheets

I would timebox the prep for this meeting to an hour or so. You will likely mostly be listening and any voting will be done later.

**Comment by afeld** [comment]
The main things to look for:

- Where there is a risk of throwing good money after bad
- Projects that are not being done iteratively, user-centered, etc.
- Opportunities for TTS business

**Comment by its-a-lisa** [comment]
Read through material
