### ISSUE TITLE
Audit Terms of Service for TTS Software

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#198]
## User Story:
As someone in the Tech Portfolio, I want to make sure all the software we're using meets our standards for terms of service. 

## Problem Statement: 
Ensure all the proper parties accept the conditions of using the software.
## Background information: 
Note:  @afeld had previously [experimented with code to do these checks](https://github.com/18F/legalese), which may be helpful.
## Actions to take:
- [ ] Check with General Counsel (OGC) on what the workflow for the audit should be
- [ ] Confirm which have had their Terms of Service reviewed, and which haven't
- [ ] Run the latter through OGC  
## Acceptance criteria: 
- [ ] All the actions have been completed 
## Supporting Documentation:
For the [software in use by TTS](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=00)
## Related Issues: 
_Moving from [Trello](https://trello.com/c/voQxY12D/288-audit-current-terms-of-service-for-all-tts-apps)._

**Comment by its-a-lisa** [comment]
Might make sense to to re-groom this card to audit our tools to assure that we're using the FedRAMP version of the tool.

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
