### ISSUE TITLE
EPIC: Develop a TTS tech portfolio proactive security roadmap

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#20]
## Problem Statement: 
What things can the TTS Tech Portfolio (directly, or working with cloud.gov, GSA IT, etc.) do to have better security across the board?
## Related Issues: 
- [ ]  Automated upgrades of packages with known vulnerabilities - #17 
- [ ] Use single sign-on for software-as-a-service (SaaS) - #19
- [ ] Anomaly detection - #22
- [ ] [Better scanning for secrets in source code](https://blog.acolyer.org/2019/04/08/how-bad-can-it-git-characterizing-secret-leakage-in-public-github-repositories/)
- [ ] Alerts for things like privilege escalation in cloud.gov, and other things that require manual - - [ ] log review for ATOs - related to #88
- [ ] vAuditing of IAM permissions - https://github.com/18F/aws-admin/issues/23

cc @coreycaitlin

**Comment by JJediny** [comment]
Setup A Terraform Repository (similar to https://github.com/18f/dns) for:

### Managing Github:
- [ ] Membership - https://www.terraform.io/docs/providers/github/r/membership.html
- [ ] Teams and their authorization on repos - https://www.terraform.io/docs/providers/github/r/team.html
- [ ] Repo Branch Protections - https://www.terraform.io/docs/providers/github/r/branch_protection.html?origin_team=T025AQGAN 
*suggestion by @pburkholder

### Managing AWS:
- [ ] Users
- [ ] IAM profiles
- [ ] Accounts
- [ ] 2FA setup - Saml/Oauth automate (google/login.gov/secureauth single sign on)

**Comment by afeld** [comment]
[Mural mapping the costs and benefits of various ideas.](https://app.mural.co/t/gsa6/m/gsa6/1565630828035/3731af854fed8909a5af9fa4a3d65234ee69d0cd)

**Comment by davemcorwin** [comment]
@afeld Just a plug here for identifying ways of facilitating and/or automating the process around GSA IT security scanning with Netsparker. This is of particular interest to Federalist as we end up in the middle of facilitating communication between GSA IT and our partners whenever there are vulnerabilities (ex JQuery), which is currently a manual, email-based process. Happy to provide more details!

cc @amirbey

**Comment by afeld** [comment]
Perhaps a part of https://github.com/18F/tts-tech-portfolio/issues/152.
