### ISSUE TITLE
EPIC: Authority to Operate (ATO) and System Security Plan (SSP) Sharing

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#208]
In [research for the FISMAtic project](https://github.com/uscensusbureau/fismatic/blob/master/research.md#a-program-teams-are-not-well-equipped-to-complete-atos), "the lack of access to examples [of System Security Plans (SSPs)] came up...more than any other topic" by people that have been through an Authority to Operate (ATO) process. Lack of access to examples was also a blocker for that project and others like it trying to do analysis across SSPs. We have the power to solve this for TTS SSPs.

- [x] Check in with FedRAMP to see if they've worked on this at all
- [ ] Check in with Security to see if they've worked on this at all
- [ ] Finalize the [SSP Redaction Guide](https://docs.google.com/document/d/1P-_ow-6CFu_uEJ62wLHTUhix-d5zWVls-hdTPD16bho/edit) - cc https://github.com/18F/open-source-policy/issues/93
- [ ] Update [our ATO documentation](https://before-you-ship.18f.gov/ato/) to reference that guidance, and give tips when authoring from scratch
- [ ] Redact and publish an existing SSP

Might make sense to split some of those out to separate issues.

cc https://github.com/opencontrol/discuss/issues/68
