### ISSUE TITLE
Strictly Enforce the cross-linking from the TTS Software Inventory and Micropurchase sheets to ensure deduplication of data and referenceability

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#216]
The two developing sources of truth for managing and tracking 1. TTS Software usage and 2. Micropurchase and Contract Tracking are being established; this task to to track the tying together of the two sources.

Acceptance Criteria
- [x] ATO/FITARA status/dates are all managed in the TTS Software Inventory with link to the artifacts folder.
- [x] The information contained in the current artifacts are transferred and double-checked against the Software Inventory
- [x] The GAP analysis of what delta remains is known as a completed output/document to take corrective actions against.

**Comment by JJediny** [comment]
SaaS portion of the Software inventory is up to date
