### ISSUE TITLE
create software budget projection - due 1/23

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#219]
...factoring in projected costs of FedRAMP Tailored sponsorship, plan upgrades, etc. Broken out from #166.

## Relevant links

- [Solutions FY20 spend plan](https://docs.google.com/spreadsheets/d/1YSfw_5ByfgB03gFOYcc0VkrFxh1vMtx5D0DpwaYUpBI/edit#gid=693933101)

## User stories

- As a member of the Finance team, I need to understand if our budget for software is sufficient.

## Implementation

- [x] Show what the Tech Portfolio plans to spend on software in FY20
- [x] Check against [software list](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=0)
- [x] Check against contract inventory - cc #155 
- [x] Show breakdown by Solutions programs, to fill in spend plan
- [x] Schedule a retro

## Acceptance criteria

- [x] All software we pay for on an ongoing basis is listed
- [x] All known upcoming software spend is listed
- [x] All software purchases are tied to their corresponding program / budget line
- [x] We have a number to give to Finance as the expected FY20 TTS (shared) SaaS spend

**Comment by afeld** [comment]
Updated to reflect that @thecapacity asked if we could have this for FY20 next week.

**Comment by afeld** [comment]
[Working spreadsheet](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=379924319), which may or may not be the final home for it.

**Comment by JJediny** [comment]
- [ ] Determine the threshold for what is a "TTS Shared Service" - what is the $ per program and # of programs using threshold
