### ISSUE TITLE
Status of event management around anomalous behavior in/of TTS systems

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#22]
## Problem Statement: 
We should have some baseline anomaly detection in place for things like changes in traffic, login attempts, egress, etc. cloud.gov and GSA Security Engineering are interested in collaborating on this.
## Actions to take:  
- [ ] Evaluated existing tools in use at TTS to see whether any support this
- [ ] Determined if monitoring for anomalous behavior is being done by any TTS systems
- [ ] Created issue around follow-up steps
## Acceptance criteria: 
- [ ] Anomalous behavior of TTS systems is detected

**Comment by JJediny** [comment]
Related to https://github.com/18F/tts-tech-portfolio/issues/88

**Comment by afeld** [comment]
Not a priority—closing.
