### ISSUE TITLE
prioritize software with expiring authorizations - due 12/18

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#220]
[Software by ATO expiration date](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=0&fvid=297851286)

## User stories

- As a member of the Security team, I want to spend time reviewing software that is the biggest need / highest risk.
- As [everyone], we want to ensure that TTS is using software that is authorized.
- As a member of TTS, I want to continue using the software that I need to do my job.

## TODOs

- [x] Update ATO expirations in spreadsheet
- [x] Figure out which of the expiring software can be deprecated (moving off to something else that _is_ approved, etc)
- [x] Create a prioritized list by need/risk and send to @boberlas
- [x] Set up a meeting with @boberlas, Tom (Eaton?), and Brian Turnau

**Comment by its-a-lisa** [comment]
Just sent Bo the prioritized [list](https://docs.google.com/document/d/1J4jrcbuTpL2r0gIFg1cEebdP1L3UBaVe/edit) and Aidan requested that instead of having meetings we do it asynchronously.
