### ISSUE TITLE
clarify the team workflow

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#221]
Reading the [Project Board](https://github.com/18F/tts-tech-portfolio/blob/master/ProjectBoard.md) doc for the first time, I had these questions/fixes:

- What are we doing with standups?
- Title typo
- “no designated person responsible for any one piece of work” - is that still true with epics?
- Sprint review - should we invite stakeholders? Should we use the infra meeting?
- Link to cybersecurity framework
- “assign yourself to it before it gets to the ready column” - this is a change, yes?
- Card template - move to issue template
- Do we explicitly write a definition of done?
- should we put exit criteria in the board?
- Is there really a difference between Grooming and Ready?
- “Backlog/Ready” and also a Ready?

**Comment by afeld** [comment]
- prioritize epics first, then order cards in the Ready column
- Sprint planning:
    - look at calendars, emails, and meeting minutes to make sure everything is reflected
    - nothing left in New Issues
    - Enforce WIP limits
    - Nothing goes into Ready without label, assignment, and acceptance criteria
- Prioritization is moving things from Icebox to Backlog
- Cards get created with acceptance criteria; during grooming, team reviews
- Recurring meeting for board grooming
- Epic owner?
- What columns are ordered/prioritized?
- What’s the difference between Waiting and Blocked?

**Comment by afeld** [comment]
@its-a-lisa offered to schedule a meeting to all work through this together.

**Comment by afeld** [comment]
More items:

- Deadlines
- Swimlanes
- Singular vs group work
- Regular board grooming meeting - #231 
- What time of day standups are

**Comment by its-a-lisa** [comment]
@afeld @JJediny -- would you both be OK if we converted the biweekly Infrastructure Sync meeting into our Review ceremony? Would still be awesome to have the other folks that regularly attend the Infrastructure meeting to still attend, but this be more codified as a review ceremony and figure we could also incorporate to Communicate Success and Achievements https://github.com/18F/tts-tech-portfolio/issues/243 as well

**Comment by afeld** [comment]
Looking at every issue _might_ be a bit too in-the-weeds for folks outside our team, but certainly happy to try it!

**Comment by its-a-lisa** [comment]
## Made some updates:
> What are we doing with standups?

> Title typo

> “Backlog/Ready” and also a Ready?

## Notes:

> “assign yourself to it before it gets to the ready column” - this is a change, yes?

Yes, it is a change. It is a result from the meeting me and @JJediny had with @abrouilette . This helps with understanding who is doing what for planning and for coworking purposes. 

> Do we explicitly write a definition of done?

I think the thought is that we have a DoD that is defined at an overall level so when we are creating acceptance criteria for each card, we have keep the definition in mind. 

>should we put exit criteria in the board?

@afeld I'm not exactly sure I know what you mean... Like a notecard explaining what the exit criteria for each of the columns are? 

>Is there really a difference between Grooming and Ready?

Yes, I think there is. But not so much that there needs to be a different column for it. We are going to handle this using labels instead.

> What’s the difference between Waiting and Blocked?

Overcome by events, these . columns got merged in a previous meeting. 

> What time of day standups are

Moved these to 12:30 EST daily

## Items to still discuss:
> “no designated person responsible for any one piece of work” - is that still true with epics?

>Prioritization is moving things from Icebox to Backlog

>Cards get created with acceptance criteria; during grooming, team reviews

>Deadlines

> Swimlanes

> Singular vs group work

## Further Action Items:
> Link to cybersecurity framework 

- [ ] @JJediny will you link to the CSF in the label description?

> Card template - move to issue template

- [ ]@afeld will you do this?

>Recurring meeting for board grooming

>Regular board grooming meeting - #231

- [ ] @its-a-lisa will book this meeting

- [ ] Need to update labels section in  https://github.com/18F/tts-tech-portfolio/edit/master/ProjectBoard.md

**Comment by afeld** [comment]
I think we talked about most of this during our meeting today. Created separate issues for a couple:

- Swimlanes: https://github.com/18F/tts-tech-portfolio/issues/257
- Issue template: https://github.com/18F/tts-tech-portfolio/issues/256

For a couple others:

- Deadlines
- Singular vs. group work

I suggest we don't worry about them until they come up again.

> > should we put exit criteria in the board?
>
> a notecard explaining what the exit criteria for each of the columns are?

Yep, that's what I was thinking, just to keep the content close to the place where it's used. Just an idea.

**Comment by afeld** [comment]
I suggest we close this issue and open up more focused ones as needed.
