### ISSUE TITLE
share out about FSGC vote

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#230]
Follow-up to #217. @its-a-lisa pointed out that it may be useful to share some info about how I voted and my rationale for doing so with TTS.

Include:

- [ ] Items that were voted on and TTS' vote
- [ ] Info about the agile budgeting presentation - https://github.com/18F/tts-tech-portfolio/issues/232
- [ ] [Info about upcoming Concept submissions](https://docs.google.com/presentation/d/1yVXeox7vWyiROB3v8wpcAinc0AEoIgG9LNfAgFp3uLI/edit?ts=5e3460bd), due 2/21

**Comment by its-a-lisa** [comment]
this [presentation](https://docs.google.com/presentation/d/1uOuzFibFCvgW3I0XL54w2sKl7ObSBxk9cUlyTchJ8Gk/edit#slide=id.g57d5603040_0_23) seems to have some good nuggets to build off of

**Comment by afeld** [comment]
Talked about it in a few channels, and a bit late for it to be relevant anymore.
