### ISSUE TITLE
propose changes around the FSGC - due 1/28

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#232]
## User stories

- As a member of the FSGC, I want to ensure I am spending taxpayer dollars responsibly.
- As a member of the FSGC, I want to maximize success of FAS IT projects.

## Implementation

- [x] Submit travel request
- [x] Book travel
- [x] Travel approved
- [x] First draft of slides created
- [x] Get feedback on slides from TTS
- [x] Send slides to FGSC leads first thing 1/27
- [x] Prepare props
- [x] Present to FSGC

## Acceptance criteria

- [x] Problems with the current model are clearly identified
- [x] Clear, actionable solutions are proposed
- [x] @dsalegov and the Tech Portfolio feel comfortable with the above

**Comment by afeld** [comment]
Email from Jeremy Hayes:

> As we are preparing for the January FSGC meeting, we wanted to reach out to you to gauge your interest in presenting your ideas for potential improvements to the FSGC. Would you have the time to pull together your ideas for this month's meeting [on 1/28]?

I have a 30-minute time slot (including discussion) where I'll present this.

**Comment by afeld** [comment]
[Slides](https://docs.google.com/presentation/d/1i12jT_imlAvGFndwDCBwo1AuKtcmUCQ3gTOqGgUjxsc/edit)

**Comment by afeld** [comment]
Done! Well received.
