### ISSUE TITLE
Pursue acquiring cloud-sync design tool

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#233]
## Background information

There is a growing demand for tools that allow direct collaboration with partners and teammates. In general the tools mentioned fall into three categories: designing interfaces, prototyping, and sharing work with collaborators

https://github.com/18F/tts-tech-portfolio/issues/165
## User stories

- As a someone that manages TTS wide requirements, I would like to initiate the process for acquiring the tool

## Implementation

- [x] Radiate intent to pursue specific option
  - [ ] Ensure whatever tool is chosen would meet user needs
- [x] Link up with AcqStack to understand next steps

## Acceptance criteria

- Whatever paperwork that needs to be process has been submitted

**Comment by afeld** [comment]
- [ ] Update title with deadline.

**Comment by its-a-lisa** [comment]
Folks are aware of what we're doing. 
Spoke with acquisition today, @melanienleopold & @stephencarroll 
Waiting to hear back from one user to make sure their needs are met; will close out once they agree.

**Comment by its-a-lisa** [comment]
Sent out the notes on what was [decided](https://groups.google.com/a/gsa.gov/forum/#!searchin/devops/cloud$20sync%7Csort:date/devops/7_MLJDY_rQI/niYOvAHOBwAJ). 

Closing based on no further action for this activity
