### ISSUE TITLE
create `prep step` issues from icebox/backlog issues

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#234]
As a team performing sprint planning and grooming; we should ensure we dedicate a portion of the time to break out preparation tasks to ensure issues are ready to be worked when appropriate. 

E.g. a proactive issue to perform a small/short engagement and communication (email/meeting/outline/etc) to obtain guidance and understanding around an issue / to get a head of a long lead issue and direction.

#### Acceptance Criteria:
- [x] create an established label - https://github.com/18F/tts-tech-portfolio/labels/prep%20step
- [ ] Update sprint/grooming documentation
- [ ] Complete https://github.com/18F/tts-tech-portfolio/issues/222

**Comment by afeld** [comment]
We can break out smaller issues on a per-issue basis; closing this as not actionable right now.
