### ISSUE TITLE
Create Directory of contacts

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#235]
## User Story:
As a team member for Tech Portfolio customer success managers reach out to individuals; would like the capture the contacts information in a centralized manner
## Problem Statement: 
Without a centralized place to keep track of external contacts who get in touch with individuals in the Tech Portfolio, information gets lost.
## Actions to take:  
- [ ] Start with creating a local document in team repository
  - [ ] Decide if this will be housed on Google Docs or GitHub repo
- [ ] Procedures for keeping directory up to date
- [ ] Populate with all currently known information
- [ ] Create a list of further information that is needed

## Acceptance criteria: 
- [ ] All current and known information is documented
- [ ] New issue is created to capture next steps
   - [ ] Investigate to see if there is a tool

## Related Issues:

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/87.
