### ISSUE TITLE
Personnel Descriptions

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#237]
## User Story:
As someone in the Tech Portfolio, I can help write up a project description
As someone who manages staff in TTS, I might have folks who have extra time to support other teams on a as-needed basis
## Problem Statement: 
We know we're understaffed, but haven't detailed what staffing areas need help. 
## Background information: 
When I saw Alan in the office, he mentioned that if there was extra help from folks int he office, would be able to utilize them?
## Actions to take:  
- [ ] Explain ask to team
- [ ] Solicit suggestions for gaps/needs
- [ ] Write up description of personnel needs
- [ ] Provide a 'first pass' to @abrouilette to see if that is what he was looking for
## Acceptance criteria: 

- [ ] All members of the team have reviewed document
- [ ] 'Demo-ed' at TTS Tech Portfolio Review Ceremony

## Related Issues: 

#193 https://github.com/18F/tts-tech-portfolio/issues/85

**Comment by its-a-lisa** [comment]
closing as stale
