### ISSUE TITLE
US Web Design System - ATO recommendation

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#241]
## User Story:
As a System Owner of USWDS going through a business change,  I would like to seek advice on cybersecurity path forward. 

## Background information: 
USWDS approached TTS Tech Portfolio to seek advice on what level of assessment and authorization is necessary for their deployable code that other federal agencies use. 

## Actions to take:  
- [x] Finalize recommendation slides
- [x] Provide USWDS with POA&M template
## Acceptance criteria: 
- [x] USWDS feels satisfied with their Cybersecurity Approach
## Supporting Documentation:
https://docs.google.com/presentation/d/1JWDINpK3MeV_bXfEkofuZ-o7ob4fYtn556KOXuaJDOA/edit#slide=id.g5ecdbbee9e_0_34 
## Related Issues:

**Comment by its-a-lisa** [comment]
@afeijoo & @thisisdano -- believe I've gotten the briefing to a point that is a good representation of what we're trying to accomplish

As far for the template for the POA&M, the GSA IT one is access controlled; but contains elements of (i) the tasks to be accomplished; (ii) the resources required to accomplish the tasks; (iii) any milestones in meeting the tasks; and (iv) scheduled completion dates for the milestones.

If you're looking for _any_ POA&M template -- the [FedRAMP POA&M template](https://www.fedramp.gov/assets/resources/templates/FedRAMP-POAM-Template.xlsm) should do the job. 

i'm moving this card to waiting/blocked until we meet on Friday

**Comment by its-a-lisa** [comment]
Met with US Web Design system and helped prioritize the next steps and advice; advised that if they need further in-depth assistance to fill out the [TTS Tech Portfolio general request form](https://forms.gle/FmCvJHNGYbWbGEFE7) and we'll prioritize it amongst the other work.
