### ISSUE TITLE
FedRAMP Agency Sponsor - TTS tasks

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#242]
## Background information
There are several tools that are essential to the business operations of the TTS team. The TTS team has offered to be the federal agency sponsors for Cloud Service Providers wishing to go through the FedRAMP Tailored process. 

https://github.com/18F/handbook/issues/1662

## User stories

As someone working in the Tech Portfolio, I want to know what role we play in the FedRAMP process when we agree to be the Agency sponsor

As s the Tech Portfolio and GSA IT, I want to know what FedRAMP cloud offerings are going to be handled in the first half of FY20

As the Tech Portfolio, I want to know where the money and people sponsoring FedRAMP packages are coming from. 

## Implementation
- [x] Add column to Software Inventory sheet to indicate whether TTS is sponsoring. 
- [x] Have meeting with GSA IT to discuss upcoming FedRAMP packages
- [x] Make sure the handbook is updated to link to the sheet that describes the cost of sponsoring
- [ ] GSA IT extends ATOs
- [x] Figure out what is required, beyond money to sponsor a CSP as an agency
- [ ] Contact the GSA IT team to understand their internal process for what process, procedures and techniques for when they perform the role of a sponsoring agency. 
   - [x] Determine if there is a cost reduction if TTS provides a body to do the activities listed in the spreadsheet

## Acceptance criteria
 - Both GSA IT and TTS  have a mutual understanding about
   - What offerings TTS will be sponsoring
   - What responsibility TTS has when they agree to sponsor
        - Time
        - Money
        - Expertise
 - Handbook documentation is updated

**Comment by its-a-lisa** [comment]
Made some significant progress on this task today -- completed a few of the tasks -- provided clarification on acceptance criteria in the [meeting notes](https://docs.google.com/document/d/12acZMCU1vC8eqhQjAurlzumvbJoelHzZWYZGN9o9rvE/edit#bookmark=id.tzcfykayu2pp)

**Comment by its-a-lisa** [comment]
The  following tasks will be addressed in the https://github.com/18F/tts-tech-portfolio/issues/267 

- GSA IT extends ATOs
- Contact the GSA IT team to understand their internal process for what process, procedures and techniques for when they perform the role of a sponsoring agency.

Recommend closing this task once https://github.com/18F/handbook/pull/1769 is merged

**Comment by its-a-lisa** [comment]
18F/handbook#1769 is merged so closing this issue

**Comment by its-a-lisa** [comment]
Contact the GSA IT team to understand their internal process for what process, procedures and techniques for when they perform the role of a sponsoring agency.

Not going to get accomplished in #267 because the process is likely to change and will happen after LiSaaS gets ironed out
