### ISSUE TITLE
Communicate TTS Tech Portfolio Success and Accomplishments

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#243]
## Background information
Purpose:

Need to better communicate the activities of TTS Tech Portfolio.  Need to assure that others are aware of what we're doing and we're telling our story. 

The traditional approach to comms is to do a lot of planning up front. Many teams will embark on a “comms strategy”, or perhaps write a set of “comms principles”, and then set about filling a calendar or grid with expected messages at expected times. Most of these are unnecessary when doing comms for agile work and agile teams.

Reference: [A guide to agile communication](https://defradigital.blog.gov.uk/a-guide-to-agile-communication/)

## User stories

As a person planning communications activity on behalf of agile teams, I would like to know what others think. 

As a person doing the communications activity (especially blogging, presenting, or filmmaking)I would like to have a better idea what I should do. 

As a person who manage the people described above, who want to understand what they're doing and why. 

## Implementation

- [ ] Discuss internally what our objectives and goals for communicating are
- [ ] Develop 'survey' to get feedback from our customers on what they'd like to see us communicate
  - [ ] Get feedback from TTS Tech Portfolio members on survey
  - [ ] Send survey to TTS
- [ ] Decide _how_ we want to communicate
- [ ] Decide _how frequently_ we want to communicate

## Acceptance criteria

- Tasks above are complete and we have taken a small step forward for communicating
   - Next task should be developing responsibility and linking back to this task

**Comment by afeld** [comment]
I believe this is unblocked; moving to Backlog.

**Comment by afeld** [comment]
Doesn't seem to be a major pain point right now, so closing.

**Comment by afeld** [comment]
For the new Business Weekly meeting structure, I am sharing updates with @HuixianXu to share with TTS Leadership. ([Last week's.](https://gsa-tts.slack.com/files/T025AQGAN/F012JKQ9HRU?origin_team=T025AQGAN)) That's a specific audience, but is part of the larger communication picture.

**Comment by afeld** [comment]
Idea from @its-a-lisa about [using a Lean Coffee format for the Sprint Review](https://gsa-tts.slack.com/archives/CNW3GL70S/p1588260768309300).
