### ISSUE TITLE
Develop Process to Investigate new tools and technologies

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#244]
## Background information
There are new technologies, tools, etc that come to my attention either through emails, conferences, other people's suggestions, etc -- and I think they might have value in our inventory now or later -- but I am unsure if looking into them would be valuable or if I do consider them valuable -- what to do with that evaluation. 

As of right now, the only guidance there is for when someone wants to use a new tool or technology is to submit a request to IT Standards. This isn't the best route because it bypasses the Tech Portfolio and we lose sight on what is being requested, if something is similar to another thing or if there is budget for the request. 

This differs from https://github.com/18F/tts-tech-portfolio/issues/339 because that is more about analyzing a requirement once one exist; where this is proposing an idea for something to become a requirement in the first place. 

## User stories

- As someone in the Tech Portfolio who has a good idea, I would like to be able to explore that good idea in a structured way. 

- As someone in the Tech Portfolio who thinks a tool would be useful TTS wide, I don't have a way of knowing if that tool has already been proposed and what the result of that proposal was.

- As someone in the Tech Portfolio who plans on looking into a new tool, I would like a way to communicate the activity with other team members. 

- As someone in the Tech Portfolio who thinks of a way of improving the organization through the use of a tool, I would like to know where that falls within the priorities of the portfolio. 

## Implementation
- [ ] Develop framework (thinking concept, discovery, proposal (https://github.com/18F/tts-tech-portfolio/issues/339), decision, prototype, deploy)
   -  [ ] determine how the Emerging Technology office in OGP fits in
   -  [ ] consider vendor pitch days

## Acceptance criteria: 
- There is a structured way for members of the Tech Portfolio to present ideas and for them to get prioritized within our workload and a record is kept for historical reference

**Comment by afeld** [comment]
https://handbook.18f.gov/software/ speaks to this somewhat.

**Comment by its-a-lisa** [comment]
Thinking of more like something like this https://github.com/18F/tts-tech-portfolio/issues/88#issuecomment-581964848 and it ties into https://github.com/18F/tts-tech-portfolio/issues/339 as well

**Comment by its-a-lisa** [comment]
closing as a result of today's Grooming session in favor of the future one created to address this problem
