### ISSUE TITLE
Investigate dynamic security analysis tools (dependency vulnerabilities)

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#245]
## Background information

-Came across the tool "LGTM" and curious if or how it would be incorporated into our inventory. 
-Unsure of how this relates to Synk or GitHub security

## User stories

As someone responsible for security within the TTS Tech Portfolio, I want to assure that we are doing the most to automate it and that we're using the latest tools.

As someone writing code, I would like to make sure bugs never make it into my project. 

## Implementation

- [ ] inquiry about whether LGTM is now covered under GitHub's existing ATO
- [ ] Determine the relationship between Code Climate & LGTM
- [ ] Update [Before You Ship page](https://before-you-ship.18f.gov/security/static-analysis/)
- [ ] Deploy LGTM

## Acceptance criteria

- LGTM is deployed

**Comment by its-a-lisa** [comment]
> <@UNVTHAJBA> looks like <http://LGTM.com|LGTM.com> has been bought by github - <https://github.blog/2019-09-18-github-welcomes-semmle/> . So like dependabot/actions maybe we should inquiry about whether that's now covered under their existing ATO?
<sub>[View in Slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1577723177059200)</sub>

**Comment by pburkholder** [comment]
Oops, I may have duplicated this in #331

**Comment by its-a-lisa** [comment]
close in favor of #403 and #331
