### ISSUE TITLE
Create a standard around Slack channel topics

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#249]
## Background information

Closing previous issue /before-you-ship/issues/190 that had a task "Work with relevant channel owners to clarify the "topic" and "purpose" text of the #infrastructure and #compliance channels." -- I believe the clarity is needed for ALL channels, not just those two channels and the requirement to have the topic and purpose of each channel should exist for all. 

https://github.com/18F/before-you-ship/issues/190

## User stories
As a user of slack, i would like to know who to talk to about a specific channel. 
As someone responsible for content in slack channels, I want to make sure that everyone in slack has is cleared to see the information.
As someone responsible for administering slack, I want to make sure there are proper signage in the channels so people know what to post in what channels. 

## Implementation

- [ ] All channels have updated the topic
  - [ ] All topics include statement in regards to NDA (ref: https://github.com/18F/tts-tech-portfolio/issues/141)
- [ ] All channels have designated a channel owner
- [ ] Add channel ownership transfer to offboarding list
- [ ] Add/create/update information to a canonical place in regards to these process and procedures

## Acceptance criteria

- Steps have taken place so slack is better managed

**Comment by its-a-lisa** [comment]
https://gsa-tts.slack.com/archives/C02KW46DP/p1584457624103800

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
