### ISSUE TITLE
Develop a TTS Information Security Continuous Monitoring (ISCM) Program

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#261]
## User Story:
- As a system owner, I don't want to have to have my ATO reauthorized every 3 years or sooner. 
- As the TTS Tech Portfolio, I want to set organizational, Tier 2, requirements for systems under our mission area to be granted a continuous ATO
## Background information: 
TTS should monitor security metrics and assesses security control effectiveness with
established monitoring and assessment frequencies and status reports customized to support TTS specific decision making. 

## Actions to take:  
- [ ] Review GSA Continuous Security Documentation
   - [ ] [GSA ISCM Enterprise Management Tools](https://docs.google.com/spreadsheets/d/1M_eZqPO5oc5YcJacidyxVCMPCzGKDoEwBNZRnU0IjGY/edit#gid=941618463)
   - [ ] [ISCM_Plan_Template_10-06-2017](https://docs.google.com/document/d/190BSsxuabuu08sVZbkHyWfPN-4Nejp6EXno0KntBM9M/edit)
- [ ] Engage with GSA IT Security
   - [ ] Conduct discovery to determine if there are any other Tier 2 ISCM strategies

## Acceptance criteria: 
- [ ] TTS Continuous Monitoring Strategy exists
- [ ] TTS Continuous Monitoring Strategy reviewed
- [ ] TTS Continuous Monitoring Strategy signed
- [ ] TTS Continuous Monitoring Strategy shared

## Supporting Documentation:
- [GSA Continuous Monitoring Strategy CIO_IT_12-66_Rev_2  10-10-2017](https://insite.gsa.gov/cdnstatic/insite/Continuous_Monitoring_Strategy_%5BCIO_IT_12-66_Rev_2%5D_10-10-2017.docx)
- [NIST SP 800-137 Information Security Continuous Monitoring (ISCM) for Federal Information Systems and Organizations](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-137.pdf)
-  [FedRAMP CSP Continuous Monitoring Strategy Guide](https://www.fedramp.gov/assets/resources/documents/CSP_Continuous_Monitoring_Strategy_Guide.pdf)
## Related Issues:

**Comment by its-a-lisa** [comment]
@JJediny should we consolidate the card you opened https://github.com/18F/tts-tech-portfolio/issues/380 with this card?

**Comment by JJediny** [comment]
Google drive folder referenced in the issue closed ^ should still be consulted

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
