### ISSUE TITLE
Outline TTS Tech Portfolio Roles and Responsibilities

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#262]
## User Story:
As a member of TTS Tech Portfolio, I want to know what I'm responsible for and what other team members are responsible for. 

As a member of TTS Tech Portfolio, there are certain roles that need to be assigned to certain individuals as primary or alternates. 

As a stakeholder of the Tech Portfolio, I would like to know who to direct certain questions to. 

## Problem Statement: 
Without roles and responsibilities, it is hard to understand what is going on and who is doing what and if everything is getting done and by whom it is getting done by. 

## Background information: 
During any discussion of roles and responsibilities, team members need to clearly know their specific tasks and the areas for which they will be held accountable. Everyone in the team should also know what everyone else is responsible for. This will build strength and mutual support.

## Actions to take:  
- [x] Initiate meeting to discuss
- [x] Start a Google Sheet document
- [x] @afeld fill in priorities
- [ ] @JJediny fill in priorities

## Acceptance criteria: 
- [ ] All team member's roles and responsibilities are documented

## Supporting Documentation:
[The Employee's Role in a Team](https://www.opm.gov/policy-data-oversight/performance-management/reference-materials/historical/the-employees-role-in-a-team/)

## Related Issues: 

#237 https://github.com/18F/tts-tech-portfolio/issues/257

**Comment by afeld** [comment]
cc https://github.com/18F/tts-tech-portfolio/issues/237

**Comment by its-a-lisa** [comment]
Google sheet: [link](https://docs.google.com/spreadsheets/d/1wfBeLc64ub0nVXQXFG7h_eEXyOEoHV0v7uYnN5Gp6sw/edit?usp=sharing)

**Comment by afeld** [comment]
[List of our existing (formal/titled) roles.](https://docs.google.com/document/d/1GF4BR9X5lhOJq2j_sMDgzdqrl_WsgGadgnFlsstsIJk/edit#heading=h.h12azldxejuu)

**Comment by afeld** [comment]
Just clarified in the meeting that we're keeping this issue scoped to documenting the current state.

**Comment by afeld** [comment]
Do we feel ok calling this "done enough for now", based on [our documented roles](https://github.com/18F/tts-tech-portfolio/blob/master/roles.md)?

**Comment by its-a-lisa** [comment]
Yup, closing
