### ISSUE TITLE
Develop a System Maintenance Policy

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#263]
## Problem Statement: 
If someone who does not typically have access to the system performs maintenance, then a security vulnerability is introduced.
## Background information: 
System maintenance requires either physical or logical access to the system. Support and operations staff, hardware or software vendors, or third-party service providers may maintain a system. Maintenance may be performed on-site or remotely via communications connections. It may also be necessary to move equipment to a repair site for maintenance. 
## Actions to take:  
- [ ] Document organizational requirements of maintenance and repairs on components 
- [ ] Document process for components  that require maintenance or repairs
- [ ] Document procedure for components  that require maintenance or repairs
- [ ] Create repository to maintain records for the information system to include the:
    -  Date and time of information system security maintenance;
    -  Name of the individual performing the information system security maintenance;
    -  Name of escort, if necessary;
    -  Description of the information system security maintenance performed; and
    -  List of equipment removed or replaced (including identification numbers, if applicable).
- [ ] Approve organizational requirements of maintenance and repairs on components

## Acceptance criteria: 
- [ ] System Maintenance Policy exists
- [ ] System Maintenance Policy has been reviewed
- [ ] System Maintenance Policy has been signed
- [ ] System Maintenance Policy has been shared

## Related Issues: 

https://github.com/18F/tts-tech-portfolio/issues/193

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
