### ISSUE TITLE
Initiate planning activities for a TTS COOP document

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#264]
## User Story:
As a TTS System Owner who is responsible for contingency planning, I want a document that focuses on continuity. 

As TTS Tech Portfolio that provides common controls and organizational wide technology and services, I want to make sure that those are available as needed. 

## Background information: 
 A formal policy provides the authority and guidance necessary to develop an effective contingency plan. 

Because there is an inherent relationship between an information system and the
mission/business process it supports, there must be coordination between each plan during development and updates to ensure that recovery strategies and supporting resources neither negate each other nor duplicate efforts. 

Focus:
- _Continuity planning_ normally applies to the mission/business itself; it concerns the ability to continue critical functions and processes during and after an emergency event. 

Other information:
- _Contingency planning_ normally applies to information systems, and provides the steps needed to recover the operation of all or part of designated information systems at an existing or new location in an emergency. 
- _Cyber Incident Response Planning_ is a type of plan that normally focuses on detection, response, and recovery to a computer security incident or event. 

## Actions to take:  

- [ ] Check with Marshall Brown about what exists and what is missing
Things we need for login.gov and cloud.gov programs, to ensure that an emergency operations plan contains the following:
    - [ ] A plan to either continue or reestablish operations within 12 hours of the incident (the operation should be sustainable for up to 30 days)
    - [ ] A plan to includes the ability to devolve from its primary location to a backup location (including consideration of technical and human resource requirements)
    - [ ] Consideration of redundancy; there should be at least one backup in a region outside of the incident location
    - [ ] The plan must consider how the program would transfer authority, any necessary process changes to relocate operations including resource requirements, and how that “devolved” operation might look.
    - [ ] If there are any risks that may need to be mitigated, that might be something to 
consider.

## Acceptance criteria: 
- [ ] TTS COOP Strategy exists
- [ ] TTS COOP Strategy reviewed
- [ ] TTS COOP Strategy signed
- [ ] TTS COOP Strategy shared
## Supporting Documentation:

- [Contingency Plan (CP) CIO IT Security 06-29 Rev 4 ](https://insite.gsa.gov/cdnstatic/insite/Contingency_Planning_%28CP%29_%5BCIO_IT_Security_06-29_Rev_4%5D_04-12-2018.docx)

- [Contingency Planning Guide for Federal Information Systems](https://doi.org/10.6028/NIST.SP.800-34r1)

- [Furlough Planning - Staffing and Activity Requirements - Tech Portfolio](https://docs.google.com/document/d/1WVBdRAKgeLSwx7QgbDXZuNYBZAd0sMlsK3fLHLIRtY0/edit?ts=5dd577cc)

- [ ORDERLY SHUTDOWN: Final Furlough Notes](https://groups.google.com/a/gsa.gov/forum/?utm_medium=email&utm_source=footer#!msg/devops/TQEyFAn26B0/K405kdQYAwAJ)
## Related Issues:

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/416. The documents exist, but just need some better organization.
