### ISSUE TITLE
Update TTS Incident Response documentation

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#265]
## User Story:
As a System Owner within TTS, I want a TTS organizational level document that I can refer to while responding to an incident. 
As a System Owner, I feel that the having the information organized in a workflow diagram would better help understanding of the steps that need to be carried out. 
## Problem Statement: 
There is currently information in the TTS Handbook on how to respond to incidents but systems also have their own plan. These plans all have different information and have information that would be better contained at the higher level so their plans only have to focus on the items that re specific to their systems. 
## Background information: 
TTS System Owners would like an Organizational level document to inherit from. And for there to be a consolidated approach. 
## Actions to take:  
- [x] Create skeleton Incident Response Workflow
- [x] Add information to skeleton
- [x] Get workflow to a solid initial version
- [x] Initial version is reviewed by others
- [ ] For reports that are out of scope, check the [security contact emails](https://github.com/GSA/data/blob/master/dotgov-domains/current-full.csv) to see if we can pass along

## Acceptance criteria: 
- [x] Initial version is accepted by others

## Supporting Documentation:
[Meeting Minutes: TTS Organizational Documentation - IR & COOP ](https://docs.google.com/document/d/1VvazOud-Cuc1CZbhqoNaSGL2pm_6CvXZiELkxME4a44/edit)

[Mural - Incident Response Workflow](https://app.mural.co/t/gsa6/m/gsa6/1578454101053/2be4f2baba395ba881353094f668cd4ef22559b8)
## Related Issues: 
https://github.com/18F/tts-tech-portfolio/issues/77

**Comment by its-a-lisa** [comment]
Moving to waiting/block because the skeleton Incident Response Workflow has been completed and [documented in a Mural](https://app.mural.co/t/gsa6/m/gsa6/1578454101053/2be4f2baba395ba881353094f668cd4ef22559b8) and next step is to get other feedback and support from system folks.

**Comment by its-a-lisa** [comment]
Effort related to getting the initial work started here is complete, will carry on the work over at https://github.com/18F/tts-tech-portfolio/issues/341

Planned implementation steps: 

- [ ] update documents with lessons from initial activity
- [ ] get feedback from folks who recently responded to incidents
- [ ] continue next steps for workflow, filling in the blanks
   - [ ] COOP
   - [ ] TTS level
- [ ] investigate whether using the mural board and creating GitHub issues from the board is a feasible activity

Decided one of the tasks wasn't a good fit for this issue and created a new one at https://github.com/18F/vulnerability-disclosure-policy/issues/52
