### ISSUE TITLE
Explore official AO backup designation

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#266]
## User Story:
As someone in TTS with Cybersecurity/Compliance/ATO responsibilities, I need access to information and in order to do that, I need to be in an IT Security role.
##  Background information: 
 The current roles (System Owner, PM, ISSM, ISSO) -- don't match or align with the role that I'm filling. 
## Actions to take:  
- [x] @afeld  to facilitate a AO (backup) letter for you.
  - [x] Template is found
  - [x] Letter is filled out
  - [x] Letter is sent to the signature authority
  - [x] Letter is signed
## Acceptance criteria: 
- [x] Alyssa has access to IT Security information

**Comment by its-a-lisa** [comment]
Spoke with ISP about this on 12/31 and they're aware of what we're trying to do and the background information.

**Comment by afeld** [comment]
Per email from Blanche Heard (`Re: FY19 POA&M Template_v4.1_11-07-2018 - Request for access`), there is such a thing as an "a AO (backup) letter." Asked for the link.

**Comment by afeld** [comment]
@its-a-lisa I started to edit the AO Designation letter to speak to a Backup role. I haven't seen that role before, and I'm not sure that it's been done at TTS. I think you have a clearer picture of how this would work than I do—game to take a crack at it (via suggested edits)?

https://docs.google.com/document/d/1t2AQF-5CwVQ-TB7k0nelTg4CESq2BSI_voh6IuYg-Ls/edit

**Comment by afeld** [comment]
On second thought, asked Blanche to help us fill out the template to ensure it's done in the way they are looking for.

**Comment by afeld** [comment]
Sent signed letter. Unclear what steps remain on Security's side, but I think our steps are done.
