### ISSUE TITLE
Identify ATO pathways for cloud offerings as pilots - due 1/24

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#267]
## Background information

Part of #186.

Work with GSA IT Security to go through our current software and propose what should stay in LiSaaS (1 year vs 3 year) or FedRAMP Tailored. 

## User stories

As TTS Tech Portfolio, I want to make sure that we aren't doing things just because thats how it is always been done. 

As TTS Tech Portfolio, I may want to use an offering that might not meet the letter of the law, but think there should be a policy update in order to allow certain types of things like it.

As GSA IT Security, I would like to allow TTS to experiment and do things that are outside of current policy, but I would like it to happen in a control and approved manner. 

## Implementation

- [x] Meet with GSA IT Security on 1/13
- [x] Brainstorm and add other SaaS that should be in this spreadsheet and include
- [x] Identify what software belongs to which categories
- [x] Send to security and get next steps

## Acceptance criteria

- [ ] Provide update to team on what pilots we are going to do going forward
- [ ] Mutual decision between GSA IT Security & TTS on what pilots for FY2020
- [ ] Create new issue for decision making matrix and help develop new policy

**Comment by afeld** [comment]
Let's reframe as the problem we are trying to solve, or a discovery around TTS's security needs/gaps, etc.

**Comment by afeld** [comment]
This is a follow-up task to "figure out how software approvals work." [TODO link]

**Comment by its-a-lisa** [comment]
Per the [TTS Tech Portfolio Review on 1/23](https://docs.google.com/document/d/1G03trzrQez5BupOLfuZUJy-boooc1Z9oYj21LYTw4cs/edit?disco=AAAAEIOd5K8) -- there was feedback that folx in the organization would like greater feedback. 

- [ ] Chat with @afeld to understand context
- [ ] Get with POC who made statement to understand what communication is currently lacking and what they would like to know, what frequency and what medium
- [ ] Groom card to include step to provide feedback

**Comment by its-a-lisa** [comment]
- [x] Provide update to team on what ~pilots~ SaaS we are going to do going forward
https://docs.google.com/document/d/1UzM57r06O1LYmFy1U4Dta3TzkCxpfgGU8q0oK4I4cUI/edit#
- [x] Mutual decision between GSA IT Security & TTS on what ~pilots~ SaaS for FY2020
- https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=0&fvid=165684251
- [x]  Create new issue for decision making matrix and help develop new policy
  https://github.com/18F/tts-tech-portfolio/issues/186

Also, although the exact steps from the [updates to the card](https://github.com/18F/tts-tech-portfolio/issues/267#issuecomment-578754284) were not followed to a T, we did sent out a [very well received communication ](https://gsa-tts.slack.com/archives/C039MHHF8/p1580767478129600) and appreciated the feedback and will try to do better in the future
