### ISSUE TITLE
upgrade GitHub

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#271]
## Background information

There is a push (from whom, not entirely clear) to:

- Upgrade our GitHub organizations from legacy plans (based on private repositories) to [Enterprise Cloud](https://help.github.com/en/github/getting-started-with-github/githubs-products#github-enterprise)
   - This is because [only the Enterprise Cloud plan is FedRAMP'd](https://marketplace.fedramp.gov/#/product/github-enterprise-cloud?sort=productName&productNameSearch=github), despite being (as I understand it) the same product with some extra features
   - For @18F, this would be a cost increase of ~23x
- Consolidate billing under the GSA Microsoft Enterprise Agreement
   - This would help us avoid the micropurchase threshold

## User stories	

- As someone responsible for the compliance of TTS GitHub, I want to use the FedRAMP'd option to make the compliance easier.
- As someone responsible for GitHub billing, I want to ensure we stay under the micropurchase threshold.

## Implementation	

- [x] Determine how the administration across repositories would work - [notes from 12/16/19 meeting](https://docs.google.com/document/d/15p6UfCGKYtMc9yD9aFnFdCK6Gmhk6cwRNqryTcYKwss/edit)
- [ ] Determine if this is a hard requirement
- [ ] Determine the upgrade/consolidation path

## Acceptance criteria	

- GitHub is upgraded and/or the billing is consolidated, or deemed unnecessary right now

**Comment by its-a-lisa** [comment]
@afeld with the upgrade, will there be an opportunity to potentially [recategorize GitHub?](https://gsa-tts.slack.com/archives/C052M2K07/p1582308122027200?thread_ts=1581560844.017500&cid=C052M2K07) I am not exactly sure how it is categorized now; but there have been a few instances of [non-availability](https://gsa-tts.slack.com/archives/C02KXM98G/p1582652122009800) within the last couple of weeks, which is fine if the system is categorized as low -- but based on how integrated the offering is within the work that TTS does, I think it should be categorized at Moderate

**Comment by afeld** [comment]
[GitHub is FedRAMP authorized for Moderate](https://marketplace.fedramp.gov/#/product/github-enterprise-cloud?sort=productName&productNameSearch=github), so I don't think paying for the upgrade would be enough.

**Comment by afeld** [comment]
We didn't capture any action items in the last meeting, and I couldn't remember what next steps were. Emailed the GSA IT folks to ask.

**Comment by JJediny** [comment]
The core requirement here is managing:
- https://github.com/18f
- https://github.com/cloudgov
- https://github.com/usagov
- https://github.com/presidential-innovation-fellows

Under a single top-level payer account.

**Comment by afeld** [comment]
That's one part of it, yeah. [Full list of TTS GitHub organizations.](https://handbook.tts.gsa.gov/github/#organizations)

**Comment by its-a-lisa** [comment]
How would this impact the actual users of the system? Do we have access to the GitHub FedRAMP package to see if there is any information there to help us understand this problem better? Would there be additional benefits/features of doing so? Would there be changes on the backend that we'd end up in a different region/physical location of our data or is this more of a billing change? Has anyone done a delta on what the different controls are between Enterprise and the version we're on now? Is this something that might be High Effort/Low Value now, but end up being High Value down the line? Are there consequences if we don't do this? Is this something we should take a step back on and think about differently?

**Comment by afeld** [comment]
> How would this impact the actual users of the system?

They likely wouldn't notice.

> Do we have access to the GitHub FedRAMP package to see if there is any information there to help us understand this problem better?

No, but we could request it.

> Would there be additional benefits/features of doing so?

https://help.github.com/en/github/getting-started-with-github/githubs-products#github-enterprise

> Would there be changes on the backend that we'd end up in a different region/physical location of our data or is this more of a billing change?

My understanding is the latter, plus some features enabled and greater guarantees on their end. (See link above.)

> Has anyone done a delta on what the different controls are between Enterprise and the version we're on now?

Not sure.

> Is this something that might be High Effort/Low Value now, but end up being High Value down the line?

Having single sign-on / [SCIM](https://developer.github.com/v3/scim/) and centralized billing would be nice.

> Are there consequences if we don't do this?

Theoretically we could be told to dramatically restrict our use or move off entirely, but no one has said that.

> Is this something we should take a step back on and think about differently?

Maybe! Open to ideas.

**Comment by afeld** [comment]
Have not heard anything, so closing for now.
