### ISSUE TITLE
Handbook blog post

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#281]
From an email:

> We take the Handbook even further and [have the content in GitHub](https://github.com/18F/handbook/tree/master/_pages), meaning [anyone (TTS staff or otherwise) can suggest changes directly](https://github.com/18F/handbook/blob/master/CONTRIBUTING.md), rather than having to go through a specific person. We have had [18 different people](https://github.com/18F/handbook/pulse/monthly) submit content changes in the past month, only four of whom are "owners" of the Handbook. This model, which was influenced by [C4](http://hintjens.com/blog:93), has been remarkably successful in reducing friction to updating content, and thus keeping it up-to-date.

## Implementation steps

- [ ] Plain language review from @AndreaSigz 
- [ ] Program alignment from @afeld
- [ ] TTS strategy and messaging review from @Dahianna

## Acceptance criteria

- [ ] Blog post published

**Comment by its-a-lisa-at-work** [comment]
@afeld you've had a lot of heavy work lately -- what about picking this up sooner rather than later to even things out?

**Comment by afeld** [comment]
The JAIC reached out to get advice about creating a Handbook to improve their onboarding experience. Might be a cool opportunity to co-author something with them if/as they get it stood up.

cc @CalvertSmith

**Comment by afeld** [comment]
[Message with some relevant points](https://gsa-tts.slack.com/archives/C0DCAMLQH/p1603372385014200?thread_ts=1603371365.012900&channel=C0DCAMLQH&message_ts=1603372385.014200)

**Comment by afeld** [comment]
Other examples of external groups being inspired by our Handbook:

- [Agency reaching out](https://gsa-tts.slack.com/archives/C01HY3A6U2C) about leveraging our Slack guidance
- [Company forking the Handbook for their own use](https://handbook.civicactions.com/en/latest/README/#acknowledgements)

**Comment by dylanirlbeck** [comment]
TODO: Read the Blogging guide.

**Comment by afeld** [comment]
https://github.com/18F/blog-drafts/issues/809
