### ISSUE TITLE
Update Tech Portfolio ProjectBoard.md doc

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#282]
## Background information

The TTS Tech Portfolio has initially laid out the workflow procedures in the document and now that the flow is being executed, there are some holes in understanding and documentation. 

supporting docs
[Tech Portfolio workflow proposal - 2020-01-03](https://docs.google.com/document/d/1GF4BR9X5lhOJq2j_sMDgzdqrl_WsgGadgnFlsstsIJk/edit#
)
## User stories

As a TTS Tech Portfolio member, i want to clearly understand what I am doing when I am running a ceremony

As a TTS Tech Portfolio member, I have a certain idea of how things should go and I want to provide those ideas to all. 

## Implementation
- [ ] clarify [priorities](https://github.com/18F/tts-tech-portfolio/issues/289) 
- [ ] clarify [grooming](https://github.com/18F/tts-tech-portfolio/issues/314) sections in doc
- [ ] clarity around [assignment](https://github.com/18F/tts-tech-portfolio/issues/257)
- [ ] revisit size [labeling](https://github.com/18F/tts-tech-portfolio/issues/296)
- [ ] clarify when labeling [happens](https://gsa-tts.slack.com/archives/GP559GCLD/p1578085991010000)
- [ ] resolve conflict of moving things from New Issues and Icebox/backlog during the Planning ceremony
- [ ] [clean up epics](https://github.com/18F/tts-tech-portfolio/issues/284)
- [ ] do we need Entrance Criteria _and_ Exit Criteria for columns, or could we [consolidate to one](https://docs.google.com/document/d/1GF4BR9X5lhOJq2j_sMDgzdqrl_WsgGadgnFlsstsIJk/edit#bookmark=id.zcz3m725yy88)?
- [x]  feedback label

Overcome by events
- [ ] clarify that epics should be ordered before ordering Backlog
- [ ] when do cards move from icebox to backlog? Per [comment](https://docs.google.com/document/d/1GF4BR9X5lhOJq2j_sMDgzdqrl_WsgGadgnFlsstsIJk/edit?disco=AAAAEG1nsUc)
- [ ] entrance criteria for Backlog Per [comment](https://docs.google.com/document/d/1GF4BR9X5lhOJq2j_sMDgzdqrl_WsgGadgnFlsstsIJk/edit?disco=AAAAEG1nsUc)

## Acceptance criteria

- Agree on the tasks that are no longer relevant
- Demo updates at Review

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/356.
