### ISSUE TITLE
TTS Tech Portfolio agile approach -- in depth discussion

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#283]
## Background information

https://github.com/18F/tts-tech-portfolio/issues/282

## User stories

- As a ..., I want ... so that ...
- As a ..., I want ... so that ...

## Implementation

- [ ] [first small task]
- [ ] [another small task]

## Acceptance criteria

   - [ ] size labeling
   - [ ] do we need Entrance Criteria and Exit Criteria for columns, or could we consolidate to one?
   - [ ] want deadlines or specifying a finish-by date?
   - [ ] Consider making a theme of the week/sprint/month

**Comment by afeld** [comment]
Discussion done; handling follow-ups in https://github.com/18F/tts-tech-portfolio/issues/356.
