### ISSUE TITLE
TTS Tech Portfolio agile approach --  update documentation to match approach

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#285]
## User stories

- As a ..., I want ... so that ...
- As a ..., I want ... so that ...

## Implementation

    - [ ]  grooming sections in doc
    - [ ]  around assignment
    - [ ] when labeling happens
    - [ ] epics should be ordered before ordering Backlog
    - [ ] when do cards move from icebox to backlog
    - [ ] when things need feedback/consensus, then the how
    - [ ] Person running retro moves Retro Action items to issues

## Acceptance criteria

- [definitive thing]
- [other definitive thing]

**Comment by afeld** [comment]
Parts of this could be addressed via https://github.com/18F/tts-tech-portfolio/issues/296.

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/356.
