### ISSUE TITLE
document how we prioritize within the board

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#289]
## Background information

https://github.com/18F/tts-tech-portfolio/issues/181#issuecomment-557642484

Ran out of time to do this, but some general principles to use for prioritization:
- Close out things that are in-progress before picking up something new. If there's too much or part of it can wait, break out a new issue for the Icebox.
- Keep an eye on things that have due dates
- Look for the tasks that are force-multipliers, i.e. where we can spend a little time now to save a lot of time in the long run
- Solve the active pain points before going to nice-to-haves

Would like to think about other/additional criteria can be added to the principle
- Is this something that people within TTS are asking for?
- Is this an action item from another meeting (Working Group, Guild, council, etc)?
- Is this a customer service task? 
- Is this something that is specifically called out in the Handbook that the Tech Portfolio does? 
- Has this been lingering for a while?
- Will this task make another task on the board easier?
- Is there a related card in progress?

## User stories

As someone working on issues, I would like to know the criteria for prioritizing. 

## Implementation

- [ ] Pull request for the Project Board on how to prioritize 
- [ ] Team members review pull request
- [ ] Pull request is approved

## Acceptance criteria

- [ ]  demo at Review
- [ ] pull request is linked to issue

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/356.
