### ISSUE TITLE
Update Before You Ship

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#291]
## Background information

Before You Ship was originally created without being integrated into GSA IT Security process and was largely to help developers who were creating custom software. There has been a shift away from creating custom software and using more COTS, so the BYS guide should reflect the current experience. 

## User stories

As someone updating Digital.gov I would like to add a number of pages from Before You Ship guide into the Good Production Practices 

As someone who maintains Before You Ship, i would like all the information to be up to date and accurate before people leverage it for other purposes

https://gsa-tts.slack.com/archives/C029KQMBZ/p1579881392025100

## Implementation

- [ ] audit content
  - [ ] consider [suggestion](https://github.com/18F/handbook/pull/1810#discussion_r375828004) of making BYS the definitive ATO source 
- [ ] make notes of what needs to get changed
- [ ] make pull requests for changes

## Acceptance criteria

- The BYS guide has information that is up to date and relevant

**Comment by afeld** [comment]
We might want to split this into more smaller issues focused on specific sections of the site, e.g. ATOs (which might be covered by https://github.com/18F/Security-Compliance/issues/2) vs. security vs. infrastructure.

**Comment by JJediny** [comment]
**potential to consolidate:**
- https://github.com/18F/tts-tech-portfolio/issues/331
- https://github.com/18F/before-you-ship/issues/160

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
