### ISSUE TITLE
TTS Risk Management Plan: Planning - Requirements

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#292]
## Background information
TTS Tech Portfolio is the middle layer of the Multilayered Organization-wide Risk Management Pyramid from NIST SP 800-39

> Tier 2 addresses risk from a mission/business process perspective and is informed by the risk context, risk decisions, and risk activities at Tier 1. Tier 2 risk management activities include: (i)  defining the mission/business processes needed to support the missions and business functions of organizations; (ii) prioritizing the mission/business processes with respect to the strategic goals and objectives of organizations; (iii) defining the types of information needed to successfully execute the mission/business processes, the criticality/sensitivity of the information, and the information flows both internal and external to organizations; (iv) incorporating information security requirements into the mission/business processes; and (v) establishing an enterprise architecture with embedded information security architecture that promotes cost-effective and efficient information technology solutions consistent with the strategic goals and objectives of the organization and measures of performance. Tier 2 activities directly affect the activities carried out at Tier 3. For example, the information security architecture portion of the enterprise architecture developed at Tier 2 influences and guides the allocation of information protection needs which, in turn, influences and guides the allocation of the security controls to specific components of organizational information systems at Tier 3. Enterprise architecture decisions at Tier 2 affect the design of information systems at Tier 3 including the types of information technologies acceptable for use in developing those systems. The activities carried out at Tier 2 can also provide useful feedback to Tier 1, possibly resulting in revisions to the organizational risk frame or affecting risk management activities carried out at Tier 1, for example those performed by the risk executive (function). Section 2.4 provides a more detailed description of the specific activities associated with Tier 2. 

https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-39.pdf

> GSA’s Enterprise Risk Management  program provides a framework for proactively identifying, managing and treating risk in achieving GSA’s strategic objectives and mission; and seeks to integrate risk management into operations in order to improve organizational effectiveness. GSA and its Service/Staff Offices (S/SOs) work collaboratively to identify and manage risks across GSA. The ERM program establishes a structure to help GSA:
> •	Increase the likelihood of successfully delivering on GSA’s goals and objectives;
> •	Encounter fewer unanticipated outcomes;
> •	Better identify, assess, and mitigate risks;
> •	Clearly describe to customers and other stakeholders what GSA is doing to manage its risks; and
> •	Reduce redundancy and improve integration among risk management methods and ensure cost-effective implementation. 

[Risk Management Strategy [CIO IT Security 18 91 Rev 2] ](https://insite.gsa.gov/cdnstatic/insite/Risk_Management_Strategy_%28RMS%29_%5BCIO_IT_Security_18_91_Rev_2%5D__03-14-2018.docx)

## User stories

As someone in the TTS Tech Portfolio, I want to manage organizational risk. 

## Implementation

- [ ] defining the current mission/business processes supporting the missions and business functions of organizations
   - [ ] Review GSA Risk Management Plan
   - [ ] Review FAS mission processes
   - [ ] Review TTS mission processes
   - [ ] Review mission processes or TTS Systems
       - [ ] Identify gaps based on existing policies
       - [ ] Pull out relevant information and put in a reference document
- [ ] prioritizing the mission/business processes with respect to the strategic goals and objectives of organizations in an sheets doc

## Acceptance criteria

- Next step in the `TTS Risk Management Plan: Planning - Responsibilities` is created and references this task `TTS Risk Management Plan: Planning - Requirements`
   - [ ] Requirements
   - [ ] Responsibilities
   - [ ] Definitions
   - [ ] Resources
   - [ ] Procedures
   - [ ] Risk Management Resource
   - [ ] Implementation
   - [ ] Strategy/Approach
- Spent no more than three hours
- 'Demo' at Sprint Review

**Comment by its-a-lisa** [comment]
Completed this activity and uploaded some [TTS Risk Management Plan - Research](https://docs.google.com/document/d/1ytgCYWME0jpXPIhGUy_xoV9zUgq66rctL93lyAV1mHY/edit#) in a document. Likely going to switch gears and go with a minimum viable approach ; have also been working on [finding other risk management plans](https://github.com/its-a-lisa/awesome-govt-security-policy) to see other examples.
