### ISSUE TITLE
workflow proposal

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#296]
## Background information

I have a clear(ish) idea of an evolution of our current team workflow that I have been referring to, but have never fully articulated. I should do so.

## User stories

- As the Director of the Tech Portfolio, I want to ensure the team has a clear idea of what to work on next, the scope of tasks, etc. so that they feel productive and satisfied
- As a member of the Tech Portfolio, I want those same things

## Implementation

- [x] Write up a proposal for the workflow
- [x] Get feedback from @its-a-lisa 
- [x] Get feedback from @JJediny 
- [ ] Modify the canonical documentation based on the proposal and/or feedback

## Acceptance criteria

- Team members feel they have a clear understanding of how work will get prioritized, scoped, assigned, etc.
- No remaining known gaps in the workflow

## Related tasks

https://github.com/18F/tts-tech-portfolio/issues/285

**Comment by its-a-lisa** [comment]
This might be a good resource when thinking through this activity: https://trello.com/c/DC3BCqKN/5-crisps-blog-agile-leadership-health-check

**Comment by its-a-lisa** [comment]
A better example using music instead of sports and the quadrant with them placed
https://www.pmi.org/learning/library/socio-cultural-agile-project-management-9661

**Comment by afeld** [comment]
Wrote up [a list of suggested changes](https://docs.google.com/document/d/1GF4BR9X5lhOJq2j_sMDgzdqrl_WsgGadgnFlsstsIJk/edit?usp=sharing). Adding tasks for the individual feedback.

**Comment by its-a-lisa** [comment]
We had some new issues that we were going to create related to workflow, but considering we already have a lot of cards, and there is the meeting on Wednesday, would rather now create the cards and add them as a comment here so we can keep track of them for now

- [ ] thumbs up proposal
- [ ] work value stream
- [ ] update issue template to include 'what problem we're trying to solve'

**Comment by its-a-lisa** [comment]
Would like to discuss some general guidelines on which channels we use for what info -- we currently have 3 #infrastructure #tts-tech-portfolio and #tts-tech-portfolio-private

Currently, two scenarios that spark me to mention this

1. I would like to post the general communication about our approach for TTS SaaS approvals, and I'm not sure which channel I should post it into and do the cross post from there
2. When there is an ask for the team vs all of TTS, I go to the private channel to look for it because it isn't cluttered, so I would like to communicate that is my preference and be on the same page with the team

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/356.
