### ISSUE TITLE
Talking Points/Success Stories - due 1/10

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#301]
## Background information

Outreach is asking for quarterly updates to the Talking Points/Success Stories for every portfolio, including the Tech Portfolio.

## User stories

- As a member of Outreach, I want to understand what the Tech Portfolio has accomplished so that I can make TTS look good.

## Implementation

- [x] Copy [template](https://docs.google.com/document/d/1z06HZvBD_UyTSFHFAftSzmR0LjqFCrZ5d0MoDZ4eUs0/edit#heading=h.axz7yjaaqcw6) for the Tech Portfolio
- [x] Link from [overall doc](https://docs.google.com/document/d/1z06HZvBD_UyTSFHFAftSzmR0LjqFCrZ5d0MoDZ4eUs0/edit#heading=h.pqc0trwlsd5f)
- [x] Fill out the template with [3-5 success stories](https://gsa-tts.slack.com/archives/C3F3HR717/p1579194071030400?thread_ts=1579152285.027200&cid=C3F3HR717)
- [x] Get feedback from team
- [x] Let Kristina Britt know it is complete

## Acceptance criteria

- Template is filled out
- Team members have reviewed

## Related cards

https://github.com/18F/tts-tech-portfolio/issues/243

**Comment by its-a-lisa** [comment]
[Our first draft](https://docs.google.com/document/d/1HmAtF3A4HUvn2HRV_nfgaXxlO8spqIJmkOP8nJoUqQs/edit#)

**Comment by afeld** [comment]
[Checking how many are desired.](https://gsa-tts.slack.com/archives/C3F3HR717/p1579152285027200)

**Comment by afeld** [comment]
Have three written up. Will make edits based on feedback as they come in, but will call this "done enough" in the meantime.
