### ISSUE TITLE
set up custom domains for StatusPage

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#302]
## Background information

The StatusPage sites (https://cloudgov.statuspage.io/ and https://logingov.statuspage.io/) are at statuspage.io subdomains; this will make it harder to transition off.

https://help.statuspage.io/help/custom-domain

## User stories

- As a customer of a service using StatusPage, I want to have a stable domain name to visit to get the site status.

## Implementation

- [ ] Check with both teams to see if there's any objection and if they are ok with `status.<service>.gov`
- [ ] Set up domains
- [ ] Confirm HTTPS
- [ ] Update references to the status page URL

## Acceptance criteria

- Status page is available at custom domain with HTTPS

**Comment by JJediny** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/224

Will reopen if Statuspage.io becomes an available option.
