### ISSUE TITLE
Clarify the references to the Infrastructure team

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#32]
Though infrastructure is still a thing that exists, the Infrastructure team no longer exists by name. Let's make this more consistent by updating references from Infrastructure to the Tech Portfolio.

- [x] [The Infrastructure repo](https://github.com/18F/Infrastructure) - either rename (tts-tech-portfolio-private?) or archive
- [ ] `#infrastructure` channel in Slack
- [x] Pages mentioned in https://github.com/18F/handbook/issues/1300
- [x] Other references across the Handbook
- [x] Other references in Before You Ship

**Comment by its-a-lisa** [comment]
> Though infrastructure is still a thing that exists, the Infrastructure team no longer exists by name. Let's make this more consistent by updating references from Infrastructure to the Tech Portfolio.
> - [x] [The Infrastructure repo](https://github.com/18F/Infrastructure) - either rename (tts-tech-portfolio-private?) or archive
- This was already archived
> - [ ] `#infrastructure` channel in Slack
- I believe the plan is to keep this for 'infrastructure' related requests; the slack channel is the only reference to the infrastructure team on pages now; if this is going to change, suggest we close this ticket and open another just for this activity. 
> - [x] Pages mentioned in https://github.com/18F/handbook/issues/1300
- Completed
> - [x] Other references across the Handbook
- Submitted the following pull requests:
  - https://github.com/18F/handbook/pull/1685
  - https://github.com/18F/handbook/pull/1688
  - https://github.com/18F/handbook/pull/1689
  - https://github.com/18F/handbook/pull/1690
  - https://github.com/18F/handbook/pull/1691
> - [x] Other references in Before You Ship
- Moved the ATO page to: 18F/handbook#1688
- Moved the Infrastructure page to: 18F/handbook#1688
