### ISSUE TITLE
Uptrends transitioning (uptime monitoring)

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#330]
_Be careful not to include any procurement-sensitive information in this issue._

## Background information

The Uptrends account/subscription we are using isn't actually a shared service offering from GSA IT; we've been using it as a courtesy. We should switch to something managed by TTS. [More details.](https://docs.google.com/document/d/1YXdyaQODASgdA5WTwcR-W6it_xpCHp8cP1CjiBxPM90/edit)

## User stories

- As a web system owner, I want to know that my site is available.
- As a member of the Tech Portfolio, I want TTS systems to use systems that are authorized for the forseeable future.

## Implementation

- [x] Get list of TTS systems in Uptrends
   - challenge.gov
   - data.gov
   - search.gov
   - Touchpoints
   - usa.gov
- [ ] Create migration plan
- [ ] Have all system owners acknowledge that plan
   - [ ] challenge.gov
   - [ ] data.gov
   - [ ] search.gov
   - [ ] Touchpoints
   - [ ] usa.gov

## Acceptance criteria

- [ ] There are no more TTS systems in the Platform Management Uptrends
- [ ] All the systems that _had_ uptime monitoring still do

**Comment by afeld** [comment]
Since Uptrends is remaining available, not going to push teams on this.
