### ISSUE TITLE
Mac display adapter purchase for for remaining DC/SF offices - due Overdue

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#333]
### Acceptance Criteria
- [x] Final count of monitored w/o for SF
- [x] Final count of monitored w/o for DC
- [x] Make the purchase and ship DC
- [x] Make the purchase and ship SF

**Comment by its-a-lisa** [comment]
@JJediny I think we should make some sort of announcement for this as well to keep folks updated on what is going on
