### ISSUE TITLE
Update TTS Incident Response documentation v2

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#341]
## Background information

https://github.com/18F/tts-tech-portfolio/issues/265

## User stories

- As someone working on the incident response improvement activity, i want to progress with it

## Implementation

- [x] update documents with lessons from initial activity
  - [x] Include [recommendations ](https://groups.google.com/a/gsa.gov/forum/#!topic/devops/hTPR_skErBo)from [IT Security]( https://gsa-tts.slack.com/archives/C0G6G1UNM/p1581014077021900?thread_ts=1580487011.020700&cid=C0G6G1UNM)
- [x] get feedback from folks who recently responded to incidents
- [ ] continue next steps for workflow, filling in the blanks
   - [ ] COOP
   - [x] TTS level
- [x] investigate whether using the mural board and creating GitHub issues from the board is a feasible activity

## Acceptance criteria

- documentation is updated
- elements that need improvement are identified

**Comment by its-a-lisa** [comment]
Blocked based on needing to update the anchor links from https://github.com/18F/handbook/pull/1854

**Comment by its-a-lisa** [comment]
Updated [meeting minutes](https://docs.google.com/document/d/1VvazOud-Cuc1CZbhqoNaSGL2pm_6CvXZiELkxME4a44/edit#) to incorporate feedback from cloud.gov/ @hillaryj before she left the organization

**Comment by its-a-lisa** [comment]
In regards to investigating previous security incidents, sent a [message](https://gsa-tts.slack.com/archives/CG8SNAEQM/p1583276419054000):
- Have meeting scheduled w/ @stvnrlly 3/5 16:30EST

**Comment by its-a-lisa** [comment]
After several meetings, realized that COOP and IR are two separate events and that at the GSA IT level, their concern for COOP is _continuity planning_ and only a fraction of our TTS are of concern. But we need to have a _contingency plan_ for all of our systems. 

Filled in one box with the TTS level responsibility for looking through to see if any policy needs to be changed based on the incident; will fill in more as needed incrementally and iteratively. 

Moving to Waiting/Locked until https://github.com/18F/handbook/pull/1854 is merged
