### ISSUE TITLE
Work with GSA IT Security on LiSaaS authorizations

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#342]
## Background information

https://github.com/18F/tts-tech-portfolio/issues/186

## User stories

- As a someone in the TTS Tech Portfolio, I want SaaS that is In-Use or Proposed to quickly get authorized

- As someone in IT Security, I want TTS Tech Portfolio to be involved and active in LiSaaS authorizations as the Champion 

## Implementation

- [x] Review the [CISO Priority for the TTS SaaS ](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=0&fvid=165684251)with IT Security
- [x] Transfer from TTS spreadsheet to GSA IT Security Spreadsheet
- [x] TTS prioritizes their top priority
- [x] GSA IT Security prioritizes their top priority
- [x] Update [TTS In Progress sheet](https://docs.google.com/spreadsheets/d/1MPMrCWfLX5CTVVI8hysUK8DFEKGgGw2L2W-T1jat4LM/edit#gid=1742590411) with contacts for top cloud solution offerings
- [x] GSA IT Security updates the e-mail with the wording to reflect the new process
- [ ] TTS & CTO Office going to do a write up to describe situation

## Acceptance criteria

- All LiSaaS In-Use has an ATO

**Comment by its-a-lisa** [comment]
@josephderosales did you take notes from when we met? I liked what we started to chat about in regards to the phased approach for how we are going to look at things.

**Comment by its-a-lisa** [comment]
This portion of the activity is closed, will open a new issue. 

Documented the [progress and status](https://docs.google.com/document/d/1rwvOFYAJi36i045sbjr9OTyORA1VF2wBbTTw8sQZMtE/edit#heading=h.9ayuzfyoz046)
