### ISSUE TITLE
Ops Rotation 2/10-2/23

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#350]
Each of the following should be done within the dates above. See the [playbook](https://github.com/18F/tts-tech-portfolio/blob/master/Operations%20Rotation%20-%20Playbook.md) for additional info.

## Outstanding
  - [x] Move Action Items from Retro into issues
- [x] Send nudges on [open security upgrade pull requests](https://github.com/search?o=asc&q=user%3A18F+user%3AGSA+author%3Aapp%2Fdependabot+is%3Aopen+archived%3Afalse&s=created&type=Issues) that are older than a few days
- [ ] Perform any outstanding `ACCOUNT DEACTIVATION` [offboarding tasks](https://docs.google.com/spreadsheets/d/1IlFY5AAvTyuS7yDHk5_odJGHYZDU_MN9HNGKJ2zXwi0/edit

## Meetings

- [x] Lead [Planning Ceremony](https://github.com/18F/tts-tech-portfolio/blob/master/ProjectBoard.md#planning-ceremony)
  - [x]  Review board prior to meeting
- [x]  Lead the daily standup
- [x] Attend the CTO Liaison Meeting
  - [x] Review and update [Trello board](https://trello.com/b/BFp37KQ6/gsa-cto-tts-liaison)
- [x]  Lead [Sprint Review](https://github.com/18F/tts-tech-portfolio/blob/master/ProjectBoard.md#sprint-reviews)
- [ ]  Lead [Retro](https://github.com/18F/tts-tech-portfolio/blob/master/ProjectBoard.md#retros)
  - [ ] Move Action Items into issues
- [ ]  Let the next person on Operations Rotation know what is outstanding

## GitHub

- [ ]  Review and ideally merge (or close) [open pull requests to Tech Portfolio repositories](https://github.com/search?utf8=%E2%9C%93&q=state%3Aopen+is%3Apr+repo%3A18F%2Faws-admin+repo%3A18F%2Fghad+repo%3A18F%2Ftts-tech-portfolio+repo%3A18F%2Fvulnerability-disclosure-policy+repo%3A18F%2FDNS+repo%3A18f%2Fhandbook+repo%3A18F%2Fbefore-you-ship+repo%3A18F%2Fchandika+repo%3A18F%2Fopen-source-policy+repo%3A18F%2Flaptop+repo%3A18F%2Fchat+repo%3A18F%2Fbug-bounty+repo%3A18F%2Flaptop++repo%3A18F%2Fraktabija&type=Issues&ref=advsearch&l=&l=)
- [ ]  [Update the public IT Standards dataset](https://github.com/GSA/data/tree/master/enterprise-architecture#updating-the-list)
- [x] Send nudges on [open security upgrade pull requests](https://github.com/search?o=asc&q=user%3A18F+user%3AGSA+author%3Aapp%2Fdependabot+is%3Aopen+archived%3Afalse&s=created&type=Issues) that are older than a few days
- [x]  Remove stale [invitations](https://github.com/orgs/18F/people)

## Communications Monitoring

Ensure you are present in the following and are responding as needed:

- [x] [Slack Channels](https://github.com/18F/tts-tech-portfolio/blob/master/Operations%20Rotation%20-%20Playbook.md#slack-channels)
- [x]  [Google Groups](https://github.com/18F/tts-tech-portfolio/blob/master/Operations%20Rotation%20-%20Playbook.md#google-groups)

## Other

- [ ] Perform any outstanding `ACCOUNT DEACTIVATION` [offboarding tasks](https://docs.google.com/spreadsheets/d/1IlFY5AAvTyuS7yDHk5_odJGHYZDU_MN9HNGKJ2zXwi0/edit)
- [x]  Check and act on open [Bug Bounty reports](https://hackerone.com/bugs)

**Comment by its-a-lisa** [comment]
- [ ] Lead [Planning Ceremony](https://github.com/18F/tts-tech-portfolio/blob/master/ProjectBoard.md#planning-ceremony)
  - [ ]  Review board prior to meeting

Actions are complete; @afeld led based on the [workflow](https://github.com/18F/tts-tech-portfolio/issues/296) still being ironed out.
