### ISSUE TITLE
determine which DotGov domains can be sunset

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#358]
## Background information

TTS has (or at least I can see) 27 domains registered in DotGov. Each costs $400/year to renew, not to mention administrative overhead. Per request from @dsalegov, let's see which we can get rid of.

## User stories

- As a member of TTS in charge of budget, I want to pay for domains that are no longer useful.

## Implementation

- [x] Come up with initial list of candidates
   - Hosts that don't resolve
   - Redirects that have been in place for a while (over a year?) that we don't think people are linking to anymore
- [x] Confirm with corresponding system owners that domains are no longer need
- [ ] Ask DotGov to delete, or at least don't renew

## Acceptance criteria

- We manage fewer domains than we did before

**Comment by JJediny** [comment]
- [x] Reached out to Challenge to remove challenges.gov
- [x] Assigned PIF to review theirs
- [x] Assigned Login to review connect.gov
- [ ] Need to assign USA.gov to review theirs

**Comment by JJediny** [comment]
Confirmed all of the questioned upcoming FY20 domain renewals, all programs have validated the list - https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=824448842 :
- [x] innovation portfolio
- [x] data and analytics portfolio
- [x] login.gov
- [x] pif.gov
- [x] usa.gov
