### ISSUE TITLE
check AWS burn

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#364]
## User stories	
As the TTS org we want to ensure the funding for AWS is sustainable with the projected spend.
related - https://github.com/18F/aws-admin/issues/20

## Acceptance criteria	
- [x] Review reseller invoicing through 2/20
- [x] Create a projected spend/burn % for each budget line
- [x] Review AWS cost explorer to compare to vendor discount/invoices
- [x] Notify program teams with their current spend and projected shortfalls

**Comment by afeld** [comment]
Let's make a new card for submitting new purchase orders (due April?) and close this out.

**Comment by JJediny** [comment]
Spreadsheets up to date as of Feb 2020.

Cloud.gov is completing its final steps to supplement their overages with a new PR. We will open a new issue at the end of March as an update to the deliverable for this issue: https://docs.google.com/spreadsheets/d/1DedSCiU9AsCAAVvAFZT0_Ii7AFIKlI-JNifzlpHNbDg/edit#gid=1178386494
