### ISSUE TITLE
Tech Talk: ATO

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#365]
## User story

https://gsa-tts.slack.com/archives/C039MHHF8/p1580851294144400?thread_ts=1580767478.129600

https://groups.google.com/a/gsa.gov/d/msgid/devops/CAOykteAwk8NOLn9bLjg9LJA9OoM6T3S%3Dd%2BzfGCZxpCAawkdtDQ%40mail.gmail.com?utm_medium=email&utm_source=footer

## Background

We've been asked to do a Tech Talk on ATOs

## Acceptance Criteria

- [ ] Understand what is needed for Tech Talk
- [ ] Develop deck for Tech Talk
- [ ] Deliver Tech Talk

**Comment by afeld** [comment]
Sounds like @boberlas is going to do it.
