### ISSUE TITLE
Figure out what to do with acquisition/procurement workload

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#366]
## User story
As someone in the TTS Tech Portfolio, I feel like there is a lot of work being done in the background and I'm not sure how to help. I would like to be able to jump in and take a task, or have a step in a process. Seems like it is a lot of work for one person, so seems reasonable for it to be broken up-- either certain people do certain steps or certain people do all steps but split up the workload. Currently, it feels nebulous -- seems like a lot and seems like it is persistently a problem. All of this seems hidden because it isn't reflected on the board. Not sure how long it is supposed to take, vs how long it is actually taking. 

## Background
This came up during a [retro](https://docs.google.com/document/d/1AllRE0PWduc_Blu1bt5RWMqIbjbkROzlEugqZ089VTg/edit#bookmark=id.4fissxniw2pm) as an action item. 

## Implementation
The workload steps are mapped out and are reflected on the board and there is a solid understanding of who is doing what and how long each step should take and how much that is expected to take from each person's capacity. 

## Acceptance Criteria

- [x] Document the current state.
- [ ] Document options
- [ ] Proposal to alleviate workload
- [ ] Proposal sent to Tech Portfolio, Acquisition, Finance, and Solutions leadership
- [ ] Documentation published and linked to here

**Comment by JJediny** [comment]
![b27551b7-526d-4772-9057-f5f28689f8ed](https://user-images.githubusercontent.com/6350035/77134293-b413cd00-6a3c-11ea-8479-b90d7a4a3471.png)

**Comment by afeld** [comment]
- [Workflow diagram](https://gsa-tts.slack.com/archives/GP559GCLD/p1587698048006400)
- [Thread about handing off the p-card purchasing](https://gsa-tts.slack.com/archives/CFQT7RP0U/p1590617414000300)

**Comment by afeld** [comment]
The P-Card seems to be the most time-consuming / toil-iest part of this, so focusing on that in https://github.com/18F/tts-tech-portfolio/issues/488.
