### ISSUE TITLE
Tech Portfolio access to dotgov.gov for TTS domain management

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#38]
#### Acceptance Criteria
- [x] Update status of former handoff of domains - https://github.com/18F/Infrastructure/issues/907
- [x] Determine whether `devops@gsa.gov` can be used for all domains ownership. _(No it must be an individual)_
- [x] Update all domain records ownership status in [TTS System Source of Truth](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=1884617968)

**Comment by afeld** [comment]
This may need to get done sooner than later due to [BOD 20-01](https://cyber.dhs.gov/bod/20-01/#enable-receipt-of-unsolicited-reports). Coordinate with Armando Quintananieves.

**Comment by JJediny** [comment]
Clarification from dotgov.gov

>The billing point of contact must be an actual person. It's a DotGov policy requirement that the three POCs associated with a domain are individuals, not distros. X is now listed as a billing POC, so once there's someone else you can identify as a billing POC, she can send a note to the DotGov Registrar (registrar@dotgov.gov) and request an update.

**Comment by melanienleopold** [comment]
I renewed the domain due on 1/13. I'd like to initiate the transfer. @JJediny will you be the billing POC?

**Comment by afeld** [comment]
[List of domains](https://docs.google.com/spreadsheets/d/1HuP2YSqk2E0IuYlXRgV5qj3tkqwS-Hn7fe3YDJZKFqE/edit#gid=0)

**Comment by afeld** [comment]
Done!
