### ISSUE TITLE
GitHub org for cloud.gov

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#385]
## Why do you want a dedicated GitHub org?

- To better answer the question: "What repositories comprise cloud.gov?"
- To make search across cloud.gov code, issues, and PRs feasible
- To properly determine which repositories are archival or not
- To consistently manage all repos with Terraform
- To simplify user management with a smaller # of users and repository combinations

https://gsa-tts.slack.com/archives/C0ENP71UG/p1580854532252900

## Tasks

1. [x] Review the [rules](https://handbook.tts.gsa.gov/github/#rules), as those will also apply to the new organization.
1. [x] Get a :+1: from the @18F/tts-tech-portfolio
1. [x] [Submit a micropurchase request](https://handbook.tts.gsa.gov/purchase-requests/) if you need private repositories.
1. [x] [Create the organization.](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch) - @cloud-gov
1. [x] [Enforce two-factor authentication.](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/requiring-two-factor-authentication-in-your-organization)
1. [x] [Add users.](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/inviting-users-to-join-your-organization)
   - [x] Add @18F/tts-tech-portfolio members and @tts-bot as Owners so we can do offboarding and other admin-y things.
1. [x] Ensure that all your webhooks, integrations, etc. are in place.
1. [x] [Transfer repositories.](https://help.github.com/en/github/administering-a-repository/transferring-a-repository)
   — GitHub does redirects, but you'll want to make sure it doesn't break things like deployment.
1. [x] Add to the [list of organizations](https://handbook.tts.gsa.gov/github/#organizations).

**Comment by pburkholder** [comment]
About the potential move the GitHub enterprise — how’s that change the pricing for us or are we already on Enterprise?

**Comment by pburkholder** [comment]
Looks done to me.

**Comment by afeld** [comment]
> About the potential move the GitHub enterprise — how’s that change the pricing for us

TBD.

> are we already on Enterprise?

Nay: https://github.com/18F/tts-tech-portfolio/issues/271
