### ISSUE TITLE
TTS 24 SaaS Approvals

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#397]
## User story

Placeholder

## Background

Placeholder

## Acceptance Criteria

- [x] Contact Vendors
- [x] Set up calls w/ Vendors
- [x] Work w/ Brian T. about FedRamp
- [x] Determine future of some SaaS
- [ ] Determine what roles from TTS will support the process and potential rotation options
- [ ] Create new issues for [transitioning](https://gsa-tts.slack.com/archives/C039MHHF8/p1586529257137800)

**Comment by its-a-lisa** [comment]
> or for this one in particular, if you throw in the "create new issues for transitioning" into the current TTS 24 card, that would be better for me
<sub>[View in Slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1586878302161700)</sub>

**Comment by its-a-lisa** [comment]
- [ ] Broke out the transitioning issues: https://github.com/18F/tts-tech-portfolio-private/issues/943 & https://github.com/18F/tts-tech-portfolio-private/issues/944 & https://github.com/18F/tts-tech-portfolio-private/issues/942

- [ ] Working on determining how TTS will be involved w/ the FedRAMP process through this activity https://github.com/18F/tts-tech-portfolio/issues/435

Based on the new issues being opened, this issue can be closed
