### ISSUE TITLE
blog post: remote work and Continuity of Operations

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#402]
## Background information	

_Like so many things, [this idea started as a tweet](https://twitter.com/aidanfeldman/status/1232782659874643968)._

Aside from general reasons remote work is good for organizations (countless books, blog posts, and talks on this subject), there are a couple of timely drivers for it:

- Coronavirus
- [Continuity of Operations (COOP)](https://en.wikipedia.org/wiki/United_States_federal_government_continuity_of_operations) and the upcoming [National Level Exercise](https://www.fema.gov/nle)

I would like to write a blog post expanding on why it matters.

cc https://github.com/18F/blog-drafts/issues/774 @tbaxter-18f @karareinsel @Dahianna 

## User stories	

- As [everyone], I want federal agencies to remain as operational as possible in the event of a major public health quarantine or disaster.

## Implementation	

- [ ] Notify the GSA COOP folks and ask for input
- [ ] Determine whether to use digital.gov or the 18F blog
- [ ] Get initial 👍 from Outreach
- [ ] Create first draft
- [ ] Solicit feedback
- [ ] Publish (there are likely multiple sub-steps here)

## Acceptance criteria	

- There is public information about why remote work is good for government continuity

**Comment by afeld** [comment]
[Article from FedScoop.](https://www.fedscoop.com/18f-telework-coronavirus-pandemic/)

**Comment by Dahianna** [comment]
We also have this post going through the approval process: https://github.com/18F/blog-drafts/issues/771

Take a look at the draft and let me know if it's similar to what you're thinking of writing.

**Comment by afeld** [comment]
Different, but related!

**Comment by afeld** [comment]
Feels like we kinda missed the timing on this, so not going to worry about it unless someone else feels strongly that we should write it.
