### ISSUE TITLE
Determine preferred security tool for dependencies - due date 5/20

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#403]
## Background information	

We currently have both Snyk and Dependabot; there is some thought that having both is redundant. Considering Dependabot is native to GitHub and included within the authorization boundary, it is worth taking a look to determine if both are necessary. 

## User stories	

As someone shepparding SaaS authorizations through the approval process, I only want to do so for capabilities that have a valid requirement. 

## Implementation	
- [x] Radiate intent in the #infrastructure, #g-security-compliance & #devops channels and start a thread for discussion
- [x] Start a [document](https://docs.google.com/document/d/1t_ECpg5C9L2gKeICgC9JtCf_JD4LGPKLGGdW8-iyfOc/edit#) to follow document any discussions, discovery and results
- [x] Determine which repos will be used as test cases	
- [x] Enable both Snyk and Dependabot for test repos	

## Acceptance criteria	

- capabilities have been baked off
- results are documented
- decision is made

**Comment by its-a-lisa** [comment]
@afeld adding you as an assignee to this card so you can add the instructions so I can execute the tasks.

**Comment by afeld** [comment]
In short, we want to see if Snyk finds/fixes things the Dependabot doesn't, and vice versa. We should enable both for a handful of repositories and see what vulnerable dependencies are found by each. Since Dependabot is enabled across our repos via [ghad](https://github.com/18F/ghad) already, probably easiest to ask in #dev where Snyk is in use and compare past security alerts for each.

Does that clarify?

**Comment by its-a-lisa** [comment]
it does, thanks!

**Comment by its-a-lisa** [comment]
@afeld I'm not exactly clear what the relationship between  [ghad](https://github.com/18F/ghad) and Dependabot. 

Just want to double check -- the expectation is that ever site under 18F also has Dependabot enabled, correct? 

Is there a way to check this? 

And should we had .dependabot/config.yml to the .github repository?

**Comment by afeld** [comment]
> the relationship between ghad and Dependabot

ghad enables Dependabot.

> the expectation is that ever site under 18F also has Dependabot enabled, correct?

[_All_ our GitHub orgs](https://handbook.tts.gsa.gov/github/#organizations), but yes. Unfortunately that's not happening right now: https://github.com/18F/ghad/issues/33

> Is there a way to check this?

[`master` branch build output for ghad](https://app.circleci.com/pipelines/github/18F/ghad?branch=master), I suppose? And/or we can spot check a sample of repositories.

> should we had .dependabot/config.yml to the .github repository?

Dependabot mostly _just works_ in my experience, but repositories that need to customize could certainly add [config](https://dependabot.com/docs/config-file/), yep.

**Comment by its-a-lisa** [comment]
@afeld is the TTS Tech Portfolio `Owners or Maintainers` on [_All_ our GitHub orgs](https://handbook.tts.gsa.gov/github/#organizations)?

**Comment by its-a-lisa** [comment]
Have made progress on which repos will be use cases (beyond the Tech Portfolio owned):
- https://github.com/18F/identity-idp
- https://github.com/18F/identity-analytics-etl/
- https://github.com/uswds/uswds-site
- https://github.com/18F/analytics-reporter
- https://github.com/18F/tock/
- https://github.com/eregs/

**Comment by its-a-lisa** [comment]
Conclusion: Due to Snyk having the ability to integrate into the CI/CD pipeline and support our approach for a Continuous ATO within the Tech Stack -- there is validity to keeping it active and having that as the preferred tool for open source projects. There might be other considerations not taken into consideration, such as custom legal terms, SSO, etc. And as one said, comparing the two are ‘fraught’. So, rather than going down the path, I would rather call this a tie for both capabilities for post-pull request vulnerability discovery and determine that Snyk is still needed as a capability within the software development lifecycle pipeline. 

@afeld ready for you to make a determination

**Comment by its-a-lisa-at-work** [comment]
Talked through this at today's standup. Marking as closed and going to inform GSA IT Security that we are going to proceed forward with Snyk
