### ISSUE TITLE
Azure for COE forms-as-a-service

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#415]
## Background information	

COEs are looking for Azure space for their forms-as-a-service project. Broken out from https://github.com/18F/tts-tech-portfolio/issues/162.

## User stories

- As a member of the COE cloud team, I want access to Azure for developing the forms-as-a-service system.

## Implementation

1. [x] Syed: Fill out the PR Request Form
    - [ASF](https://docs.google.com/a/gsa.gov/forms/d/e/1FAIpQLSe1XLcOjcejWeskmILjiO93w1-V8LSFt6VDgfKyEbwUmQOiT1.viewform)
    - [FCSF](https://docs.google.com/forms/d/e/1FAIpQLSfdM8H8YmCZ-vxuAQwKwCbL6O7SZ1jOa8qex2-ruqPkIvO0eA/viewform)
1. [x] PR created by Finance and routed for approval
1. [x] PR approved
1. [x] CO created a Purchase Order (QP) in Pegasys
1. [x] QP approved
1. [x] CO created a collaboration in ASSIST for Finance to approve
1. [x] Finance reviewed and approved
1. [x] CO created the order in ASSIST
1. [x] CO sent Fund Certification for approval to the Funding Manager
1. [x] Funding manager approved
1. [x] CO finalizes the order in ASSIST
1. [x] CO issues to the vendor
1. [x] Account(s) created

## Acceptance criteria	

- COEs have access to an Azure account that has funding available.

**Comment by saz33m** [comment]
Confirming CoE has access to Azure Government for FaaS.

**Comment by afeld** [comment]
Yay!
