### ISSUE TITLE
provide list of users for Mac Standard User pilot groups - due 4/2

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#423]
## Background information

- [Roadmap](https://docs.google.com/document/d/1djFghEuMZW0cE7xoslbBuPUr25pNeHe13WUB8iTWkFw/edit#)
- [Trello card](https://trello.com/c/0ZZ8J54h/201-standard-user-pilot)

## User stories

- As a member of the Mac Working Group, I want to know who will be in each pilot group so I can roll out admin rights removal.

## Implementation

- [x] [Ask for general volunteers](https://gsa-tts.slack.com/archives/C04KL9ZN2/p1584558743271800)
- [ ] Ask for design volunteers
- [ ] Update the introduction of the roadmap
- [ ] Provide users (email addresses) for:
   - [ ] Base application users
      - [x] Pilot
      - [ ] Extended pilot
   - [ ] Designers
      - [ ] Pilot
      - [ ] Extended pilot
   - [ ] "Light" developers

## Acceptance criteria

- We have a list of users for each group of the rollout

**Comment by afeld** [comment]
Done!
