### ISSUE TITLE
answer GitHub questions for challenge.gov - due 4/3

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#425]
## Background information

https://gsa-tts.slack.com/archives/C02KXM98G/p1585164853001900

## User stories

- As someone doing a security assessment of challenge.gov, I want to understand the security practices around GitHub/Federalist.

## Implementation

- [ ] Fill out [questions in doc](https://docs.google.com/document/d/1eHX3XgdfFcBFD8nplwhATIZ7Mt66O1Xs0Lujdy-vGqE/edit)
- [ ] Notify Tammy White
- [ ] Answer any follow-ups

## Acceptance criteria

- Challenge.gov team has their compliance questions answered (at least for now)

**Comment by its-a-lisa** [comment]
@afeld we can close this, correct?
