### ISSUE TITLE
Atlassian account migration

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#438]
## Background information

https://help.trello.com/article/1197-using-trello-with-an-atlassian-account

We may have the same steps for other Atlassian products like OpsGenie and Statuspage.

![Screen Shot 2020-04-20 at 5 56 16 PM](https://user-images.githubusercontent.com/86842/79803595-41925780-8330-11ea-8540-df51243d55e6.png)

![Screen Shot 2020-04-20 at 5 53 40 PM](https://user-images.githubusercontent.com/86842/79803392-e7919200-832f-11ea-8af0-9c021a3f8f14.png)

## User stories

- As a Trello user, I want to be able to maintain access to my boards.

## Implementation

- [ ] Determine how to manage [the Atlassian Cloud site](https://gsa-tts.atlassian.net/)
- [ ] TTS-wide message with instructions
   - [ ] Draft
   - [ ] Send
- [ ] Determine if there's anything that needs to happen on the admin side to manage the accounts
- [ ] Delete shared devops@gsa.gov Trello account

## Acceptance criteria

- Users have their accounts migrated to Atlassian

**Comment by afeld** [comment]
Haven't heard anything from users about this; not going to worry about it.
