### ISSUE TITLE
give feedback on new Federalist Site Approval process

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#441]
## Background information

https://drive.google.com/file/d/1UiqPkGWTcxSdaKWhdYUNa2ljyjl1nLOT/view?ts=5e989b12

## User stories

- As a team with a bunch of Federalist sites, I want to have the process be reasonable/clear/low-friction.
- As an AO / member of Security, I want to ensure that I understand the risk of systems I authorize.

## Implementation

- [x] Make a copy of [the draft](https://drive.google.com/file/d/1UiqPkGWTcxSdaKWhdYUNa2ljyjl1nLOT/view?ts=5e989b12) in a Google Doc, if there isn't one already
-- Made copies of the [Federalist Security Review and Approval Process](https://docs.google.com/document/d/10025jgBJ2PQF7UtlyRKa0dcv9wqYo55WxIrxO3zWXfM/edit#heading=h.gjdgxs)s & the [Federalist_Site_Review_and_Approval_Template](https://docs.google.com/document/d/1OpqkL7O6XqR7-VnfjeDWRWYmNw1tmtuN4ap8Q0cxwFc/edit#heading=h.gjdgxs)
- [x] Leave comments
   - [x] @its-a-lisa 
- [x] Send to @boberlas, Joe Hoyt, and Chris Hughes
- [x] Meeting to talk through, maybe?

## Acceptance criteria

- Security has been given feedback

**Comment by afeld** [comment]
From @JJediny:

> after reading the draft guidance document on future Federalist site(s) authorization(s); it is pretty low bar and much of what's be asked for is ripe for automation/streamlining anyway. So long as we avoid security requiring us to provide them in the traditional docx/xlsx format/process(s) for each site. This guidance might actually benefit TTS if it was expanded broader to encompass both federalist and/or ANY other cloud.gov app. Which isnt much of a stretch given the few CRM controls any custom cloud.gov app need implement. This could actually be a great justification for the work we want to be doing around compliance modernization. Per the asks in the guidance document; there are a few key areas that are automatable/repeatable:
>
> * Automating dynamic/static scan results into POAMs for tracking. Configuration and Automated Auditing test results can be used to feed the majority of `Artifacts` requested (see legend/key). Nessus/Webinspect/Zap/Pentest/dependabot/synk/etc can be via their APIs/export formats and standardized for centralized tracking far better than they are today.
> * Establishing a ~YAML/TOML/JSON file in the repo with the metadata being requested as `Documentation` (see legend/key). Ideally based in OSCAL, but similar to the opencontrol/about.yml efforts in the past. Coupled with github actions/circleci scanning pipelines there is great potential to standardize best practices and encourage reuse together with scanning setups.
> * Third party integrations/APIs/Architecture using a diagrams-as-code internal standard w/ a FIPs statement in the metadata file. Establish a clear cut/shared policy around system interconnects and system boundaries with security to isolate risky 3rd party from standard/safe/common types.
> 
> This guidance also provides us with a prime opportunity to approach TTS leadership as a ~forcing/justification mechanism for mobilizing OSCAL adoption. ~Assuming security's is ready to agree on the contentious issues of compliance-as-code and CUI to also push their hand on how willing/ready/able they are to accepting docs/artifacts/architecture in something other than docx/xslx and identify what data need be `controlled/CUI` in any context.

**Comment by afeld** [comment]
Meeting was scheduled for tomorrow at 4pm ET. Would be nice to have general feedback for Security by then, even if we don't go through and give detailed edits until later this week.

**Comment by its-a-lisa** [comment]
-- Made copies of the [Federalist Security Review and Approval Process](https://docs.google.com/document/d/10025jgBJ2PQF7UtlyRKa0dcv9wqYo55WxIrxO3zWXfM/edit#heading=h.gjdgxs)s & the [Federalist_Site_Review_and_Approval_Template](https://docs.google.com/document/d/1OpqkL7O6XqR7-VnfjeDWRWYmNw1tmtuN4ap8Q0cxwFc/edit#heading=h.gjdgxs)

**Comment by afeld** [comment]
Done!
