### ISSUE TITLE
cancel Zoom (commercial) account

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#449]
## Background information

Given the GSA IT directive to only use Zoom for Government, we should stop paying for the account we no longer use.

## User stories

- As a member of the Tech Portfolio, I don't want us to pay for accounts we can no longer use.

## Implementation

- [x] Contact Zoom
- [x] Receive prorated refund
- [x] Notify P-Card team (due to prior concern about split transactions)
- [x] Reconcile the refund
- [x] Cancel account

## Acceptance criteria

- We are no longer paying for Zoom

**Comment by afeld** [comment]
They emailed us, so I replied, asking for cancellation and prorated refund.

**Comment by afeld** [comment]
May or may not cancel the account, even if we don't use it. Subscription is cancelled, anyway.

**Comment by afeld** [comment]
[Refund received.](https://gsa-tts.slack.com/files/U0ELDTQ6L/F016WGW38CS/screen_shot_2020-07-10_at_11.19.18_am.png)
