### ISSUE TITLE
Re-authorization GitHub 

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#47]
## User Story:
As someone managing authorizations, I want to make sure we're using an authorized version of a service. 
## Problem Statement: 
We need to make sure that this isn't going to bite us later.
## Background information: 
github.com isn't part of the FedRAMP Tailored package. 
## Actions to take:  
- [ ] Review ATO Letter
- [ ] Ensuring A&A support documentation is developed and maintained for the life of the
system.
- [ ] Ensuring adherence and proper implementation of GSA’s IT Security Policy.
- [ ] Ensuring the system is operated, used, maintained, and disposed of IAW documented
security policies and procedures.
## Acceptance criteria: 
- [ ] TTS is using an authorized version of GitHub
## Supporting Documentation:
- [GitHub Enterprise Cloud on the FedRAMP Marketplace](https://marketplace.fedramp.gov/#/product/github-enterprise-cloud?sort=productName&productNameSearch=github)
- [github.com entry in GEAR](https://ea.gsa.gov/#!/itstandards/708)
## Related Issues: 
cc #46

**Comment by pburkholder** [comment]
How did you determine https://github.com is _not_ FedRAMP authorized? At https://government.github.com/ they specifically say, "let us host the code for you on GitHub.com, whatever your security requires."

**Comment by afeld** [comment]
The FedRAMP Marketplace says “GitHub Enterprise Cloud”, which is different
from github.com (as I understand it. Worth requesting the package and/or
contacting GitHub to confirm.

**Comment by afeld** [comment]
Clarification: Enterprise Cloud is in fact a plan on github.com.

**Comment by its-a-lisa** [comment]
@afeld based on Bo's comments on the SaaS tracker (GSA IT is tracking this) & the [notes](https://docs.google.com/document/d/15p6UfCGKYtMc9yD9aFnFdCK6Gmhk6cwRNqryTcYKwss/edit?ts=5df7c722) from the GitHub meeting, should we close this issue as overcome by events?

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/271.
