### ISSUE TITLE
create roadmap for handing off p-card responsibilities

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#488]
## Background information

From [Slack](https://gsa-tts.slack.com/archives/CFQT7RP0U/p1590617608000600?thread_ts=1590617414.000300&cid=CFQT7RP0U):

> we have a high-GS-level engineer (@JJediny) handling a lot of p-card purchases on a recurring basis, and it's just not a good use of his time
>
> i don't have strong feelings about whether the p-card purchasing for software should continue to sit in the Tech Portfolio or head over to BizOps or Acquisition. i could see an argument either way.

## User stories

- As the Tech Portfolio Director, I want to ensure my staff are being utilized for things that match their skills and interests.
- As [everyone], I want P-Card purchases to happen quickly by someone who knows the ins-and-outs of the systems and can dedicate time to resolving any issues.

## Acceptance criteria

- [x] There is a clear path to having someone else take on the P-Card responsibilities, in terms of team or role
- [ ] What's being handed off is well-scoped and documented
- [ ] New issue created for the transition
   - Identify the person, if they are on staff already

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
[Update](https://gsa-tts.slack.com/archives/CFQT7RP0U/p1591912378004000?thread_ts=1590617414.000300&cid=CFQT7RP0U) from @HuixianXu.

**Comment by afeld** [comment]
Per [this message](https://gsa-tts.slack.com/archives/CFQT7RP0U/p1591992442004900?thread_ts=1590617414.000300&cid=CFQT7RP0U), the plan is for BizOps to take all P-Card responsibilities. We are in a holding pattern until that person onboards, so closing this issue in the meantime.
