### ISSUE TITLE
decommission Pulse

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#506]
- [ ] Notify any users of the system, via banner across the site, email, Slack, etc. Ideally, help them find alternatives, make sure they're off in time, etc. (The needs here will be specific to your use case.)
- [x] Export any production data and put it into Google Drive, for [records retention](https://handbook.tts.gsa.gov/records-management/) purposes.
- [x] Ask [cloud-gov-support@gsa.gov](mailto:cloud-gov-support@gsa.gov) for the cloud.gov organization to be deleted.
- [x] Delete any associated AWS resources, and decommission any AWS accounts. Ask in [#infrastructure](https://gsa-tts.slack.com/messages/infrastructure) for help.
- [x] [Archive the GitHub repositor(ies)](https://help.github.com/articles/archiving-repositories/). Ask in [#admins-github](https://gsa-tts.slack.com/messages/admins-github) if you need help.
- [x] Clean up any DNS entries that are no longer needed, from [the DNS repository](https://github.com/18F/dns) or elsewhere.
- [x] If applicable, update DNS entries to point to new urls or [set up redirect(s)](https://github.com/18F/pages-redirects#domain-redirects).
- [x] If there's a custom (second-level) domain, figure out what to do with it.
- [x] If the site was operated on Federalist, contact [federalist-support@gsa.gov](mailto:federalist-support@gsa.gov) to deprovision the [custom domain](https://cloud.gov/docs/management/custom-domains/) for the site
- [x] Notify the ISSM
- [x] Email GSA Privacy Office at [gsa.privacyact@gsa.gov](mailto:gsa.privacyact@gsa.gov) so they can take down the [SORN](https://before-you-ship.18f.gov/privacy/)
- [x] Remove (sub)accounts in external services
  - [x] Mailchimp/Mandrill
  - [x] New Relic - [#admins-newrelic](https://gsa-tts.slack.com/messages/admins-newrelic)
  - [x] PagerDuty
  - [x] Twilio
- [x] Remove any external integrations
  - [x] [Slack](https://handbook.tts.gsa.gov/slack/#integrations)
- [x] Archive the Slack channel
- [x] Archive the issue tracker (Trello, etc.)

## Acceptance criteria

- [x] No Pulse resources remain in TTS AWS account(s)
- [x] All Pulse repositories are archived or transferred from the 18F GitHub org

**Comment by afeld** [comment]
Asked cloud.gov to delete the spaces from the OGP org, but otherwise, all set!

**Comment by afeld** [comment]
Still working on deleting the S3 buckets.

**Comment by ccostino** [comment]
Thanks for the link about the lifecycle policy, @afeld!

On the cloud.gov side, everything is taken care of and removed except for the following:

- Pulse S3 bucket (and associated service key in cloud.gov)
- The space associated with pulse.

Once the bucket provisioned by cloud.gov is empty, I can remove it and then finish removing the space, which takes care of everything on the cloud.gov side.  I've kept the support ticket up-to-date as well.

**Comment by ccostino** [comment]
This work is now complete on the cloud.gov side.  All remaining cloud.gov resources related to Pulse have been removed.

**Comment by afeld** [comment]
`tts-public-data` bucket deleted from the Sandbox. All cleaned up!
