### ISSUE TITLE
Provide Feedback on TTS COR Guidance - due 6/18

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#511]
## Background information
Hey TTS CORs! New GSA policy has been drafted around the COR role and responsibilities. I wanted to share with you all so you have a chance to respond and provide feedback. https://docs.google.com/document/d/1626swlY7zxWWGha9mQKCDwp2kZs4xOzYrapAQRQzNMI/edit

You can provide feedback here https://docs.google.com/document/d/1gDqgoERw_Lvtx_uYAFDtnysAsuEoAR452kn0CQRQABg/edit#

See thread: https://gsa-tts.slack.com/archives/CDSSK1221/p1591815350030800

## Acceptance criteria
- [x] Primary Review by @JJediny 
- [x] Secondary review of comments/suggested edits by @JJediny from @afeld @its-a-lisa-at-work 
- [x] Confirm comments/feedback sent to OA

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
I took a look at the document and the feedback provided; I don't have anything extra to add.

**Comment by JJediny** [comment]
Reviewed the documentation - no comments were worth making.
