### ISSUE TITLE
Perform user interviews about the SaaS authorization process

### ISSUE THREAD

**Issue by hoaiandang** [18F/tts-tech-portfolio#512]
## Background information

This is this first phase of a project documenting the software as a service (SaaS) authorization process. https://docs.google.com/document/d/149juB9USRsvXJnRSfe2oFgGipnUjyjunwKDAbb-5M0g/edit
 
Currently, it is difficult for vendors to understand the steps of the authorization process, what they need to do/understand, how much it will cost them, how long it will take, among other things. Members within other agencies and TTS also often want to know how to start using a new product, and we don't have any easy answers to those questions. We hope that this document will help.

## User stories

As someone trying to create a more streamlined document laying out the SaaS authorization process, I want to understand the knowledge, experiences, frustrations, and pain-points surrounding to clarify this process.

## Acceptance criteria

- [x] Interview at least two members from TTS
- [x] Interview at least two members from non-TTS GSA folks
- [x] Interview at least two Vendors

**Comment by its-a-lisa-at-work** [comment]
@hoaiandang what is blocked/watching about this card? Or should this be in the Epic column?

**Comment by afeld** [comment]
Cleaning up Epics.
