### ISSUE TITLE
Prepare for P-card tbd transition

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#514]
## Background information
As a result of the Tech Portfolio hastily taking over Pcard buys of TTS SaaS; user accounts for managing billing are currently split between a shared 1.`tts-software@gsa.gov`/`devops@gsa.gov` or 2. The Pcard holders' GSA Google Oauth. 

In order to be ready for a future transition of a new P-card holder. We need to transition all accounts to `tts-software@gsa.gov` so that there is team based access and auditability for access and invoicing for the accounts managed.

## User stories
As a Pcard holder, I do not want to be a single point of failure for account access and secondarily want the team to have emergency access in case of absence or emergency need, as well as to facilitate transferring to any new billing manager. 

Shared accountability and auditability of access to the account(s). 

## Implementation Steps
- [x] Change all direct Google Oauth SSO to `tts-software@gsa.gov`
- [x] Where feasible enable 2FA via QR code OTP - storing the QR image in a locked down but shared google team drive for its sole purpose/use.
- [x] Create a shared/synced keepassxc password to the google team drive ^; using `Google Drive File Stream` to manage a desktop sync to the database with other team members.
- [ ] Ensure all invoicing is fwd to `tts-software@gsa.gov`
- [ ] All of Melanie and John's Pegasys logs are reconciled and invoices are uploaded
- [ ] Recurring logs in the Micropurchase Sheet are accurate and up-to-date

## Acceptance criteria
- [ ] All recurring invoices are sent to one place
- [ ] It will be easy to hand off logging in as the billing manager to SaaS

**Comment by afeld** [comment]
[We expect the new person to join mid-September.](https://gsa-tts.slack.com/archives/CFQT7RP0U/p1595126863000500?thread_ts=1590617414.000300&cid=CFQT7RP0U)

**Comment by afeld** [comment]
cc https://github.com/18F/tts-tech-portfolio/issues/1019 re: KeePass

**Comment by melanienleopold** [comment]
Meeting with Ethan to determine how to fix dates in the micropurchase sheet.

**Comment by melanienleopold** [comment]
Closing in favor of [#1148](https://github.com/18F/tts-tech-portfolio/issues/1148)
