### ISSUE TITLE
change primary branch names

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#519]
## Background information

https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/

## Implementation steps

- [x] Notify team(s) about changing their local clones
- [x] Ensure all Federalist sites still build

## Acceptance criteria

- [x] Primary branches for [all Tech Portfolio repositories](https://github.com/18F/tts-tech-portfolio/blob/master/how_we_work/github.md) are changed from `master` to `main`

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
https://github.com/github/renaming

**Comment by afeld** [comment]
[Changed the default branch for new repositories in the 18F org to be `main`.](https://github.com/github/renaming#from-master-to-main-on-october-1-2020)

**Comment by afeld** [comment]
Seems [aws-admin](https://github.com/18F/aws-admin) was changed, which revealed some things that needed to happen in the Terraform GitHub configuration:

- The `master` branch shouldn't be deleted (or should be re-created) until the `apply` is run again.
- The file on the new branch needed to be imported. For example,

   ```sh
   t import 'module.repo["aws-admin"].github_repository_file.issue_templates["general.md"]' aws-admin/.github/ISSUE_TEMPLATE/general.md
   ```

**Comment by adborden** [comment]
I re-imported the repos whose branch changed in terraform.
```
while read repo; do
terraform state rm "module.repo[\"${repo}\"].github_repository_file.issue_templates[\"general.md\"]"
terraform import "module.repo[\"${repo}\"].github_repository_file.issue_templates[\"general.md\"]" ${repo}/.github/ISSUE_TEMPLATE/general.md:main
done <<EOF
ghad
bug-bounty
private-eye
pages-redirects
chat
aws-admin-cleanup
before-you-ship
uswds-jekyll
vulnerability-disclosure-policy
tts-tech-portfolio-private
EOF
```

**Comment by adborden** [comment]
All PRs have been merged, moving this to `Done`.
