### ISSUE TITLE
EPIC?: TTS ownership of shared applications

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#53]
We have a couple of applications that were built and are maintained by 18F, but really are TTS-wide.

- [Standup bot](https://github.com/18F/standup-slack-bot)
- [Tock](https://tock.18f.gov/) - https://github.com/18F/tock/issues/924
- [Handbook](https://handbook.18f.gov) - https://github.com/18F/handbook/issues/1513
- [Charlie](https://github.com/18F/18f-bot)

We need to:

1. [ ] Confirm with TTS Ops that we still want/need them, that "ownership" can be transferred, and our plan to maintain them
1. [ ] Get a TTS prototyping org in cloud.gov
1. [ ] Transfer the applications in - Tock needs its own

See also:

- [TTS orgs in cloud.gov](https://docs.google.com/spreadsheets/d/1Bdzl9n2E1MXWV4elXvZ-nYuZmmEj4PEU-u5aZlNGZF4/edit#gid=1352278899)
- #52

**Comment by its-a-lisa** [comment]
> Maybe something y'all can team up with the <#C02FPFGBG|bots> channel to make happen? Not trying to add more, but it does seem a simpler solution long-term.
<sub>[View in Slack](https://gsa-tts.slack.com/archives/CPELKUPDX/p1574357760001900)</sub>

**Comment by afeld** [comment]
Let's split this up into smaller issues.

**Comment by afeld** [comment]
Closing as stale.
