### ISSUE TITLE
consolidate how we share out

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#535]
## Background information

There are a number of avenues for how we share news from the Tech Portfolio:

- Weekly by Tues 2pm: Slides for the TTS Business Weekly
   - Audience is TTS leadership, but I've been cross-posting into #infrastructure
- Every week: Solutions SMT
- Every other Wednesday: TTS Bi-Weekly Collaboration
- Every other Thursday: Sprint Review
- Monthly: TTS Newsletter
- Every other week: Sol Sentinel
- Monthly: (18F) Engineering Eagle
- Ad-hoc announcements in Slack and/or to tts@gsa.gov
- All-Hands (TTS or Solutions)

That seems like too many 😄 

cc https://github.com/18F/tts-tech-portfolio/issues/243

## User stories

- As a member of TTS, I want information from the Tech Portfolio about changes that affect me.
- As a member of the Tech Portfolio, I want to ensure updates are seen by the relevant folks and that time spent on them is high-value.

## Implementation Steps
**Initial tasks**
- [x] Think of how to solve the problem
- [x] Come up with an idea to solve the problem
- [ ] Explore solutions for the problem

**Tech Portfolio related tasks**
- [x] Set up form for Tech Portfolio Members can provide updates for the activity they're working on
  - [x] Create a mock-up form
  - [x] Write up instructions for form
  - [x] [Share](https://gsa-tts.slack.com/archives/CNW3GL70S/p1598889925083900) form with team members

**Audience related Tasks**
- [x] Determine who the audience is
- [x] Spitball at which information which audience might need/want to see

**Platform related Tasks**
- [x] Create a team hub as a front facing portal
  - [ ] General
      - [ ] [Navigation](https://app.smartsheet.com/dashboards/c5mxgV7H2rqxfGxXhg8mwmVGpMjmvVPwMV8vhcW1) 
     - [x] [Shortcuts](https://app.smartsheet.com/dashboards/JxRGgxJjQxG3hHPjR3RXQGXWHV8242JJm75WmMR1)
     - [x] [Quicklinks](https://app.smartsheet.com/dashboards/mf8xqFCH3CP7HhH4fq3w3vP9468rFpW4GpxJj5g1)
     - [ ] [Open Questions](https://app.smartsheet.com/dashboards/wch9cPh57RV9mM9cWrc8mhq6P322xp6pcrhwrmp1)
     - [x] [Announcements](https://app.smartsheet.com/dashboards/HF4H8c6J5hM6jgcG5GgJg2w9Rx6qgcpppGWHHfp1)
     - [x] [Feedback](https://app.smartsheet.com/dashboards/gR4wcMRPq777269wRmPXFmPQMHJwW5jqvmwGMMp1)
     - [ ] [Pulse Check](https://app.smartsheet.com/dashboards/MgQ34RqP9QVqVf2f6qp9fVcpVWX678xgjM9cCw31)
  - [ ] Individuals related
      - [x] [Availability](https://app.smartsheet.com/dashboards/HF4H8c6J5hM6jgcG5GgJg2w9Rx6qgcpppGWHHfp1)
  - [ ] Team 
      - [x] [pictures](https://app.smartsheet.com/dashboards/V7WW2JgqPHR2PC3MXrfcfHCx27qr7cfh7Q23w2M1)
      - [x] [calendar](https://app.smartsheet.com/dashboards/HF4H8c6J5hM6jgcG5GgJg2w9Rx6qgcpppGWHHfp1)
         Meetings
         - [ ] [Action Items](https://app.smartsheet.com/dashboards/VxQmgRrF7rW4mWm8WhrpvWrQW9228prr6R4Wc8h1)
         - [ ] [Good News](https://app.smartsheet.com/dashboards/VxQmgRrF7rW4mWm8WhrpvWrQW9228prr6R4Wc8h1)
         - [ ] [Minutes](https://app.smartsheet.com/dashboards/VxQmgRrF7rW4mWm8WhrpvWrQW9228prr6R4Wc8h1)
      - [ ] Initiatives
        - [ ] [Overall Status](https://app.smartsheet.com/dashboards/fJ7qcqqFJJ3H5X69qm3p9fJQM6XfJFf25GXvHW41)
        - [ ] [Initiative Owner](https://app.smartsheet.com/dashboards/fJ7qcqqFJJ3H5X69qm3p9fJQM6XfJFf25GXvHW41)
- [x] Create a sheet that form responses will feed into
  - [ ] Make design decisions
     - [ ] Initiative Sheet
     - [ ] Initiative Report 
     - [ ] [Initiative Dashboard](https://app.smartsheet.com/dashboards/gXxQCW9pcvcgh78p6XjPGG4F79H66vXPPMqp5Cf1)
          - [ ] [OKRs](https://app.smartsheet.com/dashboards/XPr6JP4fmHrQgq8RM3cFGFhhP4WPqjf6rc4vH4H1)
          - [ ] [Initiative Scope](https://app.smartsheet.com/dashboards/Gv9xjHrMv29RpQMcC5CV8824G9v6r44J2QHWcGj1)
          - [ ] [Initiative Status](https://app.smartsheet.com/dashboards/Gv9xjHrMv29RpQMcC5CV8824G9v6r44J2QHWcGj1)
          - [ ] [Initiative Documents](https://app.smartsheet.com/dashboards/67pHRFJVGQ9m7x5phPmMWCgpcCpWvfC2x9X6QF21)
          - [ ] [Initiative Risk](https://app.smartsheet.com/dashboards/ph5GHM97w7XQwxG22cFPFPjvVFWfXRcjP74J8WQ1)
          - [ ] [Initiative Eisenhower](https://app.smartsheet.com/dashboards/9jpCv63m36qpWXVwXfcvXV2wVcVXwp668X2xwvQ1)
          - [ ] [Number of issues by status](https://app.smartsheet.com/dashboards/g4Rqf3CwF524RJrCm6HcVFJr2JGQfJFw2GrHf4f1)
          - [ ] [Number of issues by progress](https://app.smartsheet.com/dashboards/g4Rqf3CwF524RJrCm6HcVFJr2JGQfJFw2GrHf4f1)
- [x] Create reports from sheets that will be displayed on dashboard
- [x] Create a central dashboard 
- [x] Create a dashboard per audience group

## Acceptance criteria

- We have documented what kinds of updates are shared through each mechanism

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
One of the things I think about for every Sprint Review -- is it'd be nice if every issue we had had a short description that was an easy copy/paste when needed and didn't take any rework for the purpose of status update or having to ask someone what was happening.

**Comment by its-a-lisa-at-work** [comment]
Made some progress tonight. 

Have created a workspace in [Smartsheet](https://app.smartsheet.com/folders/2gQ7VRRV9Jw78w8q2C7hGG4GMM8ww3hrFqpFPmc1) and have a TTS Updates folder; we can update the information in one sheet and then have different dashboards for the various different meetings. Still building it out; but shouldn't take more than another 2hrs at most.

**Comment by its-a-lisa-at-work** [comment]
Considering this task done and we can open up another task if necessary.
