### ISSUE TITLE
SaaS Authorization: MaxMind

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#546]
https://docs.google.com/document/d/1YkQ4HWtI5OyUDxhIaIU8kmAUVGhQoAu63y8WEkrpKx0/edit#

## Background information

https://github.com/18F/tts-tech-portfolio-private/issues/944

## User stories

As someone on a product team in Solutions, I won't want to be surprised by items going away so that I can just focus on my work and not the authorizations of products that are needed for the work solutions. 

As someone doing SaaS Authorizations within TTS on the Tech Portfolio, I would like to only go through the authorization process for the products that have a long term future within TTS so that I don't have to waste my time. 

As someone in GSA IT Security, I would like for TTS to explain the differences when something doesn't align with a typical use case so that I can better understand what we're talking about. 

## Implementation Steps
- [x] Have internal team discussion to understand MaxMind better
- [x] Set up conversation with GSA IT Security to describe how MaxMind is similar and different to other SaaS
- [ ] Set up a conversation with Login.gov and Search.gov to understand if they are able to implement a similar solution to each other

## Acceptance criteria

- Login.gov gives the TTS Tech Portfolio a definitive answer on whether not they need this. 

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
Provided [update](
https://docs.google.com/spreadsheets/d/1MPMrCWfLX5CTVVI8hysUK8DFEKGgGw2L2W-T1jat4LM/edit?disco=AAAAGv2WgNU) to Tamara as a comment in the TTS 24 spreadsheet

**Comment by its-a-lisa-at-work** [comment]
Moving to Waiting/Feedback until we figure out a way forward with this.

**Comment by its-a-lisa-at-work** [comment]
Closing; decided with GSA IT Security that this isn't SaaS and it has an approval as a desktop application; it is in several TTS product SSPs
