### ISSUE TITLE
Hootsuite - Agency LiSaaS

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#548]
## Background information

Trying to get an ATO for Hootsuite

As the TTS Tech Portfolio SaaS Champ, I want to make sure I am capturing tasks that need to happen for each product so that nothing falls through the cracks

##  Implementation Steps
- [ ] Track progress of Hootsuite through the LiSaaS process
  - [ ] Get a clean scan back from Hootsuite
  - [ ] Sign LiSaaS ATO letter

## Acceptance criteria

- Hootsuite has a LiSaaS ATO

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
Nudged the vendor on 10/14 and got the following response "I can set up some time with our Director of Governance, Risk, and Compliance  to shed more light on the findings. As we are working towards FedRAMP Readiness in early 2021, I believe they are in the process of remediation as part of that work but Director can offer more detail."

Moving back to `Backlog` until that is scheduled; will move to `Planned` once we have a date

**Comment by its-a-lisa-at-work** [comment]
Sent an email to Hootsuite today nudging them on this

**Comment by afeld** [comment]
I believe this is done.
