### ISSUE TITLE
Director of Cybersecurity

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#560]
## Background information

During the #Eng-dev meeting, a lean coffee topic was related to Director of Cybersecurity. From that conversation..

- Next steps for director of engineering
   - Cybersecurity is different than engineering. We’re hiring a lot of folks under the INFOSEC direct hire authority.
   - Someone to achieve a vision of some sort.
   - Making compliance and security expertise available to teams.
   - Security is everyone’s responsibility, would a Director of Cybersecurity distract from that?
   - Cybersecurity is a subset under engineering, currently. Engineers are lacking the cybersecurity training.
   - Direct hiring authority was created for a purpose, and we should be hiring cybersecurity folks under that.
   - We need more advocacy for cybersecurity.
   - Director of Engineering as described is an advocate.

## User stories

As someone who is a cybersecurity professional, I want to be managed and supervised by someone who is also trained and experienced in cybersecurity so that I can have someone who deeply understand where I'm coming from be an advocate for me.

## Implementation Steps
- [ ] Do research about the Cybersecurity Direct Hiring Authority
- [ ] Talk to folks who are under the Cybersecurity DHA
- [ ] Talk to folks who their main responsibilities within TTS is Cybersecurity
- [ ] Get in touch w/ someone from #People-ops

## Acceptance criteria

- There is a prioritized list of clear, achievable tasks for the Tech Portfolio, with issues created for the top ones

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
I'd reframe this first step to be a proposal: why do we need one, why now, what would it involve, what would it mean for TTS, etc.

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/817.
