### ISSUE TITLE
Bug Bounty: Three Years In blog post - Review blog

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#591]
[Bug Bounty: 3 years In](https://docs.google.com/document/d/1v7xkzG03-r98jyXlnyxJfY7s6qbZjCvorScNjwHCxfg/edit#heading=h.pe3c1wf6svvh)

## Background information

We had a meeting in early January that had a lot of information together to begin with; and the thought was that it would be low effort/easy to turn into a blog post. The blog has finally been written and is now ready to go through the review. 

## User stories

As someone who has written a blog, I would like for it to get published so that I can share with the public the work that has been done. 

## Implementation Steps
- [x] Talk to Kristina Britt to determine where it should be posted
- [x] Talk to Sara Cope to get confirmation that it should be hosted in digital.gov
- [x] Fill out digital.gov template
- [ ] Determine if it will need an extra "escalation" review
- [ ] Complete Reviews
  - [x]  Plain language
  - [ ]  Program alignment
  - [x]  TTS strategy and messaging
  - [ ]  Escalation Review (if needed)
- [ ] Get access to editorial calendar
  - [ ]  Fill out event template
   - [ ] Develop short 2-3 sentences summary to include in event

## Acceptance criteria

- [Bug Bounty: 3 years In](https://docs.google.com/document/d/1v7xkzG03-r98jyXlnyxJfY7s6qbZjCvorScNjwHCxfg/edit#heading=h.pe3c1wf6svvh) blog post makes it through the [review process](https://docs.google.com/document/d/1drX3O-qvkxdptS4d8W4TEuRpx3sUHaasENzvT-clDOc/edit#)

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by JJediny** [comment]
Digitalgov contacts @ToniBonittoGSA @saracope

**Comment by its-a-lisa-at-work** [comment]
Filled in the digital.gov template with the [Bug Bounty Blog Post ](https://docs.google.com/document/d/1DaeiFHa9_izwAIHfDCaP5TDh_RFOQ0wPo4n7pIxFSjY/edit?ts=5f3d534f)and notified @ToniBonittoGSA that it has been done

Moved to Waiting/Feedback until something from me is needed

**Comment by its-a-lisa-at-work** [comment]
Got confirmation from @ToniBonittoGSA today that she saw this document

**Comment by its-a-lisa-at-work** [comment]
Updated all the alt text needed for the pictures

**Comment by its-a-lisa-at-work** [comment]
@afeld I tagged you in a few items in the [Bug Bounty Blog Post ](https://docs.google.com/document/d/1DaeiFHa9_izwAIHfDCaP5TDh_RFOQ0wPo4n7pIxFSjY/edit?ts=5f3d534f) doc so I assigned you to this too

**Comment by afeld** [comment]
Took a pass and made some (relatively minor) edits. Nice work!

**Comment by its-a-lisa-at-work** [comment]
Finished all of the tasks that are needed from me; tagged Karen to see if this met her mark as well. Updated the Alt Text for the new All Time graph that we put in recently.

At this point, I believe it is ready to ship, so I'm going to close the task until/unless we get pinged again.
