### ISSUE TITLE
Analyze user interviews and identify next steps

### ISSUE THREAD

**Issue by hoaiandang** [18F/tts-tech-portfolio#609]
## Background information
https://docs.google.com/document/d/12cQVcpeJTkDGQPVoe8ehUsvEqEaxrFvZ5msQz3aUVX8/edit#

This is this second phase of #538, a project documenting the software as a service (SaaS) authorization process. 
https://docs.google.com/document/d/149juB9USRsvXJnRSfe2oFgGipnUjyjunwKDAbb-5M0g/edit

## User stories

- As a member of TTS, I want to understand the problems identified by users to figure out how to solve them
- As a stakeholder, I need to see the problems in order to buy into any proposed solution. 

## Implementation Steps
- [x] Update roadmap to reflect acceptance criteria and timeline
- [x] Distill Information
- [x] Highlight main problems
- [x] Draft 2 solutions per problem
- [x] Finalize Presentation
- [x] Present to Tech Portfolio Team
- [x] Concurrently schedule stakeholders and decision-makers
- [x] Present to stakeholders and decision-makers

## Acceptance criteria

- Present the main problems of the process, the connections they might have to each other, and proposed solutions to main stakeholders and decision makers
