### ISSUE TITLE
Follow-up Storm-draining - Capacity Planning

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#614]
## Background information

https://github.com/18F/tts-tech-portfolio/issues/524

## User stories

As the Project Manager for the Tech Portfolio, I want to make sure that we are accurately accounting for all of our capacity so that we can better plan our sprints

As Sol leadership, I would like to know when the Tech Portfolio is over capacity and they are in jeopardy to complete their missions so that I can help in ways that I can. 

## Implementation Steps 
- [ ] Include anything that might be missing in Storm Draining
 - [ ] Do so by filling out the capacity tracker for 45 days
- [ ] Build out courses of action to increase capacity
- [ ] Share with Dom

## Acceptance criteria

- [ ] Have a full understanding of where each person is spending their time and concrete ways of making more efficient use of time. 

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
Per Sprint Planning, @its-a-lisa-at-work will update the card and ask for `g: accepted` once groomed

**Comment by afeld** [comment]
Consensus is to not worry about this right now.
