### ISSUE TITLE
TTS SaaS Tracking Smartsheet

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#626]
## Background information

Started doing this to help out with https://github.com/18F/tts-tech-portfolio/issues/551 task

## Implementation Steps
- [x] Compare the Google Sheet to the Smartsheet
  - [x] Update the Smartsheet 
- [x] Update Google Sheet directing folks to the Google Sheet
- [x] Update Smartsheet
   - [x] Clean up Workspace
        - [x] Keep only the main files useful for all people to go to in the top layer of the Workspace
        - [x] Rename previous folders to something that makes sense now for this purpose
   - [x] Clean up Sheet
       - [x] Delete conditional formatting
       - [x] Keep only the columns that exist within the historic Google Sheet
       - [x] Make Sure only the most recent and accurate data is in the sheet

## Acceptance criteria

- [x] An MVP exists for TTS SaaS in Smartsheet so TTS users know what software has been requested, approved or is expired or previously requested and denied
- [x] A meeting is set up with @melanienleopold related to the [Follow On Items](https://docs.google.com/document/d/181TOUmpDsouyNsh0JRnY3IHsD9Sg2irWBBmn7vKAqWc/edit)

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
Some user stories:

- As a member of the Tech Portfolio, I want to ensure I'm getting up-to-date information about third-party software, so that I can answer questions like "what third-party software is in use at TTS, and by whom?"
- As a member of the Tech Portfolio, I want to maintain a single list of third-party software in use at TTS, so that I don't need to manually keep information in sync in multiple places.

**Comment by its-a-lisa-at-work** [comment]
Supporting information: https://docs.google.com/spreadsheets/d/1e0qq84omixyVTXenOXAOqwSUgGkI80KdSwgoClMwk9s/edit?usp=sharing_eil&ts=5fa2bbda&urp=gmail_link&gxids=7628

**Comment by afeld** [comment]
[Meeting notes](https://docs.google.com/document/d/1Fjnn0ru55-_ItpAhm5CipE6GNlvHgy798fRxirtk9p0/edit)

**Comment by JJediny** [comment]
Suggest adding one bullet to AC:
- [ ] Confirm with a test group that anyone in TTS can publically view the dashboard and sheet (read-only) without first authenticating.

**Comment by its-a-lisa-at-work** [comment]
The [Google Sheet](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=0) is now a [Smartsheet](https://app.smartsheet.com/sheets/g2pXwW7GCVxR2W8VWmGrX9xrfx92jPj7WqVqFG41?view=grid) and a [Report](https://app.smartsheet.com/reports/QQX26C44j9MpcRR88hg8q83R8R49PV6jGp73XHm1?view=grid) is generated and displayed on a [Dashboard](https://app.smartsheet.com/dashboards/Wg7gJp6MHqJv2Gm7C5GChFqJC62GwPc4wGwW6Mx1) for folks to view what software TTS uses. 

Moving to `Waiting/Feedback` until a test group in TTS [can view the dashboard](https://github.com/18F/tts-tech-portfolio/issues/626#issuecomment-729776028).

**Comment by its-a-lisa-at-work** [comment]
Dropped the link into the FITARA slack channel to see if folks were able to access it without needing to request access and they were not. So I set up some time with a SmartSheet POC to get help on the best way to share it; it is scheduled for 0930 on 12/4.

**Comment by its-a-lisa-at-work** [comment]
Met with the Smartsheet Customer Success Manager and was provided the info that what I'm looking to accomplished can be done with groups so I requested to be a group manager within Smartsheet for TTS on the[ Smartsheet chatter page](https://gsa.lightning.force.com/lightning/r/0D5t000002PFDldCAH/view)

**Comment by its-a-lisa-at-work** [comment]
Closing this out; got confirmation from someone who already has a Smartsheet account that once I put them in the group, they were able to see the dashboard without specifically requesting Access. Created two separate issues https://github.com/18F/tts-tech-portfolio/issues/1070 and https://github.com/18F/handbook/issues/2269 since they'll need to log in at least once & then be put in the TTS (All) group to get access.
