### ISSUE TITLE
ensure all existing TTS domains have uptime monitoring

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#66]
We pay for [New Relic Synthetics](https://newrelic.com/products/synthetics) Pro - we should use it more.

#### Acceptance Criteria
Add availability monitoring to the [TTS Custom Software Single Source of Truth](https://docs.google.com/spreadsheets/d/1LGn9kZCphzf14V5HpBfV3aYjflu-k9GtHS5LmFvDywM/edit)
- [ ] public status page (if available)
- [ ] tool/service used
- [ ] slack channel for alerting (per system)

cc https://github.com/18F/tts-tech-portfolio/issues/224

**Comment by JJediny** [comment]
Many TTS programs are currently using a GSA IT provided service in Uptrends for Uptime/Availablity alerting http://uptrends.gsa.gov/

**Comment by JJediny** [comment]
Just to clarify we do not currently pay for synthetics under our new agreement, though we could put fund on the BPA to access this service.

**Comment by afeld** [comment]
Doesn’t need to be Synthetics.

**Comment by JJediny** [comment]
Closing in favor of:
- #363
- https://github.com/18F/tts-tech-portfolio-private/issues/927
- #224
