### ISSUE TITLE
Stormdraining Catchall

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#664]
## Implementation Steps
- [ ] [P-Card handoff](https://github.com/18F/tts-tech-portfolio/issues/680)
- [ ] [Automate and handoff managing SaaS to GSA IT](https://github.com/18F/tts-tech-portfolio/issues/444)
- [ ] [Get better clarity on Authorizing Official duties](https://github.com/orgs/18F/projects/11#card-43013090)
- [ ] Set up Technical Advisory Office Hours
  - [ ] Specific to Cybersecurity/ATOs
  - [ ] Specific to Engineering/Software Development
- [ ] Assign Handbook updates to @hoaiandang 
- [ ] Propose greater clarity/smaller Working Groups 
  - [ ] FSGC
  - [ ] Digital Council
  - [ ] Map out the SaaS Authorization next steps
  - [ ] Map out the Mac WG next steps

## Acceptance criteria

- [definitive thing]
- [other definitive thing]

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
we did this at the All Hands the other day; calling this closed
