### ISSUE TITLE
Determine how we manage root MFA for AWS accounts and implement

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#666]
## User Story
As the tech portfolio we want to enable 2FA for all IaaS access, at the same time we want to ensure resilience and potential on/offboarding to the team. The current tech available to the team is a OTP QR code, the available solutions are limited to using keepassxc and google drive to share encrypted access to them while providing the ability to restore access to a new device. 

## Acceptance Criteria

- [x] All QR codes are available to all Tech Portfolio

## Implementation Steps

- [x] Recoin QR codes and store them for each AWS account we own root access too - and store in shared keepass database
- [x] Recoin personal 2FA for jump account and store in a google file stream enabled folder of your personal keepass database

**Comment by afeld** [comment]
cc https://github.com/18F/aws-admin/issues/12

**Comment by amitfreeman-gov** [comment]
There are certainly pros and cons involved here which need to be considered.  The pros are generally clear, in that a defined set of folks should have the ability to log in to the root account in an emergency. 

The cons of an approach like this is that it's essentially placing the MFA in the same place as the actual password, effectively negating the Multi-Factor part of MFA (so we just have "A"), at which point we're really only preventing a brute-force attack against the account, something that's generally mitigated with a secure password anyway.

The first step in this process should involve deciding who should be the OTP holders.  It should be an extremely limited number of people, e.g. something like "The Director", "The Product Owner" & "A Senior Team Member"

Other approaches to this which mitigate the risk of sharing the OTP:
- If using a soft token, a specified pool of people securely meets, scans the QR code / loads the seed, and then the seed is destroyed as it is intended to be
- A pool of X number of hard tokens is acquired for exactly this purpose.  From the example above, let's say the 3 people named (Director, Product Owner, Senior Member) plus a reserve 4th key.  The keys can be programmed to all work as the single virtual MFA device for the aws accounts, by seeding all 4 keys with the same U2F secret.  When someone gets onboarded or offboarded, they simply return the key back into the pool.  There is no mechanism to extract the U2F secret from a key, only to program a known U2F secret onto a key.

**Comment by amitfreeman-gov** [comment]
Related to https://github.com/18F/aws-admin/issues/92

**Comment by JJediny** [comment]
All QR codes stored with AWS Master keepass database, team members have google sync setup to access. storing the QR code in the database with the password is safeguarded by the alerting of any usage https://github.com/18F/aws-admin/issues/12
