### ISSUE TITLE
Cleanup list of dead/deprecated TTS subdomain from New Relic Alerting

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#667]
## User Story
#tts-tech-portfolio-alerts is noisy

## Acceptance Criteria

- [x] We aren't getting (or are getting minimal) false positives / noise

## Implementation Steps

- [x] Remove stale/dead/deprecated subdomains that consistently return http errors
- [ ] Update [TTS Subdomains list with current status](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=1884617968)

**Comment by JJediny** [comment]
https://github.com/18F/dns/issues/412
