### ISSUE TITLE
Upgrade sites to use latest version of uswds-jekyll

### ISSUE THREAD

**Issue by hoaiandang** [18F/tts-tech-portfolio#671]
## Background information

uswds-2.0 was just merged into the uswds-jekyll master branch. We want to test this out to see if any issues arise. 

## User stories

- As someone using uswds-jekyll, I want to be certain that upgrading to uswds-2.0 won't create any bugs in my site
- As someone looking to make uswds-jekyll more opinionated, I want to know what customization options are unnecessary 

## Implementation Steps
- [x] [Eng-hiring](https://github.com/18F/eng-hiring/pull/89)
- [x] [Accessibility](https://github.com/18F/accessibility/pull/256)
- [x] [Ux-guide](https://github.com/18F/ux-guide/pull/210)
- [x] [Product-guide](https://github.com/18F/product-guide/pull/136) 
## Acceptance criteria

- Migrated 2-3 more sites (eg. eng-hiring, accessibility) and documented any potential issues and bugs

**Comment by afeld** [comment]
We actually want to switch them to use the released version of the gem (`~> 5.0`).

**Comment by JJediny** [comment]
List the specific sites to upgrade as part of the implementation steps re: 👎

**Comment by afeld** [comment]
Only outstanding thing here: https://github.com/18F/tts-tech-portfolio/issues/682
