### ISSUE TITLE
As the Office of Acquisition, I want the Tech Portfolio to manage tech contracts

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#68]
This translates to one of us becoming a Contracting Officer Representative (COR) for all TTS software and services contracts. The former mostly involves license management and invoicing, the latter is more involved. The Contracting Officers (COs) would remain in the Office of Acquisitions.

- [x] Decide on who
- [x] Get access to training system
- [x] Take FAC-COR training (8 hours) - see #fac-cor Slack channel
- [x] Confirm with Acquisition that they can be the backup, or if someone else in the Tech Portfolio should take the training
- [x] See what level of effort it would take for @its-a-lisa to refresh her training per the [TTS All-Hands](https://docs.google.com/document/d/1N4osbsZjxbNQUZCXNd706BAzWRhBlb8pfh7wAWJbnPU/edit#bookmark=id.840qgy2efjx2) as related to #123 
- [x] Get walkthrough from Office of Acquisition - they are working on additional documentation, which we can guinea pig
- [x] Determine which of [the contracts](https://docs.google.com/spreadsheets/d/1ugJMb5lzwriP0e0Jkf2GMrxbBtjrsvQkSGUJZUA5e44/edit#gid=513826371) we are going to take COR responsibilities for, vs. leaving with login.gov
- [x] COR designation letter from CO for each contract
- [x] Letter removing current COR for each contract

cc #26 @melanienleopold

**Comment by afeld** [comment]
From forthcoming team member:

> probably a good idea to get @JJediny started on the training & then I can do the same when I get on board. Down the road we can figure out who will be prime/alternate -- it can be a shared reasonability

**Comment by JJediny** [comment]
update: restarting COR training tomorrow should be completed middle of next week

**Comment by afeld** [comment]
Those sub-tasks seem large and independent enough that we should split into their own issues.

**Comment by afeld** [comment]
Would take @its-a-lisa two more classes to get GSA certification. Decision is to not bother with it right now, assuming Acquisition is ok being the backup.

**Comment by afeld** [comment]
Re: contracts, going to be the COR for the IaaS contracts right now, and possibly a TTS/Solutions-wide staffing one in the future, but that's it for now.
