### ISSUE TITLE
ask for async input on SaaS findings

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#693]
## Background information

There's a lot of ground to cover in the discussions about the SaaS findings. In order to focus the conversation a bit, I suggest we:

## User stories

As someone who wants to take action on the user research that was conducted, I would like to see follow up to happen so that I know where to focus my energy. 

## Implementation Steps

1. [ ] Pre-populate [the discussion questions](https://docs.google.com/document/d/1gsIzGLvBnxcTdxR988BS3v-Fq_Vg82ijERmpk-mDECA/edit#heading=h.cde1qwn79jc9) with things like each of the findings
1. [ ] Add instructions (how to vote, etc.)
1. [ ] Send to the attendees

## Acceptance criteria

- We have consensus with stakeholders regarding next steps for the SaaS Authorization Documentation effort

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by JJediny** [comment]
No Imp steps not AC

**Comment by afeld** [comment]
Let's convert to using the general issue template.

**Comment by its-a-lisa-at-work** [comment]
Mind if we keep this in the Backlog? I think things that are already Sprint Planned for shouldn't go back into Icebox so they stay as something that gets picked up as soon as possible.

**Comment by its-a-lisa-at-work** [comment]
Overcome by events, closing

**Comment by its-a-lisa-at-work** [comment]
Per conversation with @afeld at our 1:1 today, reopening since this still a valid issue

**Comment by afeld** [comment]
Closing as stale.
