### ISSUE TITLE
TTS Tech Portfolio DI&E Epic

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#709]
- [ ] Create a clear governance structure for the TTS Handbook
- [ ] Procedure to identify anti-DE&I activities and behaviors
- [ ] have leadership set aside time for DI&E during office hours
- [ ] Create a role within the TTS Tech Portfolio for a DI&E lead
- [ ] Specifically advertise upcoming positions at Historically Black Colleges, Women Who Code forums, etc
- [ ] Incorporate DE&I into TTS performance plan measures
- [ ] Set up a Indigenous people study day
- [ ] Set up a Women-in-tech study day
- [ ] Measure and publish diversity numbers, throughout the pipeline
- [ ] Use the a “Bias Check” tool from The Management Center

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/829.
