### ISSUE TITLE
Microrequest - SaaS ATO infographic

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#723]
## Background information

There was a thread talking about SaaS software that I thought would be good information for some Outreach support; they did a good job distilling the conversation, but my mind went to an Infographic. Around the same time, someone from 18F had asked for us to explain to another government agency about how we're able to use certain tools. This is the 3rd request of the time and since that happened at the same time as the thread, I thought the best approach would be to make an infographic of how we do things for folks who work with partner agencies can provide to their customers. 

## Implementation Steps
- [x] Meet w/ 18F PM and see if there is interest
- [x] Submit Microrequest into slack channel
- [x] Meet with designer to give background and idea
- [x] Put some ideas on to paper of what we're looking for so designer can focus on design as much as possible and not the content
- [x] Visual Designer will put some initial thoughts on paper
- [x] Tech Portfolio rep will review initial thoughts on paper that the Visual Designer is coming up with
- [x] Visual Designer will incorporate feedback and add color

## Acceptance criteria

- [x] An infographic has been created for the SaaS Authorization process

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
Moving to Waiting/Feedback while the Visual Designer puts some thoughts together based on our conversation today

**Comment by its-a-lisa-at-work** [comment]
Provided comments back on the thoughts that were submitted on [paper](https://docs.google.com/presentation/d/1s6vp4n7pR-fGGuOw23xNfxgKW-wIaLgq_nVUzhSHADM/edit#slide=id.g91c1ac7738_0_44) moving back to waiting/feedback; she has one more hour and will incorporate changes and add some coloring.

**Comment by its-a-lisa-at-work** [comment]
All steps for this task have been completed so closing; opened a new task https://github.com/18F/tts-tech-portfolio/issues/797 to do the follow up tasks
