### ISSUE TITLE
EPIC: GitHub Management

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#73]
spawned from #20
Setup A Terraform Repository (similar to https://github.com/18f/dns) for:

### Managing Github:
- [ ] Membership - https://www.terraform.io/docs/providers/github/r/membership.html
- [ ] Teams and their authorization on repos - https://www.terraform.io/docs/providers/github/r/team.html
- [ ] Repo Branch Protections - https://www.terraform.io/docs/providers/github/r/branch_protection.html?origin_team=T025AQGAN 
*suggestion by @pburkholder

**Comment by JJediny** [comment]
Iceboxing this for now
