### ISSUE TITLE
HubSpot FedRAMP Tailored

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#755]
## Background information

Working with the FedRAMP PMO and GSA IT Security to get CRM vendor through the ATO process. 

## Implementation Steps
- [x] Support SOC2 Gap Analysis
- [x] Setup Gap Analysis call
- [ ] Setup Architecture Review call
- [ ] Monitor progress of Appendix B completion

## Acceptance criteria

- [x] A go/no-go decision on whether the vendor will go ahead with FedRAMP Tailored
- [x] HubSpot provides scan results
- [x] FedRAMP process has been kicked off

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
NDA was sent to CO today from vendor through Docusign

**Comment by its-a-lisa-at-work** [comment]
- [ ] NDA signed
- [ ] Vendor provided CIS controls
- [ ] Sent information to FedRAMP POC in GSA office to get a feel of close we'd be with current state
- [ ] Meeting with vendor

**Comment by its-a-lisa-at-work** [comment]
Moving to waiting/feedback until vendor responds back to email with date that they can meet next week to review gap analysis

**Comment by its-a-lisa-at-work** [comment]
Send an email to nudge them assuring that they got the last email

**Comment by its-a-lisa-at-work** [comment]
Have a meeting set up for 12/14
- [ ] send documents passed over from Brian T.

**Comment by its-a-lisa-at-work** [comment]
We have received the go/no go answer from HubSpot and they plan on actively starting the gap assessment and other activity required to start FedRAMP but might get delayed completing it by the end of the year due to the unknown of what might have to remediated. Nate Ciano is going to talk to Bo and get back to me.

**Comment by its-a-lisa-at-work** [comment]
Additional dialogue between TTS and HubSpot on getting the scans so can process the LiSaaS

**Comment by its-a-lisa-at-work** [comment]
The LiSaaS ISSO reviewed the scans and the GSA FedRAMP POC reviewed the External Services; they are going to take their findings/assessment to GSA CISO for a way forward and get back to us. Expected time to hear back will be 1/26/21, moving to `Waiting/Feedback` until then.

**Comment by its-a-lisa-at-work** [comment]
Final decision made!

LiSaaS renewal for Hubspot Marketing Hub w/ conditions (Low Impact data, continued scans, and remediation progress) 

Marking this done at this point and will reopen if any other hiccups happen
