### ISSUE TITLE
Mural FedRAMP Tailored

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#762]
## Background information
TTS is the SaaS Champ for usage within GSA and is providing support to the GSA IT Security office to get it through the FedRAMP Tailored process. 

## Implementation Steps
- [x] Set up Introductory Meetings
- [x] Provide documentation about process
- [x] Arrange meeting for Architecture Review
- [x] Coordinate follow up meetings
- [ ] Review Appendix B documentation

## Acceptance criteria
 
- [ ] Mural has entered into `In - Process` status for their FedRAMP Tailored package

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
@afeld updated acceptance criteria

**Comment by afeld** [comment]
Messaged Brian Turnau.

**Comment by afeld** [comment]
Update as of 6/2 was that things are moving along, so closing as not actionable for the Tech Portfolio.
