### ISSUE TITLE
Consolidate incident Response Plans

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#77]
## User Story:
As a member of TTS, I don't want to have to figure out the differences per project team/system, especially in real-time. 

As a member for the Tech Portfolio, we should see where we can reconcile, to make ATOs and incident response easier / more consistent.

## Problem Statement: 
Seems that we have a number of incident response plans floating around

## Actions to take:  
- [x] Create a list of known incident response plans
- [x] Propose thinning of the cloud.gov plan
- [ ] Propose thinning of the login.gov plan
- [x] Figure out how to integrate with [Continuity of Operations Plan (COOP)](https://docs.google.com/a/gsa.gov/viewer?a=v&pid=sites&srcid=Z3NhLmdvdnxjb250aW51aXR5fGd4OjZjYzRhZDllNTA0N2U3OWI)
- [x] Clearly state required resolution times and where they come from

## Acceptance criteria: 
- [x] Obtain cloud.gov IR plan
- [x] Obtain login.gov IR plan
- [x] Obtain search.gov IR plan
- [x] Obtain data.gov IR plan
- [ ]  resolution times and where they come from are clearly stated
- [x]  setup bi-weekly meetings with interested TTS programs

## Supporting Documentation:
- https://handbook.18f.gov/responding-to-public-disclosure-vulnerabilities/
- https://github.com/18F/bug-bounty/blob/master/project-instructions.md#slas-your-program-must-meet
- [login.gov](https://docs.google.com/document/d/1a6N8DxnThYsgEay6CkeW_J0-MiphXhghUYjMQhpTAwU/edit#heading=h.kc6getqxbjzr)

## Related issues: 
cc #49

**Comment by hillaryj** [comment]
Here's the IR guide and checklist for cloud.gov:

- https://cloud.gov/docs/ops/security-ir/
- https://cloud.gov/docs/ops/security-ir-checklist/

**Comment by afeld** [comment]
From https://github.com/18F/tts-tech-portfolio/issues/49#issuecomment-518857744:

> Re SLAs, here's a document to be updated: https://github.com/18F/bug-bounty/blob/master/project-instructions.md#slas-your-program-must-meet
>
> Bug bounty refers to a 90-day SLA, but _recommends_ 7-day for high, 30-day for medium.
>
> > Though the 90-day SLA above is the only required timeline, we do (strongly) suggest that your program aims for faster remediation of more severe issues.
>
> We might want to align them better with GSA's policies.

**Comment by afeld** [comment]
Clarified this issue to be about about triaging and response, while #49 is about reporting.

**Comment by afeld** [comment]
[Notes from discussion with cloud.gov](https://docs.google.com/document/d/1UriL8JPASA32LKdlIhSB747iMSRutXb-iELZSmd84-s/edit)

**Comment by dawnpm** [comment]
Are you talking about Contingency Plans (which would include COOP) or Incident Response Plans? 

GSA uses the terms separately - Incidents are human driven (e.g., attacks, infiltrations, PII leakage), Contingencies are force majeure (e.g., the Cloud Host Has Major Problems, COOP situations). The official incident response plan is managed by the GSA IR team, so much so that there is common language for that control in the SSP templates. We are finalizing our official Contingency Plan in the GSA template, which will be posted to Google Drive. We also have an emergency procedures doc for our team's use.

**Comment by afeld** [comment]
Good point on that distinction. I think we should consider both, though maybe not at the same time.

**Comment by gbinal** [comment]
For api.data.gov, you can partially see this in how we document the process for handling abnormalities that show up in the regular monitoring.  But the process then basically says that we follow the 18F incident response process.  

https://github.com/18F/api.data.gov/blob/master/docs/procedures.md#weekly-monitoring-checklist

**Comment by dawnpm** [comment]
> Good point on that distinction. I think we should consider both, though maybe not at the same time.

Search.gov manages our own contingency plan, and uses GSA's IR plan.

**Comment by afeld** [comment]
@dawnpm Mind providing a link?

**Comment by afeld** [comment]
- [ ] Split the Contingency / Continuity of Operations plan consolidation into its own issue

**Comment by hillaryj** [comment]
Per discussion at the wg-security meeting, @its-a-lisa will be leading the unification of IR plans from the TTS Tech Portfolio side. She'll coordinate simplifying the plans into one base plan with addendums.

**Comment by dawnpm** [comment]
> @dawnpm Mind providing a link?
@afeld sure - 

Search.gov Contingency Plan (permissions managed by ISSO team): https://docs.google.com/document/d/1f6tAETRm8l8lvhd64YtSRw3_chg0FayDKFqDk7TNlqg/edit

GSA IR guide: https://insite.gsa.gov/cdnstatic/insite/Incident_Response_%28IR%29_%5BCIO_IT_Security_01-02_Rev_17%5D_03-20-2019_Signed_BB.docx

**Comment by mogul** [comment]
We ran an IR exercise for data.gov this week, and just did a retro; [notes are here](https://docs.google.com/document/d/1b3oRB-JD056REaSfHcmdRB5NPAWVqQh-onfvHihHb4g/edit?usp=sharing). 

One of our action items was to follow up and make sure y'all know we really want this consolidation. It's confusing to have our own process, and then have to fork up/out to the broader TTS process, which results in a lot of redundant comms juggling as well as documentation overload in-the-moment.

**Comment by pburkholder** [comment]
Back to @hillaryj 's point, cloud.gov has _four_ guides actually:

https://cloud.gov/docs/ops/security-ir/ - the documentation
https://cloud.gov/docs/ops/security-ir-checklist/ - what's supposed to be quicker in real-time process guide
https://cloud.gov/docs/ops/service-disruption-guide/ - incidents that aren't security incidents
https://cloud.gov/docs/ops/contingency-plan/ - sustained loss of services we depend on

I would like to see consolidation so we start with "Service disruption" and then follow paths depending on what the source of the disruption is.

**Comment by its-a-lisa** [comment]
Closing this issue today based on[ today's meeting](https://docs.google.com/document/d/1VvazOud-Cuc1CZbhqoNaSGL2pm_6CvXZiELkxME4a44/edit?disco=AAAAEEbw5Xc). 

Opened up new issue to continue on this effort: https://github.com/18F/tts-tech-portfolio/issues/229
