### ISSUE TITLE
Explore the GSA Infrastructure Request process

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#771]
## Background information

Related conversation in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1598290277043200)

## User stories

As someone managing Infrastructure within TTS, I would like to know more about the service provided with GSA so I know how we should be interacting with them. 

## Implementation Steps
- [ ] find out how this relates to the Website & Platform Management Branch
- [ ] Set up a call with this team to get an intro/briefing
- [ ] Better understand their workflow

## Acceptance criteria

- [definitive thing]
- [other definitive thing]

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/1169.
