### ISSUE TITLE
FIDO hardware for login.gov staff

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#796]
##  User Story
A TTS team is looking to procure FIDO keys that are FIPS 140-2 compliant for their devops members (~12 headcount) to better control IaaS access. We'd also like to make them available to other teams at TTS with similar needs in the future (~50-100 potentially).

As the p-card holder for TTS I'm looking for preferred hardware. We were originally looking at Yubikey (https://www.yubico.com/product/yubikey-fips-pack-of-11), but Anil mentioned there is a preference for Google's titan key, which would also meet the need. 

## Acceptance Criteria

- [x] FIDO keys ordered

## Implementation Steps

- [x] Determine if GSA IT has an existing means to procure these, such that we could reimburse GSA IT for the cost and services as part of the overall hardware/mac distribution process?
    - [ ] If not is there a process/vendor you could point us to - to make the direct buy?
- [x] Determine which FIDO (FIPS compliant) device to go with 

- Create a follow up issue to track allow for future use with Google Oauth SSO to potentially leverage them to add 2FA for third party SaaS?

**Comment by afeld** [comment]
- [ ] login.gov submit purchase request

**Comment by JJediny** [comment]
Purchase Made
