### ISSUE TITLE
SaaS Infographic Update

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#797]
Follow up to https://github.com/18F/tts-tech-portfolio/issues/723

## Background information

There was a thread talking about SaaS software that I thought would be good information for some Outreach support; they did a good job distilling the conversation, but my mind went to an Infographic. Around the same time, someone from 18F had asked for us to explain to another government agency about how we're able to use certain tools. This is the 3rd request of the time and since that happened at the same time as the thread, I thought the best approach would be to make an infographic of how we do things for folks who work with partner agencies can provide to their customers. 

## Implementation Steps
- [ ] Share with others
  - [ ] TTS Tech Portfolio
  - [ ] CTO's Office
  - [ ] SaaS WG
  - [ ] Partner agencies (USPTO, DOJ, ect)

## Acceptance criteria

- [ ] Infographic has been cleaned up and is ready to send to users when prompted

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by JJediny** [comment]
https://gsa-tts.slack.com/archives/GP559GCLD/p1597162959005000

**Comment by its-a-lisa-at-work** [comment]
https://docs.google.com/presentation/d/1s6vp4n7pR-fGGuOw23xNfxgKW-wIaLgq_nVUzhSHADM/edit#slide=id.g94dff989fd_0_60

**Comment by afeld** [comment]
There are a few other flowcharts floating around:

- Micropurchases
- A general one for acquisitions
- [TTS Software Procurement](https://gsa-tts.slack.com/archives/GP559GCLD/p1587698048006400) and [background](https://docs.google.com/presentation/d/1b8rfJT3JVvt2kNH0jRu_PVknJD6FyhSbdhD5IRWr1YA/edit)

We'll link here when we find them. Seems like they could be consolidated with a little effort.

**Comment by afeld** [comment]
See also: [acquisitions guidance from Security team](https://docs.google.com/document/d/1ZUEKGeHiC99D75lBab905B9EG0Op9NWiPIxHnlJOYgQ/edit)

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/tts-tech-portfolio/issues/1237 and https://github.com/18F/tts-tech-portfolio/issues/1259.
