### ISSUE TITLE
review MAX.gov analysis - due 9/3

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#812]
## Background information

We are meeting to talk about MAX on Friday; need to prep and absorb what's been produced.

## Acceptance criteria

- All MAX transition documentation has been read

## Implementation steps

Read the following:

- [x] [Collaboration Capabilities Binder](https://gsa-tts.slack.com/files/UPV2P4KN0/F018K9F8P42/collaboration_capabilities_binder.pdf)
- [x] [Phase 1 report](https://gsa-tts.slack.com/files/U0M62U3EU/F018ELW43QS/max_phase_1_assessment_report_may_2020__1_.pdf)
- [x] [Tollgate review](https://community.max.gov/download/attachments/1594822673/OMB%20Tollgate%20Meeting%20-%20MAX.gov%20Assessment%202020-05-12.pptx?version=1&modificationDate=1590064185312&api=v2)
- [ ] Analyses of Alternatives (AoA)
   - [ ] [Assumptions](https://docs.google.com/document/d/1kM4blRIp7FVgDpop9Gfh9MNzKlv9tC0sKd9lXyrp4Iw/edit)
   - [ ] [Analytics](https://community.max.gov/x/TDqmg)
   - [ ] [Authentication](https://community.max.gov/x/tzumg)
   - [ ] [Collaboration](https://community.max.gov/x/NRC6fw)
   - [ ] [Data Collection](https://community.max.gov/x/fzqmg)
   - [ ] [Custom Services](https://community.max.gov/x/3EKSg)
   - [ ] [PaaS](https://community.max.gov/x/WfTYfw)
- [ ] ISDC Lead Agency Coordination Portal - see email `RE: Invitation: GSA/OMB Discussion: ISDC Lead Agency Tool`
---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
Felt like I had enough information for the meeting I was trying to prepare for, even without getting through all the docs. Given the focus is on the program management rather than the systems in the near term, not going to worry about reading through the rest right now.
