### ISSUE TITLE
EPIC: Secret Management

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#84]
**acceptance criteria:**
- [ ] solution must leverage FEDRAMP approved services for the secret store/vault (e.g. AWS KMS)
- [ ] solution/procedure must protect the secret from leakage in CI
    - [ ] an honest mistake by the development team
    - [ ] malicious actor - changes ci config or code to expose/print it in the output of automated CI build as a Pull Request. 

**references:**
- https://github.com/fugue/credstash
- https://github.com/winebarrel/gcredstash
- https://github.com/mozilla/sops
- https://secrethub.io/ 
- https://git-secret.io/

**Comment by afeld** [comment]
What kinds of secrets you have in mind? I think most projects have been using [environment variables in CircleCI](https://circleci.com/docs/2.0/env-vars/), which [does have FedRAMP Tailored/Li-SaaS](https://marketplace.fedramp.gov/#/product/circleci-cloud?sort=productName&productNameSearch=circleci).

**Comment by JJediny** [comment]
Agreed, created this issue to get that ^ documented; also to track our conversations with GSA GRACE for establishing an accepted process for managing "secrets in CI" at GSA with Secops concurrence/support.
