### ISSUE TITLE
ion channel - system selection

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#852]
## Background information

The question was posed... will we keep our current accounts? I believe we will, but not sure...to get a better answer to that; will work on various steps.

## Implementation Steps (no particular order)

- [ ] Chat with TTS engineer
- [ ] Get initial instructions from Ion Channel
- [ ] Make announcement about tool
  - [ ] #dev
  - [ ] #solutions-dev
- [ ] Include in newsletters
  - [ ] #18f-engineering
  - [ ] #TTS
- [ ] Update internal documentation to reflect tool
  - [ ] TTS Tech Portfolio account management
  - [ ] TTS Tech Portfolio  Onboarding documentation
  - [ ] TTS Tech Portfolio  OpsRotation
  - [ ] Handbook
  - [ ] Before You Ship
  - [ ] 18F Engineering Guide
- [x] IT Standards
  - [x] New Software Request
  - [x] LiSaaS ATO
  - [x] FITARA
- [x] P-card purchase

## Acceptance criteria

- [ ] Documented how/when/why to use SBOM tool

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
Got an email from Ion Channel with the following asks

- [ ] A set of GitHub repos you’d like added to the pilot as the project portfolio to analyze and monitor - let us know if you want the 18F repos in there as well.
- [ ] Set up a meeting for next week

@18F/tts-tech-portfolio requesting that this get reviewed for acceptance so I can work this into the Sprint this week

**Comment by its-a-lisa-at-work** [comment]
Moving to `Blocked/Watching` until https://github.com/18F/tts-tech-portfolio/issues/935 is completed

**Comment by its-a-lisa-at-work** [comment]
Provided the list of systems, going to close this issue and move the rest of the tasks into a new issue to be done once it gets an ATO
