### ISSUE TITLE
OGP cowork FedRAMP memo

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#854]
## Background information

TTS office and OGP have been discussing removing the barriers to getting emerging technology FedRAMP authorizations. The recommendations don't seem to be convincing enough for the deep impact they'll have, so it was mutually decided that a more collaborative approach should be taken to have better use-cases backing up the change. 

## Implementation Steps
- [x] Provide a list of SaaS that have gone through the ATO process
  - [x] List ones that we had to drop because company didn't want to proceed
  - [x] List of ones that we determined didn't need to go through FedRAMP
  - [x] List ones that others have had a large interest in

## Acceptance criteria

- [x] TTS and OGP have worked through the different types of technology and have had a discussion of how that might feed into FedRAMP authorization

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
Completed task and will still engaged with OGP. The next step is that they will book a meeting with the FedRAMP office. I told them that I support the approach and will have reservations, that will probably never go away, but that they have convinced me well enough that I don't need to be a blocker and will provide the advocacy going forward.

**Comment by afeld** [comment]
Glad it's moving along! Curious to see how the conversation goes.
