### ISSUE TITLE
Update onboarding documentation

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#857]
## Background information

During some discussions, a new employee has noticed that the onboarding material didn't cover or include him in certain areas. 

## Implementation steps
- [x] Update documentation to include new employee in these areas
  - [x] workflow.md
  - [x] the form
- [x] Update onboarding documentation instructing someone to update the following docs when someone new joins the team
  - [x] workflow.md
  - [x] the form
- [x] Next onboardee provides feedback

## Acceptance criteria

- [x] Onboarding documentation more accurately reflects what someone joining the team today would need to know

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
The form portion was handled by https://github.com/18F/tts-tech-portfolio/pull/945 assigning to @afeld as PM to do the workflow portion

(didn't realize this issue existed when I did the form part, or I would have done the workflow as well)

**Comment by afeld** [comment]
@adborden said they seem ok (there have been updates since), so going to close for now.
