### ISSUE TITLE
Single line of communication for TTS system owners

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#87]
For cross-TTS notifications/data-calls, we need an established line of communication that is trusted to reach all TTS system owners and their backups (ideally a dedicated `system@gsa.gov` for each system, not a list of individuals to avoid turnover management). 

#### Acceptance Criteria:
- [x] Establish TTS Systems have a dedicated google group with all federal team members and optionally contractors.
- [x] Identify preferred slack channel for general with tech portfolio.
- [x] Update contact information into [TTS System Source of Truth Spreadsheet](https://docs.google.com/spreadsheets/d/1LGn9kZCphzf14V5HpBfV3aYjflu-k9GtHS5LmFvDywM/edit#gid=1961439299)

**Comment by its-a-lisa** [comment]
[Source of Truth](https://docs.google.com/spreadsheets/d/1LGn9kZCphzf14V5HpBfV3aYjflu-k9GtHS5LmFvDywM/edit#gid=1961439299) for systems

**Comment by JJediny** [comment]
Sent out the System inventory form awaiting responses

**Comment by JJediny** [comment]
Added the responses to TTS software SOT
