### ISSUE TITLE
Consolidated Sync - Clarity

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#875]
## Background information

Released tool without providing clear information on it. Still some fuzziness around it. 

## Implementation Steps
- [x] Make usable now for outreach
- [x] Delete dummy data
- [x] Make some instructions

## Acceptance criteria

- [x] It is clear how we should be using the tool
- [x] The documentation reflects reality for tool

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
I had an idea around the form: Instead of asking where the message should go, what if we focus on who it's relevant to? In other words, instead of asking "TTS Newsletter?", ask "Is this relevant to all of TTS?" Some example questions:

- Who is this relevant to? Examples:
   - TTS leadership
   - Solutions leadership
   - Everyone in TTS
   - A random segment of TTS (e.g. Office users)
   - Engineers
   - Etc.
- Does this require an action?

**Comment by its-a-lisa-at-work** [comment]
Updated instructions in https://github.com/18F/tts-tech-portfolio/pull/945 and created a [deck](https://docs.google.com/presentation/d/1Jgk4ZQIvCEGJoPRzdUhh4dUJZ1TbPu6DKXM-FWAykYs/edit#slide=id.ga6a5932261_0_1226) to provide some clarity for for Outreach 

Moving to Waiting/Feedback until it is used for two sprints before closing

**Comment by afeld** [comment]
- [ ] Field to link to relevant GitHub issue

**Comment by its-a-lisa-at-work** [comment]
Set up time between me and @afeld for today at 1400 ET

**Comment by afeld** [comment]
- [ ] Review https://github.com/18F/tts-tech-portfolio/pull/945

**Comment by afeld** [comment]
Updated! Waiting on the updates to our documentation: https://github.com/18F/tts-tech-portfolio/pull/1008
