### ISSUE TITLE
decommission OpsGenie - due 11/4

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#876]
## Implementation Steps

- [x] Find ATO expiration - July 20th
- [x] Mention to ServiceNow team - @afeld
   - [x] Include @josephderosales on email
- [x] Split out issue around investigating alternatives
- [x] A tool is identified to replace OpsGenie moving forward

## Acceptance criteria

- [x] TTS stops using OpsGenie by 7/20

**Comment by its-a-lisa-at-work** [comment]
Had conversation with vendor and dropped notes from it in our [Slack](https://gsa-tts.slack.com/archives/GP559GCLD/p1605547870007600)

Result: 
- Don't have a solid answer of whether or not OpsGenie is going to go through the FedRAMP Tailored process within the needed timeline

Action Items:
- [ ] Brian Turnau is going to link up with GSA IT to understand their needs and see if there is any overlap of needs to see what the consolidated approach should be
- [ ] Phoebe from Atlasssian is going to provide a roadmap timeline 

Current status: At this time, no action for TTS until the above two are completed; moving to `Blocked/Watching` until then

**Comment by its-a-lisa-at-work** [comment]
Scheduled meeting for next week, moving back to `Ready`

**Comment by its-a-lisa-at-work** [comment]
Setup meeting for next week

**Comment by its-a-lisa-at-work** [comment]
- [ ] Send @josephderosales the contacts for OpsGenie for him to reach out to them and understand their roadmap

**Comment by afeld** [comment]
[Notes from a conversation with the Corporate IT team](https://docs.google.com/document/d/1hJOel3rTbUi6jJhlgkxcHBtKKS8jRzn5yu9XbADxFpo/edit)

**Comment by josephderosales** [comment]
FAS programs such as FCS currently use ServiceNow and have published a GoogleSite for intake and support inquiries

https://sites.google.com/a/gsa.gov/gsafcs/request-report

**Comment by josephderosales** [comment]
@afeld What TTS programs currently use OpsGenie? If someone can provide a POC list, I can set up an initial meeting with ServiceNow admin for an initial discussion around TTS needs and available ServiceNow capabilities.

**Comment by afeld** [comment]
[ServiceNow may be a viable alternative.](https://docs.servicenow.com/bundle/paris-it-service-management/page/administer/user-administration/concept/c_OnCallScheduling.html) [Comparison.](https://www.getapp.com/it-management-software/a/service-now-com/compare/opsgenie/)

**Comment by afeld** [comment]
Let the ServiceNow team know we'd be interested in that functionality.

**Comment by afeld** [comment]
Collecting what programs are using OpsGenie as part of [ServiceNow requirements](https://docs.google.com/spreadsheets/d/1v8mw5grwDkuklUmL7z3FfDMNSBUMQczRBGpjpy8PM1o/edit#gid=0).

**Comment by rocheller123** [comment]
ATO has been extended for an additional 2 months while teams transition to ServiceNow.
