### ISSUE TITLE
EPIC: Automated Alerting

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#88]
* Assess the need for an 18f handbook comprehensive guide/checklist for establishing an `Alerting` program for your "system".
* Stress the preference of alerting over the manual review of logs/GUIs.
* Make the security model/mapping explicit/inheritable/reusable for new systems/teams.
https://search.usa.gov/search?utf8=%E2%9C%93&affiliate=tts-handbook&query=alert&commit=

- [ ] Start by collecting current examples from TTS SSPs 
- [ ] Coordinate a review with GSA Secops for examples/expectations/requirements

**Few examples to flesh out a list for**
## Security Alerts
- [ ] failed ssh attempts
- [ ] client requests for Server Side Request Forgery (SSRF) - to protect against metadata leakage/ escalations. See example https://krebsonsecurity.com/2019/08/what-we-can-learn-from-the-capital-one-hack/. Example alert on requests containing `/latest/meta-data/` https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html.
- [ ] Package/Application vulnerability alerts (e.g. synk/cert/component RSS feeds, etc)
- [ ] ...many more examples...

## Performance Alerts
- [ ] Availability (i.e. use of Uptrends/New Relic/Statuspage/etc for outages/uptime monitoring)
- [ ] Application Performance Monitoring (i.e. use New Relic APM) for insight into programming errors/performance.
- [ ] ...many more examples...

**Comment by afeld** [comment]
cc #88

**Comment by afeld** [comment]
Just learned that [CloudWatch now supports anomaly detection](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Anomaly_Detection.html).
