### ISSUE TITLE
SaaS Authorization: Code Climate

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#884]
## Background information

Need to move forward with Code Climate

## Implementation Steps
- [x] Set up meeting
~~-[ ] Attend meeting~~
- [x] Receive SaaS Solution Profile
- [x] Sign SaaS Solution Profile
- [ ] Determine next steps

## Acceptance criteria

- [x] CodeClimate has filled out the SaaS Solution Profile
- [x] GSA has determined the risk of Code Climate

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
Moving into Waiting/Feedback until we get the SaaS Solution Profile back
