### ISSUE TITLE
update strategic plan

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#890]
- [Old](https://docs.google.com/document/d/1837NxtM5nJeYCQIf5qpTzYiQAOnGHg0_LYvO5cgTYMM/edit)
- [New](https://docs.google.com/document/d/1D8NjruISqW6A9rXu6EBN28JWyHyjHjGM/edit#)

## Background information

While it, at a glance, still ~80% matches what I have in mind, things have changed since July, notably around / due to MAX/budget stuff. Needs to be revised.

## Implementation steps

- [x] Fill out template
- [x] Ask team for feedback
- [x] Notify Pia
- [x] Ask for feedback from stakeholders
- [x] Update Handbook page using new info
- [x] Ensure there are issues for milestones and metrics

## Acceptance criteria

- [x] Roadmap with goals laid out

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
cc https://github.com/18F/tts-tech-portfolio/issues/1055

**Comment by afeld** [comment]
Using the [Business Plan template](https://docs.google.com/document/d/1D8NjruISqW6A9rXu6EBN28JWyHyjHjGM/edit#) being used for all the Solutions portfolios.

**Comment by afeld** [comment]
Due date ended up not being necessary.

**Comment by afeld** [comment]
Business Plan is "done enough" — will continue to tweak as needed. Split out https://github.com/18F/tts-tech-portfolio/issues/1428 for the metrics work.
