### ISSUE TITLE
New Relic Billing Structure and BPA Option Renewal - due 4/01

### ISSUE THREAD

**Issue by melanienleopold** [18F/tts-tech-portfolio#893]
## Background information

New Relic is updating their billing structure to bill per user instead of usage per product. OA and the COR on the contract had a call ([meeting notes here](https://docs.google.com/document/d/18DDL3JDL6n2iT_LXrpHn-cr875YNwu4WDohoEPOSF-8/edit?ts=5f860b20)) with New Relic and Carahsoft on 10/13 to discuss the changes. The Powerpoint below reflects the changes.
[GSA_TTS_NR1_10_13_20.pptx](https://github.com/18F/tts-tech-portfolio/files/5378897/GSA_TTS_NR1_10_13_20.pptx)

## Implementation steps

- [x] The Tech Portfolio meets with New Relic and understands the changes that are happening.
- [x] TTS estimates how many users we would need to pay for.

## Acceptance criteria

- [x] Contract modified to reflect updated pricing model

**Comment by melanienleopold** [comment]
Waiting on New Relic to get us the summary of the modifications that would need to happen to the contract and how much it would cost TTS.

**Comment by melanienleopold** [comment]
Working with Melisa on the modification to the contract.

**Comment by melanienleopold** [comment]
Waiting on vendor signature
