### ISSUE TITLE
decide on SSO provider

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#92]
## User stories

- As the Tech Portfolio, we want to use a single sign-on provider that works well with our SaaS

## Background

Our plan thus far for https://github.com/18F/tts-tech-portfolio/issues/19 has been:

login.gov -> Cognito -> `[other SaaS/IaaS]`

Unfortunately, SAML isn't as standardized as we thought. Integrating login.gov with Cognito hasn't worked out of the box, but login.gov is thankfully willing to (quickly) try out changes to support it. I worry that we won't be so lucky when trying to integrate Cognito with other things.

Therefore, it would behoove us to use an authentication provider that is explicitly supported by the majority of SaaS/IaaS we use.

## TODOs

- [ ] Go through [the TTS SaaS inventory](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=0) and expand the list in https://github.com/18F/tts-tech-portfolio/issues/19 that support single sign-on (SSO; can move it to a spreadsheet if that's useful)
- [ ] For each in that list, collect which SSO providers are explicitly (read: well) supported by each
- [ ] Figure out where to go from there

Please correct me if I am misunderstanding anything.

cc @JJediny @amoose @cantsin

**Comment by afeld** [comment]
Per @amoose [in Slack](https://gsa-tts.slack.com/archives/CMB19370T/p1567635046115900?thread_ts=1567633573.114800&cid=CMB19370T):

> login.gov supports more authentication mechanisms, identity assurance levels and attributes than almost any commercial provider. hence, the complexity in our SAML implementation.

In other words, we may not have the same issue trying to integrate SAML elsewhere, such as Cognito -> whatever.

**Comment by cantsin** [comment]
On reflection, I don't think we can do login.gov -> Cognito -> `[Other SaaS/IaaS]` with our current Cognito setup. Our user pool setup addresses a different use case: using login.gov as a SSO for AWS multi-account login. (And is still quite experimental, but that's a different topic entirely 😅 )

It may be possible to use AWS SSO, but honestly, from a cursory examination of the list above, Google SSO is far more supported and more likely to work out-of-the-box. I'm happy to go through the list and collate SSO options, though. Probably best to use a spreadsheet for that, though.

**Comment by afeld** [comment]
Well, if we were _only_ trying to do cross-AWS-account access (long-term), we would just use IAM users with [cross-account roles](https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html), right? If Cognito isn't going to make sense for that, we should probably slow down and do assessment before going any further with it.

**Comment by JJediny** [comment]
At this point think it makes sense to reach out to GSA IT IDI/GRACE, SecOps, and AWS tech support collectively on our report out on current status for discussion collectively on best path fwd for AWS federation/SSO/auth2. In the meantime focus on (but concurrently move ^ fwd while first prioritizing):
* performing a review/audit of user/role/resources of existing accounts for marking cleanup actions.
* implementing the standardize accounts/roles roll out for cross-account access.

**Comment by afeld** [comment]
Note this issue isn't about actually doing the integration(s) - just about deciding what to pursue in the short term.

**Comment by JJediny** [comment]
crosswalk of the fedramped SSO service Okta with TTS Software. https://docs.google.com/spreadsheets/d/1K1V9_262bKxMgP3zSCzVEzj1Qv3cw4_13hkNZuRSpKM/edit#gid=0

**Comment by afeld** [comment]
Okta is approved for use at GSA and seems like it would meet the requirements, so closing this.
