### ISSUE TITLE
DNS Pull Request Guidance

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#921]
## Background Information

Relates to: https://github.com/18F/tts-tech-portfolio/pull/912 https://github.com/18F/tts-tech-portfolio/issues/556

## Implementation Steps
- [ ] Create guidance for DNS Pull Request review for OpsRotation
- [ ] Update OpsRotation checklist and remove the note about excluding DNS

## Acceptance Criteria

- [ ] Alyssa has paired with Assignee and validates that she feels comfortable taking DNS pull requests during OpsRotation

**Comment by afeld** [comment]
Part of https://github.com/18F/tts-tech-portfolio/issues/851.

**Comment by its-a-lisa-at-work** [comment]
Should we close this or put it in Feedback/Waiting until we do the trial @JJediny mentioned?

**Comment by afeld** [comment]
Merging into https://github.com/18F/tts-tech-portfolio/issues/851.
