### ISSUE TITLE
ensure TTS staff can continue to create custom emoji

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#925]
## Background Information

GSA IT raised concerns that:

- Emoji in Slack are publicly visible
- Someone could add an emoji that ends up being embarrassing to GSA

## Implementation Steps

- [x] [Speak to concerns](https://docs.google.com/document/d/17RXWWI1HHKjuy39c865xV1A33r3WH-N3-hTHtWkmhZw/edit#)
- [x] Call out custom emoji explicitly in Handbook - https://github.com/18F/handbook/pull/2193
- [x] [Ask for feedback from Diversity Guild](https://gsa-tts.slack.com/archives/C02DJFR0V/p1603316531240300)
- [ ] Send TTS-wide reminder about our Slack policies

## Acceptance Criteria

- [x] There is consensus between GSA IT and TTS around if/how custom Slack emoji are approved/managed

**Comment by afeld** [comment]
Per the CIO, referring to the Slack Enterprise Grid migration:

> - TTS users will still be able to create custom emojis after the upgrade
> - [The Director of the] TTS Tech Portfolio will need to manage and review TTS custom emojis for suitability until the policy is updated 
> - Every suitable emoji will be available to all users once the upgrade is complete

**Comment by afeld** [comment]
> GSA IT has updated the GSA Electronic Messaging and Related Services policy to address this issue across the enterprise. It was signed by David Shive on 12/31/2020.
> 
> …
> 
> [2160.2B CIO CHGE 3 GSA Electronic Messaging and Related Services](https://www.gsa.gov/directive/gsa-electronic-messaging-and-related-services-)
> 
> Section 8 is entitled Appropriate Use, and the updated section now says:
> 
> b. All users have an obligation to learn about electronic etiquette, customs, and courtesies. Applicable procedures and guidelines should be followed when using electronic messaging communications, participating in electronic messaging discussion groups, and sending attachments.
> 
> (1)  The use of non-verbal cues such as capitalization as a substitute for shouting, multiple exclamation points for excitement, and expression symbols for facial or other expressions must follow the prohibited usage section of the GSA Information Technology General IT Rules of Behavior and never convey any material that could be interpreted as being sexually explicit, offensive, abusive, discriminatory, or objectionable.
> 
> (2)  The content of any customizable facial expressions or other expressions (emojis or similar) created by an organization for use by employees must be reviewed by the program office/business line's management before use.

See https://github.com/18F/tts-tech-portfolio/issues/1077 for the follow-up.
