### ISSUE TITLE
Keep Airtable Negligible 

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#929]
## Background Information

[Slack thread](https://gsa-tts.slack.com/archives/CNW3GL70S/p1607358601143800?thread_ts=1607357614.143300&cid=CNW3GL70S)

Related:
https://github.com/18F/tts-tech-portfolio/issues/944
https://github.com/18F/tts-tech-portfolio/issues/982
https://github.com/18F/tts-tech-portfolio/issues/835

## Implementation Steps
- [ ] Fill out AirTable FIPS 199
- [ ] [ Inventory how it's currently being used](https://docs.google.com/spreadsheets/d/1T2YK0dDw50YkLC_eYz3RLN61bKYF-Dxvdw9Z5Z92qG8/edit#gid=658261520)
- [ ] Understand impact of downgrading (removing integrations and apps)
- [ ] Set up meeting with GSA IT Security to go over next steps

## Acceptance Criteria

- [ ] GSA IT Security accepts updated FIPS 199 for Airtable

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/handbook/issues/2335.
