### ISSUE TITLE
Clarify the IT Standards Policy in relation to section 2c

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#932]
## Background Information

Section 2c of the IT Standards policy makes it seem like open source software are automatically approved; it isn't clear to me if this has been crosswalked with new policy for security authorizations. 

I want to make sure that we're taking security into consideration even if the compliance standards are being met and we're looking at how we do business from a risk based approach. 

## Implementation Steps
- [ ] Talk with security about this
- [ ] Talk with CTOs office about this
- [ ] Talk with Tech Portfolio about this

## Acceptance Criteria

- [ ] The policy has been reviewed and determined if changes are needed

**Comment by its-a-lisa-at-work** [comment]
@josephderosales added you to this as well; going to take a look at this as I look at #1216
