### ISSUE TITLE
Software Concierge - AppSheet

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#933]
### Status Front matter
`Blocked/Watching` because there are some sticking points with security 

## Implementation Steps
- [ ] Software Request
- [ ] Security
  - [x] Document Roles and Responsibilities
     - [x] System Owner - TTS
     - [x] ISSM - Nate
     - [x] AO - Whoever the AO for the current Google Workspace is
  - [ ] Understand path to authorization
     - [ ] System Categorization (FIPS 199)
     - [ ]  Solution Profile
     - [ ]  System Checklist
- [ ] Acquisition
  - [ ] Decide if this will be a new purchase or updating current purchase

## Acceptance Criteria

- [x] TTS is able to use AppSheet for a prototype of CRM

**Comment by its-a-lisa-at-work** [comment]
Checking with Nate if we still need to tag up; if not, there isn't much action for us to do with this SaaS besides track when it will be ready to be used for TTS.

**Comment by its-a-lisa-at-work** [comment]
The GSA ISSM, Nate, is handling this -- no current action from TTS except to monitor it.

**Comment by afeld** [comment]
@its-a-lisa-at-work / @melanienleopold to update title to encompass all approval required, not just security authorization.

**Comment by its-a-lisa-at-work** [comment]
Closing this card because @ethanheppner mentioned today that he is using it for prototype and that was the Acceptance Criteria
