### ISSUE TITLE
Code Climate FedRAMP Tailored

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#934]
## Background Information

Code Climate just got a LiSaaS ATO; it'll need to go through the FedRAMP process. 

## Implementation Steps
- [x] Hold meeting with Code Climate explaining the FedRAMP Tailored process

## Acceptance Criteria

- [x] Code Climate is aware that we expect them to go through the FedRAMP process

**Comment by its-a-lisa-at-work** [comment]
- Meeting went well!
Ended up being short and sweet. 

Next steps:
-[ ] Send introductory information about GSA's process and expectations for going through FedRAMP
- [ ] Set up follow up meeting between GSA IT Security and Code Climate
