### ISSUE TITLE
Ion Channel - Agency LiSaaS

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#935]
## Implementation Steps
- [x] Answer ISSO's questions
  - [x] Fill out FIPS 199
  - [x] Figure out if this is 'per analysis'
- [x] ISSO sends checklist to Ion Channel
- [x] Ion Channel confirms receipt
- [ ] Ion Channel provides checklist back to ISSO

## Acceptance Criteria

- [ ] Ion Channel has received a determination through the Solution Profile process

**Comment by its-a-lisa-at-work** [comment]
Moving to `Waiting/Feedback` until Ion Channel provides back the checklist

**Comment by afeld** [comment]
@its-a-lisa-at-work Any action for the Tech Portfolio here?

**Comment by afeld** [comment]
[Status update](https://gsa-tts.slack.com/archives/CNW3GL70S/p1613494331160700)

**Comment by afeld** [comment]
Per thread above, sounds like the Pilot is the first step, so closing this until we determine that we want to pursue a full authorization.
