### ISSUE TITLE
Create better way to manage authorization workstreams through TTS Tech Portfolio Workflow

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#936]
## Background Information

Talking with other Product Manager folks, the way they manage their team is having multiple boards that feed into one central board. I think this would be a good idea on how to manage SaaS Authorizations, because there are distinct phases that relate to the authorization process that make sense on how to keep track of them. 

For instance, multiple different authorizations might be running at one time, but progress will be made within each of the cards through the checklist -- so a specific task might be in progress at one given point, but not very often that a whole effort will be in progress. 

## Implementation Steps
- [x] State the problem
- [x] Start a conversation in Slack
- [x] Develop the Solution

## Acceptance Criteria

- [x] It has been decided how to best manage authorizations through the TTS work stream

**Comment by afeld** [comment]
cc https://github.com/18F/tts-tech-portfolio/issues/766

**Comment by its-a-lisa-at-work** [comment]
Created a https://github.com/orgs/18F/projects/24 to better track the different software authorization pipelines. This is already better so far and a good start!
