### ISSUE TITLE
Software Requests Workflow

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#94]
_"Requests" can be for "licenses", "seats", or "access"._

Trying to keep on top of requests in Slack channels, `tts-software@gsa.gov`, and probably other places I'm forgetting is not great. There are a bunch of conditionals, such as:

- Is the software approved for use at GSA?
- Does it need an IT Standards review?
- Is the software [in use at TTS](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=0)/GSA already?
- Is the software managed by TTS or GSA IT?
- Do we need to make a new purchase?
- Can the purchase be made under the micropurchase threshold?

Acceptance Criteria:

- [x] Decide on a mechanism for requesting
   - GitHub issues (with a template) can be tracked on our board - #93
   - A Google Form would allow more structured questions
- [x] Create that intake mechanism - https://forms.gle/zY8XoVXh6VcwzTcL
- [ ] Post updates in (then archive?) the relevant Slack channels
- [ ] Make a decision tree reflecting the conditionals above
- [ ] Update the Handbook
   - [ ] https://handbook.18f.gov/software/
   - [ ] The [software and tool pages](https://handbook.18f.gov/#software-and-tools)
   - [ ] Document responsibilities for micropurchases as discussed at [All Hands
](https://docs.google.com/document/d/1N4osbsZjxbNQUZCXNd706BAzWRhBlb8pfh7wAWJbnPU/edit#bookmark=id.omzmhiwa9yxl) as related to #123 
cc @melanienleopold

**Comment by its-a-lisa** [comment]
Is this related to #125 "create a single form for software/license requests"

**Comment by afeld** [comment]
@JJediny Mind clarifying the difference?

**Comment by afeld** [comment]
Closing in favor of #125.
