### ISSUE TITLE
determine email newsletter tool for usa.gov

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#941]
### Status Front matter
`Blocked/Watching` because exploring [HubSpot](https://github.com/18F/tts-tech-portfolio/issues/755) 
## Implementation Steps
- [x] Helping them creating options
- [x] Seeing them through the process

## Acceptance Criteria

- [x] Decision on what tool usa.gov will use past 7/31 (planned HubSpot authorization expiration date)

**Comment by afeld** [comment]
- [ ] Confirm that this is primarily about email newsletters

**Comment by melanienleopold** [comment]
HubSpot is authorized for use for Newsletter functionality and USA.gov will continue with its contract.
