### ISSUE TITLE
FY21 software spend update - per TTS budget/program

### ISSUE THREAD

**Issue by JJediny** [18F/tts-tech-portfolio#944]
## Background Information

We roughly completed this task for post-facto reporting for FY20 - https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=0 . 

Given the potential for a large reduction in overall budget and firstmost to be good stewards of tax-payer funding we need an extremely accurate accounting of software purchases across contracts and p-card buys to ensure accountability and ensure fully utilization and suggest consolidation where appropriate. 

This revisiting to the single source of truth means we as a team cannot fork this work or invent new ways to manage and update this information as it relates to acq nor security coordination 

## Implementation Steps
- [x] Ensure all current/recurring software buys are reflected for total FY21 projected spend
   - [x] for pcard(s)
   - [x] for contract(s)
- [ ] Ensure each COR or Pcard Holder is associated with each software line tied to budget/program 
    - e.g. there might be 3 buys with 1 COR and 2 different Pcard Holders). The cumulative spend needs to be reflects along with the details of its procurement details as part of the default workflow to maintain.
- [ ] No other data sources are being used separately from the google sheets (e.g. airtable/smartsheet is not a source of truth for an aspect without a clear link provided for a 1:1 association).

## Acceptance Criteria

- [ ] We have a projection for spend on the SaaS budget in FY21

**Comment by melanienleopold** [comment]
https://docs.google.com/spreadsheets/d/1JDRVfHJKmhllIH26ohrZxLBIxbFLt2BmmTaKvzZt9Cg/edit#gid=0

**Comment by JJediny** [comment]
Update 2/3/2021 

We completed an update to the best of [our current knowledge and created google comment assignments for follow up work](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=1831350278). Leaving open for @afeld to assess the issue's current scoping

**Comment by melanienleopold** [comment]
Waiting on some numbers from @JJediny and the HackerOne numbers. Missing a couple of data points that I can't find - Adobe numbers and HubSpot numbers on the Solutions side. If anyone can help fill those in, this can be closed.

**Comment by melanienleopold** [comment]
[Projected FY21 Budget](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=1831350278)

**Comment by afeld** [comment]
To reiterate what I said in the co-working today:

_Goal here is to get a number for "If we continued SaaS purchases as current levels (just renewals, without buying anything new), how much would we have left over at the end of FY21?"_

Apologies if I didn't make that clear enough before. Sounds like the total in the spreadsheet above just captures our Actuals, right?
