### ISSUE TITLE
extend Amit detail - due 11/13

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#955]
## Background Information

@amitfreeman-gov's current detail expires 11/13. Both he and I have expressed interest in extending.

## Implementation Steps

- [x] [Confirm willingness from login.gov](https://gsa-tts.slack.com/archives/G01ABT0KS3B/p1604378112000800)
- [x] Submit formal extension

## Acceptance Criteria

- [x] Amit's detail is extended, or it's decided/understood that it won't be extended (for whatever reason)

**Comment by afeld** [comment]
Lynne's out this week, but I'm going to assume this went through.

**Comment by afeld** [comment]
@amitfreeman-gov just confirmed in HRLinks that it's extended to 1/12/21.
