### ISSUE TITLE
Migrate off of non-authorized software

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#956]
## Background Information

https://github.com/18F/tts-tech-portfolio/issues/859
https://github.com/18F/tts-tech-portfolio-private/issues/947
https://github.com/18F/tts-tech-portfolio/issues/816

## Implementation Steps
- [ ] Determine if software is something we're 'willing to fight for'
   - [ ] DockerHub
   - [ ] ZenHub - https://github.com/18F/tts-tech-portfolio/issues/816
   - [ ] Eventbrite
   - [ ] InVision
- [x] Create new card for software that is going to be fought for
- [ ] Close other cards for the blocked software
- [ ] Start process of getting off of software that is going to be transitioned off of

## Acceptance Criteria

- [ ] No longer using software that is not authorized

**Comment by its-a-lisa-at-work** [comment]
Adding InVision to the list since they have decided not to proceed forward with FedRAMP

**Comment by afeld** [comment]
Suggest we split up to individual issues, since the considerations/timeline will be different for each.

**Comment by its-a-lisa-at-work** [comment]
Closing in favor of other cards that were created
