### ISSUE TITLE
microrequest help, fall 2020

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#957]
## Background Information

Per Karen, [the Solutions agreement with 18F has money left on it](https://gsa-tts.slack.com/archives/CCHKEBRQT/p1603917613016000?thread_ts=1603917372.013700&cid=CCHKEBRQT). We should use it to get some small standalone stuff done.

## Implementation Steps
- [ ] Create prioritized list of good candidate issues
   - https://github.com/18F/uswds-jekyll/issues/196
- [ ] Submit to Karen
- [ ] Find out how many the Tech Portfolio can submit
- [ ] Approved by Karen
- [ ] Submit as [microrequests](https://handbook.tts.gsa.gov/microrequests/)

## Acceptance Criteria

- [ ] Microrequests submitted

**Comment by afeld** [comment]
Sounds like [we missed the boat on this](https://gsa-tts.slack.com/archives/C3F3HR717/p1608217899090300).
