### ISSUE TITLE
Negotiation Techniques (NEGT- EL)

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#966]
Negotiation Techniques (NEGT- EL) 
ILT EXT NEGOTIATION_TECHNIQUES_EL
Revision: 1 - 7/27/2020 07:37 AM America/New York
Item Description: This is a VIRTUAL CLASS for FAS ONLY.
This five-day, elective course teaches acquisition professionals how to use negotiation techniques to reach mutually beneficial agreements with vendors, internal departments, colleagues, and other stakeholders. This course focuses on finding creative, integrative solutions that satisfy each party's interests and needs, resulting in the best possible negotiated outcome. This interactive course includes dynamic hands-on negotiating exercises that allow participants to apply collaborative problem-solving techniques to realistic acquisition challenges.

# Implementation Steps:
- [x] Update SF-182
- [x] Get Supervisor Approval
   - [x] Supervisor approve in FAITAS
- [x] Reschedule meetings on calendar

# Acceptance Criteria:
- [x] Course is approved to attend
- [x] Course is completed

**Comment by its-a-lisa-at-work** [comment]
Heard from Keith W. today 

> no SF-182 is needed because there is no registration fee.  You can cancel it :)

**Comment by its-a-lisa-at-work** [comment]
Also, just noticed this line from the Event bot:

> Attendance at a free training requires only your supervisor's approval of your Individual Development Plan (IDP) in Salesforce. Once they have approved, no further action is needed.

**Comment by its-a-lisa-at-work** [comment]
@afeld moving this to `In Progress` to better match up with reality since we figured out the SF-182 piece of it
