### ISSUE TITLE
Get smart on Plain Language

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#970]
## Implementation Steps
- [ ] Read [Plain Language Guidelines](https://www.plainlanguage.gov/guidelines/)
- [ ] Read [18F Plain Language Approach](https://www.google.com/url?q=https://content-guide.18f.gov/our-approach/&sa=D&ust=1604938978921000&usg=AOvVaw0QFLmeMXtdxuUC44-zXHY_)

## Acceptance Criteria

- [ ] Feel confident in Plain Language skills
