### ISSUE TITLE
Code Climate FedRAMP - Initial Step follow up

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#973]
## Background Information

https://github.com/18F/tts-tech-portfolio/issues/934

## Implementation Steps
- [x] Send introductory information about GSA's process and expectations for going through FedRAMP
- [x] Set up follow up meeting between GSA IT Security and Code Climate

## Acceptance Criteria

- [ ] Action Items have been completed
