### ISSUE TITLE
fill out Zendesk CRM - due 6/7

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#978]
[**Working folder**](https://drive.google.com/drive/folders/1bq-T9OkKbNgbDrKCzIKgsJGeTiGEbkmX)

## Background Information

We've been given the [CRM](https://drive.google.com/file/d/13SklNGFH_cqi2uw0jKzxlAtwALrffGbY/view?ts=5fa96719) to fill out for ZenDesk. Current ATO expires ~~5/15~~ 6/14.

## Implementation Steps
- [x] Find out if other programs in GSA are using Zendesk
- [x] Check if there is a specific version of ZenDesk that is FedRAMP'd
- [ ] ~~Ask for ATO extension, pending alternative (tentative ServiceNow)~~
- [x] Get CRM from Security
- [x] Fill out [SSP](https://drive.google.com/file/d/13SklNGFH_cqi2uw0jKzxlAtwALrffGbY/view?usp=sharing) and return to Security - due 6/7
- [x] ATO signed - due 6/14

## Acceptance Criteria

- [x] Zendesk has a GSA ATO (via the FedRAMP package)

**Comment by afeld** [comment]
Also looking at GSA ServiceNow as an alternative: https://github.com/18F/tts-tech-portfolio-private/issues/979

**Comment by josephderosales** [comment]
As for Checklist ITEM #1: Reviewed IDT's BigFix monthly exports and it did not contain the information I needed. Reached out to Bruce Teng and received the following reply:

**_I am not aware of any tool that will show usage of any pure SaaS tools.  If the SaaS tool has a client footprint on the workstation, Bigfix Inventory will show usage of the Client Footprint associated with the SaaS tool.  In my opinion, each SaaS tool should have their own "usage" metering capability._**

**Comment by josephderosales** [comment]
Requested access to SmartSheet: https://app.smartsheet.com/sheets/jvrJ3QwCF3xPH84mJR7q83Mv7XXQ5pvqqG4fCHj1?view=gantt

**Comment by josephderosales** [comment]
All of Zendesk products are FedRAMP authorized. For more information you can email fedramp@zendesk.com

**Comment by afeld** [comment]
Pausing until we get further along with https://github.com/18F/tts-tech-portfolio-private/issues/979.

**Comment by afeld** [comment]
> All of Zendesk products are FedRAMP authorized.

Where did you get that? Our understanding was that only Enterprise was: https://github.com/18F/tts-tech-portfolio-private/issues/968

**Comment by josephderosales** [comment]
@josephderosales verify if the date in title is correct - if so ask for extension

**Comment by afeld** [comment]
[Folder with ZenDesk SSP to be filled in](https://drive.google.com/drive/folders/1bq-T9OkKbNgbDrKCzIKgsJGeTiGEbkmX)

**Comment by afeld** [comment]
@josephderosales Are you good to rally folks for this? The ZenDesk accounts are fully managed by the teams that use them; not sure that the Tech Portfolio is involved at all, beyond maybe billing. Put some information about the three ZenDesk instances I'm aware of into [the software inventory](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=0&range=79:81).

**Comment by afeld** [comment]
…based on [a ZenDesk inventory we made last year](https://docs.google.com/spreadsheets/d/1QLeLFVgat-9G_82Dnwtt5ZzDzQJWALNhU4pFS3kzBGc/edit#gid=0).

**Comment by josephderosales** [comment]
working session scheduled with cloud.gov Thurs 5/13

**Comment by afeld** [comment]
Sent [an update](https://docs.google.com/document/d/1mlcOb_4B2IHtx3tNx3AeCFSCT7R0az4z8_eXC4rJMZQ/edit#heading=h.rz7qbvd5b6aw) to stakeholders.

**Comment by afeld** [comment]
Apparently [the ATO has been signed](https://gsa-tts.slack.com/archives/C021P43KY6A/p1623092443001600) 🎉
