### ISSUE TITLE
clean up our published packages

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#98]
NPM:

- [x] Move packages under [18F org](https://www.npmjs.com/org/18f)
- [ ] Ask what remaining packages are missing
- [ ] [Deprecate](https://docs.npmjs.com/cli/deprecate) unmaintained packages
- [ ] [Remove owners](https://docs.npmjs.com/cli/owner) who are no longer at GSA

RubyGems:

- [ ] Figure out what packages we have
   - [`auctioneer`](https://rubygems.org/gems/auctioneer)
   - [`go_script`](https://rubygems.org/gems/go_script)
   - [`guides_style_18f`](https://rubygems.org/gems/guides_style_18f)
   - [`team_hub`](https://rubygems.org/gems/team_hub)
   - [`uswds-jekyll`](https://rubygems.org/gems/uswds-jekyll)
- [ ] Create an account for devops@gsa.gov
- [ ] Add devops@gsa.gov to all packages
- [ ] [Remove owners](https://guides.rubygems.org/command-reference/#gem-owner) who are no longer at GSA

PyPI:

- [ ] Figure out what packages we have
   - [`cg-django-uaa`](https://pypi.org/project/cg-django-uaa/)
   - [`django-uswds-forms`](https://pypi.org/project/django-uswds-forms/)
   - [`rdbms-subsetter`](https://pypi.org/project/rdbms-subsetter/)
   - [`sql-insert-writer`](https://pypi.org/project/sql-insert-writer/)
- [ ] Create an account for devops@gsa.gov 
- [ ] Find out what email is associated with [the `18f` user](https://pypi.org/user/18f/)
- [ ] Add devops@gsa.gov to all packages
- [ ] Remove collaborators who are no longer at GSA

**Comment by afeld** [comment]
Emailed NPM support (request 69183) as I was seeing some weirdness trying to remove people from packages.

**Comment by trevorbryant** [comment]
@afeld -- `18f` user, OSINT shows [this tweet](https://twitter.com/18F/status/702878467604348928?s=20) with the repo link. May help narrow down who owns that pypi account.

Could also be [Aaron Borden](https://lists.okfn.org/pipermail/ckan-dev/2018-December/023010.html).

**Comment by its-a-lisa** [comment]
Deleting as stale based on the TTS Tech Portfolio Deep Grooming session from 3/30/20; if you have any questions, comments or concerns, please let us know either in the #infrastructure or #tts-tech-portfolio slack channels
