### ISSUE TITLE
consensus on prioritization for large SaaS purchases

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#982]
## Background Information

Follow-up to https://github.com/18F/tts-tech-portfolio/issues/678. Blocked by https://github.com/18F/tts-tech-portfolio/issues/944.

TTS has a number of large SaaS purchases/upgrades we should make, either because it:

- Has compliance advantages
- Consolidates license management
- Improves administration capabilities

We can't do it all at once, for budgetary/acquisition/effort reasons, so need to decide what order to do so.

## Implementation Steps
- [x] Email all the teams
- [ ] Send nudge
- [ ] Get sign-off from:
   - [ ] Security - Nate Ciano
   - [ ] CTO - @Zergessc 
   - [ ] BizOps - @HuixianXu 
   - [ ] Tech Portfolio - @afeld 

## Acceptance Criteria

- [ ] Consensus on [the `Priority` order for SaaS upgrades](https://docs.google.com/spreadsheets/d/1Kg1KHV3J6sSY7RVPJubLK8gaQ3U0_Tg7gyFxQGtNhWA/edit#gid=0)

**Comment by its-a-lisa-at-work** [comment]
Checked in with IT Security and based on where this is falling within their list of priorities and the limited capacity through the Holidays, was informed that the earliest we'll receive an answer is in 2-3 weeks so plan on linking back with them early 01/21

Moved to `Blocked/Watching` until we get movement

**Comment by its-a-lisa-at-work** [comment]
Updated the [Software Request Spreadsheet](https://app.smartsheet.com/sheets/xCMFrXQCRmmfRVjJ3X4VrF57P2GfvVM4GrCGjqr1?view=grid) with these entries
