### ISSUE TITLE
propose path forward for TTS/GSA use of Docker registries

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#983]
## Background Information

Per https://github.com/18F/tts-tech-portfolio-private/issues/947#issuecomment-706273874, "DockerHub…will not be providing any security information nor do they seem to do security in the way we'd like." Not a great situation. Options:

- Avoid use of Docker Hub entirely
   - Would be a _lot_ of work, since basically everything uses it as an upstream
- Use Docker Hub with conditions, e.g.
   - Only for local development / outside of production
   - Only with an intermediate registry that does scanning

Probably worth doing some threat modeling to make sure everyone's on the same page about what we are protecting ourselves against.

TTS isn't the only part of GSA using containers, so we should see what's being done in GSA IT, FAS Cloud Services, etc.

## Implementation Steps
- [ ] Get a hold of any GSA-wide security documentation around containers, e.g. the hardening guide (that seems to have disappeared…?)
- [ ] Find out what GSA Security is doing
- [ ] Find out what FAS Cloud Services is doing
- [ ] Write up proposal
- [ ] Get feedback within TTS
- [ ] Send proposal to Security and CTO

## Acceptance Criteria

- [ ] We have presented a proposal around Docker registries for TTS

**Comment by afeld** [comment]
The [GSA Container Security Benchmark](https://docs.google.com/spreadsheets/d/15HBgrHs1hp1JWpk9FOS-5wIFwFX0QCHi0b56TX8_T5Y/edit#gid=884169645) may be useful here.

**Comment by its-a-lisa-at-work** [comment]
I've found this article useful as a possible way forward https://github.com/microsoft/containerregistry https://azure.microsoft.com/en-us/blog/microsoft-syndicates-container-catalog/

**Comment by afeld** [comment]
New problem here: Free teams in DockerHub are now limited to three users. Getting this error when trying to manage users:

> 10 of 3 seats filled

**Comment by its-a-lisa-at-work** [comment]
I highly recommend that we look into partner with Platform One who is doing
Container registry.

**Comment by afeld** [comment]
@ManojChalise mentioned that GSA IT's DevSecOps Tiger Team is working on a centralized registry for GSA, which presumably/hopefully we can leverage. He said he'll send me whatever documentation/plans he can, and keep us updated.

**Comment by JJediny** [comment]
Connect with Devtools
