### ISSUE TITLE
SCRM List - FedRAMP input

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#987]
## Implementation Steps
- [x] Export list of of FedRAMP Authorizations
- [x] Get input from FedRAMP on methodology should be used for putting vendors through tool
- [x] Record selection criteria methodology
- [x] Use Selection Criteria methodology to list FedRAMP-ed vendors as Very High, High, Medium, Low and Very Low to be put through the SCRM Tool
- [x] Share findings with
  - [x] Tech Portfolio
  - [ ] FedRAMP PMO
  - [x] SCRM OSC PM

## Acceptance Criteria

- [ ] A validated list of vendors related to FedRAMP is given to OSC to run through the SCRM tool

**Comment by its-a-lisa-at-work** [comment]
Completed ranking the [list](https://docs.google.com/spreadsheets/d/1kuHeHqoTphxikX60bWaB3PP6fc-t5Bb2HwB8nPnkFDw/edit#gid=727991545) based on the [selection criteria](https://docs.google.com/spreadsheets/d/1kuHeHqoTphxikX60bWaB3PP6fc-t5Bb2HwB8nPnkFDw/edit#gid=1534636037)

And let the FedRAMP office folks know in a [slack message](https://gsa-tts.slack.com/archives/C3S23TCEM/p1605649909082000)
