### ISSUE TITLE
Create goals and roadmap for TTS Software Concierge

### ISSUE THREAD

**Issue by melanienleopold** [18F/tts-tech-portfolio#989]
## Background information

Melanie has been assigned as the software concierge for the tech portfolio. As part of this assignment, there needs to be a roadmap established with roles and responsibilities. 

## Implementation Steps
- [x] Melanie create document
- [x] Alyssa review document

## Acceptance criteria

- [ ] A roadmap is established and approved by @its-a-lisa-at-work and @afeld

**Comment by melanienleopold** [comment]
[Software Concierge document](https://docs.google.com/document/d/1hoRjPSgKLWBbLj_6ta9EmUmKcEP-hd1iPyauOY1_kmo/edit#heading=h.b22if8mpuds0) ready for review

**Comment by afeld** [comment]
Added everyone in team as reviewers; remove yourself when you're done.

**Comment by afeld** [comment]
There are a bunch of outstanding comments, so will wait for more of those to be worked out before I take a look. Let me know when ready!

**Comment by melanienleopold** [comment]
@afeld ready for review!

**Comment by afeld** [comment]
Nice work! Left a bunch of comments/suggestions, which I promise is a good thing 😉 

- [ ] Resolve (majority of) Aidan's feedback
- [ ] Run it by CTO team

**Comment by melanienleopold** [comment]
Comments are resolved. I think it's ready for review by the CTO team!

**Comment by josephderosales** [comment]
Requested access to review [file](https://docs.google.com/document/d/1hoRjPSgKLWBbLj_6ta9EmUmKcEP-hd1iPyauOY1_kmo/edit#heading=h.b22if8mpuds0):

**Comment by melanienleopold** [comment]
All comments received from the team. Ready to present in the kickoff meeting.
