### ISSUE TITLE
As someone compiling data for TTS, I want to understand what the questions are

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#99]
Part of #7.

Rather than trying to collect all the data we can, let's start with:

- What metrics are we using (regularly) right now
- What questions have come up that TTS staff wish they could answer with data?

Note, "metrics" may have certain connotations, and exclude useful information. Example: A team may look at how many of their tasks are In Progress at any given time. This is technically a metric, but they may not think about it that using that term. In other words, we might want to think of a more term that casts a wider net.

## TODO

- [ ] Create a place to collect these
- [ ] Pull from @NadavTollman's [presentation appendix](https://docs.google.com/presentation/d/1Em-Ftkckk2_vwIBecJv7m1Su60KTt4qF50twxUKXcE0/edit?ts=5d729fe7#slide=id.g35ed75ccf_0134)
- [ ] Go back through [interview notes](https://drive.google.com/drive/folders/1BybZ1RZeL6Ul3gxH9By_NsmLwr7u5E_G?usp=sharing) to see if there are questions we can pull
- [ ] Gather more - perhaps a TTS (supervisor?)-wide survey?

**Comment by afeld** [comment]
Decided this is out of scope for the Tech Portfolio right now.
